### ISSUE TITLE
country name next to flag

### ISSUE THREAD

**Issue by Codepadawan** [jackocnr/intl-tel-input#1000]
Hi! First up, maximum kudos for maintaining such a great plugin, and being so responsive!

I've implemented this, but based in Australia, typically our mobiles are mostly from AU or NZ, and the flags are *way* too similar at the standard size. I couldn't find any other way to do it, so I hacked your plugin to get this outcome:

![Screen Shot 2019-11-12 at 11 13 35 pm](https://user-images.githubusercontent.com/841490/68670875-1433c780-05a2-11ea-89df-608673071ab4.png)

![Screen Shot 2019-11-12 at 11 14 13 pm](https://user-images.githubusercontent.com/841490/68670905-29a8f180-05a2-11ea-8af8-adb14a789c87.png)

![Screen Shot 2019-11-12 at 11 15 28 pm](https://user-images.githubusercontent.com/841490/68670972-5826cc80-05a2-11ea-963c-8033128c3024.png)

...etc

Do you think this is something others might find useful?

**Comment by jackocnr** [comment]
Thanks for the kudos, and nice job here - it looks good. We actually already have quite a similar feature called `separateDialCode`, which I think does the job pretty well - also avoids issues with different languages/character sets! So I don't think we need this in core, but this was cool to see, thanks :)

**Comment by Codepadawan** [comment]
Yeah I saw the `separateDialCode` option, but, I liked the way the plugin worked already with the `nationalMode` - I basically wanted as it was, but with a second identifier next to the flag - NOT the dial code... could be an option some people might prefer.

Thanks again

**Comment by JBWereRuss** [comment]
@Codepadawan 

> I've implemented this, but based in Australia, typically our mobiles are mostly from AU or NZ, and the flags are _way_ too similar at the standard size. I couldn't find any other way to do it, so I hacked your plugin to get this outcome:

Agree, those flags are a wee bit to small - I'm from NZ. Any chance you could post your code for this?

Thanks, Russ.

**Comment by Codepadawan** [comment]
@JBWereRuss 

Hi Russ, I added an option called `showCountryCode` and made these changes:

1. in the function `_generateMarkup` after `if (this.options.separateDialCode) {...}`

```
            if (this.options.showCountryCode) {
                this.selectedCountryCode = $("<div>", {
                    "class": "selected-country-code"
                }).appendTo(selectedFlag);
            }
```

2.  in the function `_setFlag` after `if (this.options.separateDialCode) {...}`

```
            if (this.options.showCountryCode) {

                this.telInput.parent().addClass("separate-country-code");
                
                this.selectedCountryCode.text(countryCode);
            }
```

I didn't fork the repo however so I hope that's enough information? Let me know if not.

**Comment by JBWereRuss** [comment]
@Codepadawan 

That's awesome, thank you.
