### ISSUE TITLE
Phone number length changed in Gabon, please update the libarary

### ISSUE THREAD

**Issue by Cedricatangana** [jackocnr/intl-tel-input#1004]
Gabon has increased the length of its phone numbers and the library no longer validates phone numbers from this country. How do we make sure to keep this always updated for all the countries ?

### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
Thanks for raising this issue. It actually only takes 5 minutes to do this yourself, if you'd be willing to submit a Pull Request? Instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber). Thanks :)

**Comment by jackocnr** [comment]
Updated to the latest version and released in v16.0.8.
