### ISSUE TITLE
TypeError: a is null

### ISSUE THREAD

**Issue by d9cp1** [jackocnr/intl-tel-input#1006]
All work but, i have same error in script when use it in laravel.
![image](https://user-images.githubusercontent.com/39772493/69737606-554cdf80-113d-11ea-801a-9b181a00eb9a.png)
Package was installed by npm.
**Require css:**
`<link rel="stylesheet" href="{{asset('library/intl-tel-input/css/intlTelInput.min.css')}}">`
**Requeire js:** 
`<script src="{{asset('library/intl-tel-input/js/intlTelInput.min.js')}}" type="application/javascript"></script>
`<script` src="{{asset('library/intl-tel-input/js/intlTelInput-jquery.min.js')}}" type="application/javascript"></script>`
`<script src="{{asset('library/intl-tel-input/js/utils.js')}}" type="application/javascript"></script>`

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by d9cp1** [comment]
@jackocnr https://codepen.io/d9cp01/pen/QWWeaJJ?editors=1111#anon-signup[](url)

**Comment by jackocnr** [comment]
If you get rid of the extra params in that URL, and just visit https://codepen.io/d9cp01/pen/QWWeaJJ then the only JS error I see is `$ is not defined` which is because you're trying to use jQuery without loading it.
