### ISSUE TITLE
Does not recognize the mobile number for Denmark

### ISSUE THREAD

**Issue by adaxx** [jackocnr/intl-tel-input#1007]
Does not recognize the mobile number for Denmark starting with +45 50 *******

**Comment by jackocnr** [comment]
This is not enough information for me to look into the issue effectively. Please read the [New Issue Checklist](https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist) and if necessary, open a new issue and follow the [New Issue Template](https://raw.githubusercontent.com/jackocnr/intl-tel-input/master/.github/ISSUE_TEMPLATE.md). If you are including any code, please [format it correctly](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Comment by adaxx** [comment]
Hello,

This is a mobile number from Denmark +45-50-293085, the script does not recognize that it is a mobile number, see [codepen](https://codepen.io/boban-adamovic/pen/LYEpgaY)
