### ISSUE TITLE
There are duplicate IDs generated when using multiple phone inputs

### ISSUE THREAD

**Issue by scottadamsmith** [jackocnr/intl-tel-input#1008]
### Steps to reproduce
1.  Initialize multiple inputs with intl-tel-input on the same page
2.  There are duplicate IDs in the DOM (country-listbox, iti-item-us, etc)
2.  Here is an example: https://codesandbox.io/s/inspiring-montalcini-eupsq

### Expected behaviour
The IDs should be unique. Especially given they are referenced by some aria-attributes on the page. 

### Actual behaviour
I have not yet tested in in a screen reader, but my assumption is that a screen reader would reference the first input no matter which input you are interacting 

My suggestion would be to append a UUID to all these IDs that could be generated once per instance. Unfortunately, this could be considered a breaking change since people may be referencing these IDs. What are your thoughts on this?

**Comment by jackocnr** [comment]
Thank you for raising this issue. I agree. We already have [an internal instance ID system](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js#L10) and we should just append that onto all IDs.

There are two places I can see where we're currently using IDs: on the dropdown container (id="country-listbox") and on each list item (e.g. id="iti-item-us"). Firstly the container should have the "iti" prefix to distinguish it as part of this plugin. And secondly they should both have the instance ID added as a suffix.

I would welcome a pull request that added this change.

**Comment by scottadamsmith** [comment]
Thoughts on this being a breaking change? I haven't checked if you document the IDs in a way that would encourage people to reference them, but if someone is, this is certainly breaking for them.

**Comment by jackocnr** [comment]
I don't document the IDs anywhere, but yeah I think it still qualifies as a breaking change.

**Comment by jackocnr** [comment]
Fixed in v17.
