### ISSUE TITLE
Input field show dial code when updated

### ISSUE THREAD

**Issue by lippomano** [jackocnr/intl-tel-input#1010]
I am using Angular 8 and I need to update the phone number in my FormControl so I use this instruction: `myForMontrol.patchValue(this.landline.getNumber())` but I always see the dial code in my input and I don't want to see it. 
When I create the form I correctly see only number and not the dial code(with correct flag)

### Expected behaviour
I am expecting that when I update the formControl I don't see the dial code

### Initialisation options
I use only initial Country

**Comment by jackocnr** [comment]
I'm afraid this is outside the scope of the support I can provide. I'd suggest you ask on StackOverflow.
