### ISSUE TITLE
Can't scroll the dropdown through arrow keys

### ISSUE THREAD

**Issue by mit2sumit** [jackocnr/intl-tel-input#1013]
As I implemented this for login in one of my client site, everything working perfectly, until I notice the country dropdown is not scrollable through Arrow keys.

### Steps to reproduce
1.  Go to here: https://temi-market-dev.openchannel.io/signin/
2.  Try to change country with arrow keys.

### Expected behaviour
- It should be allowed to scroll up/down throughout the lists.

### Actual behaviour
- Its stops after one country highlighted.

### Initialisation options
- I'm using geoIpLookup and utils. However, I also tried a simple initialization as in your demo, but its not working for me.

**Comment by jackocnr** [comment]
Does it work for you on the demo site? intl-tel-input.com

**Comment by mit2sumit** [comment]
yup, it works there and in every other places I searched the example for.
Not sure, what's causing issue in my end. I also tried initializing it in different page of same site, but it didn't worked there as well.

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by mit2sumit** [comment]
Well, I further debugged and tried to see if its some JS conflict, and then found that after disabling bootstrap, it worked for me. I've been using the alpha version of bootstrap 4 since 2016.
So, the issue for now, is resolved and I appreciate for your time and your prompt response. Thanks!
