### ISSUE TITLE
If you want to stick with the jQuery version, there is now a separate jQuery wrapped version.

### ISSUE THREAD

**Issue by johnnybenson** [jackocnr/intl-tel-input#1014]
Can you link to the jQuery wrapped version in the [README](https://github.com/jackocnr/intl-tel-input#important-since-v14-we-have-removed-the-jquery-dependency-see-below-for-how-to-initialise-and-use-the-plugin-with-pure-javascript-if-you-want-to-stick-with-the-jquery-version-there-is-now-a-separate-jquery-wrapped-version)?

It's not clear if you mean we should roll back to v13 or that there is a different version with a new wrapper on top of `intl-tel-input` at v16/latest?

**Comment by jackocnr** [comment]
Currently all new releases do also include a jQuery wrapped version (see the build directory). This may change in the future.

The pure JS version is definitely the recommended version. So I don't want to link to the jQuery version as I don't want to encourage it's use - it's not actively maintained (tho it should still work), we no longer have documentation for it and as I say we will probably remove it at some point.
