### ISSUE TITLE
Consider support for inum (+883-5100)?

### ISSUE THREAD

**Issue by saigelosli** [jackocnr/intl-tel-input#1015]
Should there be support for the iNum country code? https://en.wikipedia.org/wiki/INum_Initiative

**Comment by jackocnr** [comment]
Can you explain your use case?

**Comment by saigelosli** [comment]
In my case, I'm developing a web page where one registers using a phone number and email address. I do some IP geo-locating and preset the country code. The user can override the pre-selected country code, but also enter the in-country phone number.

I was just thinking that it might be possible, (but perhaps unlikely?) that an iNum might be one's only phone number. In that case, entering a +883 5100 phone number into the form is awkward because the country code part just goes blank.

It's probably a really obscure use case, so I'm not actually convinced that it needs to happen. I simply wanted to raise the question for consideration. Feel free to close it without further action. :-)

**Comment by jackocnr** [comment]
Well thanks for raising it. I'll close it for now, but if enough people feel it's important maybe we'll come back to it.
