### ISSUE TITLE
Country codes not changing for few countries and getting error while change the country like "TypeError: intlTelInputUtils.formatNumberByType is not a function"

### ISSUE THREAD

**Issue by RaviBandaru333** [jackocnr/intl-tel-input#1017]
### Steps to reproduce
1.Select country code as the USA  and type the phone number.
### Initial Entered Number Like +12012365456
2.  now change the country to India, existed country flag is changed to indian flag but country code not changed to,  **Expected Result +916252365456** but  **Actual Result +16252365456**
3.  In this case, getting an error like **"TypeError: intlTelInputUtils.formatNumberByType is not a function" in the console.** 

### Expected behaviour
When the user changes the country form one to another the country code should be change along with the flag.
 **Expected Result** :  +916573466086
  **Actual Result** : +16573466086
### Actual behaviour
The country flag is changed but the country code is not changed.
### Initialisation options
    allowExtensions: false,
    autoFormat: true,
    autoHideDialCode: false,
    autoPlaceholder: true,
    customPlaceholder: null,
    defaultCountry: "",
    geoIpLookup: null,
    nationalMode: true,
    numberType: "MOBILE",
    onlyCountries: void 0,
    preferredCountries: ['us', 'gb'],
    skipUtilScriptDownload: true

### Reference clips
###1. Error

![image](https://user-images.githubusercontent.com/48747224/71990540-91ee1980-3259-11ea-8fde-d586d7b626ac.png)
### 2.Initial Result
![image](https://user-images.githubusercontent.com/48747224/71990615-b4803280-3259-11ea-9179-5097e01db913.png)
### 3. After change the country code to india.
![image](https://user-images.githubusercontent.com/48747224/71990721-e72a2b00-3259-11ea-8732-fc6e0b4d2f76.png)

**Comment by jackocnr** [comment]
Hmm that looks like an old version of the plugin to me. I'm afraid I can only provide support for the latest version, so please try using that. Closing for now, but please feel free to open a new issue if you have a problem with the latest version :)
