### ISSUE TITLE
hiddenInput is empty without utilsScript

### ISSUE THREAD

**Issue by ilyasgaraev** [jackocnr/intl-tel-input#1018]
The problem is related to `getNumber` method: https://github.com/jackocnr/intl-tel-input/blob/955b9f9e3211978a2f9de17787798036dc163dc2/src/js/intlTelInput.js#L1306-L1312

Could you please clarify why it returns an empty string if I use the library without utilsScript? I don't want to format or validate the value in the field, just send it via form (with hiddenInput option). What if `getNumber` will return `this._getFullNumber()` instead of the empty string?

### Steps to reproduce
1.  Open https://codepen.io/garaevilyas/pen/JjoLddG
2. Open browser's console
3.  Fill something to a phone input field
4. Submit form

### Expected behaviour
Value in hiddenInput should be [country code + filled value].

### Actual behaviour
Value in hiddenInput is always empty if I initialize the library **without** utilsScript.

### Initialisation options
```js
{
  separateDialCode: true,
  hiddenInput: 'phone',
}
```

**Comment by jackocnr** [comment]
The original point of the `hiddenInput` option was to be able to get something different to what's in the main input - to take the main input value, and transform it into the full international number, which can only be done with the utils. If you just want the value in the input, then there's no need to use `hiddenInput`. Unless I have missed something? If so, please can you explain your use case?

**Comment by ilyasgaraev** [comment]
@jackocnr, thanks for the quick response. I want to submit a form with a full number `[country code] +[value in input]` as one parameter. For example, I want to see on server phone number like "15417543010", where the first "1" – country code and I can save it to the database.  And I see this in the documentation about `hiddenInput`:

> On submit, it will automatically populate the hidden input with the full international number. This is a quick way for people using non-ajax forms to get the full international number...

`hiddenInput` will help me with this if it returns `this._getFullNumber()`. Maybe I am wrong and need to use some different ways? Thanks for your help.

**Comment by jackocnr** [comment]
You cannot just prepend the international dial code to the number typed in the input - that will not always produce a valid phone number e.g. if user types a local formatted numbed in the UK, it will start with a 0, and then pre-pending the international dial code +44 does not make sense in this case. That is why you need to use the utils script.

**Comment by ilyasgaraev** [comment]
Ok, got it. My backend uses a library based on Google libphonenumber (like utilsScript), that's why I don't found this case. So, you think that an empty string is better than a full number in `hiddenInput`?

**Comment by jackocnr** [comment]
> So, you think that an empty string is better than a full number in `hiddenInput`?

Well as I've said, it often wouldn't be a full number - it would be a broken number. I don't want to provide functionality that often doesn't work as expected.

I have updated the readme to make it more explicit that the `hiddenInput` option requires the utils script. Thanks for raising this.
