### ISSUE TITLE
hiddenInput is not set on first submit in woocommerce checkout integration (workaround)

### ISSUE THREAD

**Issue by aliaramli** [jackocnr/intl-tel-input#1020]
### Steps to reproduce
1.  registers intl-tel-input css,javascripts to custom wordpress woocommerce gateway plugin
2.  added the instance declaration
```
  var input = document.querySelector("#phone");
  var iti = window.intlTelInput(input,{
    utilsScript: "xxxxxxxxxx/utils.js",
  	// the countries at the top of the list. defaults to united states and united kingdom
	preferredCountries: [ "my", "us", "gb" ],
    autoPlaceholder: null,
    separateDialCode: true,
    hiddenInput: "phoneNum"
   });
```
3. added field called #phone for user input 
4.  monitor the request params sent to wc-ajax=checkout 
5. noticed that on the first submit the hiddenInput param is not populated with data yet.only after the submit the data is populated.
6. the workaround of this..i added in _initKeyListeners() function in `intlTelInput.js` to populate the data in hiddenInput when user types in the #phone tel field. 

### Expected behaviour
it is expected the hiddenInput not to be set on the first submit due to the woocommerce ajax script handling. im sharing this workaround for those facing the same issue.

### Actual behaviour
hiddenInput is not set on first submit, only after submit the hiddenInput is populated properly

### Workaround
added in _initKeyListeners() function in `intlTelInput.js` to populate the data in hiddenInput when user types in the #phone tel field. 
```
 // update flag on keyup
this._handleKeyupEvent = function() {
if (_this6._updateFlagFromNumber(_this6.telInput.value)) {
    _this6._triggerCountryChange();
  }
 ----->>   _this6.hiddenInput.value = _this6.getNumber();
  };
```
### Initialisation options
utilsScript

Feel free to give feedback if there's a better way to handle this.

**Comment by jackocnr** [comment]
Hi there, thanks for sharing this workaround, but personally I have no experience with WooCommerce, and it's outside the scope of support I can provide. I'll close this for now, but if you think there's a legitimate issue with the plugin that is not tied to another library then I'd be happy to help.

Btw the hiddenInput option was designed to be used with regular page requests (non-ajax requests) - if you're using ajax requests then you shouldn't need to use this option as you can just call `getNumber` yourself and pass that value to the backend.
