### ISSUE TITLE
Hidden input not suitable for Symfony forms

### ISSUE THREAD

**Issue by Anyeos** [jackocnr/intl-tel-input#1022]
### Steps to reproduce
1. Read the docs and prepare intl-tel-input to be used with a form with Symfony.

Symfony uses TypeTel for input type="tel" and TypeHidden for input type="hidden".
The problem becomes when intl-tel-input creates a new input hidden and Symfony cannot use that.
If I don't create explicitly TypeHidden with Symfony it complains that there must not be additional fields on the form.

```
### Expected behaviour
I need that intl-tel-input use the existing input hidden field if there are one with the same name.

### Actual behaviour
When I create the hidden field with Symfony it does not claim about additional fields but intl-tel-input creates one more with the same name.  So there are exactly two input type="hidden" with the same name and I cannot read the phonenumber from Symfony, it returns a blank string.

### Initialisation options
utilsScript only

**Comment by jackocnr** [comment]
Sorry I don't know anything about Symfony - this is outside the scope of the support I can provide - I suggest you ask on StackOverflow.

**Comment by Anyeos** [comment]
@jackocnr that is because I am explaining the problem. Please, read it.
Anyway what I need is that intl-tel-input reuses a existing <input type="hidden" name="same_name_as_inputhidden_from_intl">
Actually intl-tel-input creates a new input instead of using the existing one.

I solved it manually with this code:
```
  var input = document.querySelector("#form_phone");
  if (input !== null) {
    var iti = window.intlTelInput(input , { 
      utilsScript: "{{ asset('js/utils.js') }}"
    });

    var form = document.forms["form"];
    if (form !== null) {
      form.onsubmit = function() {
        var phone_full = form.elements["form[phone_full]"];
        phone_full.value = iti.getNumber();
      };
    }
  }
```

**Comment by loverg-c** [comment]
Thanks @Anyeos for the idea, 
Other solution based on yours which maybe can help people looking for same problem on hiddenInput and ajax behavior: 
```

function yourInitFunction() {
    const inputs = document.querySelectorAll(".phone-number-input");
    
    [].forEach.call(inputs, function (input, key) {
        const originalName = input.name;
        input.name = ''

        let iti = intlTelInput(input, {
            utilsScript: utils,
            hiddenInput: originalName,
        });

        updateHiddenInput(input, iti);

        input.addEventListener('keyup', () => {
            updateHiddenInput(input, iti);
        });
    });
}

function updateHiddenInput(input, iti) {
    let phone_full = input.parentNode.querySelector('input[type=hidden]');
    phone_full.value = iti.getNumber();
}
```

**Comment by jackocnr** [comment]
Since v25.0.1 we now look for and use existing hidden inputs with the given names before creating new ones 👍🏻
