### ISSUE TITLE
Some numbers in Singapore are showing as Invalid number

### ISSUE THREAD

**Issue by kelvinkyaw** [jackocnr/intl-tel-input#1023]
I'm using a version of in last year. I believe it was V15.0.0. I'm testing at new number in Singapore and seem didn't work for latest number. I did try on https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html and number is still show invalid

### Steps to reproduce
1.  New number start with +65 8900 162x and shown as Invalid number
2.  I tried with old number +65 8876 090x and shown as valid number

### Expected behaviour
Should be valid number

### Actual behaviour
Shown Invalid number

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

**Comment by kelvinkyaw** [comment]
@jackocnr 
I did check and shown as valid number from the library. 

```
****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Phone Number region: SG
Result from getNumberType(): MOBILE
```

**Comment by jackocnr** [comment]
There is a pending PR to update libphonenumber - I think that will fix this, I just have to find the time to review it. Hopefully wont be long.

**Comment by kelvinkyaw** [comment]
Thanks @jackocnr :)

**Comment by vlaskiz** [comment]
@jackocnr don't mean to hijack this, however, facing the same issue with majority of mobile numbers from Denmark (DK).

Checking on demo site numbers seem to work:
```
****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: DK
Result from getNumberType(): FIXED_LINE_OR_MOBILE

****ShortNumberInfo Results:****
Result from isPossibleShortNumber: false
Result from isValidShortNumber: false
Result from isPossibleShortNumberForRegion: false
Result from isValidShortNumberForRegion: false
```

Example options are:
```
        $phoneInput.intlTelInput({
            formatOnDisplay: false,
            nationalMode: false,
            separateDialCode: true,
            autoHideDialCode: false,
            autoPlaceholder: 'off', // aggressive, polite, off
            numberType: "FIXED_LINE_OR_MOBILE",
            preferredCountries: ['gb', 'fi', 'no', 'dk', 'se', 'fr', 'de', 'be', 'at', 'nl', 'it', 'es', 'us', 'au'],
            initialCountry: initialCountry
        });
```

Pull request is for v8.11.1 while there's version 8.11.2 out.

**Comment by jackocnr** [comment]
I've just released v16.0.10 which includes libphonenumber v8.11.3. Please can you check if this fixes the issue for you?

**Comment by kelvinkyaw** [comment]
@jackocnr Yes, issue is fixed. Thanks for your merged.

**Comment by Keeper496** [comment]
I updated my version to get the "89** ****" phone numbers to work.  Apparently, there are "80** ****" phone numbers also in Singapore.   These are still erroring out as invalid phone numbers.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).
