### ISSUE TITLE
Country selection menu is broken on mobile

### ISSUE THREAD

**Issue by crinny** [jackocnr/intl-tel-input#1027]
### Steps to reproduce
1.  Use intl-tel-input with the following code in Bootstrap 4 on mobile:
```html
<div class="col">
    <label for="phone"></label>
    <input class="form-control" id="phone" name="phone" pattern="\d*" placeholder="912 345-67-89" required type="tel">
</div>
```
2.  Open country selection dropdown

### Expected behaviour
Country selection menu goes down from the input

### Actual behaviour
Country selection menu is in the top of the page
![image](https://user-images.githubusercontent.com/42045258/73609144-dad88a00-45db-11ea-9d65-6d7c4e2a2136.png)

### Initialisation options
```javascript
intlTelInput = window.intlTelInput(input, {
        onlyCountries: ['ru', 'ua', 'kz', 'by', 'custom'],
        initialCountry: 'ru',
        separateDialCode: true,
    });
```

**Comment by jackocnr** [comment]
Do you get the same issue on the demo site? intl-tel-input.com

If not, then I'm guessing this is a clash in your CSS.

**Comment by crinny** [comment]
Kind of
![image](https://user-images.githubusercontent.com/42045258/73649575-200ac380-4691-11ea-8435-ac3aaf6cc5d2.png)

**Comment by jackocnr** [comment]
That's working as intended.

**Comment by crinny** [comment]
Fixed by removing `display: flex`.
