### ISSUE TITLE
Number is not accepting for country Kosovo

### ISSUE THREAD

**Issue by KolesnikovR** [jackocnr/intl-tel-input#1029]
### Steps to reproduce
1.  Click your validation example/demo link: https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html
2.  Enter mobile number: +38348434107

### Expected behaviour
Valid number

### Actual behaviour
Invalid number

**Comment by kelvinkyaw** [comment]
@KolesnikovR Your issue should be solved in this PR. 

https://github.com/jackocnr/intl-tel-input/pull/1028

I tested locally and number is pass.

![image](https://user-images.githubusercontent.com/3499681/74124770-666e9e00-4c0e-11ea-9761-3536cdcad88f.png)

Please wait for @jackocnr for merge this PR :) 

@davepenfold is already make PR. So, no need to do it again and waiting for merge.

**Comment by jackocnr** [comment]
Should be fixed in v16.0.10.
