### ISSUE TITLE
Country search does not work with localized country names

### ISSUE THREAD

**Issue by koktut** [jackocnr/intl-tel-input#1031]
When using localizedCountries, the country search does not work, because The _bindDropdownListeners () function filters input with the expression / ^ [a-zA-ZÀ-ÿ] $ /. test (e.key) which does not contain Russian letters

### Actual behaviour
Country search does not work

### Initialisation options
 localizedCountries: {
	'ru': 'Россия',
	'kz': 'Казахстан'
}

**Comment by jackocnr** [comment]
Good catch! I'm afraid I don't have time to work on this myself right now, but would welcome a pull request.

**Comment by koktut** [comment]
Done https://github.com/jackocnr/intl-tel-input/pull/1032

**Comment by jackocnr** [comment]
Fixed in v16.0.11.
