### ISSUE TITLE
Flag placeholder displaces from it's position with the toggle of validation message

### ISSUE THREAD

**Issue by sohaibahmed293** [jackocnr/intl-tel-input#1033]
Flag placeholder displaces from its position when an error message is displayed and goes back to it's position when error message is no more there or field becomes valid

**Comment by sohaibahmed293** [comment]
![image](https://user-images.githubusercontent.com/21006389/74608670-02177700-5105-11ea-9b45-35ff75b33682.png)

**Comment by sohaibahmed293** [comment]
![image](https://user-images.githubusercontent.com/21006389/74608677-1491b080-5105-11ea-8dc7-78fddcc3e910.png)
flag moves to the bottom when error message is displayed. Does any one know how to fix it ?
Tried with CSS but no luck.

**Comment by jackocnr** [comment]
There's nothing in the plugin code to do this - it must be a clash with your custom CSS. If you can't solve it yourself I'd suggest asking on StackOverflow.

**Comment by erfanSW** [comment]
set height for .iti__selected-flag class .
`.iti__selected-flag {
        height: 38px;
 }`
