### ISSUE TITLE
input for regionlessNanpNumbers fails validation and no country data or pseudo country data is available for it

### ISSUE THREAD

**Issue by scott-fanetti-genesys** [jackocnr/intl-tel-input#1035]
When attempting to add a number for an Iridium phone to a form with int-tel-input the validation failed indicating an invalid country code. 

### Steps to reproduce
1.  Attach the library to an input
2.  input an iridium number or presumably any regionless Nanp Number into the input (eg:  **881 672520732**)
3.  Perform validation
Expected:
Number is valid and formatted correctly - country flag display is blank
Actual
Validation fails and display formatting seems incorrect - country flag display is blank

I added a "+" in the input to see if it would correctly interpret the country code - assuming maybe an E164 input would work better - but it did not have any information in 'getSelectedCountryData'

No options other than defaults are set.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

**Comment by scott-fanetti-genesys** [comment]
In [this line](https://github.com/jackocnr/intl-tel-input/blob/23d6e0aff13fee8b69310f64e0a689a5c7761769/src/js/intlTelInput.js#L50) the regionless nanp numbers are delineated. in the block [here](https://github.com/jackocnr/intl-tel-input/blob/23d6e0aff13fee8b69310f64e0a689a5c7761769/src/js/intlTelInput.js#L910) the method checks to first see if the number is prefixed with a 1 - then it pulls a substring from the number to check if it is regionless nanp.  

This seems to fail for numbers our users input because they are not prefixes with an international dialcode.  They can also input an E164 number - and the rest of the library seems to recognize that -- but it still does not get treated like a regionless number - and it fails because the country code seems not to exist.  

I don't know what the right behavior is supposed to be.  I would hope regionless numbers would be included as pseudo-states or something with maybe a blank flag in the UI.  But generally it just does not seem to handle naturally added regionless numbers.

**Comment by jackocnr** [comment]
This plugin is designed for phone inputs based on country flags, so I'm afraid we do not explicitly support satellite numbers.

With that said, we use libphonenumber for validation, so if you type in a valid number that is supported by libphonenumber (e.g. satellite number +881 672520732 or regionless NANP number +1 800 8727245) then this plugin will say the number is valid.
