### ISSUE TITLE
As you type formatter

### ISSUE THREAD

**Issue by gety9** [jackocnr/intl-tel-input#1038]
Is there a option to enable formatter ? 

For example on demo https://intl-tel-input.com/ mask is displayed as (201) 555-0123
but when user starts typing it goes as 
2
20
201
2015

it's not UX friendly.

it should go
(2
(20
(201)
(201) 5

Is there a way to enable formatter ?
Maybe something similar to what https://www.npmjs.com/package/google-libphonenumber has.

Basically to be UX friendly you don't have to make user put "() -" they should be added automatically. Some of users will start from typing "(2" some of users will start from typing "2" for both it should result as "(2"

**Comment by jackocnr** [comment]
This question has been answered many times - please search existing issues before creating a new one.

**Comment by gety9** [comment]
I did search for formatting, type, nothing fresh was coming up.

For anyone looking for same thing seems like reasons for removing autoformat are explained here:
https://github.com/jackocnr/intl-tel-input/issues/346
