### ISSUE TITLE
Validate on focus out from input field instead on 'keyup' event.

### ISSUE THREAD

**Issue by sohaibahmed293** [jackocnr/intl-tel-input#1041]
Phone number is getting validated using JS 'keyup' event which sends ajax request on every digit entered in the input field and causes a little bit delay and halts the input. So is there any way to validate the number once the focus gets out of the input field instead of the default 'keyup' approach ? I'm also using jquery validation plugin in the form for other fields validation.

Thanks

**Comment by jackocnr** [comment]
> instead of the default 'keyup' approach

There is nothing baked into the plugin that performs validation by default - you have to code it yourself.

If your question is just about how to code this yourself in JavaScript, then I recommend you ask on StackOverflow.
