### ISSUE TITLE
window.intlTelInput is not a function in angular 8 after prod build.

### ISSUE THREAD

**Issue by Puneetraj02** [jackocnr/intl-tel-input#1042]
![Untitled](https://user-images.githubusercontent.com/45029748/75755840-6ec18100-5d55-11ea-902e-1d17e7f7399d.png)

**Comment by jackocnr** [comment]
I'm afraid I know nothing about Angular so cannot help with this. But if you can re-create the issue with plain JS in a codepen, then I'd be happy to take a look.

For Angular specific issues, I recommend you ask on StackOverflow.
