### ISSUE TITLE
[Question] Get the length of international phone numbers

### ISSUE THREAD

**Issue by Kachilero** [jackocnr/intl-tel-input#1043]
I'm using a separate making library for the phone number input, and I'm trying to set it correctly based on the country that is selected. The mask is an array of `RegExp` ( `[/\d/, /\d/ ]` ) representing digits.
I'm running into an issue where if the number is longer than my initial mask of 7 digits, the making breaks down and does weird things.

If I could get the length of a countries phone number, I could set the mask to the appropriate length.

So my questions is: Is there a way to get the length of a countries phone number from the `utils.js` script?

**Comment by jackocnr** [comment]
In the [wiki page](https://github.com/jackocnr/intl-tel-input/wiki/utils.js) you can see the exposed methods - I guess you could use `getExampleNumber` but my guess would be that some countries have variable length numbers, so it might be dangerous to make any assumptions here.
