### ISSUE TITLE
Updating countries list doesn't return input value

### ISSUE THREAD

**Issue by NileshN** [jackocnr/intl-tel-input#1046]
We are using intl-tel-input plugin in AngularJS(v1.5) to show countries list along with country code. We have updated this plugin and added new entry in this array as "No country" and set this entry as default in the drop down.

Now when user selects this default value, "No country", and submits the form, we are not getting phone number value entered by user. This seems binding issue.

Can someone please help to get value from this input field.

Any help would be highly appreciated.

Thanks.

**Comment by jackocnr** [comment]
I'm sorry but this is not supported, and is outside of the scope of the support that I can provide - I recommend you ask on StackOverflow.
