### ISSUE TITLE
Country list being selected in mobile instead of country item

### ISSUE THREAD

**Issue by darrist** [jackocnr/intl-tel-input#1047]
### Steps to reproduce
1.  Visit https://twinliving.co and scroll down to form
2.  Try perform country dropdown selection
3.  Long hold and see country-list being highlighed instead of country item
4. Country item will also be missing after long hold

### Expected behaviour
Should perform as expected

### Actual behaviour
Weird behavior in Chrome Mobile, or Desktop Browser in Mobile resolution mode

### Initialisation options
Default

**Comment by jackocnr** [comment]
> Long hold

What do you mean? Long hold on what? And why long hold at all?

**Comment by darrist** [comment]
Hello! Please look at a video here: https://drive.google.com/file/d/1x6Tq9q47OGwcZZn0TAZXH5dvHIuIVuVH/view

It seems really weird, where when you tap, the <li> does not response to tap event. When you try to long hold, a country will went missing and flag-container will be highlighted.

I've tried adding z-index to different spot to raise the container, but it does not work.

**Comment by jackocnr** [comment]
Are you refreshing the page when changing to emulate mobile? You need to do that because the plugin initialises differently depending on the device.

And can you reproduce the issue on the demo site?

Are you seeing anything in the JS console?

**Comment by darrist** [comment]
It's reacting the same in Chrome mobile, Safari mobile, and console do not print any error.

**Comment by jackocnr** [comment]
Can you reproduce the issue on the demo site? intl-tel-input.com
