### ISSUE TITLE
Changelog is missing releases

### ISSUE THREAD

**Issue by Turbo87** [jackocnr/intl-tel-input#1048]
### Steps to reproduce
1.  visit https://github.com/jackocnr/intl-tel-input/blob/master/CHANGELOG.md 😅 

### Expected behaviour

I was expecting to find some information there about what the breaking changes in the v16 release are.

### Actual behaviour

The v16 release is not mentioned in there 😢

**Comment by jackocnr** [comment]
Hmm good point, this needs to be re-generated, thanks for raising it.

In the mean time, you can see this information in the Release notes: https://github.com/jackocnr/intl-tel-input/releases

**Comment by jackocnr** [comment]
Ok it's now updated.
