### ISSUE TITLE
setNumber with nationalMode false, cut off number

### ISSUE THREAD

**Issue by netgfx** [jackocnr/intl-tel-input#1049]
### Steps to reproduce
1.  Initiallize plugin: 
```
telInputInstance = telInput(jQuery('#phoneNumber')[0], {
	autoHideDialCode: true,
	initialCountry: 'US',
	allowDropdown: true,
	preferredCountries: ['US'],
	utilsScript: telUtils,
	nationalMode: false,					
});
```
2.  set number telInputInstance.setNumber("+306935552403"));
3. Flag is set to Greece, but number appears: `+30 693 555 24`  

### Expected behaviour
It would allow the rest of the digits to appear.

### Actual behaviour
Number is truncated

### Initialisation options
Using utils script.

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by netgfx** [comment]
Thanks, it was a simple case of maxlength, sorry to trouble you.
