### ISSUE TITLE
Could not validate "99482197" for Singapore number

### ISSUE THREAD

**Issue by optivolveiqbal** [jackocnr/intl-tel-input#1052]
### Steps to reproduce
1.  Use "99482197" for Singapore number (+65)
2.  Trigger validate function

### Expected behaviour
Number should be valid

### Actual behaviour
Validation faile

### Initialisation options
Default.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

**Comment by optivolveiqbal** [comment]
thanks @jackocnr . I've liase with the team from libphonenumber on the issue. May I know if they have any new fixes, should your team update the library? is the validation is online or using a static dataset in your build package?

**Comment by jackocnr** [comment]
Yes when libphonenumber release a fix, we will need to re-build a new version of the plugin.

**Comment by jackocnr** [comment]
I'll close this issue for now - feel free to create a new issue to update the plugin when there is a new version of libphonenumber.
