### ISSUE TITLE
Phone Number detected as invalid

### ISSUE THREAD

**Issue by nratifainah** [jackocnr/intl-tel-input#1053]
### Steps to reproduce
when i check here, https://giggsey.com/libphonenumber/ phone number detected as valid phone number. however when i use this library it says phone number is invalid

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens
Should be detected as valid phone number

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries
Phone number detected as invalid

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

**Comment by faca5** [comment]
Hello.

Can you check this phone number 069 123 123 for SI.

Your results:
false:

Their results:
true

?!


****Parsing Result:****
{"country_code":386,"national_number":69123123,"raw_input":"069 123 123","country_code_source":20}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: SI
Result from getNumberType(): MOBILE

****ShortNumberInfo Results:****
Result from isPossibleShortNumber: false
Result from isValidShortNumber: false
Result from isPossibleShortNumberForRegion: false
Result from isValidShortNumberForRegion: false

****Formatting Results:**** 
E164 format: +38669123123
Original format: 069 123 123
National format: 069 123 123
International format: +386 69 123 123
Out-of-country format from US: 011 386 69 123 123
Out-of-country format from Switzerland: 00 386 69 123 123
National format with carrier code: 069 123 123

****AsYouTypeFormatter Results****
Char entered: 0 Output: 0
Char entered: 6 Output: 06
Char entered: 9 Output: 069
Char entered:   Output: 069 
Char entered: 1 Output: 069 1
Char entered: 2 Output: 069 12
Char entered: 3 Output: 069 123
Char entered:   Output: 069 123 
Char entered: 1 Output: 069 123 1
Char entered: 2 Output: 069 123 12
Char entered: 3 Output: 069 123 123

**Comment by jackocnr** [comment]
Thanks for raising this. I can confirm. I see there is a newer version of libphonenumber, so we'll need to update to that, and that should fix it.

**Comment by faca5** [comment]
Correct!

**Comment by dumisanigegana** [comment]
Hello, am having the same issue with some ZW phone numbers like 078 752 0282.

intl-tel-input results:
false:

libphonenumber results:
true

**Comment by jackocnr** [comment]
Instructions on how to rebuild libphonenumber below. It actually only takes 5 minutes to do this yourself, if you'd be willing to submit a Pull Request? Instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber). Thanks :)

**Comment by dking-tyro** [comment]
Hi @jackocnr, I've create a pull request with the updated libphonenumber library

**Comment by dumisanigegana** [comment]
Thank you very much

*Dumisani Ndlovu*
*Mob:* +263 71 297 0291 <+263712970291>
*Email:* ndumisani@gmail.com
<https://www.facebook.com/ndlovud>
<https://www.linkedin.com/in/dumisani-ndlovu-47792a124>
<https://plus.google.com/+YourCompany>

**Comment by jackocnr** [comment]
Latest version of libphonenumber released in v16.0.14 - does that fix the issue for you guys?

**Comment by dumisanigegana** [comment]
yes i noted, this is the libphonenumber issue note intl-tel-input. Thank
you very much for the response
