### ISSUE TITLE
Kenya new phone number prefix

### ISSUE THREAD

**Issue by riccycastro** [jackocnr/intl-tel-input#1055]
### Steps to reproduce
1.  choose a country: Kenya
2.  add a valid Kenya number starting with the new prefix 01 instead of the old one 07
3.  click to validate the number

### Expected behavior
Validate method should return true

### Actual behavior
Validate method returns false

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

**Comment by riccycastro** [comment]
ok, already in touch with them, thank you
