### ISSUE TITLE
Constructor not documented?

### ISSUE THREAD

**Issue by nieware** [jackocnr/intl-tel-input#1058]
### Steps to reproduce
1.  Look at the README.md under https://github.com/jackocnr/intl-tel-input - it looks like an exhaustive documentation.
2.  However I couldn't find a documentation of the constructor window.intlTelInput() with all parameters it supports - there are some examples which use the constructor, but no actual documentation.

### Expected behaviour
I am upgrading some code which wasn't written by me from an older version of intlTelInput to the current non-jQuery version, and would like to find out if the constructor has changed (besides the obvious change that now you have to pass the DOM element as the (first?) parameter).

### Actual behaviour
Since there is no documentation, I have to look at the source code to find out what the constructor does.

### Initialisation options
n/a

**Comment by jackocnr** [comment]
The constructor takes 2 arguments: the input, and optionally an options object. See the Options section of the readme for more information.

I suppose we should document this explicitly. I'll leave this ticket open as a reminder to do that, thanks.

**Comment by jackocnr** [comment]
Ok I have now shown how to use the constructor / initialisation options in the Getting Started section, and have described how to use the constructor at the start of the Initialisation Options section. That should make things clearer. Thanks.
