### ISSUE TITLE
Validation on https://intl-tel-input.com/

### ISSUE THREAD

**Issue by gitonthescene** [jackocnr/intl-tel-input#1059]
### Steps to reproduce
1.  Go to web site https://intl-tel-input.com/
2.  pick any international code
3.  type in pure gibberish such as "this is clearly not a number"

### Expected behaviour
Tell us what should happen
I would expect you to not allow users to enter anything but numbers

### Actual behaviour
Tell us what actually happens
It allows users to type in nonsense, which is only later validated.  Ideally, you would accept numbers and flesh out the pattern as the numbers are entered.

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
A lot of people consider it bad practice to artificially disable certain keys. It is not an established standard, so it is not what users expect, and there is no standard way to communicate to the user that a key has been rejected, which is likely to confuse them.

Submit validation (or blur validation if you prefer) is the standard approach and I think it does the job just fine.

**Comment by gitonthescene** [comment]
Fair enough.  Thanks for replying!
