### ISSUE TITLE
Conflict with Mobile responsive Bootstrap

### ISSUE THREAD

**Issue by MuhammadTausif** [jackocnr/intl-tel-input#1061]
### Steps to reproduce
1.  The responsive behavior breaks when we use phone validation
2.  `
                    <div class="input-group col-lg-12 mb-4">
                        <div class="input-group-prepend" >
                            <span class="input-group-text bg-white px-4 border-md border-right-0">
                                <i class="fa fa-phone-square text-muted"></i>
                            </span>
                            <input id="phone" type="phone" name="phone" placeholder="Phone number" class="form-control bg-white border-left-0 border-md input" required="required">
                        </div>
                        
                      <script src="assets/build/js/intlTelInput.js"></script>
                      <script>
                    var input = document.querySelector("#phone");
                    window.intlTelInput(input, {
                      initialCountry: "auto",
                      geoIpLookup: function(callback) {
                        $.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
                          var countryCode = (resp && resp.country) ? resp.country : "";
                          callback(countryCode);
                        });
                      },
                      utilsScript: "assets//build/js/utils.js?1562189064761" // just for formatting/placeholders etc
                    });
                      </script>
                    </div>`
3.  The above code is not responsive.

### Expected behaviour
The input should behave responsiveness.

### Actual behaviour
While the validation happen, the actual size of the input changes ( fit to the contents instead of remain same as for others)

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by MuhammadTausif** [comment]
> If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

I have solved the issue by removing one line of code. I don't know weather it is elegant solution or not, but it worked for me. I also make other changes in my input element of DOM.

File: intlTelInput.js 
Line No: 350
Original Code: wrapper.appendChild(this.telInput);
Modified code: // wrapper.appendChild(this.telInput); ( I comment this line, and it work)

Kind Regards
