### ISSUE TITLE
phone number control renders incorrectly for me when i give it a value

### ISSUE THREAD

**Issue by steveburkett** [jackocnr/intl-tel-input#1062]
Hi there, 

When i load this control w/out a value, it shows fine (this is a rails form, with a placeholder): 

![image](https://user-images.githubusercontent.com/352161/78066975-c3531e80-734a-11ea-9b55-a34c6c8793a8.png)

When i load this control with a value, it shows up like this:

![image](https://user-images.githubusercontent.com/352161/78066857-90108f80-734a-11ea-99e7-eff46c7f9aaf.png)

Can anyone help me know what's wrong?  thanks in advance! 

This is how i'm initializes the control
```
$(document).ready(function(){
  var input = document.querySelector(".int-country-code");
  if ( input !== null ) {
    window.intlTelInput(input, {
      formatOnInit: true,
      separateDialCode: true,
      preferredCountries: ['us', 'pl']
    });
  }
});
```

This (in rails, using our form helper) is how i'm declaring the control:

```
            fh.text_field name: :phone_number,
                          type: 'tel',
                          # value: "(541)420-7890",
                          supplemental_class: 'int-country-code form-control wide',
                          placeholder:  I18n.t(:'login_signup_form.phone_number_placeholder'),
                          onkeydown: 'javascript:backspacerDOWN(this,event);',
                          onkeyup: 'javascript:backspacerUP(this,event);'
```

I'm including the js thru the rails asset pipeline 
```
//= require intlTelInput
//= require libphonenumber/utils
```

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by steveburkett** [comment]
@jackocnr this isnt the full repro, but this creates part of the problem (just adding a value to the control)

![image](https://user-images.githubusercontent.com/352161/78592264-aeb6d080-77f9-11ea-9204-f5480a6bd67a.png)

**Comment by jackocnr** [comment]
Well you've given it a number, but you haven't told it which country to display.

Please see [Recommended Usage](https://github.com/jackocnr/intl-tel-input#recommended-usage) notes. Or alternatively you can use initialCountry init option, or setCountry method.
