### ISSUE TITLE
Use intl-tel-input with programmaticly created html

### ISSUE THREAD

**Issue by suzannechang** [jackocnr/intl-tel-input#1067]
### Steps to reproduce

2.  Then scroll down and see the phonenumber field appear with settimeout 5000
3.  When i change the number i want to trigger this behaviour 

document.getElementById("extension_telefoon").addEventListener("blur", myFunction);
  
  function myFunction() {
  //  alert(window.iti.getNumber());
    var isValid = iti.isValidNumber();
    if(isValid == true) { 
      //  alert(window.iti.getNumber());
    document.getElementById("extension_telefoon").value = window.iti.getNumber();
  } else 
    { 
      // document.getElementById("extension_telefoon").value = '';
  }
  }

### Expected behaviour
The number should change to the full number like +31

### Actual behaviour
It doenst get iti.GetNumber so it gets changed to nothing

### Initialisation options
var load = setTimeout(function() {
  
  var input = document.querySelector("#extension_telefoon");
  var iti = window.intlTelInput(input, {
  preferredCountries: ["nl", "be"],
    utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@16.0.3/build/js/utils.js",
  });
  
  // store the instance variable so we can access it in the console e.g. window.iti.getNumber()
  window.iti = iti;

  }, 5000);

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by suzannechang** [comment]
Hi Jack,

I have used that, and it works fine in plain html. but my page is programmaticly loaded. so i call the plugin with a settimeout. but then the blur doenst listen to anyting.

would you please take a look? 

Gr

**Comment by jackocnr** [comment]
You need to provide much more specific information.

> When i change the number i want to trigger this behaviour

What exactly are you changing the number to? Please give a full example.

And when you say you "want" to trigger that behaviour - are you triggering it or not? Is `myFunction` getting called? Is `isValid` true? What is the result of calling `iti.getNumber()`?

I visited the link you sent and searched the JS and couldn't find anything called `myFunction`.

**Comment by suzannechang** [comment]
HI, i;m sorry

1. first the page gets loaded
2. after 5 seconds with the set timeout i call the phone number function
3. when user changes the phone field i want to blur an action that changes the phone field to the international phone number
4. i want to trigger that with the window.iti.getNumber();
5. but that stays empty

This is is the code.
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajaxsso.blob.core.windows.net/web/ssoweb/build/css/intlTelInput.css">
<script src="https://cdn.jsdelivr.net/npm/intl-tel-input@16.0.3/build/js/intlTelInput.js"></script> 
<script>
 var load = setTimeout(function() {
   
  var input = document.querySelector("#extension_telefoon");
  
  var iti = window.intlTelInput(input, {
  preferredCountries: ["nl", "be"],
  
    utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@16.0.3/build/js/utils.js",
  });
  
  // store the instance variable so we can access it in the console e.g. window.iti.getNumber()
  
  window.iti = iti;

 }, 5000);

  $('input[id="extension_telefoon"]').on('blur', function() {

    // alert(window.iti.getNumber());
        var isValid = window.iti.isValidNumber();
        if(isValid == true) { 
        //  alert(window.iti.getNumber());
        document.getElementById("extension_telefoon").value = window.iti.getNumber();
    }
});

  </script>

**Comment by jackocnr** [comment]
Please take the time to format your code properly - I can't read it like that.

And also please answer the questions I asked you. e.g. please tell me exactly what you're typing into the input e.g. "+1 702 123 1234"

**Comment by suzannechang** [comment]
HI Jack,

Thank you. the question is. to make the code in underlying url work on the b2c page, keeping in mind that the b2c page takes some time to load. 
http://secutixwebapp.azurewebsites.net/intlphonetest/demo.html

this is my input: 0612345678

the country is NL

**Comment by jackocnr** [comment]
Ok so it's working on that demo page but not on your actual website?

On your website, is the blur listener firing? If you put a console.log statement in there, is it working?

**Comment by suzannechang** [comment]
Hi, now its working sometimes on our live site and sometimes not

Sometimes the console.log gives result and sometimes not. its hard to debug
input: 0611149900

https://ajaxfans.b2clogin.com/ajaxfans.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_SignUp&client_id=ca1849b4-1273-4441-bb9f-bd209601d741&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token&prompt=login&ui_locales=en


` <script src="https://ajaxsso.blob.core.windows.net/web/ssoweb/build/js/intlTelInput.js"></script>
  <script>
    var load = setTimeout(function() {

        var input = document.querySelector("#extension_telefoon");

        var iti = window.intlTelInput(input, {
            preferredCountries: ["nl", "be"],

            utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@16.0.3/build/js/utils.js",
        });

        // store the instance variable so we can access it in the console e.g. window.iti.getNumber()
        window.iti = iti;

        document.getElementById("extension_telefoon").addEventListener("blur", myBlurFunction);
        
        var myVar;
        function myBlurFunction() {
            myVar = setTimeout(veranderFunction, 3000);
         

        }
        function veranderFunction() {
       

            var goednummer = iti.getNumber();
            if (goednummer.length > 0) {
                document.getElementById("extension_telefoon").value = iti.getNumber();


            }
        }


}, 1000);
    </script>`

**Comment by jackocnr** [comment]
Ok it sounds like the issue is just a pure JavaScript issue - getting a blur event listener to work consistently - rather than anything specific to this plugin. I'm afraid this is outside of the scope of support that I can provide. I would suggest you ask on StackOverflow.
