### ISSUE TITLE
intlTelInput with mask

### ISSUE THREAD

**Issue by kyhos** [jackocnr/intl-tel-input#1069]
Great suggestion:
Making intlTelInput and Jquery mask plugins to work together
https://stackoverflow.com/a/44541797/11954958

And It helped but there is one problem. If you change country to anyone and then select US. The format is not correct

A native solution would be interesting, not to depend on the jquery mask.

Thank you and congratulations!

**Comment by jackocnr** [comment]
This question has been answered before. Please search existing issues before creating a new one.

**Comment by peteichuk** [comment]
To enable input mask, try set parameter
autoPlaceholder: 'aggressive',
