### ISSUE TITLE
hiddenInput option not posting value

### ISSUE THREAD

**Issue by LarryBarker** [jackocnr/intl-tel-input#1070]
Hello, first thank you for sharing this package! I'm experiencing issue with the `hiddenInput` option. My details are below:

### Steps to reproduce
1.  Follow install instructions
2.  Setup input field using `hiddenInput` option
3.  Confirm the hidden input is added to the page
4. Enter a value into the main input field
5. Submit the form
6. Check post variable on server side
7. Notice the hidden input field is sent, but does not contain a value

### Expected behaviour
The hidden input field value should be available as a post variable on the server.

### Actual behaviour
The hidden input is posted to the server, but does not contain a value.

### Initialisation options

```
var settings = {
                allowDropdown: true,
                autoHideDialCode: true,
                separateDialCode: true,
                autoPlaceholder: "aggressive",
                formatOnDisplay: true,
                formatOnType: true,
                geoIp: false,
                hiddenInput: "phone_full",
                initialCountry: "US",
                nationalMode: true,
                placeholderNumberType: "MOBILE"
            };
```

Field is being initialized successfully:
![image](https://user-images.githubusercontent.com/28734844/79142334-edf89a80-7d80-11ea-86b3-531bbe4cf1b0.png)

Page source shows the `hiddenInput`: 
![image](https://user-images.githubusercontent.com/28734844/79142373-04065b00-7d81-11ea-9879-de70283ee1c6.png)

Network request shows the `hiddenInput` field is being sent but is empty:
![image](https://user-images.githubusercontent.com/28734844/79142440-213b2980-7d81-11ea-943d-7feba38d0f49.png)

Can confirm these values are being posted to the server:
```
/**
     * @inheritDoc
     */
    public function getSaveValue($value)
    {
        debug($value);
        debug(post());
        return $value;
    }
```

![image](https://user-images.githubusercontent.com/28734844/79142690-7e36df80-7d81-11ea-81fa-c8d443c0bf70.png)

Any feedback is greatly appreciated! Thanks much :)

**Comment by LarryBarker** [comment]
@jackocnr Could I have your input here please?

**Comment by jackocnr** [comment]
Well first of all, I noticed you have a few options there which are not supported (formatOnType, geoIp), and I just wanted to check you were using the latest version of the plugin?

And second, is your input nested inside a form element?

And how exactly are you submitting the form?

**Comment by LarryBarker** [comment]
Thanks for the reply 😄 AFAIK I am using the latest version (I installed through composer). The field is nested inside of a form element. I should clarify that my forms are being submitted with AJAX. However, it does not appear the value for the hidden input is being updated in the page source. This may be the intended behavior though, and the value is set when the form is submitted if I understand the source correctly?

**Comment by jackocnr** [comment]
Yes that value is only populated on the form submit event.

This hiddenInput option is designed for non-Ajax forms. If you're submitting your form with Ajax then you shouldn't need this option. Just call getNumber in your own submit handler, before you send the data to the server.

**Comment by LarryBarker** [comment]
Right on, yeah I read that and just stubbornly assumed it should fill the value on the page. After looking at the source I realized it's handled on the submit event. Appreciate your feedback and apologies for a dubious issue 😆
