### ISSUE TITLE
libphonenumber not accepting new Hong Kong number ranges

### ISSUE THREAD

**Issue by MurrayNick** [jackocnr/intl-tel-input#1071]
The validator does not allow newly released numbers in the range 4XXXXXXX, despite these being valid mobile numbers as per the latest Hong Kong OFCA number plan (attached).

### Steps to reproduce
1.  Enter a valid Hong Kong number beginning with 4 (E.g. 45450000)

### Expected behaviour
Number should be passed as valid

### Actual behaviour
Number is rejected as invalid

[no_plan.pdf](https://github.com/jackocnr/intl-tel-input/files/4474640/no_plan.pdf)

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

**Comment by MurrayNick** [comment]
Reported here: https://issuetracker.google.com/issues/154161166
