### ISSUE TITLE
country select does change unexpectedly on none country select action

### ISSUE THREAD

**Issue by Toolcrafting** [jackocnr/intl-tel-input#1072]
### Steps to reproduce
1. go to https://intl-tel-input.com/
2.  select any country which starts with +1 except US
3.  change the phone number in field
4.  now you should see that the flag has changed unexpectedly to US

### Expected behaviour
The selected country shouldn't change if phone number get changed
Keep selection if no selection change is done

### Actual behaviour
The flag changes to a country which wasn't selected before

### Initialisation options
That's actually mine code but it keep the same issue like in the demo.
$.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
                              var countryCode = (resp && resp.country) ? resp.country : "";
                              var le =  window.intlTelInput(input, {
                                  initialCountry: init_country,
                                  geoIpLookup: function(callback) {
                                      callback(countryCode);
                                  },
                                  hiddenInput: "phone_number",
                                  utilsScript: window.telUtils,
                                  formatOnDisplay: false,
                                  separateDialCode: true,
                                  preferredCountries: [countryCode]
                              });
                              $("#trader-address").on(
                                  "submit",
                                  () => {
                                      if($("#phone_country")){
                                          $("#phone_country").remove();
                                      }
                                      $("#trader-address").append('<input type="hidden" name="phone_country" id="phone_country" value="'+le.getSelectedCountryData()["iso2"]+'" />');
                                  }
                              );
                          });

**Comment by jackocnr** [comment]
Please give an explicit example of a number you are typing in, which changes the flag.

**Comment by Toolcrafting** [comment]
Sorry for interruption and making such unclear instructions.
More detailed, first I select flag American Samoa, after that the placeholder shows up the number have to start with 684, but I typed in a 3 so the first number was wrong and it changed automatically to US flag. It's still weird because the number has nothing to do with the beginning of an US number, how it looks in placeholder if US flag was selected at the beginning, but I think it's a user mistake of myself.

**Comment by jackocnr** [comment]
As you have stated, American Samoa numbers begin with 684, so if you type 3 then it will not be a valid American Samoa number so we change the flag to our best guess for what you are typing. If you type 340 or 345 you'll see other flags, but otherwise we default to the US flag because that's most likely the correct flag for a 3xx number.
