### ISSUE TITLE
help request: Using Angular with intl-tel-input

### ISSUE THREAD

**Issue by choopage** [jackocnr/intl-tel-input#1074]
### Steps to reproduce
1.  Go to https://stackblitz.com/edit/ngx-intl-tel-input
2.  You will see that using intl-tel-input works by itself
3.  You will see intl-tel-input not working with Angular v9

### Expected behaviour
intl-tel-input to work with Angular v9

### Actual behaviour
intl-tel-input works by itself but not yet with Angular v9.

### Initialisation options
Here is the problem. See app.component.ts
https://stackblitz.com/edit/ngx-intl-tel-input

**Comment by jackocnr** [comment]
Sorry I have no experience with Angular - that's outside the scope of the support I can provide.

I think there are some unofficial ports of this plugin to Angular - might be worth trying one of those.

**Comment by sarora2073** [comment]
fyi - i found this alternative package for anyone in the same situation: https://github.com/tanansatpal/ngx-mat-intl-tel-input

**Comment by choopage** [comment]
Thank you. I will check it out.
