### ISSUE TITLE
How to integrate it in Vue Js ?

### ISSUE THREAD

**Issue by cococococococo** [jackocnr/intl-tel-input#1075]
### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
I'm afraid this is outside the scope of the support I can provide. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).

**Comment by cococococococo** [comment]
this is ok , i found a solution. seems someone adapted it for vue js

**Comment by locotoko** [comment]
> this is ok , i found a solution. seems someone adapted it for vue js

Could you please share link for this adapted version?

**Comment by Dahkenangnon** [comment]
https://github.com/EducationLink/vue-tel-input
