### ISSUE TITLE
intlTelInput plugin not supporting country search on mobile view as keypad gets deactive when we open the list of countries.

### ISSUE THREAD

**Issue by BhupinderjeetKaur** [jackocnr/intl-tel-input#1076]
I am using intlTelInput js plugin and It works really smooth. One issue I am facing is that I am not able to search country name from list on mobile as keypad is not active when I open the country list.

**Comment by jackocnr** [comment]
I think on mobile devices you can only have the keyboard up when you're focused in an input, so I don't think this is possible unfortunately.

**Comment by jackocnr** [comment]
See new option `countrySearch` in v18.5.1. Let me know what you think!
