### ISSUE TITLE
how i can set country by dialCode ?

### ISSUE THREAD

**Issue by yasdeveloper** [jackocnr/intl-tel-input#1077]
hello

how i can set country by dialCode ?

example : set turkye by +90

with out set full number !?

**Comment by jackocnr** [comment]
This is not the [Recommended](https://github.com/jackocnr/intl-tel-input#recommended-usage) way to use the plugin, but if you absolutely must, you could use [getCountryData](https://github.com/jackocnr/intl-tel-input#static-methods) to look for your dial code and find the corresponding countryCode ("iso2") and then use setCountry with that.
