### ISSUE TITLE
Get selected country code and dial code in html/php submission form

### ISSUE THREAD

**Issue by Djas2017** [jackocnr/intl-tel-input#1079]
Hi, 

Let's assume that the phone input filed with international country selector in the html form which calls the submit_form.php  

How to get the selected country code in PHP? Want to return something like: <country code> <dial code> <phone number> (Ex: us +1 2222222222)

Thanks

**Comment by jackocnr** [comment]
I'm afraid this is outside the scope of the support I can provide. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).
