### ISSUE TITLE
"Undefined" error message when letter typed in input

### ISSUE THREAD

**Issue by LouisCuvelier** [jackocnr/intl-tel-input#1081]
### Steps to reproduce
1.  Update to the latest version (v17.0.0)
2.  Type a letter in the input field
3.  Error message says "Undefined"

### Expected behaviour
Like previous version, it should says "Invalid number".

### Possible solution
I search in the code and I saw that in 52211bd, you removed `"NOT_A_NUMBER": 4` in `validationError` and this piece of code : 
```js
if (e.message == i18n.phonenumbers.Error.NOT_A_NUMBER) {
    return 4;
}
```

I think it is the problem. 😄 
But, maybe it is a translation problem (I'm in French).

**Comment by jackocnr** [comment]
Are you using the getValidationError function? What is it returning?

**Comment by LouisCuvelier** [comment]
No, I have a minimal config like this :
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.0/js/intlTelInput.min.js"></script>

<script>
  var input = document.querySelector("#intlPhone");
  window.intlTelInput(input, {
    utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.0/js/utils.js",
    preferredCountries: ["fr"],
    hiddenInput: "Mobile",
    dropdownContainer: document.querySelector(".iti__flag-container")
  });
</script>
```
I'm using webpack but I tried with the CDN like above, and I've got the same error.

**Comment by LouisCuvelier** [comment]
Yes, it is returning `-99`

```js
  function checkPhone(input, errorMsg) {
    const iti = window.intlTelInputGlobals.getInstance(input);

    if (iti.isValidNumber()) {
      reset(input, errorMsg);
    } else {
      const errorCode = iti.getValidationError();
      console.log(errorCode); // Return '-99'
      errorMsg.innerHTML = errorMap[errorCode] || "Il y a une erreur.";
      showError(input, errorMsg);
    }
  }
```

**Comment by jackocnr** [comment]
Well if libphonenumber can't provide you with a specific error type, then I suggest you provide a generic fallback error message in this case, which it looks like you're trying to do - but it doesn't seem to be working - but that's outside the scope of the support I can provide - I'd suggest you ask on StackOverflow about that. Best of luck.

**Comment by ndraiman** [comment]
The issue seems to be in the utils script not handling the NOT_A_NUMBER case

![8E466E01-5292-40E0-ACBB-E656A61A313F](https://user-images.githubusercontent.com/12609607/113690825-809df200-96d4-11eb-8be2-bc3a5a9d73b5.jpeg)

Based on git history that case handling was dropped in v17.0.0
