### ISSUE TITLE
Laravel intégration

### ISSUE THREAD

**Issue by VConsulting** [jackocnr/intl-tel-input#1083]
Laravel integration

Unable to add intlTelInput to the Laravel.
I loaded intlTelInput via NPM

I added the require to app.js:
require ('intl-tel-input / build / js / utils');
require ('intl-tel-input / build / js / intlTelInput');

and CSS in app.scss:
@import "~ intl-tel-input / build / css / intlTelInput.css";

Then added a field for the input in my blade view:
<input id = "phone">

and the script:
``
     <script>
         var input = document.querySelector ("# phone");
         window.intlTelInput (input, {
             // any initialization options go here
         });
</script>
``
But I have the error:
  window.intlTelInput is not a function

What have I done wrong?

**Comment by jackocnr** [comment]
I have no experience with Laravel, so you'll have to remove that from the equation for me to be able to help you. If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

If you need help with Laravel code specifically, then I'd recommend you ask on StackOverflow.

**Comment by VConsulting** [comment]
Thank you for the answer, I installed directly via the <script> and <style> tags without going through Laravel Mix and it works, it's a shame not being able to integrate it into Mix.
Considering the number of users of the manual this would be a plus for the plugin.
Thank you

**Comment by victorybiz** [comment]
For anyone looking for a Laravel Blade and Livewire integration, try this `intl-tel-input` wrapping  package:
https://github.com/victorybiz/laravel-tel-input
