### ISSUE TITLE
Initialization of several phone fields on the same page

### ISSUE THREAD

**Issue by VConsulting** [jackocnr/intl-tel-input#1085]
Hello,
How to do when we have several phone fields on the same page?
I have a list of phone not known in advance, so it should be dynamically initialized on a class for example, I tried but only one is taken into account.

Is there a tip?

**Comment by jackocnr** [comment]
See the Multiple Instances example on the demo site.

**Comment by VConsulting** [comment]
Thank you I have already seen
Each field must be initialized :(
Since the number of fields is not known but dynamic it cannot work ...

**Comment by jackocnr** [comment]
Are you saying there are an unknown number of inputs on the page when you load the page, or that they can get added as the user is using the page?

If it's the former, just select them all with document.querySelectorAll() and then iterate through all of those results, and init the plugin for each of them.

If it's the latter, then you need a way to hook into the code that is adding the new input and init the plugin there.

**Comment by VConsulting** [comment]
Thanks but the no idea how to do it :(

**Comment by jackocnr** [comment]
I'm afraid this is outside the scope of the support I can provide. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).

**Comment by VConsulting** [comment]
Useless I will simply do without the plugin because it is more decoration than functionality.
Thanks for your help

**Comment by VConsulting** [comment]
good actually it's super simple with a night's rest the ideas are clearer :)
I invite you to add the example in your example page, thank you

`            var input = document.querySelectorAll(".phone");
            var i;
            for (i = 0; i < input.length; i++) {
                window.intlTelInput(input[i], {
                    initialCountry: "auto",
                    geoIpLookup: function (success, failure) {
                        $.get("https://ipinfo.io", function () {
                        }, "jsonp").always(function (resp) {
                            var countryCode = (resp && resp.country) ? resp.country : "";
                            success(countryCode);
                        });
                    },
                });
            }
`

**Comment by jackocnr** [comment]
Glad you figured it out :)
