### ISSUE TITLE
List of countries with dial codes

### ISSUE THREAD

**Issue by carloscarvallo** [jackocnr/intl-tel-input#1086]
### Question:
- Sorry for put this on issues, but is there a way to use intl-tel-input in a programmatic way, for example I'm only need the list of countries with the dial code to use it in a custom dropdown with my own markup, do you have some recommendations for this?

**Comment by jackocnr** [comment]
Sure you can import build/js/data.js to get the country data (inc dial codes). It also contains country codes (e.g. "us" for United States) which you can use to display flags as well if you want - you can see how we do this with class names by inspecting how it works on the demo page. For flags to work, you'd need to import the plugin CSS as well, and host the flags sprite and update the path to that in the CSS, as per the Getting Started section in the readme.

**Comment by carloscarvallo** [comment]
great @jackocnr, thank you, I'll take a look
