### ISSUE TITLE
Update libphonenumber to v8.12.3

### ISSUE THREAD

**Issue by arthutox** [jackocnr/intl-tel-input#1087]
### Expected behaviour
Pls update libphonenumber to v8.12.3
Many thx.

**Comment by jackocnr** [comment]
Thanks for raising this issue. It actually only takes 5 minutes to do this yourself, if you'd be willing to submit a Pull Request? Instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber). Thanks :)

**Comment by arthutox** [comment]
Hi @jackocnr ! I have problem with Update - https://github.com/jackocnr/intl-tel-input/issues/993#issuecomment-550317924, the same problem I had it my last ticket. I cant update it my self, can you help with update?

**Comment by arthutox** [comment]
Hi @jackocnr! I tried run `mvn compile` not `mvn -DskipTests` and it completed fine, without errors, but on the step 2, after run command - `ant -f libphonenumber/javascript/build.xml compile-demo` I have another errors -

    ```
 [exec] Error: Unable to access jarfile /Users/arthurfaria/project/libphonenumber-tools/libphonenumber/javascript/../../closure-compiler/target/closure-compiler-1.0-SNAPSHOT.jar
     [exec] calcdeps.py: JavaScript compilation failed.

BUILD FAILED
/Users/arthurfaria/project/libphonenumber-tools/libphonenumber/javascript/build.xml:99: The following error occurred while executing this line:
/Users/arthurfaria/project/libphonenumber-tools/libphonenumber/javascript/build.xml:23: exec returned: 1
```
<img width="883" alt="Screen Shot 2020-05-15 at 12 38 21 PM" src="https://user-images.githubusercontent.com/10230760/82036352-7d0f1000-96a9-11ea-881a-63ad2fd03688.png">

Please Can You help me?

**Comment by cweitat** [comment]
#1091 have already updated it to v8.12.3

**Comment by arthutox** [comment]
Hi @cweitat ! Manu thx! Waiting for release. and close this one. Thx again.
