### ISSUE TITLE
Creating large flag not working

### ISSUE THREAD

**Issue by Gabsys** [jackocnr/intl-tel-input#1088]
### Steps to reproduce
I followed the instruction on the "Large flags" example site but nothing changed. Am I missing something? 

1) Modified the width and height in retina -> sizes of responsive_images.js , 
2) Modified flagHeight and flagWidth of src -> css -> intlTelInput.scss 
3) ran "grunt build" (to be safe, I also ran "npm run build"). 
But turns out my flag size didn't change.

I realise no new img folder is built in the "build" folder after running grunt build / npm run build. Does this affect?

### Expected behaviour
A working set of JS, CSS & Img for large flag should be produced

### Actual behaviour
A set of JS & CSS is produced (although not sure if it matches my configuration), but no new flag img is produced

### Initialisation options
Was using demo.html to see the result. This is the initialisation code:

` window.intlTelInput(input, {utilsScript: "build/js/utils.js", });`

**Comment by jackocnr** [comment]
Sorry I changed how the grunt tasks work. You now have to run "grunt img" (which takes a while), then "grunt css" and it should work. I've updated the codepen. Thanks.

**Comment by jonahcastro** [comment]
grun img is not working. 

It says, "Warning: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%m:%T:%s" "node_modules/region-flags/png/AC.png" this most likely means the gm/convert binaries can't be found Use --force to continue."

**Comment by jackocnr** [comment]
Sounds like you don't have imagemagick installed properly - I'd try StackOverflow for help with this.

**Comment by jonahcastro** [comment]
> Sounds like you don't have imagemagick installed properly - I'd try StackOverflow for help with this.

Thanks for the response, @jackocnr. I already installed it and I still got the same error.

```
> intl-tel-input@17.0.5 build:img /Applications/MAMP/htdocs/intl-tel-input
> grunt img

Running "responsive_images:retina" (responsive_images) task
Warning: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%m:%T:%s" "node_modules/region-flags/png/AC.png" this most likely means the gm/convert binaries can't be found Use --force to continue.

Aborted due to warnings.


Execution Time (2020-10-01 22:02:32 UTC+8)
loading tasks              3ms  ▇▇▇▇ 6%
responsive_images:retina  43ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 91%
Total 47ms

npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! intl-tel-input@17.0.5 build:img: `grunt img`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the intl-tel-input@17.0.5 build:img script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
