### ISSUE TITLE
France +337xxxx is valid but not accepted

### ISSUE THREAD

**Issue by Zendfony** [jackocnr/intl-tel-input#1093]
Mobile number not working +33 7 29 57 01 09 but it is valid French mobile number

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

**Comment by jackocnr** [comment]
Libphonenumber says this number is invalid. You'll need to file an issue with them.
