### ISSUE TITLE
{{$1}} where pattern is created error $ undefined character

### ISSUE THREAD

**Issue by faheem121** [jackocnr/intl-tel-input#1095]
![image](https://user-images.githubusercontent.com/34395002/82538882-dbcf0080-9b65-11ea-8453-f691e8bc7f58.png)

this error came up.

**Comment by jackocnr** [comment]
That's your own code, not plugin code. I'm afraid this is outside the scope of the support I can provide. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).
