### ISSUE TITLE
+6086178113 returns valid but is invalid in libphonenumber

### ISSUE THREAD

**Issue by sitxseek** [jackocnr/intl-tel-input#1096]
Got a false positive with the number +6086178113. isPossibleNumber is true because the phone number seems to be in the correct format of +60 8x-xxx xxx, but isValidNumber returns false.

Result from the libphonenumber demo:

****Parsing Result:****
{"country_code":60,"national_number":86178113,"raw_input":"6086178113","country_code_source":10}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: MY
Result from getNumberType(): UNKNOWN

****ShortNumberInfo Results:****
Result from isPossibleShortNumber: false
Result from isValidShortNumber: false
Result from isPossibleShortNumberForRegion: false
Result from isValidShortNumberForRegion: false

****Formatting Results:**** 
E164 format: invalid
Original format: 60 86-178 113
National format: 086-178 113
International format: invalid
Out-of-country format from US: invalid
Out-of-country format from Switzerland: invalid

****AsYouTypeFormatter Results****
Char entered: 6 Output: 6
Char entered: 0 Output: 60
Char entered: 8 Output: 608
Char entered: 6 Output: 6086
Char entered: 1 Output: 60861
Char entered: 7 Output: 608617
Char entered: 8 Output: 6086178
Char entered: 1 Output: 60861781
Char entered: 1 Output: 608617811
Char entered: 3 Output: 6086178113

**Comment by arthutox** [comment]
Hi @sitxseek! I had the same error, Just write google support here, https://issuetracker.google.com/issues/new?component=192347&template=829703, then need update intl-tel-input

**Comment by jackocnr** [comment]
I've just updated to the latest version of libphonenumber, and now getting isValidNumber return false (see demo site). Thanks for reporting.
