### ISSUE TITLE
Remove JQuery dependency (geoIpLookup)

### ISSUE THREAD

**Issue by fanthomas** [jackocnr/intl-tel-input#1097]
Hello,

You say in the presentation that the **JQuery dependency has been removed**, but if I want to use " initialCountry : 'auto' ", **geoIpLookup still make its request with JQuery** while it could be done with pure JS (**XHTTP**).

Cool plugin man !

**Comment by jackocnr** [comment]
You define the function code for geoIpLookup yourself - so you can use any Ajax method you want!

**Comment by fanthomas** [comment]
Hello,

---
Yeah I've done it, but it's just that you can't say (omo) that the dependency has been completely removed. 
> IMPORTANT: since v14 we have removed the jQuery dependency. See below for how to initialise and use the plugin with pure JavaScript. If you want to stick with the jQuery version, there is now a separate jQuery wrapped version.

You say that we can initialize it with pure JS but that is false in the case of geoIpLookup using.

---

Solution for pure JS 🤗  :

```
geoIpLookup: function(callback) {
	
	var xhttp = new XMLHttpRequest();
	xhttp.onreadystatechange = function() {
		
		if (this.readyState == 4 && this.status == 200)
			callback(this.responseText.slice(0, 2));
		
	};
	xhttp.open("GET", "https://ipinfo.io/country", true);
	xhttp.send();
}
```
---

Salute ! ✌
