### ISSUE TITLE
Padding-left issue with separateDialCode and loading plugin CSS after initialising the plugin

### ISSUE THREAD

**Issue by jackocnr** [jackocnr/intl-tel-input#1099]
Forked from https://github.com/jackocnr/intl-tel-input/issues/965

Test case: https://codepen.io/JavierPAYTEF/pen/LYpvOJW

Here's my comment on this case, from the previous thread:

> I find this situation really strange - that you are managing to load the plugin JS and your custom initialisation JS before the plugin CSS has loaded.

> Please can you give more info about your specific setup? And everyone else in this thread - what setup are you using that means the plugin CSS is loading after both the plugin JS and your custom initialisation code?

> Is there no way for you to load the plugin CSS earlier? Or delay initialising the plugin until later?

cc: @JavierPAYTEF, @nitsujri 

Then I went on to mention a potential workaround, **if** this really was an unavoidable problem for a lot of people, which has yet to be decided. But even that would not work in a lot of cases, so I'm really reluctant to add it.

I'm tempted to stick to my original response in that other thread, from back in September, which is: it is a requirement in order to use the `separateDialCode` option, to ensure the plugin CSS is loaded before you init the plugin. (this would include an approach of having some kind of listener/callback for when the CSS has loaded, and only initialising the plugin then)

**Comment by ARiyou2000** [comment]
Thanks for it and i also had the same issue.
All you need to make it right is adding the following code.
```
section#contact #contactForm #phone {
  padding-left: 60px;
}
```

**Comment by jackocnr** [comment]
Sure this is a good workaround - just make sure you set the number high enough to cover dial codes with 3 digits.

In fact this is all my proposed workaround would be doing anyway, and it actually makes more sense for the dev to do this themselves anyway, so they can set it to a number that works for their design. Closing.

**Comment by phimuskapsi** [comment]
Wanted to leave a note here, I ran into the same problem when I dropped this into a Custom Element I made as a wrapper. 

What I had to do was instead of using a link tag, was within the style tags of the template, I added an "@import" line that pointed to my local copy. This immediately fixed the issue.
