### ISSUE TITLE
Country drop down menu hide under text area

### ISSUE THREAD

**Issue by ARiyou2000** [jackocnr/intl-tel-input#1101]
### Steps to reproduce
1.  I tried to change z-index of the drop down menu to be more than other elements But it's not working.

### Expected behaviour
Drop down list must show over other inputs(elements).

### Actual behaviour
The drop down hide under Text area or Text input and button and etc.
Actually it works fine when it opens from down to up but its have issue when it open from up to down.

### Initialisation options
Bootstrap 4.3 (Bootstrap Studio Version 5.0.3)

```
// allowDropdown: false,
      // autoHideDialCode: false,
      // autoPlaceholder: "off",
      // dropdownContainer: document.body,
      // excludeCountries: ["us"],
      // formatOnDisplay: false,

      geoIpLookup: function(callback) {
         $.get("http://ipinfo.io", function() {}, "jsonp").always(function(resp) {
           var countryCode = (resp && resp.country) ? resp.country : "";
           callback(countryCode);
         });
       },

       hiddenInput: "full_number",
       initialCountry: "auto",
      // localizedCountries: { 'de': 'Deutschland' },
      // nationalMode: false,
      // onlyCountries: ['us', 'gb', 'ch', 'ca', 'do'],
      // placeholderNumberType: "MOBILE",
       preferredCountries: ['us', 'jp', 'ir'],
      // separateDialCode: true,
      utilsScript: "./utils.js",
```

**Comment by jackocnr** [comment]
Sorry, like the other issue, you're free to apply your own z-index rules to the plugin markup however you like, so I'd say this is just a pure CSS question, so I'd recommend you try StackOverflow.

**Comment by ARiyou2000** [comment]
I tried to give Z-Index but it's not working and it's the reason i report it as a bug.

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by fullstackguru0711** [comment]
Same issues for me, Any solution for the issues that hide dropdown under textarea?
