### ISSUE TITLE
Double click Select all country name

### ISSUE THREAD

**Issue by ARiyou2000** [jackocnr/intl-tel-input#1102]
### Steps to reproduce
1.  The following lines must added to the CSS.
```
.iti__flag-box, .iti__country-name, .iti__dial-code {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

### Expected behaviour
The user should not to be able to select country name and text.

### Actual behaviour
All text in Drop down menu are selectable. I see that issue when i suddenly double click on flag to open drop down menu then i see all text are selected and it looks ugly.

### Initialisation options
Bootstrap studio V5.0.3

**Comment by jackocnr** [comment]
Well that dropdown is just a div with some text in - it's free for you to style however you want. We don't add any styling to force the user-select behaviour. So I'd say this just a standard CSS question, not specific to the plugin, so I'd recommend you try on StackOverflow.
