### ISSUE TITLE
component is initialized as dirty

### ISSUE THREAD

**Issue by jadavi** [jackocnr/intl-tel-input#1104]
### Steps to reproduce
1.  Go to https://stackblitz.com/edit/ngx-intl-tel-input-demo
2.  Add these lines on app.component.html:
 ```
 <div><strong>Is input pristine:</strong> <pre>{{ f.form.controls['phone'].pristine }}</pre></div>
  <div><strong>Is input dirty:</strong> <pre>{{ f.form.controls['phone'].dirty }}</pre></div>
```
3.  Refresh the right panel

### Expected behaviour
Is input pristine: true
Is input dirty: false

### Actual behaviour
Is input pristine: false
Is input dirty: true

**Comment by jackocnr** [comment]
Wrong repo
