### ISSUE TITLE
US placeholder format incorrect when using separateDialCode

### ISSUE THREAD

**Issue by moortown76** [jackocnr/intl-tel-input#1110]
### Steps to reproduce
1.  separateDialCode: true
2.  
3.  

### Expected behaviour
Format for US in placeholder should be (123) 456-7890

### Actual behaviour
MIssing last digit. It reads like this:
(123) 456-789

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries
autoHideDialCode: false,
formatOnDisplay: true,
hiddenInput: "full_number",

<img width="371" alt="Screen Shot 2020-06-19 at 6 24 35 AM" src="https://user-images.githubusercontent.com/23351173/85123289-fe504a00-b1f5-11ea-8268-c6e583e11277.png">

**Comment by jackocnr** [comment]
Hmm I can't reproduce this: https://codepen.io/jackocnr/pen/mdVWmwq

Are you sure you're using the latest version? Can you reproduce it in a codepen?

**Comment by moortown76** [comment]
Sorry!  I had another plugin conflicting with this.

However I still did notice inconsistent formatting between when separate dial code is set to true or false. See attached.

Thanks!

PS - preference would be (201) 123-1234

**Comment by jackocnr** [comment]
Glad you got it resolved.

When you have separateDialCode enabled, we're always displaying the international dial code next to the number, so the idea is that it's part of the number, which is why we choose international number formatting.

**Comment by moortown76** [comment]
Understood. Thanks! Love this plugin.
