### ISSUE TITLE
Displaying country list before input element

### ISSUE THREAD

**Issue by milosevicn** [jackocnr/intl-tel-input#1111]
### Steps to reproduce
I have updated from an older version to the latest one using npm. Since I've used the jQuery before, and for this version jQuery dependency has been removed, I have adopted my code to use this plugin with Vanilla JS (according to instructions given in Readme file).

### Actual behaviour
I've got no errors, but instead of drop down list with flags, I am getting all the countries displayed as an unordered list and input field after them, but the input field is not a drop down. As a matter of fact this input is being filled with predefined value (and it should, since I am passing it) and the number I am passing there is being correctly formatted (from "+381640123456" to "0640123456") which means that the script works.
I am using Vue and initialising the way it mentioned to be, on component mount:
```
mounted: function() {
        var self = this;
        var input = document.querySelector('[data-id="'+this.input_id+'"]');
        Vue.nextTick(function() {
        	self.input = window.intlTelInput(input, {
            	utilsScript: "/js/vendor/phone/utils.js"
            });
            if(self.entry[self.field]) {
            	self.input.setNumber(self.entry[self.field]);
            }
        });
    },
```

I was thinking this could have something with CSS, but can't seem to find where the problem really is. Maybe I haven't updated the package the way I should? Would be glad if someone help me with this. Thanks!

**Comment by jackocnr** [comment]
Yeah it sounds like the styling isn't working properly, so I'd double check you're loading the CSS file correctly.

Beyond that... if you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by milosevicn** [comment]
@jackocnr Can't reproduce the same problem I am facing, but the code looks similar to this. I have placed my whole CSS file since I don't know which part is causing the problem. Check it and if you see something weird, please tell me. If there's no problem with this code itself, then you can close this thread since I am going to assume it's the CSS and continue fixing it on my side. Thank you for your time!

Codepen:
https://codepen.io/burazzer/pen/rNxmmXV

**Comment by andrewr224** [comment]
For any other lost soul who ends up here - this is css loading issue. The list of countries signifies that js works, so fixing this is a matter of loading css properly
