### ISSUE TITLE
Always getting wrong country code in Get

### ISSUE THREAD

**Issue by RedSmarty** [jackocnr/intl-tel-input#1113]
### Steps to reproduce
1.  Set Up int-tel-input.
2.  Set all initialisation options listed below.
3.  Try to get number by iti.getNumber.

### Expected behaviour
The plugin should return phone number with actual country selected.

### Actual behaviour
It always returns a number with USA tel code +1 no matter which country is selected.

### Initialisation options
utilsScript, prefferedCountries, initialCountry, getNumber with iti properly defined.

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by RedSmarty** [comment]
Hey, thanks for the reply.
It look like i was using iti in a wrong way. I saw your pen and corrected it. It now works like a charm.
And i do have another question. You have written in readme that you no longer need jquery 
but it itself uses it in document .getQuerySelecter initializer. How can i avoid that?
And is this free for commercial use?

**Comment by jackocnr** [comment]
Please can you link to where you think you're seeing jQuery in the source code.

And yes it's free for commercial use.

**Comment by RedSmarty** [comment]
here :-
`<script src="path/to/intlTelInput.js"></script>
<script>
  var input = document.querySelector("#phone");
  window.intlTelInput(input, {
    // any initialisation options go here
  });
</script>`
can i simply replace 
`document.querySelector('#phone);`
 with 
`document .getElementById('phone');`
and there is no other jquery code?
can i replace id phone with something else?
Sorry is this is dumb question.

**Comment by jackocnr** [comment]
Actually document.querySelector is pure JavaScript, not jQuery!
