### ISSUE TITLE
Support for ES Modules

### ISSUE THREAD

**Issue by Christian-Seiler** [jackocnr/intl-tel-input#1114]
Would you be supporting ES Modules?

**Comment by jackocnr** [comment]
Yes you can import the plugin using ES modules:

`import intlTelInput from 'intl-tel-input';`

**Comment by spatocode** [comment]
I think this usage should be documented.

**Comment by jackocnr** [comment]
Yes I think you're right. I'd like to split up the Getting Started section of the readme into 2 sub-sections: first "Using a bundler e.g. Webpack", which says:

(1) Install with npm: `npm install intl-tel-input --save` or yarn: `yarn add intl-tel-input`
(2) Import CSS: `import 'intl-tel-input.css';` - NOTE: haven't checked this actually works? Implied from this commit: https://github.com/jackocnr/intl-tel-input/commit/b6c8c3b6738064df79e0e9e6a8f7915c790c5873
(3) Override the path to flags.png in your CSS (same as current section)
(4) Import JS and initialise plugin: `import intlTelInput from 'intl-tel-input'; ........ (init code)`
(5) Recommended utilsScript section (same as current section)

And then the second section is called "Not using a bundler", and the content is the same as what's currently there.

Would you be up for putting that together in a PR?

**Comment by jackocnr** [comment]
Thanks @spatocode, any update on this?

**Comment by jackocnr** [comment]
No worries, I've got some time today - I'll do it.
