### ISSUE TITLE
getNumber() function is not working

### ISSUE THREAD

**Issue by SourabhDogra1511** [jackocnr/intl-tel-input#1117]
Thank you for the wonderful plugin.
I integrate the plugin as you instructed to get started.
In the UI it displays all the country flag with code, but when I trying to retrieving the value than giving me blank.

`<link rel="stylesheet" href="{{ asset('argon') }}/assets/css/intlTelInput.css">`
`<input type="tel" class="form-control" placeholder="Phone *" id="phone" name="mobno" required="" value="" />`

`<script src="{{ asset('argon') }}/assets/js/intlTelInput.js"></script>`
 ` <script type="text/javascript">`
  `  var input = document.querySelector("#phone");`
  `  window.intlTelInput(input, {`
   `allowDropdown: true,`
    `  autoHideDialCode: true,`
     ` autoPlaceholder: "on",`
   `   dropdownContainer: document.body,`
      `excludeCountries: ["us"],`
    `  formatOnDisplay: true,`
      `hiddenInput: "full_number",`
     ` initialCountry: "auto",`
      `nationalMode: true,`
     ` placeholderNumberType: "MOBILE",`
     ` separateDialCode: true,`
      `utilsScript: "{{ asset('argon') }}/assets/js/utils.js",`
   ` });`
 ` </script> `

Here is the code of retrieving the value.
I try with getExtension(); it is also not working for me.

`<script>`
`var iti = intlTelInput(input);`
 `var number = iti.getNumber();`
`alert(number);`
`</script>`

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by SourabhDogra1511** [comment]
Thank you @jackocnr for the quick reply.
Here is the code pen [link](https://codepen.io/sk1511/pen/JjGvPQy)

**Comment by jackocnr** [comment]
In `getValue` you are re-initialising the plugin - that will be the problem. You just need to drop that first line in that function and it should work fine.

**Comment by SourabhDogra1511** [comment]
@jackocnr thank you its working
