### ISSUE TITLE
Avoid an Execive Dom size

### ISSUE THREAD

**Issue by shajeermhmmd** [jackocnr/intl-tel-input#1119]
### Steps to reproduce
1.  Open a website integrated intl-tel-input 
2.  Go to google console
3.  open the Lighthouse for the performance

### Expected behaviour
Working perfectly but loading Execive dom elements

### Actual behaviour
![image](https://user-images.githubusercontent.com/12708552/87285589-5847e500-c500-11ea-9fcd-40b5d536b0a7.png)

### Initialisation options
var input = document.querySelector(".ff_phone");
 var iti = window.intlTelInput(input, {
            utilsScript: "<?php echo base_url(); ?>assets/public/country-code/js/utils.js",
            initialCountry: "qa",
        });

Please help me to solve this problem.
Thank you

**Comment by jackocnr** [comment]
But do you still see this issue if you remove the plugin? Looks to me like your biggest issue is just having over 3000 DOM nodes in your document, of which, maybe 300-500 are from the plugin, but the rest is just your custom code.

**Comment by shajeermhmmd** [comment]
> But do you still see this issue if you remove the plugin? Looks to me like your biggest issue is just having over 3000 DOM nodes in your document, of which, maybe 300-500 are from the plugin, but the rest is just your custom code.

I will check that, and update you. Thank you

**Comment by shahid1579** [comment]
@jackocnr 
My code:
var iti = window.intlTelInput(input, {
  utilsScript: <?= base_url(); ?>+"/assets/js/utils.js?1590403638580"
});

**Error:**  http://localhost/ecoguard/build/js/utils.js?1590403638580 net::ERR_ABORTED 404 (Not Found)
Why It is pointing to build/js

**Comment by jackocnr** [comment]
I'll close this for now.
