### ISSUE TITLE
Placeholder don't show

### ISSUE THREAD

**Issue by 12cassie34** [jackocnr/intl-tel-input#1120]
### Steps to reproduce
1. Downloaded the plugin through npm.
2.  html 
`<input type="tel" id="phone" class="form-control" required>`
3.  js
```
var input = document.querySelector("#phone");
window.intlTelInput(input, {
    initialCountry: "jp",
    separateDialCode: true
});
```
  

### Expected behaviour
There should be a placeholder in `<input>`.

### Actual behaviour
Placeholder don't show.
<img width="716" alt="Screen Shot 2020-07-14 at 11 49 20 AM" src="https://user-images.githubusercontent.com/35912741/87381831-2c903200-c5c8-11ea-9094-843de1b152d3.png">

### Initialisation options

Thank you for reviewing this issue :)

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by Shanyu82321** [comment]
Hi,

Thank you for your reply! 
I posted my code in the code-pen, it seems that everything works fine, but not in my app.

**Comment by jackocnr** [comment]
Hmm I'm guessing there's a problem somewhere else in your code then. I'm afraid I can't really help unless you can reproduce the issue, so I'll close this for now, but please do post again if you find a way to repro.

**Comment by callshark** [comment]
@12cassie34 Make sure you include the `utilsScript` when you initialize the plugin.

So, in your example, use this instead:

window.intlTelInput(input, {
    initialCountry: "jp",
    separateDialCode: true,
    utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@17.0.3/build/js/utils.js",
});

**Comment by 12cassie34** [comment]
@callshark 

Oh, I just added `utilsScript` and it works.
Thank you so much for the solution you provided! 

Happy coding to you.

**Comment by callshark** [comment]
@12cassie34 I'm glad to hear it! Thanks for letting me know it worked. :)
