### ISSUE TITLE
about input mask

### ISSUE THREAD

**Issue by esakarya** [jackocnr/intl-tel-input#1121]
its doesnt support input mask ?

**Comment by esakarya** [comment]
dont say me check past issues. i check all i cant find any easy way.

**Comment by jackocnr** [comment]
Really? If you search for "input mask" and click on "issues", results 5 and 6 will answer your question.

**Comment by jackocnr** [comment]
Or if they don't answer your question, you will need to give me much more detail / an example of what you want!

**Comment by esakarya** [comment]
boss i try all samples. also find similar this codes. but doesnt gelp. why you wont add similar usage just mask = true ?

`   $('.cm-mask-phone').keydown(function(e)
    activePlaceholder = $this.attr('placeholder'),
        newMask = activePlaceholder.replace(/[1-9]/g, "0");

    $this.mask(newMask);
  }`

**Comment by peteichuk** [comment]
To enable input mask, try set parameter
`autoPlaceholder: 'aggressive',`
