### ISSUE TITLE
remove unuset countries from utils.js

### ISSUE THREAD

**Issue by esakarya** [jackocnr/intl-tel-input#1122]
Hi, i want use this script. its looking amazing. but almost 300kb  increased our page total size. i will use only 3 country ,  can you offer me about this ?

**Comment by jackocnr** [comment]
Hi there. Please see the `utilsScript` option to lazy load the utils script, so it doesn't slow down your inital page load.

I'm afraid there is no way to limit the countries.

**Comment by esakarya** [comment]
any sample for lazy load ?  your documention really poor.
