### ISSUE TITLE
How can we Search a Country Code

### ISSUE THREAD

**Issue by shahid1579** [jackocnr/intl-tel-input#1123]
How to show a search bar on top to search your country or code ?

**Comment by jackocnr** [comment]
You can just type the country name when the dropdown is open. No plans to add a search input at this point.

**Comment by shahid1579** [comment]
@Thanks

**Comment by bilalsds** [comment]
It is not good user experience we need to show search bar to user in which he/she can search country. I try for customise but when dropdown open no event are happened then so How I will allow my event when dropdown open ?

**Comment by jackocnr** [comment]
See new option `countrySearch` in v18.5.1. Let me know what you think!

**Comment by CodeSprint01** [comment]
@jackocnr I used this version but country flag is not showing.

**Comment by jackocnr** [comment]
@CodeSprint01 please open a new issue, and fill in the template properly, maybe include a screenshot if relevant.
