### ISSUE TITLE
Mandatory country select

### ISSUE THREAD

**Issue by collimarco** [jackocnr/intl-tel-input#1124]
### Steps to reproduce
Create a simple tel input in a form and initialize this library as described in the getting started guide.

### Expected behaviour
The user MUST select a country or enter an international prefix.

### Actual behaviour
The user can enter a number without selecting the country and submit the form.

How can you prevent the user from submitting the form if the country is empty? i.e. make the country select a required field in order to allow only numbers in international format

**Comment by jackocnr** [comment]
Just listen for the submit event in the JS and show an error if they haven't selected a country.
