### ISSUE TITLE
How to implement utils.js using webpack ?

### ISSUE THREAD

**Issue by akshayp660** [jackocnr/intl-tel-input#1126]
### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
we should somehow load utils.js with window.intlTelInput=require('intl-tel-input'); in app.js itself that will reduce request and save manual work

### Actual behaviour
when using web pack user adds window.intlTelInput=require('intl-tel-input'); to app.js but the problem is it is dependent on utils.js so to make functional we have to manually set path to utils which create +1 js load request.

**Comment by jackocnr** [comment]
Please see https://github.com/jackocnr/intl-tel-input#recommended-usage
