### ISSUE TITLE
block input with flag or change following country select choose

### ISSUE THREAD

**Issue by leccyril** [jackocnr/intl-tel-input#1130]
hello, 

we want to know how to block for one input flag to one specifiq country

and we want to automatically change the flag on country selected ? 

how we can do it ? 

thanks !

**Comment by jackocnr** [comment]
Hi there, I'm afraid I don't understand. Please can you explain in more detail, and provide a specific example? Thanks.

**Comment by leccyril** [comment]
https://snipboard.io/edS8TL.jpg

on the screenschot on red for now we can deliver in only one country, we want the country flag to be blocked on the same country (here CAP VERT)

on blue color, if i change country to italy for example we want the flag country change automatically to italy !

but we don't know how to do it with your code -D

thank you very much !

**Comment by jackocnr** [comment]
> on the screenschot on red for now we can deliver in only one country, we want the country flag to be blocked on the same country (here CAP VERT)

See `allowDropdown` option.

> on blue color, if i change country to italy for example we want the flag country change automatically to italy !

It should work like that by default - what issue are you seeing? Please describe the exact steps you take, and what you expect to happen, and what actually happens.

Cheers.

**Comment by leccyril** [comment]
i modify country on another select input (not relatedà i would like to the flag change according to the other select input modified.

for allowdropdown we can do it event for one input on a form where is present 2 others phone input ? thak you

**Comment by jackocnr** [comment]
> i modify country on another select input

See "Country Sync" example on https://intl-tel-input.com/

> for allowdropdown we can do it event for one input on a form where is present 2 others phone input ?

You can initialise the plugin once for each input, and you can pass different options each time.

**Comment by leccyril** [comment]
And how to deativate for one input ? there is 2 type phone input , in 2 form but one have to be validated and other we don't want dropdown, we don't want flag we want a normal input how to process it ?

**Comment by leccyril** [comment]
Moreover we saw this number is not valid : 5850597 ! it comes from google lib and with capoverde do you think it is possible to deactivate validation on this kind number start with 5 ? 

thank you

**Comment by leccyril** [comment]
ok i saw it was a bug from older version upgrading utils.js fix the issue

**Comment by jackocnr** [comment]
Great. Closing.
