### ISSUE TITLE
How to check number is Valid or Not

### ISSUE THREAD

**Issue by shahid1579** [jackocnr/intl-tel-input#1132]
iti.setNumber("+447733123456");
I am using this to get previously submited value.
Now i want to show it is valid or not.
Please tell me

**Comment by shahid1579** [comment]
@jackocnr  Dear Please Reply

**Comment by jackocnr** [comment]
https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html

**Comment by shahid1579** [comment]
No WHen Form reload and if any field is missing so i am again putting number using it.setNumber()
But it is not showing that it is valid or not but when i click on it and mouseout then it will show it is valid.
I want to show valid at the same time when i set number

**Comment by jackocnr** [comment]
That example calls iti.isValidNumber() in the blur callback, but you can call it wherever you want. So you can call that straight after calling setNumber if you want...

**Comment by shahid1579** [comment]
yeah i am calling it after set number but it is getting Null value

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by shahid1579** [comment]
Here is my [code pen](https://codepen.io/shahid099/pen/KKzdLrK) @jackocnr

**Comment by jackocnr** [comment]
The problem is that you're calling isValidNumber before the utils script has loaded. Please see the readme, for the utilsScript option, about it returning a Promise, and using .then() to run code after it has finished loading.

https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/init-promise.html

**Comment by shahid1579** [comment]
Thanks Alot Dear @jackocnr
