### ISSUE TITLE
Chrome Dev Tools insect element is very slow on pages with intl-tel-input

### ISSUE THREAD

**Issue by dima-horror** [jackocnr/intl-tel-input#1134]
Problem on demo page (not really slow, but you can see problem)  https://www.screenpresso.com/=aYjT
The same on our page (extremely slow)) https://www.screenpresso.com/=bFT4f

### Steps to reproduce
1.  Open demo site https://intl-tel-input.com/ in Chrome (latest)
2.  Open Dev Tools, click to "Select an element on page" (or Ctrl+Shift+C)
3.  Move cursor around page. Everything is very slow (on demo page not really, but on our prod pages it's extremely slow)
4.  Open countries dropdown of intl-tel-input and try to "Select an element on page" again. Now the chrome render dev tooltips 
normally (very quickly).

### Expected behaviour
Quick render of chrome help tooltips

### Actual behaviour
While intl-tel-input counties dropdown is hidden page is lagging.

### Initialisation options
No matter. It can be reproduced on demo page

**Comment by jackocnr** [comment]
I cannot reproduce this. It is just as fast as this Github Issue page for me.
