### ISSUE TITLE
getNumber() doesnot work

### ISSUE THREAD

**Issue by kotaibahRed** [jackocnr/intl-tel-input#1135]
### Expected behaviour
return full number

### Actual behaviour
return null

### Initialisation options
var iti = window.intlTelInput(input, {
            // any initialisation options go here
            initialCountry: "LB",
            nationalMode: true,
            utilsScript: "{{asset('js/int-phone-num/utils.js')}}",
        });

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by asologor** [comment]
@kotaibahRed  I encounter the same behavior if utils script is not loaded. Check the `window.intlTelInputUtils` object in your browser console to ensure that utils were loaded.

**Comment by jackocnr** [comment]
Thanks @asologor. Yes as per the readme, getNumber requires the utils script to be loaded to work. Closing this for now, but let me know if you have any questions.

**Comment by GoudekettingRM** [comment]
I just tried using the getNumber method as well, but am running into the same problem. I defined my input options like this: 
```js
const intlPhoneInputOptions = {
  customContainer: 'inputField__text',
  utilsScript: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js',
};
```
And then in my class I initialise the input like so (`this.input` is just a selected inputfield from the dom): 
```js
this.intlInput = intlTelInput(this.input, intlPhoneInputOptions);
```

I subsequently add this to the input to check for when the country changes:
```js
    this.input.addEventListener('countrychange', () => {
      console.log('country changed');
      console.log('this.intlInput.getNumber()', this.intlInput.getNumber());
    });
 ```


I do see the strings being logged, but the `this.intlInput.getNumber()` remains empty.

**Comment by GoudekettingRM** [comment]
Alright, I got it to work by not using the cdn, but moving the utils script to a public folder in my app!

**Comment by rod-dd** [comment]
@GoudekettingRM this idea helps me. thanks.
