### ISSUE TITLE
Can't load intlTelInput.js file while running site

### ISSUE THREAD

**Issue by kir-smarty** [jackocnr/intl-tel-input#1139]
### Steps to reproduce
1.  install package
2.  setup gulp to copy file from node_module
3.  import intltelinput.js file into a typescript code
           **import intlTelInput from 'intl-tel-input';**
4.   Then,
           **var input = document.getElementById("mobileNo");
           intlTelInput.intlTelInput(input);**
5.  run code

### Expected behaviour
At this point, the web page should render a dropdown correctly with international codes

### Actual behaviour
The input element doesn't convert to a dropdown. No changes. Upon checking Developer Tools, noticed that the site is not loading intltelinput.js file. 

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
This sounds like an issue with your build process, which is outside the scope of the support I can provide. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).
