### ISSUE TITLE
I want to remove flag when enter wrong country code 

### ISSUE THREAD

**Issue by riyas145** [jackocnr/intl-tel-input#1140]
I have add country country field when enter wrong code like +914 it's shows india flag i want to remove flag image when country code is wrong 
![screenshot-qa way2smile com-2020 08 29-11_27_54](https://user-images.githubusercontent.com/57698276/91629929-fd6c2f00-e981-11ea-88c2-34ba08576bc8.png)

**Comment by jackocnr** [comment]
It sounds like you want to have a separate input for the country dial code, and for the main number, which is not supported by this plugin.

I suggest you use a single input, and enable separateDialCode option.

**Comment by riyas145** [comment]
Yes, But now i wrote custom function for that. I can have all country codes used in your project  in CSV or Json format?

**Comment by jackocnr** [comment]
You should be able to import allCountries data from build/js/data.js
