### ISSUE TITLE
Whether I need to pay in order to use geoIpLookup?

### ISSUE THREAD

**Issue by diaolanshan** [jackocnr/intl-tel-input#1142]
Is there anyone can answer this question?

I try to use this:
`geoIpLookup: function(success, failure) {
    $.get("https://ipinfo.io", function() {}, "jsonp").always(function(resp) {
      var countryCode = (resp && resp.country) ? resp.country : "";
      success(countryCode);
    });
  },`

should I buy a license from ipinfo.io if I have a lot of user and will query the country information frequentlyu?

**Comment by nafetswirth** [comment]
@diaolanshan yeah afaik you will need to pay for the IP lookup service yourself [here](https://ipinfo.io/). 50k lookups are free per month according to their [pricing](https://ipinfo.io/pricing)

**Comment by ashish02121** [comment]
I am using this service which is completely free with unlimited lookups
 https://api.apiclub.in/api/v1/getip for getting IP address and 
 https://api.apiclub.in/api/v1/ip_track/<ip_address> to fetch country.
 Although we need to register and get API key.

**Comment by srushtiKan123** [comment]
is there any alternative of it ?? any free version ?
