### ISSUE TITLE
Accessibility update

### ISSUE THREAD

**Issue by iesoftwaredeveloper** [jackocnr/intl-tel-input#1143]
https://github.com/jackocnr/intl-tel-input/blob/3b3ab1140eeafa861ba4fc22e086a7eb589a1ee1/src/js/intlTelInput.js#L360

While doing an accessibility audit, my tools indicated the following WGAC A issue.
"Select box has no description"
A suggested fix would be to add an aria-label to the countryList element.  This will resolve the accessibility issue.
Another option is to add a "title" attribute.  Either will resolve the issue.  However, using title will cause the text to appear on a hover of list items.

**Comment by jackocnr** [comment]
Thanks for raising this issue. I prefer the aria-label solution. I'm afraid I don't have time to work on this myself right now, but would welcome a pull request.

**Comment by iesoftwaredeveloper** [comment]
Pull request submitted.  I will close the issue and let it be tracked via the pull request.
