### ISSUE TITLE
country code is not present when sen the form

### ISSUE THREAD

**Issue by ph1823** [jackocnr/intl-tel-input#1146]
### Steps to reproduce
1.  Install with npm
2.  create input
3.  setup script

### Expected behaviour
Value input with nation code in form data when send a form

### Actual behaviour
Value input phone but no nation code in the value ..

### Initialisation options
        separateDialCode: true,
        preferredCountries: ["fr", "be", "ch", "ca"],
        initialCountry: "fr",

**Comment by jackocnr** [comment]
if you're submitting the form with ajax, then you can use the `getNumber` method to get the full number with international dial code.

if not, you can use the `hiddenInput` option for this.
