### ISSUE TITLE
country code conflict

### ISSUE THREAD

**Issue by charan-techv** [jackocnr/intl-tel-input#1148]
In INTL-TEL-INPUT plugin there is a country codes with same numbers 
ex: UK, Guernsey, Isle of man having +44 codes.
When user try to call UK automatically it is switching to Guernsey as per array hierarchy.
Can any one help me out from this issue .

**Comment by jackocnr** [comment]
This is not enough information for me to look into the issue effectively. Please read the [New Issue Checklist](https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist) and if necessary, open a new issue and follow the [New Issue Template](https://raw.githubusercontent.com/jackocnr/intl-tel-input/master/.github/ISSUE_TEMPLATE.md). If you are including any code, please [format it correctly](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).
