### ISSUE TITLE
Pressing Enter to select a country/region will not re-verify the phone

### ISSUE THREAD

**Issue by jixingLiu** [jackocnr/intl-tel-input#1150]
If I choose enter in the project notes,
 the country and region will not be retrieved. 
At the same time, please note that this problem has been resolved [#179](https://github.com/EducationLink/vue-tel-input/issues/179). 
Has the code been merged and released?

**Comment by kkoomen** [comment]
@jackocnr When can this fix be released?

**Comment by jackocnr** [comment]
That's a different project
