### ISSUE TITLE
Swaziland should be renamed to Eswatini

### ISSUE THREAD

**Issue by trojanc** [jackocnr/intl-tel-input#1164]
### Steps to reproduce
1.  Open the dropdown and scroll to Swaziland

### Expected behaviour
`Swaziland` has been renamed to `Eswatini` in 2018
https://en.wikipedia.org/wiki/Eswatini

### Actual behaviour
It still displays as Swaziland

### Initialisation options
Any method to get the plugin to load should result in the same behaviour...

https://github.com/jackocnr/intl-tel-input/blob/master/src/js/data.js#L1125

**Comment by jackocnr** [comment]
Merged your PR, thanks again.

**Comment by trojanc** [comment]
I'm not sure if my PR messed it up, but it appears South Africa is now displaying the wrong flag... I'll check before my PR now...
![image](https://user-images.githubusercontent.com/7879229/97674742-b0e2c400-1a96-11eb-9e65-d32c752576c6.png)
