### ISSUE TITLE
Issues with Belgian phone numbers

### ISSUE THREAD

**Issue by clusterr023** [jackocnr/intl-tel-input#1166]
I have an input field with intl-tel-input initialised:
var input = document.querySelector("#gsm");

    var iti = window.intlTelInput(input, {
        utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js", initialCountry: 'be', separateDialCode:true
    });

If i enter a Belgian phonenumber: 471 12 12 12 Whenever i get to this:  471 12 12 1 the iti.getValidationError() returns 0 => valid but the iti.isValidNumber() returns false. How does this come? 471 12 12 1 is not a valid number there is a digit missing.

Output results: 
Yellow circles indicate that it says false but code is 0. 
![phonevalidation1](https://user-images.githubusercontent.com/44799769/97604237-8dc00200-1a0d-11eb-8349-eab2ad826e29.jpg)

A second problem is with the phone numbers that start with +32455, +320455, +32456 and +320456. These are valid number prefixes but the methods say they are not. 

Source: https://en.wikipedia.org/wiki/Telephone_numbers_in_Belgium#Mobile_numbers

Output result:
Yellow circles indicate that it says false but code is 0. The last output line still says the result is false.
![phonevalidation2](https://user-images.githubusercontent.com/44799769/97604238-8e589880-1a0d-11eb-96fd-b562f5d04358.jpg)

Any idea what i am missing or doing wrong?

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by clusterr023** [comment]
The problem has been found and solved. This can be closed.
