### ISSUE TITLE
Not compatible with resolve-url-loader 3.0+

### ISSUE THREAD

**Issue by Daniel4Digital** [jackocnr/intl-tel-input#1167]
# Steps to reproduce
1. Having Resolve url loader above 3.0+  
2. Having last version of intl-tel-input (17.0.8)
3. Try to run: npm run dev

### Expected behaviour
It should be successfull

### Actual behaviour
It gives error:
`These relative modules were not found:

* ../../../node_modules/node_modules/intl-tel-input/build/img/flags.png in ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/dist/cjs.js??ref--5-5!./resources/assets/sass/app.scss
* ../../../node_modules/node_modules/intl-tel-input/build/img/flags@2x.png in ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/dist/cjs.js??ref--5-5!./resources/assets/sass/app.scss
                                              `

### Possible solution:
By editing "intlTelInput.scss" and replace:
background-image: url("#{$flagsImagePath}#{$flagsImageName}.#{$flagsImageExtension}");
background-image: url("#{$flagsImagePath}#{$flagsImageName}@2x.#{$flagsImageExtension}");

with:
background-image: url("../#{$flagsImagePath}#{$flagsImageName}.#{$flagsImageExtension}");
background-image: url("../#{$flagsImagePath}#{$flagsImageName}@2x.#{$flagsImageExtension}");

This solves the issue. Dunno if the best approach.

**Comment by NouranMahmoud** [comment]
Hey, I faced almost the same issue and webpack complaints but I solved it by only overriding the variable `flagsImagePath`

my.scss file:
```
$flagsImagePath: "../images/";
@import 'intl-tel-input/src/css/intlTelInput';
```

**Comment by slavabogov** [comment]
It can also be solved like this:

```scss
$flagsImagePath: '~intl-tel-input/build/img/';
@import '~intl-tel-input/src/css/intlTelInput';
```

**Comment by jackocnr** [comment]
Thanks guys. Sounds like there's an easy workaround, so closing this for now, unless anyone thinks the library itself really needs to be changed here?
