### ISSUE TITLE
Mobile Hybrid App: Still allow input country code

### ISSUE THREAD

**Issue by nhutlam1274** [jackocnr/intl-tel-input#1169]
Steps to reproduce
1.  Allow Input country code

Expected behaviour
Not allow input country code

version: 0.8.3

![image](https://user-images.githubusercontent.com/38564185/98067349-f7b42d80-1e8b-11eb-8ba9-fb27bd27138a.png)

**Comment by jackocnr** [comment]
Firstly you're using an ancient, unsupported version of the plugin. And secondly its bad practice to interfere with what the user types in an input. Better to let them type what they want and then use validation to give them feedback.
