### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by folarinmartins** [jackocnr/intl-tel-input#1170]
### Steps to reproduce
1.What the UI looks like
![int-l-ui](https://user-images.githubusercontent.com/11775526/98681106-9a741c80-2362-11eb-9018-a9a123b2823a.png)
2.Script at end of UI
![int-l-script](https://user-images.githubusercontent.com/11775526/98681113-9c3de000-2362-11eb-8580-74bbb2cbbfb8.png)

### Expected behaviour
Upon submit of UI form, I expect the validation to fail and refuse the form submission

### Actual behaviour
It submits an incorrect local phone number to the backend

### Initialisation options
<script type="text/javascript">
		var input = document.querySelector("#phoneX");
		window.intlTelInput(input, {
			utilsScript:"assets/libs/int-tel/js/utils.js",
			initialCountry: "auto",
			geoIpLookup: function(success, failure) {
				$.get("https://ipinfo.io?token=xxxxxxx", function() {}, "json").always(function(resp) {
					var countryCode = (resp && resp.country) ? resp.country : "ng";
					success(countryCode);
				});
			},
			customContainer:"w-100",
			hiddenInput:"phone",
			// any initialisation options go here
		});
	</script>

**Comment by jackocnr** [comment]
Are you listening for the submit event, and calling isValidNumber? See the validation example on the demo site.

**Comment by folarinmartins** [comment]
Thanks brother. God bless you. Much love from Nigeria (Great work).
Comment was helpful, issue resolved! @jackocnr

**Comment by folarinmartins** [comment]
Thanks brother. God bless you. Much love from Nigeria (Great work).
Comment was helpful, issue resolved! @jackocnr
