### ISSUE TITLE
Multiple hiddenInput

### ISSUE THREAD

**Issue by FaresShawa** [jackocnr/intl-tel-input#1172]
Hello, I'm pretty to this package and I find it pretty awesome, however, can you consider the user to add multiple hiddenInputs? 

### Expected behaviour
Currently I have tried this:
  hiddenInput: "['isoCode','dialCode' ]"

but this is reading as a single array field: as shown:
"main" => "123123"
    "['iso','code']" => "+355123123"

what should happen is:
"main" => "123123"
"iso" => "AL",
"code" => "+355",

**Comment by jackocnr** [comment]
Please see Recommended Usage section of readme - you should only need to send one value to your server: the full international number, which you can get from using the hiddenInput option normally. You can then derive all 3 of those pieces of information you mention from that one string.

I'm not interested in expanding the scope of the hiddenInput option. If you really need to save all 3 of these values, then you can easily create hidden inputs yourself, and listen for the form submit event and populate them yourself.

Hope that helps.
