### ISSUE TITLE
Ascension Island is missing from Country list

### ISSUE THREAD

**Issue by pjcarly** [jackocnr/intl-tel-input#1173]
Name: Ascension Island
Country Code: AC 
International Calling Code: +247

**Comment by jackocnr** [comment]
Does it meet [the criteria for adding a new country/territory](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/data.js#L3)? If so, I'd welcome a pull request.

**Comment by pjcarly** [comment]
As far as I can tell, it is yes on all 4 questions.
I'm willing to create a PR, but I have no idea how to work with sprites, and add a flag to it (and not mess up any other flags)

**Comment by jackocnr** [comment]
All you need to do is add an entry in src/js/data.js and run the JS build command. See the contributing guide: https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md

**Comment by pjcarly** [comment]
PR created, the flag was already in the sprite.

**Comment by jackocnr** [comment]
Merged, thanks
