### ISSUE TITLE
Change default Country

### ISSUE THREAD

**Issue by FinalRule** [jackocnr/intl-tel-input#1176]
How Can I change the default country to be for example to be Egypt instead of USA?

**Comment by phjorgensen** [comment]
Hey,

If you want to change the country that is selected initially, you can just set it in the options like this:
```javascript
intlTelInput(inputElement, {
    initialCountry: 'NO'
});
```

The value should be an alpha-2 country code.

Link for more information: https://github.com/jackocnr/intl-tel-input#initialisation-options

**Comment by jackocnr** [comment]
Thanks @phjorgensen! Closing.
