### ISSUE TITLE
Special character issue with php

### ISSUE THREAD

**Issue by afajansari** [jackocnr/intl-tel-input#1180]
### Actual behaviour
Special Character issue.
Local language is not encoded.
### Initialisation options
special character issue with PHP.

`function IntTel(finput, fullphone, insnum = 0) {
        var input = $('[id^=' + finput + ']');
        window.intlTelInputGlobals.loadUtils("https://cdn.jsdelivr.net/npm/intl-tel-input@15.0.0/build/js/utils.js");
        $(input).intlTelInput({
            //allowDropdown: false,
            autoHideDialCode: false,
            dropdownContainer: document.body,
            formatOnDisplay: true,
            initialCountry: "auto",
            geoIpLookup: function(success, failure) {
                $.get("https://ipinfo.io", function() {}, "jsonp").always(function(resp) {
                    var countryCode = (resp && resp.country) ? resp.country : "";
                    success(countryCode);
                });
            },
            initialCountry: "IN",
            nationalMode: true,
            separateDialCode: true,
        });
        $("#" + finput).on("blur change", function() {
            $("#" + fullphone).val('');
            $("#" + fullphone).val('+' + window.intlTelInputGlobals.instances[insnum].s.dialCode + $('#' + finput).val());
            $("#countryc").val('');
            $("#countryc").val('+' + window.intlTelInputGlobals.instances[insnum].s.dialCode);
            $("#iso_code").val('');
            $("#iso_code").val(window.intlTelInputGlobals.instances[insnum].s.iso2);
            console.log(window.intlTelInputGlobals.instances)
        }).blur();`
[
![image](https://user-images.githubusercontent.com/31520700/100867720-97330300-34c0-11eb-87c3-5c7846aa1df2.png)
](url)

**Comment by jackocnr** [comment]
You need to serve your page as UTF-8 e.g. have this at the top of your `<head>` section:

`<meta charset="utf-8">`

**Comment by afajansari** [comment]
@jackocnr Thank you.
