### ISSUE TITLE
Apply mask to phone numbers

### ISSUE THREAD

**Issue by wh1le** [jackocnr/intl-tel-input#1183]
Hello and **thank you** for this awesome tool!

Is there a better way to use masks with this library?

I didn't find anything related to it in docs but discovered [the function](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/utils.js#L7) that does it. Is there any way to access it from API?

```javascript
(function(input) {
  var initialCountry = document.querySelector('#user_phone_country_iso2').value

  var initializedLibrary = intlTelInput(
    input, {
      autoHideDialCode: false,
      initialCountry: initialCountry,
      preferredCountries: ['US', 'CA', 'MX', 'GB'],
      separateDialCode: true
    }
  )

  Inputmask({
    mask: PHONE_MASKS_DICTIONARY[initialCountry.toLowerCase()],
    clearMaskOnLostFocus: true,
    autoUnmask: true,
    greedy: false 
  }).mask(input);

  input.addEventListener('countrychange', function() {
    var countryCode = initializedLibrary.getSelectedCountryData()

    document.querySelector('#user_phone_country_iso2').value = countryCode.iso2

    input.value = ''

    Inputmask({
      mask: PHONE_MASKS_DICTIONARY[countryCode.iso2],
      clearMaskOnLostFocus: true,
      autoUnmask: true,
      greedy: false
    }).mask(input);
  });
})(document.querySelector('#user_phone'));
```

Let me know and I'll add a PR for the README

**Comment by jackocnr** [comment]
> Hello and thank you for this awesome tool!

:) glad you're enjoying it.

> Is there a better way to use masks with this library?

I'm afraid we don't support masks. We used to have an autoFormat feature, but sadly it had to be dropped - you can read more about this if you search in the issues.

I recommend you show a good placeholder (see autoPlaceholder option) and then let the user type whatever they like and apply validation when they submit the form and give them a helpful error message if the number is not valid.
