### ISSUE TITLE
How to use intl-tel-input with vue ?

### ISSUE THREAD

**Issue by suraj235** [jackocnr/intl-tel-input#1184]
I have created a user registration form using VueJs. I am trying to add a country code dropdown input field using an intl-tel-input plugin. I tried to make it work but now I'm stuck at a point where I'm getting a JS error on the console: _**Error in mounted hook: "TypeError: Cannot read property 'getAttribute' of undefined"**_ (Please see an attachment below)

Here is my code:

```
<div class="form-field__control" v-if="mode === 2">
     <input type="tel" name="user-mobileCode" class="form-field__input" placeholder=" " ref="usermobileNumber"
         :class="{ 'form-group--error': $v.mobileNumber.$error }"
         v-model.trim="$v.mobileNumber.$model"/>
</div>

```
```
mounted() {
    const contactInput = this.$refs.usermobileNumber;
    intlTelInput(contactInput, {
      utilsScript: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.3/js/utils.min.js',
      autoPlaceholder: 'aggressive',
      geoIpLookup: function (success) {
        $.get('https://ipinfo.io?token=064f37dcbabd0e', function () {}, 'jsonp').always(function (resp) {
          var countryCode = (resp && resp.country) ? resp.country : '';
          success(countryCode);
        });
      },
      preferredCountries: ['in', 'us', 'uk'],
      separateDialCode: true,
    });
}
```

I am using the Vuelidate package for Input validation.
Any help will much be appreciated.

![image](https://user-images.githubusercontent.com/65009827/105532210-8a889980-5d10-11eb-9712-e21ec8128f4b.png)

**Comment by jackocnr** [comment]
I'm afraid this is outside the scope of the support I can provide. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).
