### ISSUE TITLE
Ivory Coast: phone numbers to increase from 8 to 10 digits on January 31

### ISSUE THREAD

**Issue by aureliencaruel** [jackocnr/intl-tel-input#1185]
Hi.

Phone numbers of Ivory Coast will be increase to 10 digits in few day.
https://www.tellerreport.com/news/2020-12-28-%0A---ivory-coast--phone-numbers-to-increase-from-8-to-10-digits-on-january-31%0A--.rkWLsXPaD.html

Is it possible to update the library please ?

Thanks by advance.
Your plugin is very useful.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by aureliencaruel** [comment]
OK. Thanks a lot.
Have a good day
