### ISSUE TITLE
Invalid number for MTN Benin Republic

### ISSUE THREAD

**Issue by monejoel** [jackocnr/intl-tel-input#1193]
Error map return Invalid phone number when I select Benin Republic and enter 51 80 04 51 which is for MTN Network. Moov and others are seem to be valid.

How can this be resolved?

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by jonathan42** [comment]
I submitted an update of lib  #1213

**Comment by jackocnr** [comment]
I've just published a new version (v17.0.13) using a newer version of libphonenumber, which should have fixed the issue. Feel free to post here if you're still seeing the issue tho.
