### ISSUE TITLE
Specific countries order?

### ISSUE THREAD

**Issue by vasikgreif** [jackocnr/intl-tel-input#1195]
Is it possible to pass a list of countries with a specific order? I'd need to have two countries at the top. I use the following options, both the `onlyCountries` and `localisedCountries` contain the correct order, but in the dropdown the order is still default.

```js
const intl = intlTelInput(input, {
        initialCountry: wpifyWooPhoneValidation.defaultCountry,
        onlyCountries: wpifyWooPhoneValidation.onlyCountries,
        localizedCountries: wpifyWooPhoneValidation.localizedCountries,
        utilsScript: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.11/js/utils.min.js'
    });

```

**Comment by jackocnr** [comment]
You can specify the countries to appear at the top with the preferredCountries option, but all countries in the dropdown will always be ordered alphabetically, which is the only thing that makes sense because we have the feature where you can type the name of the country to scroll to it.
