### ISSUE TITLE
after user returns in his Dashboard or Profile, how from the saved data eg +1 987 123 4567, I can populate this drop-down menu

### ISSUE THREAD

**Issue by lse123** [jackocnr/intl-tel-input#1196]
### Steps to reproduce
1.  I plan to use this dropdown flag/tel input, I tested ok but --- in a LARAVEL 8.x CRUD Web App after saving a user data including tel-code/number-phone, after user returns in his Dashboard or Profile, how from the saved data eg +1 987 123 4567, I can populate this drop-down menu... in order to show the country + number[USA +1 987 123 4567...? 
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
If the input's value is set to the number when you initialise the plugin, then it should select the right flag for you automatically.

**Comment by lse123** [comment]
// hiddenInput: "full_number",

you mean this^^^???

**Comment by lse123** [comment]
<input id="phone" name="phone" type="tel" value="+cc number">    // working
