### ISSUE TITLE
Input Phone Validation

### ISSUE THREAD

**Issue by najBaby** [jackocnr/intl-tel-input#1197]
### Steps to reproduce
1.  Create a input phone.
2.  When you type a phone for country **Ivory Coast**
3.  Validation locks my input.

### Expected behaviour
You must be able to type 10 digits for Ivory Coast .

### Actual behaviour
It is good for 08 digits but Ivory Coast is not to 08 digits. 

### Initialisation options
preferredCountries

**Comment by jackocnr** [comment]
Duplicate of #1189
