### ISSUE TITLE
How to Get List of All Possible Country Codes

### ISSUE THREAD

**Issue by ProfessorManhattan** [jackocnr/intl-tel-input#1199]
There seems to be a gap in the public methods. I would like to run a function on the input with a value of "+1" and return all the country codes that start off with "+1". Is there anyway using this library that it can be accomplished?

**Comment by mguinness** [comment]
Can't you use `window.intlTelInputGlobals.getCountryData()` and filter with `dialCode`?

**Comment by jackocnr** [comment]
Yes @mguinness's solution is the way to do it. Thanks.
