### ISSUE TITLE
Compile warning related to import/export on angular application

### ISSUE THREAD

**Issue by valterbarros** [jackocnr/intl-tel-input#1202]
### Steps to reproduce

1. setup angular and angular/cli >= 10
2. ng create new-project
3. install intl-tel-input via npm
4. create a page and add intl-tel-input implementation to that page
5. run ng serve

### Expected behavior
not show compilations warnings

### Actual behavior
ng serve is returning this error:

`ui-components.js depends on 'intl-tel-input'. CommonJS or AMD dependencies can cause optimization bailouts.`

### Initialisation options
```
  const intlTel = intlTelInput(input, {
    initialCountry: countryCode,
    separateDialCode: true,
    nationalMode: false,
    formatOnDisplay: false,
    utilsScript: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.3/js/utils.min.js'
  })
```

Would be good to turn the intl lib to use es6 import/export is there planning to that?

**Comment by valterbarros** [comment]
if you need I can create a stackblitz project

**Comment by jackocnr** [comment]
I'm afraid this is outside the scope of the support I can provide. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).
