### ISSUE TITLE
Support for/with DSN numbers

### ISSUE THREAD

**Issue by mrhuttner** [jackocnr/intl-tel-input#1203]
Feature Request or New Country.
DSN (Defense Switched Network) is a completely separated from the traditional telecom network.

### Steps to reproduce
1.  Need to add DSN (Defense Switched Network)
2.  ie input "DSN: 312-866-5333"
3.  .getNumber() should out put DSN: 312-866-5333
4.  https://en.wikipedia.org/wiki/Defense_Switched_Network (information about the "area" codes in DSN)

### Expected behaviour
N/A

### Actual behaviour
N/A

### Initialisation options
N/A

**Comment by jackocnr** [comment]
Sorry we don't plan to add support for this, as these numbers don't have an international dial code, so it would require serious changes to how the plugin works.
