### ISSUE TITLE
https://api.ipdata.co/?api-key=test 403

### ISSUE THREAD

**Issue by usmanfarzandali** [jackocnr/intl-tel-input#1210]
![Screenshot from 2021-03-11 11-56-44](https://user-images.githubusercontent.com/22232100/110748165-28084000-8261-11eb-8c9e-7508ce625528.png)

### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by mguinness** [comment]
You need to [signup](https://ipdata.co/pricing.html) for a plan and get an API key.

**Comment by jackocnr** [comment]
Thanks @mguinness
