### ISSUE TITLE
Invalid Phone number in mauritius phone number

### ISSUE THREAD

**Issue by lubinMathew** [jackocnr/intl-tel-input#1214]
Valid phone number in Mauritius showing as invalid phone, We have updated the util js to latest version but still showing invalid number .Can you please help us to fix the issue

**Comment by jonathan42** [comment]
hey #1213

**Comment by jackocnr** [comment]
I've just published a new version (v17.0.13) using a newer version of libphonenumber, which should have fixed the issue. Feel free to post here if you're still seeing the issue tho.
