### ISSUE TITLE
Wrong validation for Chinese phone number

### ISSUE THREAD

**Issue by yiddou** [jackocnr/intl-tel-input#1216]
This number (09301784598) is not valid mobile number for China. But the result of isValidNumber() is valid.

**Comment by jonathan42** [comment]
#1213 
the new version of lib utils should be fixed ?

**Comment by yiddou** [comment]
I've tried. It is not fixed in the latest version.

**Comment by jonathan42** [comment]
have you tested on the demo of https://github.com/google/libphonenumber

**Comment by jackocnr** [comment]
I've just published a new version (v17.0.13) using a newer version of libphonenumber, which should have fixed the issue. Feel free to post here if you're still seeing the issue tho.
