### ISSUE TITLE
flag not updated for 00 starting numbers

### ISSUE THREAD

**Issue by thomasSchrambach** [jackocnr/intl-tel-input#1217]
### Steps to reproduce
1.  in an intl tel input, select the spanish flag and write a french number starting with "00336..."

### Expected behaviour
The flag should become automatically the french flag. 

### Actual behaviour
In the case specified, the spanish flag isn't replaced by the french flag.

### Initialisation options
                initialCountry
                utilsScript: "../../Content/vendors/intlTelInput/js/utils.js",
                autoPlaceholder: "off",
                hiddenInput: "Phone",
                preferredCountries: ["pt", "gb", "es", "be", "it", "de", "ch", "nl", "ae", "tn"],

**Comment by mguinness** [comment]
Looking at [Telephone numbers in France](https://en.wikipedia.org/wiki/Telephone_numbers_in_France) is that a valid number?

**Comment by thomasSchrambach** [comment]
you can use either 00 or + in an international indicator(so +33 or 0033 for France, +34 or 0034 for Spain etc...)

**Comment by mguinness** [comment]
Extract from [List of country calling codes](https://en.wikipedia.org/wiki/List_of_country_calling_codes)

> By convention, international telephone numbers are represented by prefixing the country code with a plus sign (+), which also indicates to the subscriber that the local international call prefix must first be dialed. For example, the international call prefix in all countries of the North American Numbering Plan is 011, while it is 00 in most European, Asian and African countries.

I don't think the call prefix is supported in [libphonenumber](https://github.com/googlei18n/libphonenumber), check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) and maybe file an issue with them instead.

**Comment by luigifab** [comment]
Out of curiosity I tested on our website, I tried to set Spanish flag, then I enter "0033673737337", for me the flag was updated to French.

I using:
```js
var codes = ['FR', 'ES'], texts = {'fr': 'France', 'es': 'Espagne'},
  elem = document.querySelector('input[id*="telephone"]');

elem.iti = self.intlTelInput(elem, {
	utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/utils.min.js",
	hiddenInput: 'temp',
	initialCountry: 'FR',
	localizedCountries: texts,
	preferredCountries: codes
});
elem.addEventListener('blur', function () {
	this.iti.setNumber(this.iti.getNumber());
}.bind(elem));
```

**Comment by jackocnr** [comment]
This question has been answered before - please search existing issues before creating new ones. Cheers.
