### ISSUE TITLE
Placeholder not showing or updating when changing countries 

### ISSUE THREAD

**Issue by A7madXatab** [jackocnr/intl-tel-input#1220]
First of all, thank you very much for creating this gem(package). 

### Steps to reproduce
Clean installation and basic set up.

### Expected behaviour
the input placeholder should be formatted and have a default placeholder changing when changing countries, like. the demo.

### Actual behaviour
The placeholder is empty

<img width="580" alt="Screenshot 2021-04-21 at 00 56 21" src="https://user-images.githubusercontent.com/38360603/115469002-8e0ebc80-a23c-11eb-96bd-d18a9c1005e4.png">

and when changing countries the placeholder isn't changing, 

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by mguinness** [comment]
Produce a minimal set of code that reproduces the problem and put that in a CodePen.  You can fork this [example pen](https://codepen.io/jackocnr/pen/yehvE) to get started.

**Comment by A7madXatab** [comment]
sorry my bad!, didn't import the `utils` script!.
