### ISSUE TITLE
Wrong italian phone validation

### ISSUE THREAD

**Issue by matteomelotti** [jackocnr/intl-tel-input#1226]
Hi,
I tried to enter a valid italian mobile phone (ex: (+39) 3283456782) and:
- added one, two or three chars after the last digit
- replaced some numbers with chars
and the isValidNumber returns always true even with the utils.js.

Thank you.

**Comment by mguinness** [comment]
Using [Validation Example](https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html) it fails when you add three extra characters.

Also did you read read [New Issue Checklist](https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist) as shown in the new issue template?

> We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

**Comment by matteomelotti** [comment]
Thank you @mguinness and sorry for the waste of your time.
I reported the issue to libphonenumber.
