### ISSUE TITLE
country resets to US/Canada if dialing code is +1

### ISSUE THREAD

**Issue by fahadali916** [jackocnr/intl-tel-input#1228]
### Steps to reproduce
1.  Select any country with +1 dialing code other than the US/Canada.
2.  Trying writing the telephone number.
3.  The country selection field resets to US or Canada from the one you had selected.

### Expected behaviour
The country field shouldn't change unless the user has changed it themselves, for specific country codes like the +1.

### Actual behaviour
The country changes to either US or Canada (both have same dialing code +1). The same issue doesn't appear for country codes like +44 or anyother I guess. I have checked only +44 and it doesn't revert back to UK. 
See it here https://screencast-o-matic.com/watch/crhl1gVfYOm

### Initialisation options
Default settings, event the demo page has this issue.

**Comment by mguinness** [comment]
I think this is to be expected.  The +1 country code uses [NANP](https://en.wikipedia.org/wiki/List_of_North_American_Numbering_Plan_area_codes) which includes US, Canada & Caribbean Islands.  When you type the area code the corresponding country is also selected.  For example, 232 is Pennsylvania and 343 is Ottawa.  If you entered 246 you would get Barbados.  If you don't like that behaviour you could try looking into the `customPlaceholder` option.

**Comment by 4davidk123** [comment]
Can you give an example? I am experiencing the same issue.  How would using the customPlaceholder fix this?

**Comment by mguinness** [comment]
> If you don't like that behaviour you _could try looking_ into the customPlaceholder option.

I wasn't sure which is why I said try.  Looks like it won't work, you'll have to override the `keyup` event.

https://github.com/jackocnr/intl-tel-input/blob/ca94755d5899417c2dc674775ee357b32c2c2fa0/src/js/intlTelInput.js#L592-L598

**Comment by fahadali916** [comment]
@mguinness So you mean this is normal?

**Comment by mguinness** [comment]
I suspect so, as otherwise you could end up displaying a US flag for a Canadian number and vice versa.  So you could call it a feature and not a bug :)

**Comment by fahadali916** [comment]
> I suspect so, as otherwise you could end up displaying a US flag for a Canadian number and vice versa. So you could call it a feature and not a bug :)

I see. Its okay, i get it. But it was kind of very annoying to me when it happened to me :) That's why wanted to bring into notice here.

Thanks

**Comment by paddotk** [comment]
> as otherwise you could end up displaying a US flag for a Canadian number and vice versa

@mguinness Isn't that exactly the reason why this shouldn't happen?

**Comment by paddotk** [comment]
This also triggers the `countrychange` event. So if I type in '787', for instance, the country changes to Puerto Rico. This results in not being able to distinguish between when the user is typing, or selects a country with the dropdown.
