### ISSUE TITLE
Issue with Mexican cell phone numbers. '1' is removed with no reason

### ISSUE THREAD

**Issue by akaclaster** [jackocnr/intl-tel-input#1230]
### Steps to reproduce
1.  go here https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/national-mode.html
2.  type +5215527285048 in the field
3.  return will be without '1' after country code (like: +525527285048)

### Expected behaviour
Expected to have full number with '1' after +52

### Actual behaviour
It removes '1' from result for some reason
![image](https://user-images.githubusercontent.com/56870061/119571054-bfac0380-bd65-11eb-936a-509ae27e4f34.png)

plz be so kind and fix.
Thank you,
Alexey

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by jackocnr** [comment]
I just tried it and confirm that the libphonenumber demo page, if you enter "+5215527285048" then it shows the "international format" without the 1. If you think this is incorrect you'll need to raise an issue with them.
