### ISSUE TITLE
🇧🇪 Phone numbers starting with 045 flagged invalid.

### ISSUE THREAD

**Issue by Alweezy** [jackocnr/intl-tel-input#1231]
### Steps to reproduce
1.  Install any any version of `intl-tel-input` eg `$npm install intl-tel-input@17.0.0`
2.  Use the validation to validate a textfield.
3.  Enter a valid belgian 🇧🇪 number that starts with `045`

### Expected behaviour
Textfield should recognize number as valid.

### Actual behaviour
The Belgian phone numbers starting with `045` are flagged as invalid.

<img width="622" alt="invalidPhoneNumber" src="https://user-images.githubusercontent.com/9264935/119970998-18bfa580-bfb9-11eb-88eb-fd7beea6fb35.png">

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by Alweezy** [comment]
Looks Valid from `libphonenumber`s site:
<img width="763" alt="validBelgianPhoneNumber" src="https://user-images.githubusercontent.com/9264935/120212462-b1b12380-c23a-11eb-8cb2-641bd1e6520f.png">
I was running on v`17.0.0`  `intl-tel-input`, going to attempt and bump up the version of `libphonenumber`, thanks.

**Comment by jackocnr** [comment]
I've just released a new version (v17.0.14) which is built against the latest version of libphonenumber, which should fix the issue. Please let me know if you still see any issues after updating.
