### ISSUE TITLE
New Philippines Telco Carrier DITO Mobile Number is not supported

### ISSUE THREAD

**Issue by firephantomassasin** [jackocnr/intl-tel-input#1242]
There is a new Philippines Telco Carrier DITO and its Mobile Number is not supported in this library.

Upon checking the libphonenumber github -- there is already a fix for the DITO number

https://issuetracker.google.com/issues/185733649

https://github.com/google/libphonenumber/pull/2591

I hope this library will be updated to have the updated mobile number validation by using the latest libphonenumber -- v8.12.24

**Comment by chloe-1903** [comment]
I have the same issue. There is a [PR](https://github.com/jackocnr/intl-tel-input/pull/1237/files) for an update but tests are failing

**Comment by jackocnr** [comment]
I've just released a new version (v17.0.14) which is built against the latest version of libphonenumber, which should fix the issue. Please let me know if you still see any issues after updating.
