### ISSUE TITLE
New Number Length for Coasta Ivory (+225)

### ISSUE THREAD

**Issue by maahibhat88** [jackocnr/intl-tel-input#1249]
The "Autorité de Régulation des Télécommunications/TIC de Côte d’Ivoire" (ARTCI) hereby announced the modification of the national numbering plan of Côte d’Ivoire, from eight (8) to ten (10) digits, effective 31 January 2021 in Côte d’Ivoire.
https://en.wikipedia.org/wiki/Telephone_numbers_in_Ivory_Coast

**Comment by jackocnr** [comment]
I've just released a new version (v17.0.14) which is built against the latest version of libphonenumber, which should fix the issue. Please let me know if you still see any issues after updating.
