### ISSUE TITLE
Add new Country code for USA (689)

### ISSUE THREAD

**Issue by luiskkstti** [jackocnr/intl-tel-input#1250]
### Steps to reproduce
1.  For USA phone number, area code 689 is invalid
2.  I modified AreaCodes to add 689 but still is invalid
3.  

### Expected behaviour
Area code 689 should be valid

### Actual behaviour
validation block area code 689
![image](https://user-images.githubusercontent.com/87709795/126338831-7c9c0c0d-787b-4f0f-bdd1-882c1dd8abdf.png)

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
I've just released a new version (v17.0.14) which is built against the latest version of libphonenumber, which should fix the issue. Please let me know if you still see any issues after updating.
