### ISSUE TITLE
Update the name of North Macedonia

### ISSUE THREAD

**Issue by psrcek** [jackocnr/intl-tel-input#1255]
### Expected behaviour
The country of Macedonia is officially known as the Republic of North Macedonia under the [Prespa agreement](https://en.wikipedia.org/wiki/Prespa_agreement).

### Actual behaviour
The UI shows the name as `Macedonia (FYROM) (Македонија)`

### Initialisation options
utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/js/utils.js"

**Comment by jmprosper** [comment]
Hello. I agree, current official name is "North Macedonia" so should be updated.
I already commented out of here. Also I'm not sure if other countries have changed their name, probably not.
Thanks in advance.

**Comment by jackocnr** [comment]
This has now been changed in the latest version.
