### ISSUE TITLE
Can i search country code in input list

### ISSUE THREAD

**Issue by khnbzkrt** [jackocnr/intl-tel-input#1256]
### Steps to reproduce
1.  I want to search country code in the list
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
See new option `countrySearch` in v18.5.1. Let me know what you think!
