### ISSUE TITLE
Accessibility Issue: Geopolitical Problems

### ISSUE THREAD

**Issue by Guzinanda** [jackocnr/intl-tel-input#1260]
Based on some recent feedback, it is not good global business practice to use flags to select countries.

This is because some countries/regions are not recognized as countries in all parts of the world. This causes tensions, and can lead to refusal of doing business with companies that show flags for these countries.  

**Case in point:** 
China has refused to do business with Marriott because it showed the Taiwanese flag on its website.

**Questions:**
1. Do you know something about this? 
2. What would you do about this?
3. Is there a way to solve this or adapt the flag base according to this?

**Comment by jackocnr** [comment]
It's easy to hide the flags with CSS if you want to. If you search the issues you'll find advice on how to do that.

I can't think of any good alternative to flags. Google and several other popular global websites use them, so I don't think we need to do anything differently.

**Comment by shrkbait-hpe** [comment]
You are free to edit flags.png to adjust for your business needs.  Or build https://github.com/fonttools/region-flags after some edits.

**Comment by jackocnr** [comment]
New option: showFlags added recently, which you can set to false to hide all flags. Recommended to use it with the separateDialCode option, to show the selected dial code instead.
