### ISSUE TITLE
French number starts from 0692 invalid

### ISSUE THREAD

**Issue by trussss** [jackocnr/intl-tel-input#1264]
Wiki says that numbers starts from +330692 and mobile phone numbers, and they should be valid.
![image](https://user-images.githubusercontent.com/5835344/132014675-d23cfbd6-3484-4995-b28e-444c50906b05.png)

### Steps to reproduce
1.  enter french number +330692xxxxxxxx

### Expected behaviour
Phone number should be valid

### Actual behaviour
Phone number is invalid

### Initialisation options
this.userCountry = '';

this.telInputOptions = {
            utilsScript: window.intlTelInputGlobals.loadUtils,
            preferredCountries: ['fr', this.userCountry || ''],
            initialCountry: 'fr',
            formatOnDisplay: true
        }

**Comment by jackocnr** [comment]
I've just released a new version (v17.0.14) which is built against the latest version of libphonenumber, which should fix the issue. Please let me know if you still see any issues after updating.
