### ISSUE TITLE
Entering ? at the beginning of a number validates but doesn't check international dropdown

### ISSUE THREAD

**Issue by samwa** [jackocnr/intl-tel-input#1267]
### Steps to reproduce
1.  go to example web site https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html
2.  pick India as an example country
3.  enter a valid Australian number but with ? around it, such as ?+61 412 345 678?

### Expected behaviour
It should return an invalid number, 
or switch the country in the dropdown to Australia

### Actual behaviour
it says its a valid number. iti.isValidNumber() is true and iti.getNumber() returns +61412345678
iti.selectedCountryData.dialCode return 91

### Initialisation options
check initialisation on example page

**Comment by jackocnr** [comment]
It turns out even a space is enough to stop the selected country from auto-updating as you type (e.g. if you type " +44" it doesn't update). This is now fixed in v18.5.2.
