### ISSUE TITLE
Colombia (+57) Mobile phone number validation error that starts with 324.

### ISSUE THREAD

**Issue by ltortiz** [jackocnr/intl-tel-input#1277]
Hello, I am getting an error for a mobile phone number that starts with 324 for Colombia (+57) I expect to receive a valid number as true, but it throws me a false.

isValidNumber: true, The number is: +57321123****
isValidNumber: false, The number is: +57324123****

**Comment by jackocnr** [comment]
I've just released a new version (v17.0.14) which is built against the latest version of libphonenumber, which should fix the issue. Please let me know if you still see any issues after updating.
