### ISSUE TITLE
Issue with numbers from Ivory Coast ?

### ISSUE THREAD

**Issue by edouardroger** [jackocnr/intl-tel-input#1278]
Hi,

I'm encountering an issue with numbers from Ivory Coast for which method isValidNumber doesn't return false although these numbers are not correct according to libphonenumber.

Indeed, using the Python port (8.12.31) is_valid_number method returns false and is_possible_number_for_type_with_reason returns 2 (i.e. TOO_SHORT).

Please find bellow two examples :

+22559005608
+22546783090

Thank you !

**Comment by jackocnr** [comment]
I've just released a new version (v17.0.14) which is built against the latest version of libphonenumber, which should fix the issue. Please let me know if you still see any issues after updating.

**Comment by edouardroger** [comment]
Hi,
It works like a charm :).
Thanks !
