### ISSUE TITLE
Validation for RO phone numbers with 078****** and 079****** not working

### ISSUE THREAD

**Issue by alexandrupuscu** [jackocnr/intl-tel-input#1280]
### Steps to reproduce
1.  Go to: https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html
2. Introduce the number 07**8**1231123 and 07**9**1231123

### Expected behaviour
Acording with https://www.itu.int/oth/T02020000AC/en, https://www.ancom.ro/en/numbering_134, https://en.wikipedia.org/wiki/Telephone_numbers_in_Romania and https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L24592-L24611
**The validation should pass**

### Actual behaviour
"**Invalid number**" received
![image](https://user-images.githubusercontent.com/3798694/138452658-c9b07187-3c5d-44cb-96e0-7886c8c5f76d.png)
![image](https://user-images.githubusercontent.com/3798694/138452962-252100ee-06bf-448b-b086-3e75f4635ab4.png)

### Initialisation options
I am using the oficial intl-tel-input demo page.

**Comment by jackocnr** [comment]
I've just released a new version (v17.0.14) which is built against the latest version of libphonenumber, which should fix the issue. Please let me know if you still see any issues after updating.
