### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')     at new c (intlTelInput.min.js:7)     at intlTelInput.min.js:8     at phone (account.js:76)     at HTMLDocument.<anonymous> (account.js:85)     at c (jquery.min.js:3)     at Object.fireWith [as resolveWith] (jquery.min.js:3)     at Function.ready (jquery.min.js:3)     at HTMLDocument.H (jquery.min.js:3)

### ISSUE THREAD

**Issue by Ella-Adu** [jackocnr/intl-tel-input#1282]
### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
Sounds like you need to destroy the plugin instance (see `destroy` method) before navigating away.

**Comment by Ella-Adu** [comment]
Thank you very much for your help. I have been able to resolve it




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
11/05/21,
08:56:50 AM
