### ISSUE TITLE
Country Code Instead of Flag

### ISSUE THREAD

**Issue by ahmetbarut** [jackocnr/intl-tel-input#1285]
Hello to everyone. I am using this package in a project I am using.
### Expected behaviour
Country codes instead of country flags

### Actual behaviour
Country flags are displayed
![image](https://user-images.githubusercontent.com/36641723/141932232-c202023e-a80f-4926-8cf6-0dfa6bddca6f.png)

### Initialisation options
```javascript
            var input = document.querySelector("#phoneNumber");
            const itl = intlTelInput(input);


```

**Comment by jackocnr** [comment]
I'm afraid it is not possible to replace the flag with the country code. The nearest thing we have is the separateDialCode option - give that a try.
