### ISSUE TITLE
Getting error "Uncaught TypeError: window.intlTelInput is not a function"

### ISSUE THREAD

**Issue by linups** [jackocnr/intl-tel-input#1286]
Hello, 

I have tried to run your example, but getting error: 
`Uncaught TypeError: window.intlTelInput is not a function`

Here is codePen link: https://codepen.io/linups/pen/KKvbPaZ

If it is needed, i can give link to my page.

Thank you for your awesome script!

**Comment by jackocnr** [comment]
It looks like the plugin isn't loading properly. Try loading it from the CDN instead of from Github - see the readme.

Or re-use the [example pen](https://codepen.io/jackocnr/pen/yehvE) where it is working.
