### ISSUE TITLE
Issue with Uganda Phone numbers

### ISSUE THREAD

**Issue by sirlojik** [jackocnr/intl-tel-input#1287]
### Steps to reproduce
1.  Select Uganda - 256
2.  Try 760213589 or 761987456
3.  It fails validation

### Expected behaviour

The phone number also validates at the libphone test page +256761987456

The phone number range is new and for MTN Uganda. Check link https://techjaja.com/mtn-uganda-assigned-a-new-076-number-range/

### Actual behaviour
Fails with Invalid phone number

### Initialisation options
Prefered country is 'UG' 256. i new utilsScript.js and i have the latest update

**Comment by sirlojik** [comment]
If you could compile for us the latest utilsScript.js. i would highly appreciate it. I tried to do it myself but got an error

ERROR: The 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace

**Comment by jackocnr** [comment]
I've just released a new version (v17.0.14) which is built against the latest version of libphonenumber, which should fix the issue. Please let me know if you still see any issues after updating.
