### ISSUE TITLE
User can enter alphabets also. "tel" not working

### ISSUE THREAD

**Issue by apsher91** [jackocnr/intl-tel-input#1288]
User can type alphabets symbols also, as well it gets submitted.
Tried demo http://intl-tel-input.com

Not sure if it is issue or there is workaround or option to address this. 
I am am new to programming.. this is my first GitHub comment.

**Comment by jackocnr** [comment]
In my opinion it's best practice to let the user type whatever they want and then catch any invalid chars / invalid phone numbers during a validation step when they submit.

If you want to prevent them typing specific characters, then you can do that outside of this plugin.

**Comment by jackocnr** [comment]
I have now added a `strictMode` option, which prevents users from entering invalid characters and caps the input at the maximum valid number length. Added in v20.2.0.
