### ISSUE TITLE
Flag dropdown styling issue when errors occur

### ISSUE THREAD

**Issue by ateequrrahman97** [jackocnr/intl-tel-input#1291]
### Expected behaviour
When error occur on phone field, iti__flag-container height should be same like normal

### Actual behaviour
When error occur on phone field, iti__flag-container height having styling issue
![image](https://user-images.githubusercontent.com/74288984/146012903-65fdf4a0-3952-40a0-8d65-5d63e4470f77.png)

**Comment by gurbuzyagiz** [comment]
You Are Having A Conflict With Your CSS Files. You Should Check for Elements That May Be in the Same Class.

**Comment by jackocnr** [comment]
Agreed this is an issue with your site's CSS. I'm afraid this is outside the scope of the support I can provide. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).
