### ISSUE TITLE
Update google/libphonenumber

### ISSUE THREAD

**Issue by faggv** [jackocnr/intl-tel-input#1294]
### Steps to reproduce
1.  Try to validate phone numbers starting with 791 for RO (like 791555555)
2.  Should be valid 

### Expected behaviour
Vodafone in Romania had launched a new series of phone numbers that are already supported by the last version of libphonenumber

### Actual behaviour
Tells that the number is not valid

**Comment by faggv** [comment]
Just wanted to say that I tried to follow this guide: https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber.
But when I run test with the new complide utils.js I get errors 😢 . Sorry

**Comment by dev-eduka** [comment]
Hello,
I am encountering the same issues. We need an update because the numbers in Cote D'ivoire (Ivory Coast) are now obsolete, in the current library they're 8 digits but now in real life they are 10 digits.

**Comment by jackocnr** [comment]
I've just released an updated version of libphonenumber in v17.0.16 - this should fix your issue. If not, please let me know, cheers.

**Comment by uhalexuh** [comment]
Hello,

Any ideas why numbers with 792 (ex: +40792123456) is not valid, but in libphonenumber demo it is?

Others like 791 (ex: +40791123456) are valid

https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html
