### ISSUE TITLE
Auto-switch of countries makes it impossible to select certain countries

### ISSUE THREAD

**Issue by paddotk** [jackocnr/intl-tel-input#1295]
### Steps to reproduce
1. Select a country with a 'shared' dial code, e.g. Puerto Rico (+1)
2. Start typing in a phone number
3. The USA will be auto-selected, because this also has +1 as dial code

### Expected behaviour
I would expect to be able to manually select a country, then fill in my phone number, without the library's code meddling.
The above steps are one example, but it's not exclusively NANP/+1 or with shared dial codes with area codes per country.

### Actual behaviour
While typing a phone number, the component keeps selecting different countries. In some cases (such as a country that uses NANP with a single area code) it can be omitted by automatically getting the area code from the selection and putting it in the input field. But in some cases, you can't select a country because it immediately changes to another country when you type. For instance, try to select Mayotte. It has +262 as dial code, but because Réunion has the same dial code, it gets auto-selected instead.

This issue addresses the same thing but is closed for some reason:
https://github.com/jackocnr/intl-tel-input/issues/1228

### Initialisation options
Irrelevant.

**Comment by jackocnr** [comment]
Apologies for the delay in replying, I've been dealing with a family emergency.

If I go to intl-tel-input.com and select the Puerto Rico flag and type a Puerto Rican number (e.g. 787 234 5678) then it keeps the Puerto Rican flag selected. It's only if I type a number from another country (e.g. an American number like 702 123 4567) that it changes the flag to that country.

I'll close this for now, but if you still think there's an issue please let me know.
