### ISSUE TITLE
getNumber is null when utils.min.js fail to load

### ISSUE THREAD

**Issue by luigifab** [jackocnr/intl-tel-input#1296]
When utils.min.js fail to load (bad network, 404, Content-Security-Policy...), there is the following error in the console:
`Uncaught TypeError: window.intlTelInputGlobals.instances[b][a] is not a function`
The problem is for `getNumber()`.

### Steps to reproduce
1.  download intlTelInput.min.css
2.  download intlTelInput.min.js
3.  use the following example:
```html
<input type="tel" id="tel">

<link rel="stylesheet" media="all" type="text/css" href="intlTelInput.min.css" />
<script type="text/javascript" src="intlTelInput.min.js"></script>
<script type="text/javascript">
var elem = document.getElementById('tel'), iti = self.intlTelInput(elem, {
	utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/utils.min.js",
	hiddenInput: 'temp',
	initialCountry: 'FR',
	preferredCountries: ['FR']
});

elem.iti = iti;

elem.addEventListener('blur', function () {
	this.iti.setNumber(this.iti.getNumber());
}.bind(elem));
</script>
```

### Expected behaviour
`getNumber()` must return original string instead of empty string?

### Actual behaviour
`getNumber()` return empty string

**Comment by jackocnr** [comment]
> getNumber() must return original string instead of empty string?

You mean just return the current value in the input? This is dangerous, as the point of getNumber is that it merges the (possibly nationally formatted) number in the input with the international dial code of the selected country, which can only be done safely with the help of utils. If a required lib like utils fails to load, then I would just display an error to your user as lots of things will not be able to function properly.
