### ISSUE TITLE
feature request: support native constraint validation

### ISSUE THREAD

**Issue by jimmywarting** [jackocnr/intl-tel-input#1302]
Currently you don't seem to use the [constraint validation](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Constraint_validation) in any way...?
it would be desirable if you could use this somehow.

this would make it possible to style the input using css [:invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid) 

and it could also prevent user from submitting a invalid form.

It's possible to set a custom messages as well `imputElm.setCustomValidity('sry, it is not valid format')`

**Comment by jackocnr** [comment]
Apologies for the delay in replying, I've been dealing with a family emergency.

This plugin just wraps your input in a div - you're still free to use constraint validation with that input/form element however you like. For example, you should be able to use the "required" attribute just fine. Have you tried and hit a problem? 

Or do you mean you'd like this plugin to dynamically update the `pattern`/`min`/`max` attributes each time you select a different country / type a different region code? Unfortunately the validation rules used to determine valid phone numbers for each country/region are so complex and constantly changing - that's the reason we use Google's libphonenumber library for validation - and as far as I know, they don't provide a way to translate their validation rules into HTML pattern attributes, so I'm afraid that would be outside the scope of this plugin. For number validation, you just have to call the isValidNumber method.

Closing for now, but do let me know if I've misunderstood.

**Comment by jimmywarting** [comment]
Hmm, yea i was thinking in other terms than just slamming in `required` attribute...
a phone number can be optional too, so it should not be your responsibility to set it.

dynamically updating the `pattern/min/max` attribute could certainly be a solution, but i was thinking of a more simplare solution than that... 

when the input updates then it would automatically call `isValidNumber` if it's `false` then it would set a [custom](https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/setCustomValidity) error message, if true then it would empty the error message.

something like:
```js
function validateIntlInput (evt) {
  const elm = evt.target
  const val = elm.value
  const msg = val === '' || isValidNumber(elm.value) 
    ? '' 
    : elm.dataset.invalid-message || 'The phone number is wrong'
  
  elm.setCustomValidity(msg)
}

input.setCustomValidity && input.addEventListener('input', validateIntlInput)
```
☝️  that is basically all you need to do and this is what i'm asking of you in this issue, you don't need to update no attribute or add no html to the DOM in any way and we will be able to use `:invalid` css 


demo: https://jsfiddle.net/pk65r9nw/1/

**Comment by jimmywarting** [comment]
you could also use what is pressented in the mdn example...

```js
  if (toShort) {
    input.setCustomValidity('Phone number is too short')
  } else if (tooLong) {
    input.setCustomValidity('Phone number is too long')
  }
```

**Comment by jackocnr** [comment]
Hmm it's an interesting idea, but as you say, it would not work in countries with different languages, and also even in English, I don't think the plugin should decide how to word each kind of error message.

Due to this, and the fact that this functionality can be easily added outside of the plugin, I would recommend people just do that.
