### ISSUE TITLE
Switching of countries

### ISSUE THREAD

**Issue by inai-sahil-sachdev** [jackocnr/intl-tel-input#1303]
Whenever i start typing after choosing canada it switches to USA

### Steps to reproduce
1.  Initilize library
2.  Choose canada
3.  Start typing

### Expected behaviour
Stick to canada

### Actual behaviour
Switches to USA on typing

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by paddotk** [comment]
Duplicate https://github.com/jackocnr/intl-tel-input/issues/1295

**Comment by jackocnr** [comment]
See my comment in the above linked issue.
