### ISSUE TITLE
I want to switch off search functionality

### ISSUE THREAD

**Issue by inai-sahil-sachdev** [jackocnr/intl-tel-input#1305]
### Steps to reproduce
1.  Initialize library
2.  Open dropdown
3.  Type

### Expected behaviour
Dont search

### Actual behaviour
Searching

**Comment by inai-sahil-sachdev** [comment]
@jackocnr HELPPPPP

**Comment by jackocnr** [comment]
This is currently not possible. Why do you want to do this? Is it causing a problem?

**Comment by inai-sahil-sachdev** [comment]
@jackocnr Dude, i could only find your library working fine with our issue, thing is we cant take it forward until we dont have search box in country list dropdown, i need explicit search box. wont be able to create i dont switch yours off. Please give suggestions

**Comment by inai-sahil-sachdev** [comment]
Hey it won't be confusing as input wont be outside dropdown, but with help of css it could be fit inside dropdown, opened when dropdown is open, a fixed input at top of list and below will be the scrolling list. We are planning to use this library for a product which is a global payment solution ( can't reveal name )! So, if we go without search box it will be hard for mobile users to find their country. So, please assist us with this. 

i am adding a mock of some other dropdown for you to imagine.
<img width="217" alt="image" src="https://user-images.githubusercontent.com/86119521/164472077-85603593-0c60-4ede-a857-fccf798e8c4f.png">

**Comment by inai-sahil-sachdev** [comment]
@jackocnr  It would be pretty awesome if you could do this yourself and add in library with a search box instead of search on type, it would solve a greater problem

**Comment by jackocnr** [comment]
Yes as I said, the search input would be inside the dropdown, at the top. My question is, what does the dropdown look like next to the phone input, so you would see two inputs next to each other. I think this would be confusing.

**Comment by rubenbasco** [comment]
Hi @jackocnr 

Our team will also benefit from this. And same with @inai-sahil-sachdev , only this library is working for us. I think adding the search input will not be confusing as long as we put placeholder text in the field like screenshot below.

![dropdown](https://user-images.githubusercontent.com/92568008/166144372-5c1b24e3-b09a-4513-935c-ba8edaf768df.PNG)


Thank you.

**Comment by jackocnr** [comment]
Sorry but I find this super confusing.

The only design I can imagine that would work would be to move the dropdown to be a full screen modal, like we have on mobile, but personally I don't think it's worth it - I think on desktop it's a better UX to have the dropdown appear contextually  just below the selected flag.

Also I often refer to Google's design for this element (e.g. in Google Contacts) and they don't have this input search feature, so IMO this isn't a critical feature and is not worth the added code complexity and the worse UX, sorry.
