### ISSUE TITLE
No optional country for country dropdown

### ISSUE THREAD

**Issue by haripri-vt** [jackocnr/intl-tel-input#1306]
### Steps to reproduce
1.  Use the plugin
2.  Choose the pulldown for country
3.  No optional No country.

### Expected behaviour
Country dropdown should have an optional no country or select an option

### Actual behaviour
Country is required.

Even tried adding a "Select a country" using https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/modify-country-data.html
initializeIntlTelInputPlugin() {
      var countryData = window.intlTelInputGlobals.getCountryData(),
        input = document.getElementById(this.id);
      var newCountry = {
        areaCodes: null,
        dialCode: "",
        iso2: "",
        name: "Select",
        priority: 0,
      };
      countryData.unshift(newCountry);

      this.iti = intlTelInput(input, {
        preferredCountries: ["", "us", "ca"],
        separateDialCode: true,
        autoPlaceholder: "off",
        utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/utils.min.js",
      });
      this.iti.promise.then(() => {
        this.setInitialCountry(this.countryCode);
      });
    },

This does not work as well. Select shows up with + with no code and shows up both in preferred and regular list.

**Comment by haripri-vt** [comment]
Well such is our requirement , our database schema design that country code is optional. Also there is a mention that the plugin is used by ebay, I did check and somehow they got it working with one of the option being "Select a country". So I am wondering if others might be interested in this feature as well.

**Comment by jackocnr** [comment]
You haven't explained why this feature would be useful. And I can't see how it would possibly make sense from a design perspective.

As I said, if you're concerned about showing the wrong flag to the user initially, then I recommend you try the geoIpLookup initialisation option to automatically set the initial flag to the visitor's current country.

**Comment by nikmauro** [comment]
I have the problem, we have users to travel to other countrys and the geip return the current location and not the real country of the user.
