### ISSUE TITLE
Intialize intl-tel-input for dynamic fields

### ISSUE THREAD

**Issue by srivastava-jyoti** [jackocnr/intl-tel-input#1308]
### Steps to reproduce
1.  I have created a form. And clone of the form is created dynamically. Whenever I am trying to initialize the input(phone) field the initial form is getting Initialized while the other forms which are created dynamically are not initialized. Here' the code which I have written:
```jQuery('.bulk-gifting-collapse').on("click",function(){
    var phoneInput = jQuery(this).parents('.bulk-gifting-accordion-body').find('.bulk_gift_recipient_phone');
    phoneInput.each(function(){
        PhoneDisplay();
    })
});

function PhoneDisplay(){
    var input = document.querySelector('#bulk_gift_recipient_phone');
    window.iti = window.intlTelInput(input, {
        initialCountry: "in",
        utilsScript:  PARAMS.phone_utils_script,
        autoPlaceholder:'off'
    });
}
```

### Expected behaviour
Dynamically created fields should also be intialized.

**Comment by jackocnr** [comment]
I'm afraid this is just a straight JavaScript/jQuery problem, and so is outside the scope of the support I can provide. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).
