### ISSUE TITLE
setNumber/getNumber

### ISSUE THREAD

**Issue by Raketten1963** [jackocnr/intl-tel-input#1310]
### Steps to reproduce
1. create phone input object 
2. call setNumber(valid number)
3. call getNumber()

### Expected behaviour
getNumber should return valid number provided in the setNumber call

### Actual behaviour
getNumber return empty string
if calling setTimeout(getNumber,2000) the right number will be returned, so empty string is only returned if calling getNumber immediatly after calling setNumber

### Initialisation options
            autoPlaceholder: "aggressive",
            initialCountry: "auto",
            geoIpLookup: function(success) {
                // Get your api-key at https://ipdata.co/
                fetch("https://api.ipdata.co/?api-key=mykey")
                  .then(function(response) {
                    if (!response.ok) return success("");
                    return response.json();
                  })
                  .then(function(ipdata) {
                    success(ipdata.country_code);
                  });
              },
            separateDialCode: true,
            preferredCountries: ["us", "dk", "se", "de", "tw"],
            utilsScript:
            "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js",

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by ca-soho** [comment]
I am also experiencing this issue. I've just migrated a project from jQuery 1.8.3 to 3.6.0 and was previously using a very old version of `intl-tel-input` (v6.4.3) that was stored locally as a `min.js` file. I can confirm that this issue was not present before upgrading jQuery versions. Though, it is present with both v6.4.3 & v17.0.17. This is leading me to think that it might be something to do with using a deprecated jQuery method.

I have noticed that `string.trim()` has been replaced with `$.trim(string)` from jQuery 3.5.0 onwards. Perhaps it has something to do with that?

[Deprecated jQuery 3.5 method](https://api.jquery.com/category/deprecated/deprecated-3.5/)

I have also found evidence of `intl-tel-input` using the old, now deprecated method:
[intlTelInput-jquery.js Line 1129](https://github.com/jackocnr/intl-tel-input/blob/master/build/js/intlTelInput-jquery.js#L1129)

**Comment by boldizsarf** [comment]
I'm having the same issue, still not fixed. 

`function setDefaultNumber() {
        let preloadedNumber = '308113853';
        phoneInput.setNumber(preloadedNumber);
        console.log(phoneInput.getNumber());
    }`

With this, I got nothing in the console.

**Comment by ca-soho** [comment]
@boldizsarf I was having issues with this, it may not help but my issue was actually because I was using an outdated jQuery with the version of int-tel-input. I'd make sure that you're using the latest version of both int-tel-input and jQuery if not doing so already

**Comment by boldizsarf** [comment]
I'm using the latest jQuery and the latest version of int-tel-input, and still not working.

**Comment by fetis** [comment]
@jackocnr here's the pen that reproduces the bug
https://codepen.io/fetis/pen/oNqNVQK?editors=1111

if you call it immediately ->  empty string
if you click button to get a value -> value is returned but not in international format

**Comment by autb** [comment]
It's seems  the issue comes from the "window.inTelInputUtils" which is not yet loaded when  the first call of getNumber() is called due to the fact the documentReady() function return false becasue the document.readState is "loading" and not yet complete.

**Comment by thhVictor** [comment]
Had the same issue. In my case, it was because my intlTelInput was not initialized quick enough before I attempted to get the number. Initializing it early before I attempted to get the phone number worked.

**Comment by jackocnr** [comment]
As others have pointed out, this is a race condition. `getNumber` only works when the utils script has been loaded, which is an async process, so you need to make sure that has finished before you call it. If you check the docs for `utilsScript` option, you will see info about how the initialisation returns a promise that you can use to know when it's finished loading.
