### ISSUE TITLE
Reunion number validation issue

### ISSUE THREAD

**Issue by ferdossi** [jackocnr/intl-tel-input#1311]
### Steps to reproduce
1.  Select Reunion region (262)
2.  enter number  693 37 25 96

### Expected behaviour
It should be valid.

### Actual behaviour
It is not valid.  If you change only one number and replace with 693 3**9** 25 96, it will work, why?

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by ferdossi** [comment]
Thank you, just created an issue on libphonenumber
