### ISSUE TITLE
New telco in Oman, Vodafone's number not being accepted as Valid Number

### ISSUE THREAD

**Issue by p7Rck** [jackocnr/intl-tel-input#1312]
New telco in Oman, Vodafone's number not being accepted 
968 77XXXXXX

### Steps to reproduce
1.  Select Oman Region (968)
2.  Enter 77651234

### Expected behavior
It should be accepted because it is a valid number

### Actual behavior
It is considered not a valid number.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by jackocnr** [comment]
I've just released v17.0.17 with the latest version of libphonenumber - please see if that fixes your issue, else you'll need to open an issue with libphonenumber.
