### ISSUE TITLE
Us and Canada both selected because of same dialCode?

### ISSUE THREAD

**Issue by r-a-tutsek** [jackocnr/intl-tel-input#1320]
Hello,

Is there a way to configure this library to select Us and Canada differently?
The problem I currently have that If I select Canada it automatically Us too so I cannot select flags separately.

Or can the flag input be hidden?

Thanks!

**Comment by jackocnr** [comment]
This is not enough information for me to look into the issue effectively. Please read the [New Issue Checklist](https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist) and if necessary, open a new issue and follow the [New Issue Template](https://raw.githubusercontent.com/jackocnr/intl-tel-input/master/.github/ISSUE_TEMPLATE.md). If you are including any code, please [format it correctly](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Comment by hossein-hajimali** [comment]
i have the same problem for all countries with same country code, for example +1
