### ISSUE TITLE
intlTelInputGlobals.getInstance returns undefined

### ISSUE THREAD

**Issue by abilogos** [jackocnr/intl-tel-input#1322]
### Steps to reproduce
1.  var input = document.querySelector('#phone');
2.  var iti = window.intlTelInputGlobals.getInstance(input);

### Expected behaviour
iti be the instance on the page like what has been mentioned in the documents

### Actual behaviour
typeof(iti) == undefined

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries
preferredCountries, initialCountry

When trying to get the instance on the page with the ```intlTelInputGlobals.getInstance``` it returns undefined.
from the source code I have found out there should be a ```data-intl-tel-input-id``` attribute associating with the input field some time.

but it has been removed, so it didnt working properly.
I have fixed my problem with ```window.intlTelInputGlobals.instances[0]```
but there is a bug to report.

and if there is room, I can contribute myself too.

Thanks for providing such a good library.

**Comment by theseafoxx** [comment]
Experienced this issue in v17.0.19 intlTelInput-jquery.js

Added the following line within _generateMarkup() :

this.telInput.setAttribute("data-intl-tel-input-id", this.id);

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by valguss** [comment]
Here we go: https://codepen.io/valguss/pen/zYJmQOv
It's specifically the Jquery implementation doesn't set "data-intl-tel-input-id"

**Comment by jackocnr** [comment]
That getInstance stuff was only added for the pure JS implementation. If you're using the jQuery version you can just do it the jQuery way e.g. `$("#phone").intlTelInput("getNumber");` - there's a link to the old (out of date) jQuery docs here: https://github.com/jackocnr/intl-tel-input/blob/9512d6a7abcaa25769ac3b732390f3bb19872e76/README.md
