### ISSUE TITLE
[how to] Add Custom Floating Label 

### ISSUE THREAD

**Issue by ashickur-rahman** [jackocnr/intl-tel-input#1324]
I want to add custom floating label. Is there any way to do it?

**Comment by jackocnr** [comment]
Apologies for the delay in getting to this. Sometimes life gets in the way!

This plugin doesn't provide any kind of floating labels. You're free to add them yourself in your own code, or with another library or something, but that's outside the scope of the support I can provide - I'd recommend you ask on StackOverflow or something like that.
