### ISSUE TITLE
Non-numeric inputs as "Valid"

### ISSUE THREAD

**Issue by the-turk** [jackocnr/intl-tel-input#1327]
### Steps to reproduce
1.  Head into https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html
2.  Choose "Turkey" as the country.
3.  Type in **5313597243a** and click anywhere outside the input. (Note that phone numbers like 5313597243 is perfectly valid in Turkey)
4. See the "valid" text.

### Expected behaviour
Non-numeric inputs shouldn't be valid.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by the-turk** [comment]
Thanks! I've filed an issue on that library https://issuetracker.google.com/issues/237993328

**Comment by jackocnr** [comment]
Update: isValidNumber now returns false if it finds any alpha chars
