### ISSUE TITLE
Incorrectly recognizes the phone +660931234567

### ISSUE THREAD

**Issue by lvivphp** [jackocnr/intl-tel-input#1333]
```
(function ($) {
    $('#phone').intlTelInput({
      separateDialCode: true,
      hiddenInputField: "hiddenPhone"
    });
    $('#phone').on('change countrychange', function() {
       $('#hiddenPhone').val($('#phone').intlTelInput('getNumber', intlTelInputUtils.numberFormat.E164));
       // Or $('#hiddenPhone').val($('#phone').intlTelInput('getNumber'));
   });
})(jQuery);
```

When I enter the number "**+66**0931234567", the library correctly recognizes the country code *+66* (Taiwan), but the number itself parses "931234567" without a zero, but it should be "0931234567". And in the field hiddenPhone substitutes the number without zero "**+66**931234567".
The correct value should be "**+66**0931234567" in hiddenPhone.
I tried through the hidden method _getFullNumber, but jquery-version of this library, there is no access to this private method.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).
