### ISSUE TITLE
Phone number placeholder in Montenegro is a real number - owner is being called by random people

### ISSUE THREAD

**Issue by ybensadoun** [jackocnr/intl-tel-input#1334]
### Steps to reproduce
1.  Select Montenegro
2.  Placeholder number (067 622 901) is real

![image](https://user-images.githubusercontent.com/6509307/178537658-df0bbb46-a885-4ce7-88ed-dd1a766d4b06.png)

### Expected behaviour
Placeholder number should be a dummy phone number. It should follow the standar number of adding 12345 after the first numbers which show format. ie 067 622 901 becomes 067 123 456 (which I verified is not a real number)

### Actual behaviour
Placeholder number is a real number

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by faggv** [comment]
was going to open the same issue 👍 🙏

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).
