### ISSUE TITLE
Please make GH releases, not just tags

### ISSUE THREAD

**Issue by slaFFik** [jackocnr/intl-tel-input#1335]
I subscribed to Watch > Custom > Releases for this repo, but it's not triggering for lib's new releases because v17.0.17 (the current one) is not properly "Released" on GH (same goes for all the previous up until v17.0.0).

I would really appreciate if after creating and pushing the tag you could also go to GH and create a proper GH release, even without the description. This way GH will notify all subscribed.

Thank you.

**Comment by rbrezynski** [comment]
I would also be interested in this!

**Comment by raid5** [comment]
Same here! Also, we noticed v17.0.17 isn't on npmjs.com still...

**Comment by jackocnr** [comment]
Ok I've added one for 17.0.7 and will try and remember to do this moving forwards. Thanks.

**Comment by slaFFik** [comment]
@jackocnr I'm sorry for bothering you, but you created `v17.0.7` release for the `v17.0.17` tag which is a little bit confusing especially because you have https://github.com/jackocnr/intl-tel-input/releases/tag/v17.0.7 tag as well.

**Comment by jackocnr** [comment]
Oops! I blame Github as it was saying 17.0.7 is the "latest release" on the project homepage for some reason. Anyway it's fixed now with v17.0.18.

**Comment by jackocnr** [comment]
That happens automatically after some time
