### ISSUE TITLE
ngx-intl-tel-input using this can i give a custom tabindex dynamically in angular 2+??

### ISSUE THREAD

**Issue by Adhi-24** [jackocnr/intl-tel-input#1338]
### Steps to reproduce
1.  Make ngx-intl-tel-input as a separate component 
2. Use through out the application
3.  After that try to give custom tab index dynamically depends on page

### Expected behaviour
Tabindex should work properply

### Actual behaviour
It's working but not in a excepted way and tabindex is not proper

**Comment by jackocnr** [comment]
Sorry I have no knowledge of that package, you'd need to raise the issue with them.
