### ISSUE TITLE
945 area code is missing

### ISSUE THREAD

**Issue by adammcc** [jackocnr/intl-tel-input#1340]
### Steps to reproduce
1.  Enter a valid US phone number with area code 945, eg, (945) 555-5555
2.  The number will be invalid, but 945 is a valid area code for Dallas, TX

### Expected behaviour
945 area code should be valid. It is a new area code in Dallas, TX

### Actual behaviour
945 is showing as invalid.

### Initialisation options
N/A

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by jackocnr** [comment]
The number you gave is now coming up as valid.
