### ISSUE TITLE
TypeScript error in Project: 'IntlTelInput' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by sandeep10071996** [jackocnr/intl-tel-input#1341]
### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens
Its instance type 'IntlTelInput' is not a valid JSX element.
The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/Users/sandeep/Projects/Ionic/Nailsnow-Consumer/ionic-app/node_modules/@types/react-redux/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
          Type '{}' is missing the following properties from type 'ReactPortal': key, children, type, props

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
This is not enough information for me to look into the issue effectively. Please read the [New Issue Checklist](https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist) and if necessary, open a new issue and follow the [New Issue Template](https://raw.githubusercontent.com/jackocnr/intl-tel-input/master/.github/ISSUE_TEMPLATE.md). If you are including any code, please [format it correctly](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).
