### ISSUE TITLE
Dropdown Menu too big

### ISSUE THREAD

**Issue by Seven11HY** [jackocnr/intl-tel-input#1344]
I just can't get the problem fixed

![Screenshot 2022-08-06 175519](https://user-images.githubusercontent.com/108432556/183257709-40895fe9-b163-4a1c-8fb4-a83142733c40.jpg)

For some reason, the font size of the dropdown menu is way too big and I don't find the dedicated value in the CSS file to fix it.

**Comment by jackocnr** [comment]
We don't specify a font size in the plugin CSS, so this is all controlled by your own custom CSS.
