### ISSUE TITLE
intl-tel-input just show list of countries under phone input

### ISSUE THREAD

**Issue by mTLamouchi** [jackocnr/intl-tel-input#1347]
I have download intl-tel-input from github, but it's not working properly it just shows a list of countries under the phone input like so:
![image](https://user-images.githubusercontent.com/75030389/183964794-61560c98-facb-4fe0-95a1-8543b58a47fe.png)

**Comment by rohanharikr** [comment]
You have to import the `.css` file as well.

If you are using a bundler,
`import 'intl-tel-input/build/css/intlTelInput.css'`

If not,
`<link rel="stylesheet" href="path/to/intlTelInput.css">`

These are in the [README](https://github.com/jackocnr/intl-tel-input#getting-started-using-a-bundler-eg-webpack) of this repo.

**Comment by jackocnr** [comment]
Yes you need to follow all of the steps in the Getting Started section. If you have any problems, I would recommend asking on StackOverflow.
