### ISSUE TITLE
how to add in this search filter / search bar

### ISSUE THREAD

**Issue by khodidas-webmavens** [jackocnr/intl-tel-input#1351]
### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
This is not enough information for me to look into the issue effectively. Please read the [New Issue Checklist](https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist) and if necessary, open a new issue and follow the [New Issue Template](https://raw.githubusercontent.com/jackocnr/intl-tel-input/master/.github/ISSUE_TEMPLATE.md). If you are including any code, please [format it correctly](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Comment by jackocnr** [comment]
See new option `countrySearch` in v18.5.1. Let me know what you think!
