### ISSUE TITLE
+590 691 XX XX XX not valid (Guadeloupe)

### ISSUE THREAD

**Issue by DavidVlm** [jackocnr/intl-tel-input#1365]
but +590 690 XX XX XX works.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by DavidVlm** [comment]
Thanks for your reply.

I check from the test site, it confirms the phone number is rejected:

****Parsing Result:****
{"country_code":590,"national_number":691000000,"raw_input":"691000000","country_code_source":20}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: null
Result from getNumberType(): UNKNOWN

****ShortNumberInfo Results:****
Result from isPossibleShortNumber: false
Result from isValidShortNumber: false
Result from isPossibleShortNumberForRegion: false
Result from isValidShortNumberForRegion: false

****Formatting Results:**** 
E164 format: invalid
Original format: 691 00 00 00
National format: 0691 00 00 00
International format: invalid
Out-of-country format from US: invalid
Out-of-country format from Switzerland: invalid

****AsYouTypeFormatter Results****
Char entered: 6 Output: 6
Char entered: 9 Output: 69
Char entered: 1 Output: 691
Char entered: 0 Output: 6910
Char entered: 0 Output: 69100
Char entered: 0 Output: 691000
Char entered: 0 Output: 6910000
Char entered: 0 Output: 69100000
Char entered: 0 Output: 691000000
