### ISSUE TITLE
Automatic replace letters with numbers if number has  the right lenght

### ISSUE THREAD

**Issue by leenfares** [jackocnr/intl-tel-input#1366]
### Steps to reproduce
Hi every one , I have this problem

### Expected behaviour
I got "true" as result from isValidNumber() method when I use  "055fff5088" as UAE phone number .
From inspect I found the  intl-tel-input replace letters with numbers to give this "+971553335088"  as a result form getNumber()  
### Actual behaviour
 should return false from isValidNumber() and invalid number error 

Thanks  in advance

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by limjinsun** [comment]
I have same issue. Is this resolved? 
How can I prevent for changing "letter" to "number"?

**Comment by jackocnr** [comment]
Regarding the original issue, it seems that the op thought that isValidNumber should return false when the number contained alphabetic characters, but as I said, we use libphonenumber for validation, and so if you have an issue with validation you should contact them.

@limjinsun please can you open a new issue if you have a different problem?
