### ISSUE TITLE
North Macedonia - updates

### ISSUE THREAD

**Issue by tom-waat** [jackocnr/intl-tel-input#1367]
### Expected behaviour
* North Macedonia should be displayed as "North Macedonia (Северна Македонија)"
* alphabetically should be placed between "North Korea" and "Northern Mariana Islands"

### Actual behaviour
* North Macedonia is displayed as "North Macedonia (Македонија)" (name in brackets is incorrect)
* it's not placed alphabetically (between "Macau" and "Madagascar")

**Comment by jackocnr** [comment]
Thanks for raising this. I agree on both counts. I don't have time to implement this myself right now, but would be open to a pull request. All you need to do is update src/js/data.js and then build the JS - see the contributing instructions for more details.

**Comment by tom-waat** [comment]
I added pull request #1399
