### ISSUE TITLE
Area code 945 is showing invalid phone number.

### ISSUE THREAD

**Issue by RaviBandaru333** [jackocnr/intl-tel-input#1371]
I am using this package for couple of years but getting validation error for **945** area code as invalid phone number can any one help me on this. i am using the version 0.0.16.

    **"international-phone-number": "^0.0.16",**

### Steps to reproduce
1.  Enter 945 as a area code in the phone number field 
2.  showing the invalid phone number but it is one area code of Dallas city.
3.  Attaching the screenshots for [referance.](
![image (1) (1)](https://user-images.githubusercontent.com/48747224/199941328-7efcf366-169b-4741-8432-9c8623f0d512.png)

![image](https://user-images.githubusercontent.com/48747224/199941336-b2fd7333-01c8-4c0d-b328-81287a962a0c.png)

)

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by HannibalZA** [comment]
Use this as utilsScript to grab the latest libphonenumber build:

```
var iti = window.intlTelInput(input, {
  utilsScript: "https://cdn.jsdelivr.net/gh/codefixes/intltelinput/utils.js",
}); 
```

**Comment by jackocnr** [comment]
Please make sure you're using the latest version of the plugin.
