### ISSUE TITLE
Add the new wana extension (area-code): (53899)

### ISSUE THREAD

**Issue by merouaneamqor** [jackocnr/intl-tel-input#1372]
### Steps to reproduce
![image](https://user-images.githubusercontent.com/37594453/200885196-3f028bf4-d479-4c2f-aad1-03ad75e072c0.png)

### Expected behaviour
Pass the validation

### Actual behaviour
The validation stops all my forms to submit

Country: MA
Example number(s) and/or ranges: +212538-946062
Where or whom did you get the number(s) from: From my clients.

Authoritative evidence (e.g.national numbering plan, operator announcement):
here's the source

[https://www.itu.int/oth/T0202000090/en](https://www.google.com/url?q=https://www.itu.int/oth/T0202000090/en&sa=D&source=buganizer&usg=AOvVaw3z6Tnc9ljhrFcYFt27r6Mx)

[https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000900022PDFE.pdf](https://www.google.com/url?q=https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000900022PDFE.pdf&sa=D&source=buganizer&usg=AOvVaw3vI2526tEvVx4NoceW8BOC)

**Comment by merouaneamqor** [comment]
libphonenumber test result :


****Parsing Result:****
{"country_code":212,"national_number":538996833,"raw_input":"+212538996833","country_code_source":1}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Phone Number region: MA
Result from getNumberType(): FIXED_LINE

****Formatting Results:**** 
E164 format: +212538996833
Original format: +212 53899-6833
National format: 053899-6833
International format: +212 53899-6833
Out-of-country format from US: 011 212 53899-6833
Out-of-country format from Switzerland: 00 212 53899-6833

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by jackocnr** [comment]
This now passes as valid, so one of the updates to libphonenumber must have fixed it. Thanks for raising.
