### ISSUE TITLE
The description of the "countrychange" event in the readme is misleading.

### ISSUE THREAD

**Issue by smarekp** [jackocnr/intl-tel-input#1374]
The description of the "countrychange" event in the readme is misleading.

> **countrychange**
> This is triggered when the user selects a country from the dropdown.

The event can also be triggered by the country being auto-detected while the user is typing a number.

This became a problem for me when I set a validation message to appear on the "change" and "countrychange" events. The validation message would appear while I was typing because the country code changed on its own.

I suggest the readme be ammended, or the event only be triggered by the user deliberately changing the country via the dropdown.

### Steps to reproduce
1.  Create an input element with a value of "(541) 754-3010" (a US number) and initialize the plugin.
2.  Add a "countrychange" event listener to the input that produces an alert.
3.  Type "514" (a Canadian area code) into the input element.

### Expected behaviour
The alert is not triggered.

### Actual behaviour
The alert is triggered.

### Initialisation options
formatOnDisplay: true,
nationalMode: true,
utilsScript: "path/to/utils.js'

**Comment by dami95-tagvenue** [comment]
I agree that country-detection logic could add at least one property in `countrychange` event.

**Comment by jackocnr** [comment]
Thanks for pointing this out. I have updated the readme for now.

If you feel strongly that we need to have a property in the event data to differentiate between different types of country change events, then please open a separate issue and clearly outline the use case - why do you need to respond to different types of country change events in different ways? With clear examples. Thanks.
