### ISSUE TITLE
Regular Expression error when using the component

### ISSUE THREAD

**Issue by DavidOs55** [jackocnr/intl-tel-input#1377]
Hi,
I just downloaded ver  [17.0.19](https://github.com/jackocnr/intl-tel-input/releases/tag/v17.0.19).
I had a problem to run this component. 
The errors in the console:
first Error:
Uncaught SyntaxError: Invalid regular expression: /^[a-zA-ZÃ€-Ã¿Ð°-ÑÐ-Ð¯ ]$/: Range out of order in character class   
The error was in intelTelInput.js :763

Second error in my js file:
Uncaught TypeError: window.intlTelInput is not a function.
The error was for this row in my js:
`window.intlTelInput(input, {
      autoPlaceholder:"polite",
      utilsScript:'./build/js/utils.js'
    });`

**This is the solution for this bug:**
Add **charset="utf-8"** to the script tag:
<script src="./build//js/intlTelInput.js" charset="utf-8"></script>

I found this here:
[https://stackoverflow.com/questions/70917406/uncaught-syntaxerror-invalid-regular-expression-intltelinput/72238029#72238029](url)

The intel-tel-input team should add it to the demo here:
[https://github.com/jackocnr/intl-tel-input#getting-started-not-using-a-bundler](https://github.com/jackocnr/intl-tel-input#getting-started-not-using-a-bundler)

regards,
David

**Comment by jackocnr** [comment]
You should be declaring this charset in the `<head>` of your page: https://dev.to/maggiecodes_/why-is-lt-meta-charset-utf-8-gt-important-59hl
