### ISSUE TITLE
auto generate multiple instances and get data

### ISSUE THREAD

**Issue by fs0711** [jackocnr/intl-tel-input#1381]
I am generating 2nd phone number input field dynamically and there is no limit to the number of input fields tha user can generate. This library works great on 1 field thats loaded with the page but how to make it work with n number of inputs? It might be simple but I am relatively new to jquery and ajax. At the moment my ajax script is creating an array of all phone number inputs and posting it to api. How can I create an array of multiple fields using getNumber() function in ajax?

**Comment by jackocnr** [comment]
You just need to initialise the plugin once for each input, and keep hold of the instance variable (e.g. `iti` in the readme) for each one, and then call `getNumber` on each instance variable to get all of the numbers.

I'm afraid this isn't really about the plugin, it's more about general javascript advice, so if you have any followup questions, I'd suggest asking on StackOverflow.
