### ISSUE TITLE
HiddenInput name not working

### ISSUE THREAD

**Issue by mrelliot69** [jackocnr/intl-tel-input#1382]
### Steps to reproduce
1.  Try hiddeninput with array

WHen using a name like this on the input txRepeater[0][contact] the hiddenInput not works, can someone help figured out how i can have the hidden input being generated correclty txRepeater[0][contact][full] without problems

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
If your input has the name `txRepeater[0][contact]` and you init the plugin with `hiddenInput: "contact_full"` then the hidden input will be given the name `txRepeater[0][contact_full]`. That's the best we can do I'm afraid.
