### ISSUE TITLE
flag are looking so blurry specially USA

### ISSUE THREAD

**Issue by surindercrebos** [jackocnr/intl-tel-input#1383]
### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
Are the flags blurry for you on the [demo site](https://intl-tel-input.com/)? If not, then it sounds like an issue with your CSS. I'd suggest asking on StackOverflow.
