### ISSUE TITLE
I integrated intl-tel-input with WordPress plugin Ninja Forms

### ISSUE THREAD

**Issue by yaroslav-borodii** [jackocnr/intl-tel-input#1385]
## Message
Hello, I integrated intl-tel-input with WordPress plugin Ninja Forms
Please add an integration in the Integrations list.

## Links
**WordPress** page: https://wordpress.org/plugins/smart-phone-addon-for-ninja-forms/
**GitHub** repository: https://github.com/JDI-company/Smart-Phone-for-Ninja-Forms

Thank you

**Comment by jackocnr** [comment]
Done
