### ISSUE TITLE
Countries not sorted correctly when using localizedCountries option

### ISSUE THREAD

**Issue by lasseeee** [jackocnr/intl-tel-input#1390]
### Steps to reproduce
1.  Set localizedCountries to an object as per the docs
2.  Click the code dropdown in the browser
3.  Check the sort order for "Åland island" before and after adding the localizedCountries option

### Expected behaviour
Expect countries to be sorted correctly as it is before setting the localizedCountries option.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/1869424/212477717-d1eedfe1-abe8-4fda-96e5-46d6984f83f2.png">

### Actual behaviour
Sorting seem to not be utf8 aware anymore.

<img width="307" alt="Screenshot 2023-01-14 at 15 45 25" src="https://user-images.githubusercontent.com/1869424/212477683-9179aa82-14a9-45b0-8eea-417a4093b737.png">

### Initialisation options
```
localizedCountries: {
    'ua': '{{ trans('countries.ua') }}',
},
```

Even when leaving the localizedCountries option as an empty object or translating the offending country, the result is the same.

**Comment by lasseeee** [comment]
The fix would be to allow passing the locale to sort by as an option along to the second parameter of the `localeCompare()`used to sort the localizedCountries list., for example as `localizedSort`:

```
localizedCountries: {
    'ua': '{{ trans('countries.ua') }}',
},
localizedSort: "se",
```

**Comment by lasseeee** [comment]
I took some to try making a PR for this, but my knowledge about how this project gets it's options and just JS in general is too limited.

**Comment by jackocnr** [comment]
I've just pushed a change that should fix this - let me know if that works for you.

**Comment by jackocnr** [comment]
@lasseeee can you be more specific about what the problem is?

I actually now think it makes much more sense to have Aland Islands under Afghanistan than at the end of the list.

**Comment by lasseeee** [comment]
Good summary here: https://news.ycombinator.com/item?id=8004909

I lean towards agreeing with you.

**Comment by jackocnr** [comment]
Thanks for the link. Ok I'll close this one then 👍🏻
