### ISSUE TITLE
Unable to use New Zealand 11 digit mobile number

### ISSUE THREAD

**Issue by kjpluck** [jackocnr/intl-tel-input#1394]
### Steps to reproduce
1.  Enter NZ mobile number 02902011111 - have also tried   2902011111  +6402902011111 +642902011111 06402902011111 0642902011111 

### Expected behaviour
NZ number should be accepted.
[NZ mobile numbers begin with 02, followed by seven to nine digits (usually eight) ](https://en.wikipedia.org/wiki/Telephone_numbers_in_New_Zealand#Mobile_phones)

### Actual behaviour
Form doesn't accept format.

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by kjpluck** [comment]
I noticed this on two separate websites, however I just tried your demo page with the google validation library and it accepts it.
![image](https://user-images.githubusercontent.com/3460017/216801317-dfccd972-02a9-4d60-94c0-6bc888a9555e.png)
So it appears to be an implementation issue for the sites and not intl-tel-input.

Perhaps clearer configuration instructions are in order?

**Comment by Jameru** [comment]
I ran into the same issue with an 11 digit mobile number from Brazil.

But the demo isn't working for me either. No matter what I fill in, the ✓Valid check never appears. Is it broken right now?

![image](https://user-images.githubusercontent.com/8572067/221557242-a286fbd9-09bd-416e-a45a-d17ef09d01d6.png)

**Comment by jackocnr** [comment]
I think you just need to update to the latest version of the plugin (and utils.js!)
