### ISSUE TITLE
Reinit after Pjax call

### ISSUE THREAD

**Issue by strtob** [jackocnr/intl-tel-input#1395]
Is there a function to reninit the inlt-tel-input after .e.g. a pjax call. After pjax call the complete number is shown without a flag selected.

Cheers!

**Comment by jackocnr** [comment]
This is not enough information for me to look into the issue effectively. Please read the [New Issue Checklist](https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist) and if necessary, open a new issue and follow the [New Issue Template](https://raw.githubusercontent.com/jackocnr/intl-tel-input/master/.github/ISSUE_TEMPLATE.md). If you are including any code, please [format it correctly](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).
