### ISSUE TITLE
Add show/hideFlag option

### ISSUE THREAD

**Issue by johnnyshields** [jackocnr/intl-tel-input#1398]
Add a simple option to hide the flag element from the input. Some users may not want flags for aesthetic or political reasons.

Propose to make it `showFlag: true` by default, able to set it to `false`.

Users can use it in combination with `separateDialCode` to show dial code instead of flag.

**Comment by BariqDharmawan** [comment]
Maybe you could make a PR and the owner review it and merge it?

**Comment by jackocnr** [comment]
Hmm thanks for the idea. For me the flag is pretty integral to the plugin. I don't think many people will use this feature, so I don't want to bloat the code with it.

As a workaround, you can do this with 2 lines of CSS. Set the selected flag to `display:none` and override the `margin-left` on the selected dial code to zero.

**Comment by johnnyshields** [comment]
@jackocnr I would urge you to reconsider this. There are many major global corporations who have policies to avoid using flags because they can have political sensitivities. I think you are greatly underestimating the number of users who this would benefit.

**Comment by jackocnr** [comment]
Here are the 2 lines of CSS required, in case it is useful to you or anyone else (note this is specifically to be used with `separateDialCode` enabled):

```css
.iti__flag, .iti__flag-box { display: none; }
.iti--separate-dial-code .iti__selected-dial-code { margin-left: 0; }
```

https://codepen.io/jackocnr/pen/mdzyopv

**Comment by johnnyshields** [comment]
@jackocnr its a bit more involved than that. You need to set `separateDialCode` to true, and if I look at my code there's some dynamic CSS.

Again, given the common use case for this option, why not make it standard rather than have lots of users maintain brittle hacks?

**Comment by jackocnr** [comment]
Thanks for the input. You're right - a few other people have requested this over the years. I've just added a new `showFlags` option in v18.1.0 - let me know how it works for you.
