### ISSUE TITLE
Not loading on page change

### ISSUE THREAD

**Issue by nizalsha** [jackocnr/intl-tel-input#1408]
### Steps to reproduce
1.  set input in html
2.  initialize the input
3.  change page

### Expected behaviour
the input hast be shown when moved to one page and return to the same page

### Actual behaviour
when return to the same page input not shown, on reload it comes again
### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

 // Initialize the intl-tel-input plugin
    this.phoneInput = document.querySelector('#phone');
    if (this.phoneInput) {
     this.phoneInitializer = intlTelInput(this.phoneInput, {
       // Options
       utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@17.0.3/build/js/utils.js",
       initialCountry: Resources.providerDetails.country_code, // Set default country to provider country,
       preferredCountries: ['ae', 'in'], // Set preferred countries
     });
   }

this is how how i initialize the input, I am using it in angular.

**Comment by jackocnr** [comment]
Well this may well be an Angular specific issue, and unfortunately I have no experience with that so wont be much help.

Have you tried debugging it in Chrome devtools? If you put a breakpoint on your init code, is that being re-run when you return to the page? It sounds like it's not, in which case it's problem in your own code that I cannot help with. I'd recommend asking on StackOverflow.
