### ISSUE TITLE
403 error when using intl-tel-input

### ISSUE THREAD

**Issue by Benkooo** [jackocnr/intl-tel-input#1410]
I am currently trying to use the [ember-phone-input](https://github.com/qonto/ember-phone-input) package, which uses intl-tel-input dependency. 
Unfortunately I am getting the following error:

![Capture d’écran 2023-04-04 à 11 17 23](https://user-images.githubusercontent.com/39528559/229746442-f6e39e80-5d7a-4e01-86eb-f72b4d2bb85d.png)

I tried to add `intl-tel-input` to the dependencies of my repository but it does not seem to work.

Any thoughts?

**Comment by jackocnr** [comment]
Sorry I don't know anything about that package so cannot advise. I suggest you raise an issue with them, or on StackOverflow.
