### ISSUE TITLE
Auto country quota exceeded

### ISSUE THREAD

**Issue by hkalkhalifa** [jackocnr/intl-tel-input#1411]
Hello,
We're exceeding the daily quota of the ipinfo auto detection which results in the following:
<img width="229" alt="image" src="https://user-images.githubusercontent.com/129230544/230016739-fedc2d2c-e8cb-45aa-be46-b1a2c2951623.png">

We have a subscription in this website:
https://ipfind.co

I tried passing it to this but how does the ip address gets passed or fetched ?

`initialCountry: "auto",
        geoIpLookup: function(success, failure) {
            jQuery.get("https://ipfind.co/me?auth=key", function() {}, "jsonp").always(function(resp) {
                var countryCode = (resp && resp.country) ? resp.country : "";
                jQuery("#form-field-user_location").val(resp.country);
                success(countryCode);
            });
        },`

**Comment by jackocnr** [comment]
This is not enough information for me to look into the issue effectively. Please read the [New Issue Checklist](https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist) and if necessary, open a new issue and follow the [New Issue Template](https://raw.githubusercontent.com/jackocnr/intl-tel-input/master/.github/ISSUE_TEMPLATE.md). If you are including any code, please [format it correctly](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).
