### ISSUE TITLE
Sass compile warning

### ISSUE THREAD

**Issue by gonenli** [jackocnr/intl-tel-input#1414]
Latest version gives the following logs

Dart Sass compiled successfully, but with warnings:
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($arrowWidth, 2) or calc($arrowWidth / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div

Error: $triangleBorder: $arrowWidth / 2 !default;
File: node_modules/intl-tel-input/src/css/intlTelInput.scss 20:18

**Comment by jackocnr** [comment]
Thanks for reporting, I've just fixed this in v18.1.3.
