### ISSUE TITLE
A11y issue with country dropdown 

### ISSUE THREAD

**Issue by ElenaShevchenko** [jackocnr/intl-tel-input#1415]
A11y
### Steps to reproduce
1.  Set "separateDialCode" to true, country dial code next to the selected flag is appear
2. Choose Finland in a country list 
2.  Use NWDA screen reader and navigate to the flag dropdown

### Expected behaviour
NWDA should announce something like:  “Finland +358 combo box  collapsed”.

### Actual behaviour
NVDA announces “Finland +358 combo box +358 collapsed”. **SO the code is announced twice** 

### Initialisation options          
            separateDialCode: true,
            autoHideDialCode: true,
            allowDropdown: true,
            nationalMode: false,
            formatOnDisplay: true,
            
This issue is appear becouse country code is duplicate in "title" attribute
![image](https://user-images.githubusercontent.com/11269499/233320275-88c0f117-d0f9-491f-976b-6eff75d816fc.png)

**Comment by jackocnr** [comment]
Hmm what would you propose?

**Comment by ElenaShevchenko** [comment]
I think we can remove "+358" from the title for iti__selected-flag div in case separateDialCode: true,
only "Finland" should stay
