### ISSUE TITLE
Entering international number with starting 00 doesn't change the country

### ISSUE THREAD

**Issue by AdiIndoSwiss** [jackocnr/intl-tel-input#1416]
### Steps to reproduce
1.  If, i enter for example: 0041767684626 it should change to +41767684626 with swiss flag.
2.  If, i enter for example: 0033686579014 it should change to +33686579014 with french flag. 
3.

### Expected behaviour
1.  If, i enter for example: 0041767684626 it should change to +41767684626 with swiss flag.
2.  If, i enter for example: 0033686579014 it should change to +33686579014 with french flag. 
### Actual behaviour
nothing happens , flag stays the same

### Initialisation options
everything by default.

**Comment by jackocnr** [comment]
This question has been answered several times, please search the existing issues before creating a new one.

https://github.com/jackocnr/intl-tel-input/pull/5
