### ISSUE TITLE
A11y issue with selecting country option on Chrome

### ISSUE THREAD

**Issue by grzegorz-romanczuk** [jackocnr/intl-tel-input#1419]
A11y bug

### Steps to reproduce
1.  Go to https://intl-tel-input.com/ on Chrome
2.  Use VoiceOver and navigate to the country dropdown
3.  navigate between options using keyboard

### Expected behaviour
VoiceOver should read currently focused country. 

### Actual behaviour
VoiceOver skips reading currently focused country and reads the selected one.

### Initialisation options
Library demo

![image](https://user-images.githubusercontent.com/97388222/234282863-b56247fa-3bf1-45d8-ae1b-7f6064507a5a.png)

**Comment by jackocnr** [comment]
Hmm I'm not familiar with VoiceOver. When navigating with the keyboard, how do we communicate to VO which is the highlighted country?

**Comment by jackocnr** [comment]
Yes well the W3 example that we use as the basis for our aria tags actually doesn't include aria-owns so I would be happy to remove it. I would be open to a pull request that makes this change. Thanks
