### ISSUE TITLE
With initialCountry: "auto" and if only one country is set in onlyCountries, then an error occurs if another country is determined by IP

### ISSUE THREAD

**Issue by Morbids** [jackocnr/intl-tel-input#1422]
### **Steps to reproduce**
1.  If with such settings the user logs in from another country (let's say from Germany), then the flag (instead of the flag is a gray rectangle) and the country code are not displayed.

### **Expected behaviour**
It is necessary that the flag and country code of the US be displayed

### **Actual behaviour**
Error intlTelInput.js:1072 Uncaught Error: No country data for 'de'

### **Initialisation options**
```
var сountry = window.intlTelInput(inputTelephhone, {
   autoHideDialCode: false,
   nationalMode: false,
   formatOnDisplay: false,
   autoPlaceholder: false,
   separateDialCode: true,
   initialCountry: "auto",
   geoIpLookup: function(success, failure) {
     fetch('https://ipapi.co/json')
     .then( res => res.json() )
     .then( data => data)
     .then( (data) => {
       success(data.country_code?.toUpperCase());
     })
     .catch( error => success('us') );
   },
   onlyCountries: ["us"],
   utilsScript: "catalog/view/javascript/tel-input/js/utils.js"
 });
```

**Comment by jackocnr** [comment]
I don't understand why you'd ever want to have only one country in onlyCountries - can you explain your use case?

**Comment by Morbids** [comment]
Because during registration there are no options that the number will be with the code of another country, only one country is needed.
It turns out that either use a plugin with several countries or refuse to use this plugin? Or is there another option?

**Comment by Morbids** [comment]
If I understand correctly, then I need to replace "auto" with the country I need.

**Comment by jackocnr** [comment]
If you only have one country in onlyCountries, then you shouldn't need to use the initialCountry option at all.

I'll close this issue for now, but do let me know if you're still having problems.
