### ISSUE TITLE
Pasting the phone number into the field (international mode with separate dial code)

### ISSUE THREAD

**Issue by majokmet** [jackocnr/intl-tel-input#1425]
Hello,

### Steps to reproduce
1.  Use intl phone input in international mode with separate dial code
2.  Paste the number including country code (i.e. +421903123123) into the field

### Expected behaviour
Same as when using API - iti.setNumber('+421903123123'):
1) The numbers should get formatted
2) Country code should be only displayed in . iti__selected-flag "listbox" 

### Actual behaviour
Country code is displayed twice, number is not formatted

### Initialisation options
See the codepen: https://codepen.io/majokmet/pen/Rweeegb

Best regards,
Marian

**Comment by jackocnr** [comment]
Hmm I'm not sure about this. I don't like messing with what the user enters, and I count pasting as user input. It's one thing for the selected flag to update, but to suddenly reformat the number might be quite a jarring experience. E.g. if you paste a UK number (+44xxx), and then reformat, and you have nationalMode enabled, the formatting will remove the +44 but add a 0 at the beginning, which might feel weird for the user - to see the number changing and jumping around like that. I think currently nothing is broken - everything will work well, it just looks slightly odd to see the intl dial code twice like that, but I don't think it's a problem. And how often will users be pasting numbers with international dial codes anyway? I think it will be rarely. So I'd like to leave how it currently works. Thanks tho.
