### ISSUE TITLE
Phone number 0493753194 is a valid mobile number in Australia but intl-tel-input returns invalid number

### ISSUE THREAD

**Issue by tessamarelic** [jackocnr/intl-tel-input#1428]
### Steps to reproduce
1.  On your Demo site enter 0493753194
2.  Shows error invalid number
3.  Ring the number you'll see it is a valid mobile number.

### Expected behaviour
This number should be valid

### Actual behaviour
Returns invalid number

### Initialisation options
In our code we have used the following:
[allowedCountries]="['au']"
[isMobileOnly]="true"
placeholder="0400100100"
ngDefaultControl

**Comment by jackocnr** [comment]
This plugin doesn't use any of those options. I think perhaps you're using an angular version of this plugin? You'd need to open the issue with them instead.

**Comment by tessamarelic** [comment]
My mistake, those commands are not used directly with your library but with out own design system. We are using your library, when I add the number 0493753194 to your demo site it says invalid number but it isn’t. When I directly input into google phonenumber it is valid. Do you need to update your version.

**Comment by tessamarelic** [comment]
Hi Jack, sorry for confusion, we use intl-tel-input not the angular version, ignore those commands. I tried adding 0493753194 to your demo site and it returns invalid. When I enter it into google libphonenumber  version 8.13.14, the number is valid. Do you need to upgrade?We would really appreciate it if you could check on this as we use it to check customer numbers before opening their bank account and some are complaining.Thank you in advance.RegardsTessaSent from my iPhoneOn 15 Jun 2023, at 1:32 am, jackocnr ***@***.***> wrote:﻿
This plugin doesn't use any of those options. I think perhaps you're using an angular version of this plugin? You'd need to open the issue with them instead.

**Comment by jackocnr** [comment]
That number is coming up as valid on the demo site now 👍

**Comment by mathiashsteffensen** [comment]
@jackocnr We are still experiencing this issue on version 18.2.1. Is there a fix that has been merged into master?

We are currently loading the utils script distributed with this package "intl-tel-input/build/js/utils"

**Comment by theiconicpedropapa** [comment]
> @jackocnr We are still experiencing this issue on version 18.2.1. Is there a fix that has been merged into master?
> 
> We are currently loading the utils script distributed with this package "intl-tel-input/build/js/utils"

Be sure you're using both `intlTelInput.min.js` and `utils.js` to the same version (v18.2.1). Can confirm we were having the same issue with 0493XXX phone numbers and it has been fixed in this newest version.
