### ISSUE TITLE
Valid phone number shows invalid on your demo site.

### ISSUE THREAD

**Issue by tessamarelic** [jackocnr/intl-tel-input#1429]
### Steps to reproduce
1.  Enter phone number au 0493753194 into this demo site
2.  When I check on google libphonenumber version 8.13.14 the number is valid
3.  Do you need to update libphonenumber version, this is a customers valid mobile number, I have rung and talked to them.

### Expected behaviour
Valid number

### Actual behaviour
invalid number

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
Thanks for raising this. Yes it sounds like we need to update to the latest version of libphonenumber. I'll try and get around to it this weekend if I can, but alternatively it's quite straightforward to do yourself - see the Contributing guidelines.

**Comment by tessamarelic** [comment]
Thanks Jack, that would be great if you can update it. I'm not very familiar with this stuff.

**Comment by biokillos** [comment]
@jackocnr @tessamarelic I raised a PR here - https://github.com/jackocnr/intl-tel-input/pull/1437 🙏

**Comment by tessamarelic** [comment]
Thank you @biokillos

**Comment by jackocnr** [comment]
Just published v18.1.7 with this in 👍

**Comment by biokillos** [comment]
@tessamarelic yes, the docs were pretty helpful - https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber

@jackocnr I confirm it's all working now for me and latest AU numbers are now valid using the widget, thank you for quick turnaround with merging
