### ISSUE TITLE
Countries displayed on screen as <li> elements, not dropdown

### ISSUE THREAD

**Issue by ScogMellonhead** [jackocnr/intl-tel-input#1436]
### Steps to reproduce
Hi, I'm using jquery UI tabs, and trying to implement your telephone plugin. The issue I'm having is, the countries are displayed on the screen within the tab as a <ul> rather than as a dropdown select list. I'm guessing that because I'm loading/using the plugin within a tab, and not on the parent document/url, this is causing issues. I'm guessing I need to target the specific tab I'm in rather than the "Window."?
Any ideas?

![image](https://github.com/jackocnr/intl-tel-input/assets/65965339/d14b26de-ef33-41b4-a09d-c7bfea2a041f)

Thanks!

- Scog (Tim)

**Comment by jackocnr** [comment]
I'm afraid I don't know anything about jQuery UI Tabs, but it looks to me like the CSS isn't being applied. Can you check that the plugin CSS is being loaded on the page?

**Comment by ScogMellonhead** [comment]
Bingo - thanks!
