### ISSUE TITLE
Need to override ext. text adding to the phone number

### ISSUE THREAD

**Issue by vasundharask65** [jackocnr/intl-tel-input#1438]
### Steps to reproduce
1.  I am copying the text from notepad  (example: "6504191505,,357825348#")  and pasting in the telephone textbox which is linked to this plugin.  
2.  As soon as I paste, it is formatting the text as "'(650) 419-1505 ext. 357825348'" in the textbox
3.  I actually have two text boxes one linked with this utility and another to save the extension.  
4. The user expectation is to show this as error and not considered as extension

 

### Expected behaviour
The user expectation is to show this as error and not considered as extension

 

### Actual behaviour
But it concatenates all text and adding extension in the middle and render everything in one text box 
![image](https://github.com/jackocnr/intl-tel-input/assets/85946757/ebea8b27-ebad-4858-956f-476569813d64)

**Comment by jackocnr** [comment]
Sorry I don't understand. Please can you break it down into simple and clear steps, as per the [New Issue Guidelines](https://github.com/jackocnr/intl-tel-input/issues/new).

**Comment by vasundharask65** [comment]
### Steps to reproduce
1.  I am copying the text from notepad  (example: "6504191505,,357825348#")  and pasting in the telephone textbox which is linked to this plugin.  
2.  As soon as I paste, it is formatting the text as "'(650) 419-1505 ext. 357825348'" in the textbox
3.  I actually have two text boxes one linked with this utility and another to save the extension.  
4. The user expectation is to show this as error and not considered as extension

 

### Expected behaviour
The user expectation is to show this as error and not considered as extension

 

### Actual behaviour
But it concatenates all text and adding extension in the middle and render everything in one text box 
![image](https://github.com/jackocnr/intl-tel-input/assets/85946757/ebea8b27-ebad-4858-956f-476569813d64)

**Comment by jackocnr** [comment]
Hmm, which version of the plugin are you using? This plugin hasn't supported auto-formatting on paste for a long time, and I'm afraid I can only provide support for the latest version.

**Comment by vasundharask65** [comment]
We are using International Telephone Input v17.0.19.

**Comment by jackocnr** [comment]
I'm pretty sure we didn't have auto-format-on-paste in the plugin at v17.0.19. Are you sure it's not your own code that is creating this behaviour?

If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by vasundharask65** [comment]
![image](https://github.com/jackocnr/intl-tel-input/assets/97882351/236da52a-2d3b-4ce5-abc4-2d5cbfe01dae)

I debugged after pasting the invalid phone pattern, this below line 
**window.appIntl[input.id].setNumber(value);**  setNumber() is converting the 6504191505,,357825348# to (650) 419-1505 ext. 357825348

**Comment by jackocnr** [comment]
This is not plugin code... it must be your own! I think this is a question for StackOverflow. I'll close this for now.

**Comment by vasundharask65** [comment]
I have forked and put up sample in the codePen. I request you to have a look at it. 

CodePen sample: [https://codepen.io/Vasundhara-the-builder/pen/dyQOJKj](url) 

Explanation: 
1. I did include formatOnDisplay as true and initialCountry as US. 
2. As always the utilscript is loaded 
3. On "Keyup" event, I'm getting the value from input text box and setting it using this line **window.iti.setNumber(input.value);** This setNumber() is the one converting my phone number to valid pattern. 
4. If you try with the below samples and paste it in the input, you would see **ext. text** getting added to the phone number. 

Sample phone number:
1. 6504191505,,357825348# 
2. TF (888-846-1970 x 477
3. 717 -751-0300 x349

I want to know why it is adding ext. text to the phone number and want to override this method so that I can separate ext value and place it to other textbox. I'm pretty sure that is not from our own logic. 

Could you please have a look at it.

**Comment by jackocnr** [comment]
I see, so your question is: when I call `setNumber` with "6504191505,,357825348#" why is it formatting it like this "+1 650-419-1505 ext. 357825348". The answer is simply that we use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting - you can play with [their test site here](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) - if you enter that number, and put default country=us then you will see "International format" returns "+1 650-419-1505 ext. 357825348". So by default when you call `setNumber`, it gives you the international format. 

An alternative to calling setNumber is to call `intlTelInputUtils.formatNumber` (see [wiki](https://github.com/jackocnr/intl-tel-input/wiki/utils.js)) where you can specify the format you want - you could either get the E164 format, which ignores any extension, or if you want to extract the extension part, there's currently no straightforward way to do this, but an easy way would be to get the international format, and then check if the string contains "ext." and if so, split on that and get the bit after "ext.". Does that make sense?
