### ISSUE TITLE
Some numbers in Singapore are showing as Invalid number

### ISSUE THREAD

**Issue by robertwang101** [jackocnr/intl-tel-input#1441]
### Steps to reproduce
1. Select country as Singapore
2. Enter a phone number with format like +658067XXXX

### Expected behaviour
The Singapore mobile number started with 8067 should be valid, e.g. +658067XXXX

### Actual behaviour
The Singapore mobile number started with 8067 has been defined as invalid. Pls find below as the result of testing +658067XXXX in the test site

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: SG
Result from getNumberType(): UNKNOWN

**Comment by jackocnr** [comment]
We use isValidNumber for validation, and as you can see from your results, libphonenumber declares that invalid. You'll need to raise the issue with them.
