### ISSUE TITLE
How to change default formatting on custom format?

### ISSUE THREAD

**Issue by 0x800040005b** [jackocnr/intl-tel-input#1442]
Hi! I use your plugin in my  project. I want to add brackets to dial code, and change default format number on my format what i will specify. But i can't find any property, which will change default format number to my... When i try to add brackets to dial code through native JS the script doesn't react anything.

How to do it???

P.S. Thank for the answer

**Comment by jackocnr** [comment]
Sorry what exactly are you talking about? The formatting that gets applied when you initialise the plugin on an input that already contains a phone number?

Can you provide a specific example of a number, and which country, and how it is currently being formatted, and how you would like it to be formatted?

**Comment by 0x800040005b** [comment]
Yes, the formatting that gets when plugin initialises. I'd like to change it  to add brackets of dial code for example: (380) or (1) etc. 

for example: + (380) 66 375 12 441

 i'd like to specify my custom formatting

but i can't find the property to do it

**Comment by jackocnr** [comment]
First of all, libphonenumber says that your example number is invalid, so better to use a real number, e.g. a random hotel's number, like this one:  +380472360199.

The only formatting control you have is with the `nationalMode` flag - so either national format or international format, which are listed below (taken from the [libphonenumber test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html))

National format: 0472 360 199
International format: +380 472 360 199

**Comment by 0x800040005b** [comment]
ok. but i can change number and how do i get number format???

**Comment by jackocnr** [comment]
You cannot specify your own custom format. You can only set nationalMode to true (for national formatting) or false (for international formatting).
