### ISSUE TITLE
Side Panel gets closed upon changing the country in mobile view

### ISSUE THREAD

**Issue by SoniAmit7198** [jackocnr/intl-tel-input#1443]
### Steps to reproduce
1.  Open website: [https://www.revatics.co.uk](https://www.revatics.co.uk) in mobile view
2.  Click on the call icon from the header [a side panel will get opened from the right]
3.  Change the country from the dropdown.
4. The side panel will get closed.

### Expected behaviour
The side panel should not get closed

### Actual behaviour
Side panel gets closed upon changing country in the mobile view

### Initialisation options
`let config = {
    preferredCountries: ["gb", "ca", "us", "in"],
    utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@18.1.7/build/js/utils.js",
    separateDialCode: !0
}`

https://github.com/jackocnr/intl-tel-input/assets/115342760/ad4b15ef-a258-4e8b-8eed-037b8935a301

**Comment by jackocnr** [comment]
I'm afraid this is an issue with your own website code and so is outside the scope of the support I can provide. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).
