### ISSUE TITLE
Flags are not showing correctly.

### ISSUE THREAD

**Issue by qalbit** [jackocnr/intl-tel-input#1444]
![image](https://github.com/jackocnr/intl-tel-input/assets/34829268/95a31a1d-a4ce-4b28-aa2c-9db193a1b54e)

I have linked tel input in my site. But it not showing flags images properly. Any solution?

**Comment by jackocnr** [comment]
This is just a case of making sure your page loads the plugin CSS file, and the image file, so it's not really a plugin specific issue. It might be a network issue, or a caching issue... I would recommend you ask on StackOverflow.
