### ISSUE TITLE
Do not working on Django

### ISSUE THREAD

**Issue by allysonp23** [jackocnr/intl-tel-input#1448]
Hello, I'm trying to implement your plugin in a Python-Django project. However, it raised a question;
Can you tell me if the project is compatible with Django? Because I can't send the correct formatting to the Django form, it always returns an error saying the format is invalid, even though it is sent correctly when I put the code on Codepen, for example.

**Comment by jackocnr** [comment]
I'm afraid I don't have any experience with Django, but if it allows you to run JavaScript and add CSS to the page, then there's no reason it shouldn't work. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).
