### ISSUE TITLE
Some Flags are showing wrong

### ISSUE THREAD

**Issue by viveknath3222** [jackocnr/intl-tel-input#1454]
Hi,

Some of the flags are showing incorrectly. I've added JS and CSS files correctly to my project folder and initialized with below script

`<script>`
  `const input = document.querySelector("#phone");`
 ` const inputMobile = document.querySelector("#Mobile");`
  `const inputCompany = document.querySelector("#CompContact");`
  `window.intlTelInput(input, {`
    `initialCountry: "Au",`
   ` utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@18.1.1/build/js/utils.js",`
  `});`
  `window.intlTelInput(inputMobile, {`
   ` initialCountry: "Au",`
  `  utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@18.1.1/build/js/utils.js",`
 ` });`
  `window.intlTelInput(inputCompany, {`
  `  initialCountry: "Au",`
 `   utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@18.1.1/build/js/utils.js",`
`  });`
`</script>`

![image](https://github.com/jackocnr/intl-tel-input/assets/138550507/b2150330-b0c7-4dca-bb20-f968b9ffb7e6)

**Comment by jackocnr** [comment]
Try using the latest version of the plugin, that may fix it.

**Comment by viveknath3222** [comment]
> Try using the latest version of the plugin, that may fix it.

Just updated to latest version and its working perfectly.

Thanks.
