### ISSUE TITLE
There has been an error with pakistan mobile number code (0338 and 0339) validation!

### ISSUE THREAD

**Issue by shariqshahab** [jackocnr/intl-tel-input#1460]
Kindly view attached screenshot 
![Screenshot 2023-08-21 173054](https://github.com/jackocnr/intl-tel-input/assets/11956324/20872a42-b6fa-4660-8719-4050c56f1f9a)

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).
