### ISSUE TITLE
Live searching need add

### ISSUE THREAD

**Issue by wdshahadat** [jackocnr/intl-tel-input#1461]
### Steps to reproduce
1.  live search not working
### Expected behaviour
A country name search option is needed.
is it possible to add a search option?

### Actual behaviour
Country name search option not found.

### Initialisation options
List any options you're using e.g. utilsScript or preferred countries

**Comment by jackocnr** [comment]
> live search not working

You should be able to open the dropdown and type the first few characters of a country name and it should select that country. Is that not working for you?

**Comment by muhammadawais93** [comment]
Hey, I'm waiting for the search country feature and it will be really helpful if we merge this feature, Thanks

**Comment by a-asmaa** [comment]
@jackocnr I'm looking forward to adding this feature country search, which will enhance the user experience. any plan to merge this PR?

**Comment by jackocnr** [comment]
I am now open to this idea, but the linked PR needs a lot of work before it's ready to merge.

**Comment by jackocnr** [comment]
I've implemented this myself now. See new option `countrySearch` in v18.5.1. Let me know what you think!
