### ISSUE TITLE
Integration with NextJS or React

### ISSUE THREAD

**Issue by dexterarmy** [jackocnr/intl-tel-input#1462]
Hi , can you please show me how can i use this library with NextJS  , I am really finding it difficult to integrate it with nextJS. Can you just show me an example code ?

If not NextJS , you can also show me an example with React ?

**Comment by jackocnr** [comment]
If you search the issues for "react" you will find an example of how to use the plugin with react. As for NextJS, I would just say on the server render you only want to render the input, and then only initialise the plugin in the client-only code. Does that make sense? I'll close this for now, but let me know if you have any more questions.
