### ISSUE TITLE
json-schema 0.2.3 has security vulnerabilities

### ISSUE THREAD

**Issue by bickart** [jackocnr/intl-tel-input#1468]
### Steps to reproduce
1.  json-schema version 0.2.3 is used and is identified in jackocnr/intl-tel-input/package-lock.json

### Expected behaviour
json-schema is known to have security vulnerabilities 

### Initialisation options
Upgrade to a newer version of json-schema such as 0.4.0

**Comment by jackocnr** [comment]
Thanks. Fixed.
