### ISSUE TITLE
`isPossibleNumber` undefined when loading utils from CDN

### ISSUE THREAD

**Issue by ArjanJ** [jackocnr/intl-tel-input#1470]
### Steps to reproduce
1.  Load utils script from `https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/utils.js`
2.  Call `isPossibleNumber()` method
3.  Receive error `Uncaught TypeError: iti.isPossibleNumber is not a function`

### Expected behaviour
`isPossibleNumber` should be defined

### Actual behaviour
`isPossibleNumber` is undefined so no validation happens

### Initialisation options
```
  iti = intlTelInput(phoneInput, {
    utilsScript: 'https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/utils.js',
  });
```

Might be useful, logging the `iti` object, as you can see there's no `isPossibleNumber` method.

![image](https://github.com/jackocnr/intl-tel-input/assets/8673267/2d248080-0546-408e-8bd5-59858444c665)

**Comment by georgijk5** [comment]
I'm also getting this issue, only on Safari browsers (IOS/MAC). From the tests that I've run, the initialization promise does not go through.

Using 18.2.1 library and utils script.

**Comment by jackocnr** [comment]
Sounds like a caching issue to me.
