### ISSUE TITLE
On Post Request not getting the full number .

### ISSUE THREAD

**Issue by shabyis** [jackocnr/intl-tel-input#1472]
I have saved the full number in first try that look like this:

![image](https://github.com/jackocnr/intl-tel-input/assets/134594431/191765f4-e846-4e98-b3a4-a1df605f0d6f)

But second time when i submit the form again it give me the number without country code and an additional 0

![image](https://github.com/jackocnr/intl-tel-input/assets/134594431/9dcefb24-68bf-4029-8124-7679ea840e98)

That is causing the validation issue in some cases.

Can you guide how to get full number in php after submiting the form

**Comment by jackocnr** [comment]
If you're using old-school form submits that reload the page, then see the `hiddenInput` option for getting the full international telephone number.

If you're using modern ajax requests, then you can get the full number with `getNumber` method.

Does that answer your question? I'll close this for now, but feel free to re-open if you're still having problems.
