### ISSUE TITLE
utils.js:1 Failed to load resource: the server responded with a status of 500 ()

### ISSUE THREAD

**Issue by Novanesthi** [jackocnr/intl-tel-input#1473]
i am experiencing the error "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" when trying to access the "National Mode" feature.

I have tried to:

Reload the page.
Try again later.
Clear my browser's cache and cookies.
Try accessing the feature using a different browser.
I have provided the following information to help you diagnose the issue:

Environment:

OS: Windows 10
Browser: Chrome 103.0.5060.114
Code version: 1.0.0
Steps to reproduce the issue:

Open the "National Mode" feature.
Click the "Start" button.

Once you submit the issue, the developer will be able to see it and start working on a solution. They will let you know about their progress through comments on the issue.

Here are some tips for creating an effective issue:

Provide a clear title and a detailed description of the issue you are experiencing.
Include as much information as possible that can help the developer diagnose the issue.
Use relevant labels to help developers find your issue.
I hope this helps!

**Comment by jackocnr** [comment]
I'm afraid this is outside the scope of the support I can provide. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).
