### ISSUE TITLE
Multiple problems in IE 11

### ISSUE THREAD

**Issue by M4ttsson** [jackocnr/intl-tel-input#1476]
Unfortunately we still have customers that use IE 11 and the latest version is not working. The live demo page is also not working in IE11. 

It seems like there might be two issues, one is the usage of 'closest' method that is unsupported. And an error in utils.js that only says 'Const must be initialized (6,541)' but we were unable to figure out what is wrong there, "isValidNumber" method always returns false. 

Usage of 'closest' was added in #1430. A workaround is to use a Polyfill as per stackoverflow (https://stackoverflow.com/a/61958369). But still not working properly due to our usage of utils.

### Steps to reproduce
1.  Create site with intl-tel-input, everything default. (or use included html example below)
2.  Start IE11, go to page. 
3.  Look at errors in console, input field is just an empty input field and no flags etc.

### Expected behaviour
IE 11 is listed as supported so it should work.

### Actual behaviour
Two errors in console. One is that closest is unknown (flags will not be shown) and the other is that utils.js has syntax errors and will not work.
![image](https://github.com/jackocnr/intl-tel-input/assets/14147055/46f4f394-bae5-4cce-bf4e-9995d79d5cf3)
![image](https://github.com/jackocnr/intl-tel-input/assets/14147055/c1ebc6cc-7c58-48c4-9a8c-a421ccfa0c14)

### Initialisation options
See getting-started-using-a-cdn on Readme. Including a tiny repro page below. 

### Repro page
```
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/css/intlTelInput.css">
    </head>
    <body>
        <input id="phone" />

        <script src="https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/intlTelInput.min.js"></script>
        <script>
          const input = document.querySelector("#phone");
          window.intlTelInput(input, {
            utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/utils.js",
          });
        </script>
    </body>
</html>
```

Ps. If using Win 11. The easiest way to still open IE is to put the following in a .vbs file.
`CreateObject("InternetExplorer.Application").Visible=true`

**Comment by jackocnr** [comment]
Thanks for reporting this, but unfortunately, given IE11 has now [been retired](https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/), we'll be dropping support too. I've updated the readme to reflect this.
