### ISSUE TITLE
Getting Avoid an excessive DOM size while checking the page on Google page insights

### ISSUE THREAD

**Issue by technicalbirdVayuz** [jackocnr/intl-tel-input#1487]
### Steps to reproduce
1.  Go to Google page insights
2.  Mention the website link where you integrated this library
3.  Check the DIAGNOSTICS section as the part

### Expected behaviour
- Error should not come

### Actual behaviour
- error is coming

**Comment by jackocnr** [comment]
If you search the issues for "DOM size" you will find the solution - see `dropdownContainer` option.
