### ISSUE TITLE
"ReferenceError: window is not defined" since release 18.3.0

### ISSUE THREAD

**Issue by jeffaus** [jackocnr/intl-tel-input#1489]
### Steps to reproduce
1. Install version 18.3.0 or above 
2. Import intlTelInput from 'intl-tel-input' in a NextJS project
3. Bring the project up and view the terminal output

### Expected behaviour
intl-tel-input should check if window is available.

### Actual behaviour
I am using intl-tel-input in a component library project which is then installed into a NextJS project. Since version 18.3.0 I am now getting the following error in my terminal:
⨯ node_modules/intl-tel-input/build/js/intlTelInput.js (163:92) @ <unknown>
⨯ ReferenceError: window is not defined

I have tracked down the issue to the introduction of the useFullscreenPopup option. Specifically line 163 where the default value is defined and it checks either the user agent, or if window.width < 500

https://github.com/jackocnr/intl-tel-input/blob/03277c42303dfec9bd53c78fe9f8bad891598799/build/js/intlTelInput.js#L163C30-L163C30

I realise I could just overwrite the default option, so there's an easy workaround for now. But figured I'd let you know in case anyone else raises the issue.

**Comment by jackocnr** [comment]
Released in v18.3.4
