### ISSUE TITLE
Is there a reason why I have to flags displaying?

### ISSUE THREAD

**Issue by NubbDev** [jackocnr/intl-tel-input#1490]
### Steps to reproduce
Video of what's happening: https://img.nubbless.me/2023/12/j3vHwa2aSs.mp4

Using Svelte and using the CDN (because the npm package giving me weird `navigator undefined` error)
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/css/intlTelInput.css">
<script src="https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/intlTelInput.min.js" defer></script>
```

```svelte
<script lang="ts">
    import { onMount } from 'svelte';
    export let phone: string;
    let input: HTMLInputElement;
    let iti: any;
    
    onMount(() => {
        window.intlTelInput(input, {
            utilsScript: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js',
            initialCountry: 'ca',
            preferredCountries: ['ca', 'us']
        })
        iti = window.intlTelInputGlobals.getInstance(input)


    })

    const phoneHandler = () => {
        phone = `+${iti.getSelectedCountryData().dialCode}${iti.getNumber()}`
    }

</script>

<input type="tel" id="phone" name="phone" placeholder="Phone number" bind:this={input} on:input={phoneHandler}/>
```

### Expected behaviour
Show input, then hide input

### Actual behaviour
A second flag is displayed when updating anything on the screen

### Initialisation options
```js
utilsScript: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js',
initialCountry: 'ca',
preferredCountries: ['ca', 'us']
```

**Comment by jackocnr** [comment]
The `navigator undefined` error should now be resolved if you update to v18.3.4.

Please use the same version in both the plugin version and the utilsScript version.

As for the duplicate flag - I'm guessing you're somehow initialising the plugin a 2nd time - can you inspect the markup to confirm this? If so, this is a problem in your own code, which is outside the scope of support I can provide - I recommend you ask on StackOverflow.
