### ISSUE TITLE
Version 18.2.1 compared to the recent versions in Sveltekit

### ISSUE THREAD

**Issue by brnkgabriel** [jackocnr/intl-tel-input#1494]
### Steps to reproduce
1.  pnpm install intl-tel-input
2.  setup the code in a project like so
<script lang="ts">
	import intlTelInput from 'intl-tel-input'
	import "../../../styles/intlTelInput.min.css"
	import { onDestroy, onMount } from 'svelte';
	import { Events } from '$lib';
	
	let phoneInput: HTMLElement;

	let countryName: string = 'Nigeria';
	let countryCode: string = '+234';
	let countryIsoCode: string = 'ng';
	let phoneInputIntl: intlTelInput.Plugin;

	const handleCountryChange = () => {
		countryIsoCode = phoneInputIntl.getSelectedCountryData().iso2
		countryCode = `+${phoneInputIntl.getSelectedCountryData().dialCode}`;
		countryName = phoneInputIntl.getSelectedCountryData().name;
	};

	onMount(() => {
		// handling international phone input
		phoneInputIntl = intlTelInput(phoneInput, {
			// utilsScript: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/utils.min.js',
      utilsScript: '/utils.min.js',
			preferredCountries: ['uk'],
			separateDialCode: true,
			initialCountry: "ng"
		});

		countryName = phoneInputIntl.getSelectedCountryData().name;

		phoneInput && phoneInput.addEventListener(Events.COUNTRYCHANGE, handleCountryChange);
	})

	onDestroy(() => {
		phoneInput && phoneInput.removeEventListener(Events.COUNTRYCHANGE, handleCountryChange);
	});
</script>

<svelte:head>
	<title>Booking | 3H Villas</title>
	<meta name="description" content="Secure Your Stay Today for Exclusive Offers and Rates" />
	<meta property="og:description" content="Secure Your Stay Today for Exclusive Offers and Rates" />
</svelte:head>
<section>
	<div class="acenter flex justify-center items-center">
		
		<form action="?/book" method="post" enctype="multipart/form-data" class="flex flex-col gap-4 w-full max-w-md">
			<input type="date" name="arrival" class="input input-bordered bg-transparent w-full max-w-xs date-input" />
			<input type="date" name="departure" class="input input-bordered bg-transparent w-full max-w-xs date-input" />
			<input type="email"  name="email" placeholder="Email address" class="input input-bordered bg-transparent w-full" />
			<input type="number"  name="phoneNumber" bind:this={phoneInput} placeholder="Phone number" class="input input-bordered bg-transparent w-full" />
			<select
				class="select select-bordered w-full bg-transparent dark:text-white"
				name="levelOfStudy"
				required>
				<option disabled selected>Room Type</option>
				<option class="dark:text-font" value="classic">Classic</option>
				<option class="dark:text-font" value="deluxe">Deluxe</option>
				<option class="dark:text-font" value="executive">Executive</option>
			</select>
		</form>
	</div>
</section>
4.  

### Expected behaviour
should work without clientside errors on a serverside page

### Actual behaviour
Gives this error: navigator is not defined  at C:\Users\JUMIA-4275\Documents\2-Me\4-Websites\Sveltekit\3hvillas\node_modules\.pnpm\intl-tel-input@18.3.3\node_modules\intl-tel-input\build\js\intlTelInput.js:163:86

### Initialisation options
Version 18.2.1 works fine however version 18.3.3 gives the navigator not defined error

**Comment by jackocnr** [comment]
This should now be fixed in v18.3.4
