### ISSUE TITLE
Cursor Positioning Issue When Overwriting Phone Number Input

### ISSUE THREAD

**Issue by douglasdavidmelo** [jackocnr/intl-tel-input#1495]
### Steps to reproduce
1.  Go to: https://flexibilidadeemocional.com.br/pagamento/?wcf-add-to-cart=20242
2.  Type any number in "Telefone" field
3.  Select all the numbers that you typed
4. Start typing again (without using backspace first)
5. The first and second numbers will be in reverse positions (example: if you type 6 first and 1 second in the form, instead of displaying 61, they will appear as 16). This only happens with numbers from countries whose mask starts with "(".

### Expected behaviour
When the number sequence is selected and without using the backspace to delete, i.e., just rewriting over the old numbers, the first and second numbers entered should be in the correct order.

### Actual behaviour
When the number sequence is selected and without using the backspace to delete, i.e., just rewriting over the old numbers, the first and second numbers entered are displayed in reverse.

### Initialisation options
formatOnDisplay: true,
    hiddenInput: "full_number",
    initialCountry: "br",
    preferredCountries: ['br', 'us', 'pt'],
    utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/11.0.14/js/utils.js"
    
    
![Numbers selected](https://github.com/jackocnr/intl-tel-input/assets/155187551/5c5c0c68-57ee-422f-ac79-d73949c2d6b9)
![16 insteado of 61](https://github.com/jackocnr/intl-tel-input/assets/155187551/f9e46e30-631f-4f9e-bd9f-a2290599c67b)

**Comment by jackocnr** [comment]
A few things I noticed that you'll want to fix:

- You seem to be using v18.0.3 of the plugin, with v11.0.14 of the utils script - firstly these 2 versions need to be the same, and secondly, you should use the latest version - v18.3.4 at the time of writing.
- You seem to have a weird issue where if you click the selected flag to open the dropdown, then clicking the selected flag again does not close it - this will be a conflict in your code which you should fix
- When I type a digit in the input, I see an error in the JS console `iti.formatNumber is not a function` which indicates to me that either the utils script is not loading properly, or maybe it's just that it's using a really old version which didn't have this function - either way you will need to figure this out and fix it.

Finally, I looked into your code, and noticed you're listening to the `input` event and calling formatNumber - this is not recommended and is probably the source of the bug you describe. I recommend you don't do this - we removed the auto format feature from the plugin for many reasons, including the fact that it would always be buggy - see discussion here: https://github.com/jackocnr/intl-tel-input/issues/346
