### ISSUE TITLE
Australian numbers appearing as invalid and isPossibleNumber not working

### ISSUE THREAD

**Issue by badddams** [jackocnr/intl-tel-input#1498]
### Steps to reproduce (invalid number)
1.  Try entering an Australian number that starts with `0493`
2.  Number will say it's invalid

### Steps to reproduce (isPossibleNumber not working)
1.  Try entering a number and calling `isPossibleNumber`
2.  Error occurs indicating: Uncaught TypeError: intlTelInputUtils.isPossibleNumber is not a function

### Expected behaviour
I expect that the invalid Australian number is just a new number that has yet been update in the underlying libraries. However, my solution to get around this was to use the `isPossibleNumber` validation to future-proof against this (as suggested in the docs) but it seems to throw an error whenever I call it (see attached image).

### Actual behaviour
Uncaught TypeError: intlTelInputUtils.isPossibleNumber is not a function

### Initialisation options
I am using the UtiilsScript and initialising exactly as described in the docs. I am already using `isValidNumber` and `getNumber` and they work perfectly.

<img width="634" alt="image" src="https://github.com/jackocnr/intl-tel-input/assets/9041723/08d21cc0-11b8-4559-8046-0712572be0ae">

**Comment by jackocnr** [comment]
Which version of the plugin, and which version of utils.js are you using?

**Comment by badddams** [comment]
Hey @jackocnr, I'm going to delete this issue.

The Australian number not working is not your issue it's the underlying library that needs to update that number.

The `isPossibleNumber` problem was a user error on my end. I've been using this library for quite some time and believe the utilsScript was being imported correctly but I have just confirmed that it wasn't and `isPossibleNumber` is working fine.

Apologies for any time wasted or inconvenience caused on your end.

**Comment by badddams** [comment]
Hey @jackocnr, since my update earlier I've done some more testing and it seems like there's some sort of issue with the way the utils script is loaded.

`isPossibleNumber` doesn't seem to be loaded when I'm on a Safari browser but when I'm on a chrome browser, sometimes it's loaded and other times it is not. I can't work out why.

This is how I'm loading the utils script. I'm using it in a React project.
![image](https://github.com/jackocnr/intl-tel-input/assets/9041723/b1b2a8ad-40b6-4ea2-a616-22a3d4e0bc22)
![image](https://github.com/jackocnr/intl-tel-input/assets/9041723/26b9e8b5-e133-4b59-bb74-eed6f0f2c25b)
