### ISSUE TITLE
Separation of Phone Field

### ISSUE THREAD

**Issue by som3apf** [jackocnr/intl-tel-input#1499]
Hello,

I want to ask if something is doable on Instapage.

Now, I am integrating this library and it is working fine, however, I am in need of a customisation that I want to make sure it is available.

By any chance, is there any doable way for me to be able to take the field and have it as 2?

Currently, after every form, I am sending the value as it is (e.g +971555555555), is there a way to have it automatically send (+971) and (555555555) both alone in separate values? I have came up with the below, however, I am not sure how to proceed further from here.

------------------------------------------------------------------------------------------------
$("form").on("submit", function(event) {
    event.preventDefault(); // Prevent form submission for this example

    var isValid = telInput.intlTelInput("isValidNumber");
    console.log("isValid: " + isValid);

    if (isValid) {
      var selectedCountryData = telInput.intlTelInput("getSelectedCountryData");
      console.log("Selected Country Data: " + selectedCountryData)
      var dial_code = selectedCountryData.dialCode;
      console.log("Country Dial Code: " + dial_code)
      var number_without_dial_code = telInput.intlTelInput("getNumber");
      console.log("Phone Number: " + number_without_dial_code)
    } else {
      telInput.val('');
      console.log("Invalid phone number");
    }
  });
------------------------------------------------------------------------------------------------

### Expected behaviour
What I want to happen is to automatically send the values on 2 different fields on Instapage.

### Actual behaviour
It is only sending one field.

### Initialisation options
utilsScript

Thank you in advance for your help.

Best

**Comment by jackocnr** [comment]
If you want to get the national number (without international dial code), you can pass `intlTelInputUtils.numberFormat.NATIONAL` as an argument to `getNumber` (see the readme for more info)
