### ISSUE TITLE
formatAsYouType includes prefix when not showing flags

### ISSUE THREAD

**Issue by lekoala** [jackocnr/intl-tel-input#1502]
### Steps to reproduce
When disabling the flags and enabling the dial code, formatAsYouType works differently
showSelectedDialCode is required to disable flags, so there is no way to have a regular dropdown with the dial code instead of the flag and having the number formatted as you type in national format

### Expected behaviour
the number is formated as you type using national format

### Actual behaviour
the prefix is added while typing

### Initialisation options
showFlags: false,
showSelectedDialCode: true,

**Comment by lekoala** [comment]
@jackocnr thanks ! it's not adding the prefix anymore, but it's not spacing numbers as per national format as far as I can tell

i think it's due to this part were getFullNumber returns the number with the dial code, and therefore formatAYT doesn't add space

formatATY should use whatever is provided by the user

https://github.com/jackocnr/intl-tel-input/blob/35e1ca28104cd7ac14197fd1ac7592f815e104b4/src/js/intlTelInput.js#L1605-L1615

**Comment by lekoala** [comment]
@jackocnr yes, but i think the issue is linked to getFullNumber  including the dial code even if it is not typed by the user. so instead of using getFullNumber you just use the actual value, the formatter will do its job i think (just like when showSelectedDialCode is set to false)

**Comment by jackocnr** [comment]
Ah sorry yes you're right. When showSelectedDialCode is enabled, we think of the displayed dial code as being part of the typed number, and so prefix it when doing the as-you-type formatting (and then remove it again before displaying the formatted number). This is why it always formats it in international format.

My only concern with not doing this, and just passing what the user types, is if the **user** thinks of the displayed dial code as being part of the number, and so types the rest of the number in international format, which in some countries would lead to an invalid number (which might break the as-you-type formatter). For example, in the UK, a mobile number in national format would be something like "07947123123", or in international format "+447947123123", and so if the user considers the displayed dial code to be part of the number, they might type "7947123123" which would be an invalid number on its own.

Does that make sense?

**Comment by lekoala** [comment]
yes i see what you mean, indeed without the "0" it formats things with spaces as expected

it's still a bit odd because when you have placeholder for mobile phones for example, it shows something like this

<img width="322" alt="image" src="https://github.com/jackocnr/intl-tel-input/assets/250762/a5982e70-2d8b-415f-a05e-e9868c924381">

you've got similar issues with us numbers where the placeholder as parenthesis but the format AYT doesn't work when the user follows the proposed input.
