### ISSUE TITLE
@types/intl-tel-input is not synced with intlTelInput.Options

### ISSUE THREAD

**Issue by Nedimko123** [jackocnr/intl-tel-input#1503]
For example this: countrySearch
Type: Boolean Default: false
Add a search input to the top of the dropdown, so users can filter the displayed countries.

it's missing from the types inside your types intreface intlTelInput.Options
There are some other options in there, so please sync them up

**Comment by Nedimko123** [comment]
Using all the latest versions:
      "@types/intl-tel-input": "^18.1.4",
   "intl-tel-input": "^19.1.0",

**Comment by pedro-dalben** [comment]
the option "hiddenInput" change name?

**Comment by jackocnr** [comment]
I'm not familiar with that project, but here's a list of recent changes to help someone:

- [Enable countrySearch and fixDropdownWidth by default](https://github.com/jackocnr/intl-tel-input/commit/8a177c12b1a0b1ef3a2fcced56000acbb7ee13a5)
- [Change hiddenInput to take a function](https://github.com/jackocnr/intl-tel-input/commit/685809d302f87a63903c519320ac7ad98114e791)
- [Rename localizedCountries to i18n](https://github.com/jackocnr/intl-tel-input/commit/fc0fc06f7a0ae0777d1cf199fd02093cc1972094)
- [Rename customContainer option to containerClass](https://github.com/jackocnr/intl-tel-input/commit/5bad83268c1f2bf54a93c303965282be12f6f00d)
- [Rename separateDialCode to showSelectedDialCode](https://github.com/jackocnr/intl-tel-input/commit/e2117ffe7577137aa06be5e616187a6e3419e779)
- [Rename validation methods](https://github.com/jackocnr/intl-tel-input/commit/78ec6a9dcb0a1425b5c8ecd4f4326130238ee7e5)

**Comment by Nedimko123** [comment]
I thought you guys mantained this package https://www.npmjs.com/package/@types/intl-tel-input , guess not, ehh, well for anyone wondering there are some other options that aren't mentioned in the types

**Comment by jackocnr** [comment]
I'd say let's leave this open until it gets fixed, so people know 👍

**Comment by pedro-dalben** [comment]
@jackocnr preferredCountries not work here.
`const intlTelInputInstance = intlTelInput(input, {
      utilsScript: 'intl-tel-input/build/js/utils.js',
      hiddenInput: function () {
        return (input || {}).dataset.hiddenInputData
      },
      initialCountry: 'us',
      preferredCountries: ['us', 'br'],
      autoPlaceholder: 'aggressive',
      autoInsertDialCode: true,
    })`
    
![image](https://github.com/jackocnr/intl-tel-input/assets/57180027/bf8ab22f-3465-4724-b2e4-577809925228)

Another problem I'm having is when I selected some countries
![image](https://github.com/jackocnr/intl-tel-input/assets/57180027/a5a7d953-5748-43e9-aeb7-8c7056d72e72)
![image](https://github.com/jackocnr/intl-tel-input/assets/57180027/c3aceb63-9300-4e09-922c-822a9bb1f0a8)

**Comment by jackocnr** [comment]
@pedro-dalben please create a separate issue

**Comment by Shekhar-Zealous** [comment]
@jackocnr I am facing 1 issue with the latest version "intl-tel-input": "^19.2.12",.

While using the isValidNumber() method
```
cosnt iti = intlTelInput(input, {
	showFlags: true,
	separateDialCode: true,
	utilsScript: 'https://cdn.jsdelivr.net/npm/intl-tel-input@18.1.1/build/js/utils.js',
});

if(iti.isValidNumber()) {
   // Code block
}
```
the below erros appears in console:

```
intl-tel-input.js?v=96d63b55:1414 Uncaught TypeError: intlTelInputUtils.isPossibleNumber is not a function at Iti2.isValidNumber 
 ````
 
 Can you check the above and see what is the issue here.

**Comment by jackocnr** [comment]
@Shekhar-Zealous this is not the right place for asking unrelated questions, but to save time: you need to use the same (latest) version in the utilsScript argument as well.

**Comment by jackocnr** [comment]
I've just moved this project to Typescript (in v21.0.0), so types are now included automatically (see build/js/intlTelInput.d.ts).
