### ISSUE TITLE
SetAttribute error

### ISSUE THREAD

**Issue by pedro-dalben** [jackocnr/intl-tel-input#1505]
After selecting some countries (in the test the problem occurs in Brazil) an error appears in the console
![image](https://github.com/jackocnr/intl-tel-input/assets/57180027/21035d29-782f-4b32-bae9-3754ca348709)
![image](https://github.com/jackocnr/intl-tel-input/assets/57180027/08cd0fd3-d77f-4d05-b50c-53e4f1823f16)
This error occurred when there is more than one phone field on the screen
the ids are different
version 19.2.1

**Comment by pedro-dalben** [comment]
after disabling country search the problem disappears

**Comment by mikadev** [comment]
The same only with multiple instances (version 19.2.3) how to fix that please ?

**Comment by jackocnr** [comment]
Fixed by https://github.com/jackocnr/intl-tel-input/commit/374d510fb8692fed930cd99fc9db11103fa8c296
