### ISSUE TITLE
reference custom element in wiki

### ISSUE THREAD

**Issue by lekoala** [jackocnr/intl-tel-input#1506]
If you are interested (since i see you are working on a react component...)
i have been working on a custom element using your library (amongst others)

repo
https://github.com/lekoala/formidable-elements

demo
https://formidable-elements.vercel.app/demo/tel-input.html

:-) if you think it might be interesting for others, maybe it could be added to the wiki

**Comment by jackocnr** [comment]
Sure :)
Added here: https://github.com/jackocnr/intl-tel-input/wiki/Integrations
