### ISSUE TITLE
Deleting all characters from input results in console error

### ISSUE THREAD

**Issue by campbellja** [jackocnr/intl-tel-input#1507]
This issue was found in latest intl-tel-input version as of this writing: 19.2.3.
Replicated using browsers:
- Microsoft Edge 120.0.2210.121
- Chrome 116.0.5845.111

### Steps to reproduce
1. Using your browser of choice, open a page running a minimal example of intl-tel-input version 19.2.3 (or open the following example: https://jsfiddle.net/abdefghg/yh58kLqu/13/)
2.  Type some characters into the phone number input field - ensure that it contains some characters - for example `+614`;
3.  Attempt to delete all of the characters from the input using the backspace key, and
4. Open your browser's dev tools and note the console errors that appear.

Please see attached demonstration GIF:
![intl-tel-input-trim-error](https://github.com/jackocnr/intl-tel-input/assets/6846704/f14ccfba-3a90-41fd-97cc-cd6c0f497d32)
Also, please see the following jsfiddle used to replicate the issue: https://jsfiddle.net/abdefghg/yh58kLqu/13/

### Expected behaviour
No console errors should appear for normal user text deletion or insertion.

### Actual behaviour
The following error appears in the browser's dev tools console:
> Uncaught TypeError: Cannot read properties of undefined (reading 'trim')

### Initialisation options
Minimal init options:
> initialCountry: "au",
    showSelectedDialCode: true,
    utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@19.2.3/build/js/utils.js"

**Comment by campbellja** [comment]
Hello. Thanks for your support and please let me know if I have missed anything in my submission, cheers

**Comment by mikadev** [comment]
The same :)
I'm agree @campbellja there is alternative to this one ? by the way not working properly on firefox autoformat on typing, but the main demo page yes work on firefox...

**Comment by jackocnr** [comment]
Thanks for reporting this. Fix released in latest version 👍

**Comment by campbellja** [comment]
Cheers @jackocnr
