### ISSUE TITLE
Cursor pointer

### ISSUE THREAD

**Issue by pedro-dalben** [jackocnr/intl-tel-input#1512]
### Steps to reproduce
1.  latested version
2.  Add Inputmask
3.  error..
19.2.3
https://github.com/jackocnr/intl-tel-input/assets/57180027/c7d31b82-9353-4584-8d32-6c77541f301a
18.5.3:
https://github.com/jackocnr/intl-tel-input/assets/57180027/3e03abf5-3926-469f-aab9-f35e40197bf8

**Comment by jackocnr** [comment]
I would argue that with the placeholder number automatically displayed, and with the new formatAsYouType feature, that you shouldn't need to use a third-party mask plugin.

If, however, you're set on using the third-party plugin, you will need to disable formatAsYouType.

**Comment by renatocarvalho** [comment]
@jackocnr I had the same issue @pedro-dalben.

Setting: `formatAsYouType: false` worked great!
