### ISSUE TITLE
Search country input on mobile browsers is not tapable

### ISSUE THREAD

**Issue by dmitrue** [jackocnr/intl-tel-input#1516]
Hi, can't tap into search bar and search for country on iOS 17 Safari. Just tested on Android Chrome, it doesn't work as well.

![image](https://github.com/jackocnr/intl-tel-input/assets/6647735/4e8d347d-676d-44f2-870d-1c1e75bdf6cc)

**Comment by jackocnr** [comment]
Does it work for you on the [demo site](https://intl-tel-input.com/)?

What initialisation options are you using?

**Comment by dmitrue** [comment]
It's buggy, it's opened first time and then I can't dismiss it, please see screenshot

![IMG_3192](https://github.com/jackocnr/intl-tel-input/assets/6647735/6d5ff80d-e98f-4bc7-92c4-41c3c5e9375a)

My options:
<img width="788" alt="Screenshot 2024-01-20 at 16 28 44" src="https://github.com/jackocnr/intl-tel-input/assets/6647735/3d400b54-f6ef-43f7-a49c-5f7e4c674e58">

**Comment by jackocnr** [comment]
> I can't dismiss it

Have you tried tapping at the side, on the dark gray background?

Are there any other bugs? Please can you provide as much detail as possible.

**Comment by dmitrue** [comment]
Yes, if search for non-existent country, for example, and results are empty, next time you tap on int tel input it will be `frozen`, I attach video.

https://github.com/jackocnr/intl-tel-input/assets/6647735/9155b5dc-bc8c-4041-9984-2f8c86d597ac

As for input is not tappable, I think it has something to do that my form is in the modal...

**Comment by jackocnr** [comment]
Thanks for reporting this - it was a bug. Fix released in v19.2.8.

> As for input is not tappable, I think it has something to do that my form is in the modal...

Yes, it might be a z-index issue in your CSS? It's best to ask on StackOverflow about this kind of thing 👍

**Comment by dmitrue** [comment]
I think this is Bootstrap modal focus issue, https://github.com/sweetalert2/sweetalert2/issues/374
