### ISSUE TITLE
React version of intl-tel-input throws an error when unmounted

### ISSUE THREAD

**Issue by aklessin** [jackocnr/intl-tel-input#1517]
Hi. I created a widget, built with React, for phone verification. The first modal in the widget collects the user's phone number using the IntlTelInput component - it renders well and validates the phone number. When I click "Next" to move onto the next step, the script tries to render the next modal but fails, with this error: 

> Uncaught TypeError: Cannot read properties of null (reading 'removeEventListener')
>     at IntlTelInput.js:44:24
>     at safelyCallDestroy (react-dom.development.js:22932:5)
>     at commitHookEffectListUnmount (react-dom.development.js:23100:11)
>     at commitPassiveUnmountInsideDeletedTreeOnFiber (react-dom.development.js:25098:11)
>     at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (react-dom.development.js:25048:5)
>     at commitPassiveUnmountEffects_begin (react-dom.development.js:24956:11)
>     at commitPassiveUnmountEffects (react-dom.development.js:24941:3)
>     at flushPassiveEffectsImpl (react-dom.development.js:27038:3)
>     at flushPassiveEffects (react-dom.development.js:26984:14)
>     at react-dom.development.js:26769:9
>     at workLoop (scheduler.development.js:266:34)
>     at flushWork (scheduler.development.js:239:14)
>     at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:21)

IntlTelInput.js is trying to remove an event listener from the <IntlTelInput> component in the first modal which is now already unmounted and doesn't exist in the DOM.

This is how the component is being rendered:

<IntlTelInput
    className={'form-control form-control-lg text-secondary'}
    initialValue={phone || '+1'}
    onChangeNumber={setPhone}
    onChangeValidity={setIsPhoneValid}
    initOptions={{
        nationalMode: false,
        utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@19.1.0/build/js/utils.js"
    }}
/>
Thanks for your help.

**Comment by jackocnr** [comment]
Thanks for reporting this. Fix released in v19.2.12.
