### ISSUE TITLE
There should be no 0 after the code in Türkiye number

### ISSUE THREAD

**Issue by bariskrdrl** [jackocnr/intl-tel-input#1519]
Hi, The placeholder and mask after +90 in the Türkiye number are wrong. 
It should be in the format +90 501 234 56 78. 

The example in the latest version is not correct. +90 0501 234 56 78
Thanks

**Comment by jackocnr** [comment]
Thanks @leecollings-sb 

@bariskrdrl I can only assume you're using showSelectedDialCode and you're thinking of the displayed dial code as being part of the number. In this case, if you want the placeholder to be in international format, then you can set nationalMode to false.

I'll close this for now, but let me know if you're still having any issues.

**Comment by aycomp** [comment]
for Turkey, the text after country code shouldn't start with  0 (zero)
![image](https://github.com/user-attachments/assets/c89c7eb0-1ae7-490b-8e1e-d17701f3ece2)

**Comment by jackocnr** [comment]
@aycomp since you say "after country code" I assume you mean with `separateDialCode` enabled? In which case we do not show the leading 0 - see [demo page](https://intl-tel-input.com/examples/separate-dial-code.html). Please make sure you're using the latest version of the plugin.

<img width="323" alt="Screenshot 2024-08-16 at 14 14 50" src="https://github.com/user-attachments/assets/2e89176c-2504-420b-baa7-adc90624e27a">

**Comment by leecollings-sb** [comment]
@jackocnr I **think** what @aycomp is trying to show you, is that on the demo page, on National Mode, when Turkey is selected, the placeholder text showing an example number, has a leading zero... when it shouldn't.

But I could be wrong...

![Screenshot 2024-08-16 at 14 21 16](https://github.com/user-attachments/assets/0a91ed07-da7c-452f-a70a-0758e8c612a6)

**Comment by aycomp** [comment]
Hello [jackocnr](https://github.com/jackocnr), [leecollings-sb](https://github.com/leecollings-sb)
I was trying make show phone number part (0 501 234 56 78) without leading zero when the separateDialCode is set to false.
But as far as I understood it is not possible.

I will continue to use library with the setting separateDialCode = true

Thank you for replies :)

**Comment by jackocnr** [comment]
> on the demo page, on National Mode, when Turkey is selected, the placeholder text showing an example number, has a leading zero... when it shouldn't.

But according to libphonenumber, it should have a leading zero when being shown in national format. If we look at the libphonenumber output posted by @leecollings-sb:

> National format: 0501 234 56 78
> International format: +90 501 234 56 78

So if you have nationalMode enabled (which it is by default), you will get the national format. Or if you disable it, you will get the international format. If you think one of these is incorrect, then you need to raise an issue with libphonenumber (see the relevant info/links in my original comment).

**Comment by aycomp** [comment]
in my code I didn't set nationalMode, so it was enabled as default. 
I got the point, I can set nationalMode to false to use it in International format.
I am now more clear about how the library is working. I think there is no issue, it is working properly. 
Thank you both for the clarification. [jackocnr](https://github.com/jackocnr) [leecollings-sb](https://github.com/leecollings-sb)
