### ISSUE TITLE
Search field not appearing within drop down 

### ISSUE THREAD

**Issue by BryanMalunje** [jackocnr/intl-tel-input#1523]
### Steps to reproduce
1. I am using C# MVC as my web framework alongside jquery and bootstrap 5 

### Expected behaviour
When i initialize it just as the documentation says, my input is supposed to have the search country input by default

### Actual behaviour
But i do not have the search input on my input

### Initialisation options
```
const secondaryNumber = document.querySelector("#txtAlternateNumber");
window.intlTelInput(secondaryNumber, {
    nationalMode: false,
    autoInsertDialCode: true,
    initialCountry: "auto",
    searchPlaceholder:"Search country",
    utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@19.2.16/build/js/utils.js",
});
```

**Comment by BryanMalunje** [comment]
![Screenshot 2024-02-07 091410](https://github.com/jackocnr/intl-tel-input/assets/133231269/dbfd300c-86f0-4beb-b162-13540b307801)
This is a screenshot of what my input looks

**Comment by jackocnr** [comment]
Which version of the plugin are you using? Please make sure you're using the latest version.

**Comment by BryanMalunje** [comment]
@jackocnr  I was using version 18 but I have managed to get the search working using version 19 . When i use the cdn files thats when I get the issue but when I switch to local build files it works

**Comment by jackocnr** [comment]
If you want to use the CDN files, you should be able to update the version number in the URL
