### ISSUE TITLE
Send Country data to Hubspot

### ISSUE THREAD

**Issue by DanFabDinner** [jackocnr/intl-tel-input#1526]
### Steps to reproduce
1.  When user selects the country code selector
2.  Either place in the dial code in the phone field or send country to the property in Hubspot
3.  Also, remove the default phone-numbers, that the plug-in suggest in the phone-number field

### Expected behaviour
Get country or dial code in hubspot

### Actual behaviour
We only see the country by looking at the url

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
If you use `getNumber` that will give you the full number including the international dial code, so you don't need to send the country code separately.

If you want to remove the placeholder number, you can set `autoPlaceholder` to `"off"`.
