### ISSUE TITLE
initialCountry does not work if you send the country code in the upper register

### ISSUE THREAD

**Issue by wayheming** [jackocnr/intl-tel-input#1530]
Hello, after update to latest version i have problems with `initialCountry` option

https://github.com/jackocnr/intl-tel-input/blob/a56ca8ab8b1c5e7b07afa5c33a68a1fe066d184f/src/js/intlTelInput.js#L592

I think that when submitting the code for validation, we should change it to lower case

` const isValidInitialCountry = initialCountry && !!this._getCountryData(initialCountry.toLowerCase(), true);`

I can create a PR if you agree with it, as I have broken functionality in this place since I always passed the code in the upper register.

**Comment by jackocnr** [comment]
Thanks for raising this. It's now fixed in master and will be included in a new release soon.

**Comment by wayheming** [comment]
@jackocnr Thank you very much for the quick fix, I appreciate it!

**Comment by jackocnr** [comment]
Released in v19.2.20
