### ISSUE TITLE
Issue with setNumber()

### ISSUE THREAD

**Issue by zipelkopf** [jackocnr/intl-tel-input#1531]
Hi, I'm using the latest version v19.2.20.
I appreciate any advice, hopefully I'm just missing something, thanks!

### Steps to reproduce
1.  I initialise the input like that
```javascript
var phoneInput = intlTelInput($('[name="myPhoneInput"]')[0], {
            showSelectedDialCode: true,
            utilsScript: 'https://cdn.jsdelivr.net/gh/jackocnr/intl-tel-input@v19.2.20/build/js/utils.min.js'
        }).setNumber('+353858345344');
```
3.  Alternativelly, I also tried calling `phoneInput.setNumber` or to wait a couple of seconds in case of an async issue... same problem.
4.  The HTML input, I tried also to remove the `disabled` attribute, same issue
```html 
<input name="myPhoneInput" disabled>
```

### Expected behaviour
I expect to see the phone nicelly formatted like this one below, where the relevant country code and flag are correctly identified and selected from the set number
![image](https://github.com/jackocnr/intl-tel-input/assets/21308710/e24028a5-ab48-4912-97ac-402da00eea60)

### Actual behaviour
Instead, the number still contains the international prefix, with the wrong country / flag picked. It seems the first country in the list.
![image](https://github.com/jackocnr/intl-tel-input/assets/21308710/a93c35f8-14ce-4208-b971-b2500767480c)

### Initialisation options
I also tried to `setNember` after the utilScripts are loaded separatelly (using `.then`), but same issue

**Comment by jackocnr** [comment]
Can you just put the phone number in the input before you initialise the plugin?

**Comment by zipelkopf** [comment]
@jackocnr Thanks a lot, that works and actually it allowed me discovering the root cause of the issue.
The problem is not with the plugin, but with the `+` sign of the phone number which was not properly encoded.

All solved, thanks!
