### ISSUE TITLE
Valid Turkey number starting with some prefixes etc.0561 returns invalid number 

### ISSUE THREAD

**Issue by hrstcke** [jackocnr/intl-tel-input#1537]
### Expected behaviour
isValidNumber returns invalid

### Actual behaviour
Should be valid in my country

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please [file an issue](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md) with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by hrstcke** [comment]
I just want package to check phone number length for a specific country. for validity and let all phone numbers of that length be valid.How can i manage that? Which method should i change?

**Comment by jackocnr** [comment]
If you just want to check number length, you should use the `isValidNumber` method. If you use the latest version of the plugin (and utils.js), then this will return true for 0561 numbers e.g. 05612345678. When I check that number on [the demo site](https://intl-tel-input.com/examples/validation-practical.html), it validates as true.
