### ISSUE TITLE
Wrong validation with letters

### ISSUE THREAD

**Issue by wannevancamp** [jackocnr/intl-tel-input#1539]
### Steps to reproduce
1.  select Belgium in the country select
2.  Fill in a number with letters `03 454aaa`
3.  Validate number with `iti.isValidNumber()`

### Expected behaviour
Number should be invalid. Only numbers are allowed, no letters

### Actual behaviour
The validation function must return the correct error instead of telling that the number is valid.

### Initialisation options
```
utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@19.5.2/build/js/utils.js",
autoInsertDialCode: true,
autoPlaceholder: "aggressive",
initialCountry: "auto",
showSelectedDialCode: true,
```

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please [file an issue](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md) with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by wannevancamp** [comment]
This ticket can be closed. The issue is not related to this package. Thx!
