### ISSUE TITLE
JSON import for localization 

### ISSUE THREAD

**Issue by julianwitzel** [jackocnr/intl-tel-input#1544]
I was wondering if it is somehow possible to load the translations from an external source. That way the code stays more clean and the translation files can be used for multiple projects.

The code I tried did not work. Is there any way this is possible already?

```
i18n: fetch(langFilePath)
    .then(response => response.json())
    .then(data => {
    return data;
  })
  .catch(error => {
    console.error('Error loading JSON file:', error);
}),
```

**Comment by jackocnr** [comment]
Fetch returns a promise, so you are effectively initialising the plugin with the i18n option set to a promise which won't work. Instead you need to finish loading your JSON before you initialise the plugin, and then pass the result as the value to i18n.
