### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by sungraizfaryad** [jackocnr/intl-tel-input#1547]
### Steps to reproduce
1.  You can visit your site homepage https://intl-tel-input.com/
2.  Open the Chrome Inspector and go to the console
3.  You will see the error

### Expected behavior
It should auto-detect the country and put the flag.

### Actual behavior
Right now it is showing the first country on the list.

**Comment by jackocnr** [comment]
Hmm that's strange, it's working fine for me on my home laptop and on my mobile browser. I wonder why we would be having different experiences. Is there a chance your problem is a Chrome configuration setting?

Are other people getting this error?

**Comment by violuke** [comment]
It's working fine for me 👍

**Comment by sungraizfaryad** [comment]
Hi,

Here is a video for you guys.

https://jmp.sh/2b67lMAV

You can see the error on the console and I want to clarify that I have not installed any Chrome extension.

Although I'm from Pakistan, the flag being displayed is incorrect. I have been working as a web developer since 2013 and I'm confident that I'm not missing anything. 

Can you please take a look and let me know if I need to make any changes?

Thanks!

**Comment by jackocnr** [comment]
Can you try in Firefox/Safari and see if it works there?

**Comment by sungraizfaryad** [comment]
The same results are on Safari and Firefox.

https://tppr.me/MCwOpF

https://tppr.me/AIcxBg

**Comment by sungraizfaryad** [comment]
Hi,

Any update?

**Comment by jackocnr** [comment]
Can you visit the [Lookup user's country](https://intl-tel-input.com/examples/lookup-country.html) demo page in Chrome and open devtools, network tab, and click on the request to `https://ipapi.co/json` (mine just says "json" in the left sidebar), and click the "Headers" tab, and screenshot all of the headers and share that here?

**Comment by sungraizfaryad** [comment]
Hi,

Here is the screenshot that you requested.

https://tppr.me/G4cDRr

I hope it will help you identify the issue. I am using gest mode to prevent any extension conflict.

Regards,

**Comment by jackocnr** [comment]
Thanks, but it looks like the "Response Headers" section gets cut off - could you somehow share all of that section?

Also, given you seem to be the only person experiencing this issue, I wonder if it's to do with your IP address? Could you try checking on your phone, with wifi disabled, so it's using the mobile data, which should have a different IP.

**Comment by jackocnr** [comment]
For reference, here's what I see. Note the `Access-Control-Allow-Origin` response header, which is required for CORS requests.

<img width="1274" alt="Screenshot 2024-04-02 at 17 49 01" src="https://github.com/jackocnr/intl-tel-input/assets/1186883/ac06010a-af04-4547-ae84-a5e7744ff49d">

**Comment by sungraizfaryad** [comment]
Hi,

Here are all the header screenshots that you asked for.

https://tppr.me/nqMQuh

https://tppr.me/esYh5G

https://tppr.me/bLbIv7

Here is what I am seeing in Chrome Console.

https://tppr.me/rndtKy

The Response header you have shared is not present.

Also, I tried with a different internet connection including mobile. It is the same for me.

I am using it for a client so I need it to work.

Thanks!

**Comment by jackocnr** [comment]
From my limited understanding of CORS, and the error you're getting - it looks like the problem is actually that when your browser makes the ipinfo request, it returns 403 Forbidden, and that error response does not include the required Access-Control-Allow-Origin header (probably because it's just an error response, there's no actual content loaded) and so the browser throws a CORS error. So I actually don't think this is a CORS issue, I think that's just a side-effect of ipinfo rejecting the request from your browser. So if I were you, I would contact ipinfo.co and ask why the request is returning 403 Forbidden. I'm guessing it's to do with your IP address. For instance: what happens when you visit https://ipapi.co/ in your browser - does it work correctly, showing your location data etc?

**Comment by sungraizfaryad** [comment]
When I access the URL https://ipapi.co/json , I can see the results.

https://tppr.me/r9ZnOR

So, it is not ipinfo issue.

**Comment by jackocnr** [comment]
I'm sorry, but seeing as how you are the only one with this problem, I've got to assume it is something to do with your setup, or with where you are. From my understanding, the demo site is doing everything it needs to do correctly, hence it working for everyone else. I would advise you to contact ipinfo support and explain the situation and ask if they have any ideas why their API is returning 403 Forbidden just for you. But please do post back here when you hear back from them.

**Comment by anthony0030** [comment]
# I can reproduce this error.

When I connect to a Pakistan VPN server more specifically ```Pakistan #1``` using Nord VPN. I have the same problem.
When I visit https://ipapi.co/json I get a human verification check that just loads and loads.

![Just-a-moment](https://github.com/jackocnr/intl-tel-input/assets/13033263/9b6405ed-200d-4273-91cd-4edb2b817741)

It is possible that when you visit the page directly the js works, but when you "visit" it via an API request it sees you as a bot and doesn't have the context of cookies, etc. to verify that you are not a bot. There is also a possibility that you are having a problem with IPV6, as a test disable IPV6 for your computer, or full network if possible. Your IPv4 address might get access immediately.

Most countries have dual stack networks where you get an IPV6 address and an IPV4 address behind a CGNAT.

**Comment by jackocnr** [comment]
Thanks Anthony, good idea with the VIP, and yes I also wondered about the ipv6 thing, as it looks like a long v6 IP address in the screenshot.

I would add that @sungraizfaryad if you're having a problem with the ipinfo service, you could try to find another IP lookup service that works better for you / your IP range.

I'm going to close this issue for now, as I don't think it is anything to do with intl-tel-input.

**Comment by ipapi-co** [comment]
It appears that some users are having problem accessing [ipapi.co](https://ipapi.co/). This can happen if there are too many requests under the free tier from certain regions or networks. Please accept our apologies for the inconvenience. If you notice this issue, please [reach out](https://ipapi.co/contact/) to us with your github username. We would be glad to resolve this for you.

**Comment by nidamunir-extreme** [comment]
I am from Pakistan and I can reproduce this. 

![Screenshot 2024-10-02 at 07 08 32](https://github.com/user-attachments/assets/d216e29a-8b8d-48f0-9f2a-72d663790896)

**Comment by ipapi-co** [comment]
> I am from Pakistan and I can reproduce this.
> 
> ![Screenshot 2024-10-02 at 07 08 32](https://private-user-images.githubusercontent.com/179488521/372705545-d216e29a-8b8d-48f0-9f2a-72d663790896.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4Mzg2MDgsIm5iZiI6MTcyNzgzODMwOCwicGF0aCI6Ii8xNzk0ODg1MjEvMzcyNzA1NTQ1LWQyMTZlMjlhLThiOGQtNDhmMC05ZjJhLTcyZDY2Mzc5MDg5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwMzA1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGI1YjcxOTIwZjk3MDI0MjNkNzk3NWFlYWU3ZDRlNzA0YTJkMmJjYTNmMjUwNGYxNjA5NjI5MjY1ZDBmZWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1RoGmgZl7DDQRGKMmTTLqy5_wL5DeDCJnt1Jq4YIo90)

@nidamunir-extreme Can you please drop us a message at https://ipapi.co/contact/ referencing this issue.

**Comment by srushtiKan123** [comment]
> It appears that some users are having problem accessing [ipapi.co](https://ipapi.co/). This can happen if there are too many requests under the free tier from certain regions or networks. Please accept our apologies for the inconvenience. If you notice this issue, please [reach out](https://ipapi.co/contact/?ref=intl-tel-input) to us with your github username. We would be glad to resolve this for you.

find any solution for this ???

**Comment by ipapi-co** [comment]
> > It appears that some users are having problem accessing [ipapi.co](https://ipapi.co/). This can happen if there are too many requests under the free tier from certain regions or networks. Please accept our apologies for the inconvenience. If you notice this issue, please [reach out](https://ipapi.co/contact/?ref=intl-tel-input) to us with your github username. We would be glad to resolve this for you.
> 
> find any solution for this ???

Please send us a message at http://ipapi.co/contact referencing this issue.

**Comment by oknasir** [comment]
> > > It appears that some users are having problem accessing [ipapi.co](https://ipapi.co/). This can happen if there are too many requests under the free tier from certain regions or networks. Please accept our apologies for the inconvenience. If you notice this issue, please [reach out](https://ipapi.co/contact/?ref=intl-tel-input) to us with your github username. We would be glad to resolve this for you.
> > 
> > 
> > find any solution for this ???
> 
> Please send us a message at http://ipapi.co/contact referencing this issue.

Reported using contact form on ipapi.co, now did you find the solution
