### ISSUE TITLE
`intlTelInput.min.css` is out of date vs `intlTelInput.css`

### ISSUE THREAD

**Issue by violuke** [jackocnr/intl-tel-input#1548]
Thanks for the great package and the v2 update. We're having a problem, though.

`.iti__a11y-text` for example is in [intlTelInput.css](https://github.com/jackocnr/intl-tel-input/blob/master/build/css/intlTelInput.css) but not in [intlTelInput.min.css](https://github.com/jackocnr/intl-tel-input/blob/master/build/css/intlTelInput.min.css) which is causing this:

<img width="265" alt="Screenshot 2024-03-17 at 12 07 00" src="https://github.com/jackocnr/intl-tel-input/assets/6420347/7c621ae3-9897-409c-a83c-4065a7e8bc16">

For now, we've switched to use the non-minified version (and I know we could improve our own tooling here), but a solution would be much appreciated.

Thank you :pray:

**Comment by jackocnr** [comment]
Good catch, thanks! Updated in v20.0.2.

**Comment by jackocnr** [comment]
@Sotiris-k thanks for letting me know. Fix released in v21.0.1.
