### ISSUE TITLE
 Mismatched ARIA Attributes and Roles in intl-tel-input

### ISSUE THREAD

**Issue by Rashadking786** [jackocnr/intl-tel-input#1549]
During accessibility testing using Lighthouse, I encountered an error regarding mismatched ARIA attributes and roles in the intl-tel-input component.

### Issue found here:

`<div class="iti__selected-flag" aria-expanded="false" aria-label="Selected country" aria-haspopup="true" aria-controls="iti-0__dropdown-content" tabindex="0">`

### Additional Information:

- Version of intl-tel-input used: 20.0.4.
- This issue impacts the accessibility of intl-tel-input and needs to be addressed to ensure compliance with accessibility standards.

**Comment by jackocnr** [comment]
Thanks for reporting this. Can you tell me which initialisation options you were using?

And what exactly is the mismatch?

**Comment by Rashadking786** [comment]
![image](https://github.com/jackocnr/intl-tel-input/assets/26774614/f1f985e7-a3c2-4037-a18e-ab404f45652f)


Please run live demo in page speed you will get the issue: https://pagespeed.web.dev/analysis/https-intl-tel-input-com/nkiaqnnx19?form_factor=desktop


**Options I have used:**

```
        const options={
          preferredCountries: ["AE"],
          separateDialCode: true,
          lazyLoading: true,
          showFlags:true,
          showSelectedDialCode:true,
          placeholderNumberType: "MOBILE",
          utilsScript: utilsScript,
          initialCountry:"AE",
        }
```
