### ISSUE TITLE
No search input is showing. 

### ISSUE THREAD

**Issue by suvrodattamitu** [jackocnr/intl-tel-input#1551]
I have added countrySearch: true in configs, but no country search input is showing.

**Comment by jackocnr** [comment]
Which version of the plugin are you using? Please make sure you're using the latest version.

If you're still having a problem: try to find the minimal set of code that reproduces the problem and put that in a CodePen, and I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/DyrVbw) with the plugin up and running - feel free to fork this if it helps.

**Comment by suvrodattamitu** [comment]
Hi @jackocnr, I used code from the codepan  and it's working. I used from minified file from here. But search input was missed. Now it's fine, I tried from the codepan in my env.

**Comment by jackocnr** [comment]
I'm a bit confused. Is your problem solved now? Shall we close this issue?

Or if you're still having a problem, can you please describe in as much detail as possible (which version, how are you downloading it etc) what you're doing and what you expect to happen and what is actually happening?

**Comment by suvrodattamitu** [comment]
@jackocnr , yes please close this issue. Sorry for late reply again. It works perfectly. Maybe issue occured just because i was using old version. Thanks for your help and time.
