### ISSUE TITLE
intlTelInput.d.ts is not a module.

### ISSUE THREAD

**Issue by olafurw** [jackocnr/intl-tel-input#1555]
Just upgraded from 20.3.0 to 21.0.1 in my Svelte/TS project and while running my build I get this error.

```
Error: File '/home/olafurw/project/node_modules/intl-tel-input/build/js/intlTelInput.d.ts' is not a module. (ts)
    import { onMount } from 'svelte';
    import intlTelInput from 'intl-tel-input';
    import 'intl-tel-input/build/css/intlTelInput.css';
```
Not sure if I need to change anything on my end, because the import code is the same as before.
```
import intlTelInput from 'intl-tel-input';
```
Reverting back down for now, no big stress on my end.

**Comment by jackocnr** [comment]
> while running my build

Can you share your tsconfig and your build command?

For now, you should be able to get this working by upgrading to v21.0.2 and adding the following to your tsconfig:

```json
{
  "compilerOptions": {
    "paths": {
      "intl-tel-input": ["./node_modules/intl-tel-input/types/src/js/intlTelInput.d.ts"]
    }
  }
}
```

TBH I'm new to Typescript, so I'm still figuring out the best way to do this!

**Comment by jackocnr** [comment]
Or in v21.0.4 you should be able to just `import "intl-tel-input/types.d.ts";` to get the types.

**Comment by olafurw** [comment]
> > while running my build
> 
> Can you share your tsconfig and your build command?

I don't have much time to create a full repro but you could try the svelte typescript setup 

`npm create svelte@latest my-app`

And set it to use typescript and then import like you suggest in the readme to see if it works. If it does then it might be something on my end.

**Comment by jackocnr** [comment]
Thanks. I'm still figuring this out. But in v21.0.5, you can now do 

`import "intl-tel-input/build/js/types.d.ts";`

This new types file only includes the types for the core JS plugin, and excludes the types for the intl-tel-input react component (as this was causing problems for someone else). Let me know if that works for you.

**Comment by olafurw** [comment]
Beautiful, thanks for the quick turnaround. Works.

**Comment by jackocnr** [comment]
Update: in v21.0.6 you should no longer need to manually import types
