### ISSUE TITLE
.isValidNumber() result diferent from .isValidNumber() from google phone library

### ISSUE THREAD

**Issue by mmorales-aeropost** [jackocnr/intl-tel-input#1559]
### Steps to reproduce
1.  Input number +50600000000

### Expected behaviour
When phone is validated using .isValidNumber() result should be FALSE like google phone library shows.
https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html
![image](https://github.com/jackocnr/intl-tel-input/assets/11032271/fd8c9de6-8971-4b82-bf32-926ca6dec436)
.isValidNumberPrecise() shows as invalid, but it is too complex to use.

### Actual behaviour
.isValidNumber() shows as valid
![image](https://github.com/jackocnr/intl-tel-input/assets/11032271/bc353e31-0573-4134-b8af-d2275361c437)

### Initialisation options
Default

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please [file an issue](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md) with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by jackocnr** [comment]
I've just released v21.0.7 with the latest version of libphonenumber. That should fix your issue, so I'll close this issue for now, but feel free to re-open if you're still having problems.
