### ISSUE TITLE
Force to use the prefix

### ISSUE THREAD

**Issue by Magic73** [jackocnr/intl-tel-input#1566]
Hi,
I would like to force the user to enter a number so that the prefix is always there. currently, even if I set it to default, he has the possibility of deleting it and entering a number without the prefix. Is it possible to prevent it from deleting it, or to reinsert it automatically when it loses focus and control?

Thank you :)

**Comment by jackocnr** [comment]
Can I ask why you want this?

Did you know that even if the user types their number in the national format (without the international dial code), you can always use `getNumber` to get the full international number (including the international dial code)?

**Comment by Magic73** [comment]
HI,
to add validation on the obligatory nature of having a prefix without having to use other tools afterwards, such as pop-ups or external alerts. Some of our users, when editing the telephone number, have the habit of removing the prefix with the result that the subsequent sending of a text message fails due to the lack of it.

By having an integrated validation check that requires the presence of the prefix, we standardize the input error reporting.

**Comment by jackocnr** [comment]
As per my previous message, you do not need to restrict the user in this way. You can allow the user to enter their number however they like, and you can always get the standardised international number using `getNumber`. Closing for now, but let me know if you have any problems.

**Comment by Magic73** [comment]
![image](https://github.com/jackocnr/intl-tel-input/assets/7645382/5ab036ed-c42f-40ee-bb11-baee84428a55)

calling getNumber on this, doesn't return +41 12345678

**Comment by jackocnr** [comment]
> calling getNumber on this, doesn't return +41 12345678

No because that's not a valid number. As per the readme, `getNumber` only works with valid numbers so you need to use `isValidNumber` to confirm the number is valid first. If it is valid, then you can use `getNumber` to get the full international number.
