### ISSUE TITLE
ES5 Support on AngularJS App

### ISSUE THREAD

**Issue by iJerson** [jackocnr/intl-tel-input#1575]
Hi, On version - 18.1.4 onwards utils.js is build with ES6. Is there a way to get an ES5 build for utils.js file because our application currently doesn't support ES6. Or is there any other option you can suggest. Thanks you!

**Comment by jackocnr** [comment]
Can you tell me more about your use case - what exactly is it that doesn't support ES6? I thought there was pretty comprehensive support in 2024...

**Comment by jackocnr** [comment]
> when we build the application it failed because of the ES6 features(const, let, arrow functions, etc) in the library

What bundler/build tool are you using? Have you considered updating the config to allow ES6, which is the industry standard now? Or are you having to support some super old browser/version for some specific reason?

**Comment by iJerson** [comment]
We are using grails to build the application
