### ISSUE TITLE
Demo with javascript locacles

### ISSUE THREAD

**Issue by eplatforms-uk** [jackocnr/intl-tel-input#1598]
Has anyone got a working demo with locales but in javascript ?

**Comment by jackocnr** [comment]
The [i18n demo page](https://intl-tel-input.com/examples/localise-countries.html) is in javascript. What issue are you having?

**Comment by jackocnr** [comment]
> This is React though not javascript

No, it isn't React. What made you think that?

**Comment by eplatforms-uk** [comment]
Sorry my mistake I got confused along the way. I found your demo with import didn't actually work though. I had to do the following below this to get the Russian demo to work. Maybe it was due to running on windows hosting, but I was trying locally firstly on my mac then I uploaded sample to windows hosting and then had to make changes as below to get it working.

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>International Telephone Input</title>
    <link rel="stylesheet" href="./build/css/intlTelInput.css" />
    <link rel="stylesheet" href="./build/css/demo.css" />
  </head>

  <body>
    <h1>International Telephone Input</h1>
    <form>
      <input id="phone" name="phone" type="tel" value="" />
      <button class="button" type="submit">Submit</button>
    </form>

    <script src="./build/js/intlTelInput.js"></script>
    <script type="module">
      // Import named exports
      import { countryTranslations, interfaceTranslations } from "./build/js/i18n/ru/index.js";
      
      // Import default export
      import ruTranslations from "./build/js/i18n/ru/index.js";

      const input = document.querySelector("#phone");

      // You can use either the named exports or the default export here
      window.intlTelInput(input, {
        // Using named exports
        i18n: { ...countryTranslations, ...interfaceTranslations },

        // Using default export
        // i18n: ruTranslations,

        initialCountry: "ru",
        utilsScript: "./build/js/utils.js",
      });
    </script>
  </body>
</html>
