### ISSUE TITLE
Arabic locale

### ISSUE THREAD

**Issue by eplatforms-uk** [jackocnr/intl-tel-input#1599]
Arabic locale isn't right to left. You need support for this.

**Comment by jackocnr** [comment]
The Arabic translation strings are all here: https://github.com/jackocnr/intl-tel-input/tree/master/build/js/i18n/ar

Can you provide an example of an incorrect translation string, and say how it should be instead?

**Comment by jackocnr** [comment]
And have you tried adding `dir="rtl"` to a container/ancestor element?

**Comment by eplatforms-uk** [comment]
Yes but you will see it comes from left to right automatically instead of right to left. I'm proposing an option somewhere should be considered. Translation itself is fine.

**Comment by jackocnr** [comment]
Are you talking about CSS changes? You will see we have several RTL styles already: https://github.com/jackocnr/intl-tel-input/blob/master/src/css/intlTelInput.scss (search "rtl"), but perhaps they're out of date now? I would welcome a PR to update them.

**Comment by eplatforms-uk** [comment]
We can do a RTL with CSS of course. But if you are using the react then by default Arabic should be right to left.

**Comment by jackocnr** [comment]
I added a RTL demo page here for future reference: https://intl-tel-input.com/examples/right-to-left.html
