### ISSUE TITLE
U.S. is not showing the u.s. flag

### ISSUE THREAD

**Issue by taylorvib** [jackocnr/intl-tel-input#1607]
### Steps to reproduce
1.  Can see example on our website here : https://vib.community/le/ai-ml-powered-fraud-prevention-for-websites-mobile-apps-2/

### Expected behaviour
This should be the U.S. flag

### Actual behaviour
It is not the U.S. flag

<img width="273" alt="Screenshot 2024-05-10 at 9 48 14 AM" src="https://github.com/jackocnr/intl-tel-input/assets/150082759/8615b09c-b0f9-4805-b290-1201ef748eac">

**Comment by jackocnr** [comment]
I don't have access to a computer right now, but it looks like the flags
are working fine in the dropdown, it's just the selected flag that is
misbehaving. It looks like it's the background position CSS rule that's not
working properly. I'm guessing your custom site CSS is interfering with the
selected flag CSS somehow?

**Comment by jackocnr** [comment]
The only thing I can think is that you're using a flags image from a different version of the plugin.

I see you're using the plugin v17.0.8 - that's quite out of date now - I'd strongly recommend you update to the latest version, and update your flag image too, and then it should all work fine.

**Comment by jackocnr** [comment]
I'll close this for now but feel free to re-open if you're still having problems.

**Comment by taylorvib** [comment]
Can you not update this plugin from wordpress directly? It does not say it is due for an update in my dashboard. Thanks!

**Comment by taylorvib** [comment]
I am using 1.0.4 which is the latest version shown on the plugin page

<img width="1244" alt="Screenshot 2024-05-13 at 5 29 06 AM" src="https://github.com/jackocnr/intl-tel-input/assets/150082759/f2c11a1f-f32d-4fcb-8fdd-6084cd99bb34">

<img width="1268" alt="Screenshot 2024-05-13 at 5 29 22 AM" src="https://github.com/jackocnr/intl-tel-input/assets/150082759/775f0764-98a2-4c34-ae44-c662928252b9">

**Comment by taylorvib** [comment]
Confirming I removed the plugin and reinstalled it from wordpress.org repository and same issue.

**Comment by jackocnr** [comment]
Sorry I can't help with a Wordpress plugin - you'll need to create an issue with them instead.

**Comment by taylorvib** [comment]
Is this not your plugin? This github page is linked on the plugin page for support.

**Comment by jackocnr** [comment]
Yes but I have no idea about the wordpress plugin and how it uses this plugin. You need to contact the author of that plugin and get them to update it to use the latest version of this plugin.
