### ISSUE TITLE
This input doesn't work on two elements

### ISSUE THREAD

**Issue by purpleFade** [jackocnr/intl-tel-input#1617]
Hi everyone, I wanna use intTelInpur through CDN. I want to use it on two different input elements, but it simply doesn't work! It can be used only on one element at a time. How to fix this?

**Comment by purpleFade** [comment]
![image](https://github.com/jackocnr/intl-tel-input/assets/57455737/f0710d4a-cd03-464b-87ba-ac2160959e24)
![image](https://github.com/jackocnr/intl-tel-input/assets/57455737/c08c6cd4-c79e-4d4b-bc5d-d7ffde690c61)

here are some screenshots

**Comment by jackocnr** [comment]
This is not enough information for me to look into the issue effectively. Please read the [New Issue Checklist](https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist) and if necessary, open a new issue and follow the [New Issue Template](https://raw.githubusercontent.com/jackocnr/intl-tel-input/master/.github/ISSUE_TEMPLATE.md). If you are including any code, please [format it correctly](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Comment by jackocnr** [comment]
By the way, I tried this quickly on codepen and it seemed to work fine: https://codepen.io/jackocnr/pen/LYopYKa?editors=1010

Please make sure you're using the latest version.
