### ISSUE TITLE
Getting error while using utilsScript

### ISSUE THREAD

**Issue by udit-001** [jackocnr/intl-tel-input#1618]
### Plugin version
v23.0.4

### Expected behaviour
No errors should be there

### Actual behaviour
Getting the following errors in browser console: 

**Brave Version 1.65.132 Chromium: 124.0.6367.202** 
```js
Uncaught SyntaxError: Unexpected token 'export'
```

**Firefox 125.0.3**
```js
Uncaught SyntaxError: export declarations may only appear at top level of a module
```

### Initialisation options
I am not using webpack or any other bundler, I am using vanilla JavaScript and specifying the `utilsScript` as follows:
```js
 utilsScript: "/static/js/utils.js",
```

Here's the script for reference:
```js
var fieldDiv = document.querySelector("field-phone_number");
window.addEventListener('load', function (event) {
    var input = document.querySelector("#id_phone_number");
    var jsConfig = {
      initialCountry: "id", 
      separateDialCode: true,
      strictMode: true,
      onlyCountries: ["in", "id"]
    }
    const widgetConfig = {
        ...jsConfig,
        useFullscreenPopup: true,
        utilsScript: "/static/phones/js/utils.js",
        hiddenInput: function(telInputName) {
            return {
                phone: "phone_number_1"
            };
        }
    }
    window.intlTelInput(input, widgetConfig);
});
```

### Comments
Should I include utils script in a different way in my project?

**Comment by jackocnr** [comment]
What version of the plugin are you using?

**Comment by udit-001** [comment]
I'm using v23.0.4

**Comment by udit-001** [comment]
No, I don't see that error on the demo site.

Can I use `build/js/intlTelInputWithUtils.js` instead of using a separate utils file?

**Comment by udit-001** [comment]
Thank you for your help, the issue has been resolved. 

It appears that the utils file was being included as a script tag as well. I was attempting to integrate this with Django, and there was a slight configuration issue, which caused the error to occur.

**Comment by gotexx1** [comment]
Add `type="module"` remove the error:
`<script type="module" src="https://cdn.jsdelivr.net/npm/intl-tel-input/build/js/utils.js"></script>`
