### ISSUE TITLE
Selecting any country with Country code +1 and adding number, it resets the country to US.

### ISSUE THREAD

**Issue by Usman-Ejaz** [jackocnr/intl-tel-input#1626]
### Steps to reproduce
1.  Select country 'Anguilla'
2.  Enter number like 12345

### Expected behaviour
Selecting country with +1 countryCode should be selected when entering any number.

### Actual behaviour
Selecting country with +1 countryCode and entering any number is changing the selected country to US and changes the flag.

**Comment by jackocnr** [comment]
Please search the existing issues before creating a new one, as this question has been answered many times before.

Anguilla only has the dial code 264, so if you type a number starting with that, it will stay selected.
