### ISSUE TITLE
Brazilian numer is formating national code without parenthesis

### ISSUE THREAD

**Issue by sciotta** [jackocnr/intl-tel-input#1627]
### Plugin version
v23.0.7

### Steps to reproduce
1.  Choose Brazil
2.  Note the place holder displaying "(11) 96123-4567"
3.  Enter 12936180822

### Expected behaviour
Number must be formatted like "(12) 93618-0822"

### Actual behaviour
Number formated as "12 93618-0822"

### Initialisation options
strictMode: true
formatAsYouType: true
nationalMode: true *I tried otherwise too

**Comment by jackocnr** [comment]
Yes I agree this is inconsistent and not ideal. We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for  generating (and formatting) the placeholder numbers, as well as for the as-you-type formatting. [Here](https://libphonenumber.appspot.com/phonenumberparser?number=11961234567&country=BR) you can see the libphonenumber output for that phone number - the national formatting is "(11) 96123-4567" but annoyingly the as-you-type formatter seems to return it in international format: "11 96123-4567". You're welcome to [file an issue](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md) with libphonenumber if you want. Ideally, the as-you-type formatter would have a way of specifying which format you want. I'll close this issue for now, as there's nothing we can do until they change it upstream.
