### ISSUE TITLE
Error when import then build

### ISSUE THREAD

**Issue by dohoangtung** [jackocnr/intl-tel-input#1669]
### Plugin version
From v21.x.x => v23.1.0 

### Steps to reproduce
1.  import intlTelInput from "intl-tel-input";
2.  yarn build

Got the error:

ERROR in ./node_modules/intl-tel-input/build/js/intlTelInput.js 1513:6
Module parse failed: Unexpected token (1513:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   var Iti = class {
|     //* Can't be private as it's called from intlTelInput convenience wrapper.
>     id;
|     //* NOT Private
|     promise;
 @ ./src/form-elements/TelInput/index.js 4:0-42
 @ ./src/form-elements/index.jsx
 @ ./src/form.jsx
 @ ./src/index.jsx

Downgrade to version v20.x.x or v19.x.x => Build OK

**Comment by jackocnr** [comment]
What does `yarn build` do? Please give as much detail as possible - what your build system is, which version, include config files etc.

But from the error message, it appears to be struggling with the syntax on this line: https://github.com/jackocnr/intl-tel-input/blob/master/build/js/intlTelInput.js#L1513 which uses [class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields).

So I guess your build system is not setup for that syntax. The error message suggests you might need to use an appropriate loader to handle this syntax?

**Comment by dohoangtung** [comment]
Hi, 

thanks for quick response

Yarn build will execute webpack => babel with very simple config: 

.babelrc :

{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-transform-class-properties",
    "@babel/plugin-transform-runtime",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-json-strings",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta"
  ]
}

webpack.config
...
  {
        exclude: /node_modules/,
        test: /\.js$|.jsx?$/,
        use: [
          { loader: 'babel-loader' }
        ]
      },
...
