### ISSUE TITLE
Jquery support?

### ISSUE THREAD

**Issue by jrowe88** [jackocnr/intl-tel-input#1677]
Hello- it appears that in Version 21.0.0, you removed the "legacy jquery support".  For those of us who still use Jquery, is there a way to use this still?

### Plugin version
v23.1.0

**Comment by jackocnr** [comment]
There's no longer a jQuery plugin, but there's nothing stopping you just using pure JavaScript! Don't be afraid, it's not that hard! Just switch from the following:

```js
$("#phone").intlTelInput(options);
```

to the following:

```js
const input = document.querySelector("#phone");
window.intlTelInput(input, options);
```

And follow the readme - you'll be fine 😉

**Comment by jhogervorst** [comment]
For anyone finding this issue — if you want to keep using `$.intlTelInput()` through jQuery with later versions, you can copy the following small snippet into your code:

```js
var itiPluginName = "intlTelInput";
$.fn[itiPluginName] = function(options) {
	var args = arguments;
	if (options === undefined || typeof options === "object") {
		return this.each(function() {
			if (!$.data(this, "plugin_" + itiPluginName)) {
				var iti = window.intlTelInput(this, options);
				$.data(this, "plugin_" + itiPluginName, iti);
			}
		});
	} else if (typeof options === "string" && options[0] !== "_") {
		var returns;
		this.each(function() {
			var instance = $.data(this, "plugin_" + itiPluginName);
			if (typeof instance === "object" && typeof instance[options] === "function") {
				returns = instance[options].apply(instance, Array.prototype.slice.call(args, 1));
			}
			if (options === "destroy") $.data(this, "plugin_" + itiPluginName, null);
		});
		return returns !== undefined ? returns : this;
	}
};
```

This registers a jQuery plugin which passes any invocation to `window.intlTelInput()`, new versions supported. It was copied (and slightly adjusted) from the latest release that officially supported jQuery, and should work without any changes (except for breaking changes in the library itself).

<sub>Also: hi to anyone else still using jQuery in 2026 👋</sub>
