### ISSUE TITLE
Adding Farsi (Persian) Translation

### ISSUE THREAD

**Issue by mahyarsbt** [jackocnr/intl-tel-input#1685]
Hi there,

I have created a Farsi (Persian) locale for the intl-tel-input library and attached it as a zip file. Please consider adding it to the library.

Additionally, I am developing a new module (PhoneNumber) for Drupal that integrates intl-tel-input with enhanced features.

Thank you for your attention and support.

Best regards,
Mahyar SBT

[fa.zip](https://github.com/user-attachments/files/16113353/fa.zip)

**Comment by jackocnr** [comment]
Thank you so much for this! Released in v23.1.1.
