### ISSUE TITLE
Padding isn't removed from input when instance is destroyed

### ISSUE THREAD

**Issue by john-ackerman** [jackocnr/intl-tel-input#1697]
### Plugin version
v23.1.1

### Steps to reproduce
1.  Apply intl-tel-input to an input element with `separateDialCode` set to true
2.  Destroy the intl-tel-input instance that was created

### Expected behaviour
The padding that is added to prevent text from overlapping with the dial code should be removed when intl-tel-input is destroyed

### Actual behaviour
The padding remains and must be manually removed

### Initialisation options
separateDialCode

From what I can tell this isn't an issue when `separateDialCode` is set to false, because that doesn't add a `style` tag to the element.

**Comment by jackocnr** [comment]
Fixed in v23.4.1.
