### ISSUE TITLE
Latest versions not available on jspm.io

### ISSUE THREAD

**Issue by dorianmariecom** [jackocnr/intl-tel-input#1706]
https://ga.jspm.io/npm:intl-tel-input@23.3.0/build/js/intlTelInput.js 

https://ga.jspm.io/npm:intl-tel-input@23.3.1/build/js/intlTelInput.js

https://ga.jspm.io/npm:intl-tel-input@23.3.2/build/js/intlTelInput.js

https://ga.jspm.io/npm:intl-tel-input@23.3.3/build/js/intlTelInput.js

Notice only 23.3.0 is available.

Not sure if the problem is on your side or jspm.io side

That's what's used by default by rails import maps

**Comment by jackocnr** [comment]
This is the latest version and it works for me: https://ga.jspm.io/npm:intl-tel-input@23.3.2/build/js/intlTelInput.js 

Probably there was just a bit of a delay for them to add the latest version.

**Comment by dorianmariecom** [comment]
oh, thanks, not sure what happened
