### ISSUE TITLE
As per Breaking Changes in SCSS move properties above nested rules

### ISSUE THREAD

**Issue by ico3iain** [jackocnr/intl-tel-input#1707]
Example move these 2 to line 162
https://github.com/jackocnr/intl-tel-input/blob/342f7df4a4992cc8c30008dc9ad1f64e915eb375/src/css/intlTelInput.scss#L177

Reference
https://sass-lang.com/documentation/breaking-changes/mixed-decls/

**Comment by jackocnr** [comment]
Thanks for raising this. I don't have time to work on this myself right now, but I would welcome a pull request.

**Comment by jackocnr** [comment]
Fixed in v23.5.0
