### ISSUE TITLE
Hide search field

### ISSUE THREAD

**Issue by crowsturnwhite** [jackocnr/intl-tel-input#1709]
### Plugin version
v23.0.11

### Steps to reproduce
1.  Initialize intl-tel-input

### Expected behaviour
No search field in the dropdown.
Hide search field in the dropdown.

### Actual behaviour
Cannot hide search field.

### Initialisation options
countrySearch: false
utils: (using 23.0.11)

**Comment by jackocnr** [comment]
Can you please describe your use case? Why would it be a better UX without the search feature?

**Comment by JRoussos** [comment]
I think what @crowsturnwhite means is that despite setting the countrySearch option to false, it doesn't hide the search input. I run into the same issue

**Comment by jackocnr** [comment]
I understand what you're trying to do, but I think it would help to understand why you're trying to do it.

**Comment by jackocnr** [comment]
If you upgrade to the latest version, I've re-added the countrySearch option.
