### ISSUE TITLE
[BUG] When toggle inputProps.disabled, Button for CountryList not working!

### ISSUE THREAD

**Issue by bgb10** [jackocnr/intl-tel-input#1718]
Hello! Thank you for making this awesome library. I searched for several phone number libraries, and `intl-tel-input` was just perfect.

I wanted to display user's phone number with input disabled, and when the user want to modify their number, I wanted to enable input.
**But even the `inputProps.disabled` changed, a button for CountryList isn't worked (input tag was working).**

https://github.com/user-attachments/assets/d3b31306-f2c9-4e9a-8820-bfa1c22e4c7e

### Plugin version
v23.7.3

### Steps to reproduce

1. use the example code below to reproduce the problem.
```tsx
import React, { useState, ReactElement } from "react";
import { createRoot } from "react-dom/client";
import IntlTelInput from "../src/intl-tel-input/reactWithUtils";

const App = (): ReactElement => {
  const [isDisabled, setIsDisabled] = useState(true);

  const toggleDisabled = () => setIsDisabled(!isDisabled);

  return (
    <form>
      <IntlTelInput
        inputProps={{
          disabled: isDisabled
        }}
      />
      <button className="button" type="button" onClick={toggleDisabled}>Toggle</button>
    </form>
  );
};

const container = document.getElementById("app");
if (container) {
  const root = createRoot(container);
  root.render(<App />);
}
```

### Expected behaviour
Want Input and its CountryList both work when `inputProps.isDisabled` is `true`

### Actual behaviour
Even the `inputProps.isDisabled` changed from `false` to `true`, CountryList not showing! (button not working)

### Initialisation options
Used `import IntlTelInput from "../src/intl-tel-input/reactWithUtils";`

### What was the root cause?
To address the problem, I deep dived in the code and found the cause.

1. in `react.tsx`, `inputProps.disabled` passed directly into the input tag.
```tsx
// react.tsx

return (
    <input
      type="tel"
      ref={inputRef}
      onInput={update}
      defaultValue={initialValue}
      {...inputProps}
    />
  );
```

2. in `intl-tel-input.ts`, when `IntlTelInput` initialized, if `this.telInput.disabled=true` then selectedCountry disabled.

```ts
// line 840

if (this.telInput.disabled) {
          this.selectedCountry.setAttribute("disabled", "true");
}
```

3. After `inputProps.disabled` become `true`, `<input>` will be enabled because the props are directly passed (noted in 1), but selectedCountry doesn't because `intlTelInput` is already initialized. (noted in 2)

### Solution
I think user would think 'disable/enable IntlTelInput` means disable/enable both CountryList and Input tag. So I added a prop for it, and modified the code. All the tests are passed, and `allowDropdown` is also working.

https://github.com/user-attachments/assets/587ffdf1-db40-432c-96c0-f5dea6e27814

p.s. Actually this is my first time contributing open source, and I really hope to contribute in your repo. All feedbacks are welcome. Thanks 😊

**Comment by jackocnr** [comment]
Thanks so much for your work on this! I've manually merged your commits.
