### ISSUE TITLE
Wrong Lithuanian phone number placeholder

### ISSUE THREAD

**Issue by emaliukou** [jackocnr/intl-tel-input#1728]
### Plugin version
e.g. v23.8.0

Steps to reproduce
<img width="310" alt="Screenshot 2024-08-02 at 12 27 57" src="https://github.com/user-attachments/assets/08d291cc-b3fa-4dae-8c85-b1b2cdbf1419">
1.  Enter your actual demo page
2.  Choose Lithuania from countries list
3.  See wrong placeholder with 0 at the beginning

**Expected behaviour**
I want to see actual Lithuanian phone placeholder after I chose that country.
We don't need 0 at the beginning, placeholder should look like 8 digits divided into 3 groups e.g. "123 45 678".
So full phone number will look like that → +370 123 45 678

**Actual behaviour**
When I choose Lithuania from countries list I get right phone prefix but wrong phone placeholder with "0" at the beginning.
It mislead users and they place phone with the 0 at the first place and it doesn't work as we don't use that 0 number after the prefix.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please [file an issue](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md) with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by jackocnr** [comment]
I tried the libphonenumber test site with that number and it says it's a valid mobile number:

<img width="375" alt="Screenshot 2024-08-02 at 14 58 21" src="https://github.com/user-attachments/assets/cbbac2c8-ffc9-47da-88e2-1152a651d1e4">

**Comment by jackocnr** [comment]
> I need to create an issue on their page?

Yes. We have no control over the placeholder numbers. I'll close this for now.
