### ISSUE TITLE
Detect default country without external services (solution provided)

### ISSUE THREAD

**Issue by msykes** [jackocnr/intl-tel-input#1734]
Your demo tutorials show GeoIP solutions to detect user countries, which is great but depends on services.

I came up with a pretty reliable method to detect country based on browser timezone, here's the code and example:

https://gist.github.com/msykes/4bbdbefd0a26b9d1516eb709b717ff07

Also, thanks for the great work!

**Comment by jackocnr** [comment]
Thanks for sharing!

> I came up with a pretty reliable method

Do you have an idea of just how reliable it is? Any known limitations etc?

And does it attempt to identify every single one of the 200+ countries/regions that we use in this plugin? (see the country codes in [data.ts](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intl-tel-input/data.ts))

**Comment by jackocnr** [comment]
Sounds great! Thanks for sharing it. I copied and pasted it into [this codepen](https://codepen.io/jackocnr/pen/MWMoEBv), and it correctly identifies my country 🇬🇧 

Have you done much reading around this? Can you link to any articles etc that discuss the accuracy of this approach? Or highlight the potential downsides?

[This StackOverflow answer](https://stackoverflow.com/a/71563540/217866) says they found users timezones could identify their American/Canadian users with about 90% accuracy, but I wonder about other countries. Or I wonder if there are certain devices where this doesn't work as well or something like that? 🤔

**Comment by jackocnr** [comment]
This approach will not work for territories/regions that do not have their own JS timezone, like Ascension Island and Kosovo.

It also won't work for people using VPNs or proxies - they will just get another random country that probably won't make sense to them.

**Comment by msykes** [comment]
This was done a while ago (6 months ago maybe) and sitting for release, so I don't have any reading references. Generally, I checked the accuracy of timezones based on browser and browser support for this method, it's purely based on what the user (or browser) selects as their timezone.

Interestingly, I live between Andorra/Spain and I've noticed the country switches correctly as I'm in one place or another... these days browsers are getting smarter at auto-detecting timezone.

It's not perfect by any means. IP lookup is more reliable, but then with VPNs neither is the IP lookup. I could imagine going a step further maybe in making situations where countries overlap timezones could be added to the preferred list at the top. Since that was written, I notice you added a globe to the selection options, which would make sense to start with plus prioritized matches.

For our purposes, it initially suffices as a helpful switch for default countries, we have implemented a settings section where people can choose countries they want to include/exclude, prioritize along with turning this detection feature on/off.

I'm pretty sure we'll get some more feedback on reliability over the coming weeks once we roll this out, especially in other countries. We can adapt/improve as we go and share feedback here if you'd like!

**Comment by msykes** [comment]
> It also won't work for people using VPNs or proxies

Come to think of it, it may work BETTER with VPNs because the browser still serves the original timezone, right?

**Comment by jackocnr** [comment]
> We can adapt/improve as we go and share feedback here if you'd like!

That would be amazing, thanks! Depending on how it goes, I'll mention it in the readme as an option for people to try.

I'll close this issue for now tho. Thanks again.

**Comment by dkameleon** [comment]
"Europe/Kyiv" need to be added due to corrected transliteration
