### ISSUE TITLE
missing CDN resource?

### ISSUE THREAD

**Issue by budg1e** [jackocnr/intl-tel-input#1736]
v23.8.0

### Steps to reproduce
1.  missing CDN resource at https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/23.8.0/img/flags.webp ?

### Expected behaviour
Flags should appear

### Actual behaviour
Flag do not appear, see 404 in the network tab on load

### Initialisation options

initialCountry: "auto",
preferredCountries: ["gb", "us", "sg", "au", "za", "ae"],
initialCountry: '',
nationalMode: false,
utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/23.8.0/js/utils.js", 
placeholderNumberType: "MOBILE",
separateDialCode: false

**Comment by jackocnr** [comment]
Yes I confirm it's not working for me, but the png version is working. I have no affiliation with that CDN so you'll need to raise this issue with them directly.

**Comment by jackocnr** [comment]
I've submitted a PR to update their json config for this project: https://github.com/cdnjs/packages/pull/1862

**Comment by budg1e** [comment]
thanks -are you able to recommend a better CDN for this?

and thank you again

**Comment by jackocnr** [comment]
Yes if you search the readme for "CDN". I'll close this for now.
