### ISSUE TITLE
Strict mode with extension

### ISSUE THREAD

**Issue by andinera** [jackocnr/intl-tel-input#1737]
I'm looking for a way to block letters in the number input but still allow extension input. I've tried using strictMode but that blocks extension input. My current workaround is below, but I'm unsure if this would affect any international functionality, and unfortunately this breaks entering 'ext.' rather than 'x'. If the plugin provides similar functionality, that would be preferable.

Thank you!

```
const number = this.phoneNumberInput.getNumber();
if (number.match('[^+\\d]')) {
    this.phoneNumberInput.setNumber(number.replaceAll(new RegExp('[^+\\d]', 'g'), ''));
}
```

### Plugin version
e.g. v23.8.0

### Steps to reproduce
1.  Enable strictMode
2.  Attempt to add number with extension
3.  Plugin blocks extension input

### Expected behaviour
Block letters for number input but allow extension input

### Actual behaviour
Blocks letters for number input and blocks extension input

### Initialisation options
autoPlaceholder: 'off',
countryOrder: ['us'],
separateDialCode: true,
strictMode: true

**Comment by jackocnr** [comment]
Hmm how do you see this working with strictMode? Once they finish typing their number, do we allow them to enter a space character, or do we expect them to type the "E" straight after the last digit? Do we only accept uppercase "E" and ignore lower case "e"? I see that lots of people include a comma after the number, do we allow that? And some people write "Ext." and some write the full word "extension". And what about other languages? On reflection, this doesn't feel very compatible with strictMode - I would recommend you just disable strictMode if you want to support this kind of number.

**Comment by andinera** [comment]
I wouldn't think it would matter what they type afterward. Once the number portion is deemed valid, the remainder follows the non-strict extension validation.

This doesn't need to fall into the 'trictMode paradigm. Just something that prevents validating letters as numbers. I simply mentioned strictMode because it was the only thing I saw that prevents validating letters as numbers, but then was disappointed when I saw extensions were disabled.

**Comment by jackocnr** [comment]
> This doesn't need to fall into the strictMode paradigm. Just something that prevents validating letters as numbers

I'm a bit confused. So if you disable strictMode, then what exactly is the problem? Is it to do with `isValidNumber`? Can you describe what you expect to happen vs what is actually happening?

**Comment by andinera** [comment]
With strictMode disabled, a user can enter something like +1555callattx1234 and it's valid. getNumber() converts it to +15552255288 and of course getExtension returns 1234. I would like a way to disallow replacing numbers with letters. I would like +1555callattx1234 to be invalid. The user should have to enter +15552255288x1234 explicitly.

**Comment by jackocnr** [comment]
> I would like +1555callattx1234 to be invalid

I just checked on the [validation demo page](https://intl-tel-input.com/examples/validation-practical.html) and it returns invalid.

**Comment by andinera** [comment]
It looks like anything with an extension is invalid. I input a known good number (all numbers, no letters) with an extension and it returned invalid. That number is marked as invalid but the validationError is marked as 'IS_POSSIBLE'. What would make something invalid but still possible? It seems counter-intuitive.

**Comment by jackocnr** [comment]
> It looks like anything with an extension is invalid

This should now be fixed in v23.8.1 (and on the demo site, if you do a cache refresh). Does that solve your problem?

**Comment by andinera** [comment]
The issue we were discussing seemed to work fine on the site. Thank you!  
However, if you put an 'x' after a valid number with no extension, it reported it as valid. Unsure if that's desired. I feel it would be preferable if an extension indicator with no extension were invalid.

**Comment by jackocnr** [comment]
> The issue we were discussing seemed to work fine on the site. Thank you!

Fab 👍 

> However, if you put an 'x' after a valid number with no extension, it reported it as valid

We use libphonenumber for validation, and they do [say that is valid](https://libphonenumber.appspot.com/phonenumberparser?number=%2B17024181234x). If you think this is wrong, you'll need to [file an issue](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md) with them instead. I'll close this for now.

**Comment by andinera** [comment]
No worries. Thanks for your quick turn around and support with my issue!
