### ISSUE TITLE
Default Belgian placeholder number is the phone number of an escort service.

### ISSUE THREAD

**Issue by bob-timeblockr** [jackocnr/intl-tel-input#1743]
### Plugin version
e.g. v23.8.1 (please try latest version)

### Steps to reproduce
1.  Open a page with the intl-tel-input 
2.  select Belgian flag
3.  The placeholder is visible
4. (don't) call the phone number visible as placeholder text
![image](https://github.com/user-attachments/assets/2790c609-75a7-480b-8880-13aba45b447d)

### Expected behaviour

The phone number is not in use, it is an example.

### Actual behaviour
A belgian escort service answers your call

### Initialisation options
any configuration with Belgium enabled.

**Comment by jackocnr** [comment]
Wow that is an unfortunate coincidence!

We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - please [file an issue](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md) with them instead.
