### ISSUE TITLE
Error during the phone number validation for Japan.

### ISSUE THREAD

**Issue by arthutox** [jackocnr/intl-tel-input#1745]
**Plugin version**
v23.8.1

**Steps to reproduce**
1.  https://intl-tel-input.com/examples/validation-practical.html 
pls try to paste valid Japan phone number - +81 3 3523 0811
<img width="779" alt="Screenshot 2024-08-13 at 17 19 20" src="https://github.com/user-attachments/assets/cd1b3b6e-a4fc-4469-8258-9f015d9d7c91">

When validating the number, an error is returned because the plugin considers it invalid.
I checked this number in the libphonenumber. 
Result from isValidNumber() | true

<img width="557" alt="Screenshot 2024-08-13 at 17 22 13" src="https://github.com/user-attachments/assets/f5584416-b959-4a78-b6d9-e8af50c61186">

https://libphonenumber.appspot.com/phonenumberparser?number=%2B81+3+3523+0811

**Expected behaviour**
The plugin's response to the valid number check is true.

**Actual behaviour**
The plugin's response to the valid number check is false.

**Comment by jackocnr** [comment]
As per the instructions in your screenshot, by default, isValidNumber only returns true for mobile numbers. If you want it to accept other kinds of numbers, you need to also set validationNumberType accordingly (see readme).
