### ISSUE TITLE
Integrate React component with React Hook Form Controller wrapper component

### ISSUE THREAD

**Issue by ibarral** [jackocnr/intl-tel-input#1747]
### Plugin version
v23.8.1

It's possible to integrate the React Component (https://intl-tel-input.com/examples/react-component.html) with React Hook Form Controller (https://react-hook-form.com/docs/usecontroller/controller) so when there is an error on the form it focus on the telephone form field using TypeScript?

Thanks!

**Comment by jackocnr** [comment]
I have no experience with that. I think you'd be better off asking this kind of question on StackOverflow.

**Comment by ibarral** [comment]
Thanks @jackocnr !

I have done a lot of experiments and I think that the error can be that the React Component of `IntlTelInput` has not implemented the default HTMLElement `focus() ` method (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) when we pass the ref to the component (https://github.com/jackocnr/intl-tel-input/blob/master/react/demo/SetNumberApp.tsx#L36), is that possible?

**Comment by jackocnr** [comment]
Hmm probably the issue is that the IntlTelInput react component just renders an `<input>` element, but then when it initialises the plugin, that gets wrapped in a `<div>` by the plugin JS, but not in a react way - it's just manually injected into the DOM.

Wherever you're using the plugin, could you try wrapping it in a react div e.g. `<div><IntlTelInput /></div>` - perhaps that would help?

**Comment by ibarral** [comment]
I have tried wrapping in a `div` but got no luck :(

Any other suggestion? or it needs to update the plugin to wrap the div in a react way?

Thanks!

**Comment by jackocnr** [comment]
> or it needs to update the plugin to wrap the div in a react way?

No, if you have wrapped it in a div in a react component then that's the same thing

> Any other suggestion?

I'm afraid not. I just have no experience with that library. Maybe you can ask them what is required for compatibility, and link them to this issue? Best of luck.

**Comment by ibarral** [comment]
Hello @jackocnr ,

I found this documentation about how to integrate with external components:

https://react-hook-form.com/docs/usecontroller/controller

Please tell me if you need something else 😀

Thanks a lot for your help!

**Comment by jackocnr** [comment]
That says "Wrapper component for controlled inputs" and this is very much an uncontrolled input (and has to be due to the fact that this is just a thin react wrapper around a JS plugin).

**Comment by BrunoViera** [comment]
Hello!
The issue occurred when integrating the IntlTelInput component with React Hook Form (RHF). If the input has an error, RHF attempts to focus on the component to display the error to the user. However, the ref returned by IntlTelInput does not implement the standard HTML input reference interface, so the .focus() method does not exist, causing it to fail.

How did we fix it?
We resolved the issue by wrapping IntlTelInput in a custom component that exposes a reference with the .focus() implementation.


```
...
const inputRef = useRef(null);
  useImperativeHandle(ref, () => {
    return {
      focus() {
        inputRef?.current?.getInput().focus();
        inputRef?.current?.getInput().scrollIntoView({ behavior: "smooth", block: "end" });
      },
    };
  }, []);

  return (
    <IntlTelInput
      ref={inputRef}
...
```

We reviewed the IntlTelInput source code and noticed that the library exposes a ref with two key methods: getInput and getInstance. These were crucial in helping us resolve the issue. It would be helpful to include this information in the README for future reference.

**Comment by jackocnr** [comment]
@BrunoViera thanks for sharing this, and I'm glad you found a solution to your issue. So are you saying you now have the intl-tel-input react component working well with React Hook Form? I'm surprised that everything works, as I thought RHF only worked with controlled inputs?

Would you be able to show us your solution in a codepen, so we can play with it? Here is [an example pen](https://codepen.io/jackocnr/pen/qBvrVvN) with the ITI react component up and running - feel free to fork that if it would help.
