### ISSUE TITLE
Antarctica missing from /intlTelInputWithUtils.js & /intlTelInput.js

### ISSUE THREAD

**Issue by JamesShaver** [jackocnr/intl-tel-input#1749]
### Plugin version
v23.9.2

### Steps to reproduce
1. Run the CodePen demo: https://codepen.io/jackocnr/pen/DyrVbw
2.  Search for "Antarctica" or "672" 
3.  No results ![image](https://github.com/user-attachments/assets/90afafd3-051b-4a4e-abe5-2cac5a36d4c3)

4. Confirmed the flag image and CSS already exist: 
![image](https://github.com/user-attachments/assets/e77acf5b-2ff2-4e3f-955a-c29edbac503f)
![image](https://github.com/user-attachments/assets/1a9706ec-5d61-4624-8187-50520161fba1)

### Expected behaviour
Antarctica should be returned, with a calling code of 672

### Actual behaviour
No results

### Initialisation options
const input = document.querySelector("#phone");
const iti = window.intlTelInput(input, {
  // separateDialCode: true,
  initialCountry: "gb",
  utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@23.3.2/build/js/utils.js",
});
window.iti = iti;

**Comment by jackocnr** [comment]
Please see [the criteria for supporting a country](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intl-tel-input/data.ts#L3-L7) - unfortunately, Antarctica does not have its own country calling code (672 is shared with other territories like Norfolk Island), and it is not supported by libphonenumber, so it's impossible for us to support it.
