### ISSUE TITLE
Viet Nam flag wrong

### ISSUE THREAD

**Issue by JackG55** [jackocnr/intl-tel-input#1768]
Please check the flag and change it. I found it's wrong when I access ubunu home page
Here the link: "https://ubuntu.com/engage/from-vmware-to-openstack?utm_source=takeover"

**Comment by jackocnr** [comment]
It's not just Vietnam - all their flags are wrong. Looks like it's loading the CSS and images from different versions of the plugin - this may just be a caching issue (on their end), or it may be that they've updated the plugin (inc CSS) but forgotten to update the hosted image files.

If you check the official [demo site](https://intl-tel-input.com/) the flags should be working fine.
