### ISSUE TITLE
Want to Restrict to change country only from dropdown not from input

### ISSUE THREAD

**Issue by noor-nisar77** [jackocnr/intl-tel-input#1769]
In fact, this is not the issue, but I need assistance. I want to restrict changing the country flag through direct input and only allow changes via the dropdown menu. Additionally, I need to display a popup message (e.g., "Some features of our service are only available in the "US") before the country is changed, while still allowing the user to select any country.

Currently, we can show the message using the "**open:countrydropdown**" event. However, we are unable to display the message when the country is changed by entering a number (e.g., if "US" is selected and the user types '204', it changes to "Canada" without showing the message).

How can we achieve this functionality? Your support is greatly appreciated. Thank you in advance.

**Comment by jackocnr** [comment]
See `countrychange` event in the readme. That is fired both when the user selects a country from the dropdown and when they type a different dial code. Does that solve your problem?

**Comment by noor-nisar77** [comment]
I regret to inform you that the "**countrychange**" trigger activates after the country has been changed. However, I would prefer it to behave like the "**open:countrydropdown**" trigger, which activates before the country change. Similarly, I want this behavior when the country is changed through direct input.

**Comment by jackocnr** [comment]
> I regret to inform you that the "countrychange" trigger activates after the country has been changed. However, I would prefer it to behave like the "open:countrydropdown" trigger, which activates before the country change.

I'm confused. You can use "open:countrydropdown" for when they open the country dropdown. But there is no equivalent action that happens before the user types a different dial code - either they type it or they don't. I don't understand how you want this to work. Can you please give a really clear breakdown of how you want this to work in the case of the user typing a different dial code?

**Comment by noor-nisar77** [comment]
Okay, Is there any way or setting to allow to change the country from the dropdown only and restrict the country change from direct input?

**Comment by jackocnr** [comment]
If you enable separateDialCode and strictMode then it will prevent the user from typing a plus character to change the international dial code, which is the main way the user can change the selected country by typing. But it doesn't solve area code use case you mentioned of having USA selected and typing "204" for Canada. There's no way to prevent this. There are so many different area codes like this in the +1 region alone - currently we have 25 countries (or territories) that each have their own +1 area codes (e.g. "868" for Trinidad), and some of those countries have several e.g. Canada alone has over 50 area codes. So you would need to massively restrict which numbers the user could enter, and I think that would be very confusing - it would feel broken.
