### ISSUE TITLE
maybe a small bug, which change country flag while type a number

### ISSUE THREAD

**Issue by FlorinParaschivescuServerSys** [jackocnr/intl-tel-input#1780]
Hey,

First of all, thank you very much for this plugin! I'm not sure if this is a bug but, below are the steps to reproduce:

1 - https://intl-tel-input.com/examples/separate-dial-code.html
2 - select Åland Islands (+358) as a dial code, than start typing 11, you'll see the flag changing to Finland
3 - select American Samoa (+1),  type like any number, 11, or just 3, the flag is changing to USA one

Probably are other as well, I didn't test them all.

Cheers!

**Comment by jackocnr** [comment]
> First of all, thank you very much for this plugin!

Glad you're finding it useful 😊 

> select Åland Islands (+358) as a dial code, than start typing 11, you'll see the flag changing to Finland

That is because +35811 is a Finish number. Aland Islands numbers start with +35818.

> select American Samoa (+1), type like any number, 11, or just 3, the flag is changing to USA one

Same situation here. American Samoa numbers start with +1684.
