### ISSUE TITLE
search box is not appearing in intl-tel-input dropdown

### ISSUE THREAD

**Issue by Eli-Imran** [jackocnr/intl-tel-input#1793]
i can not see the search option. how to enable it?
![image](https://github.com/user-attachments/assets/fc8a2ff6-254e-4bc9-8e8c-b84b55e148cf)

`
var input = document.querySelector("#phone");
  window.intlTelInput(input, {
    initialCountry: "auto", // Set the initial country to auto
    geoIpLookup: function(success, failure) {
      fetch('https://ipinfo.io/json?token=your_token', { headers: { 'Accept': 'application/json' }})
      .then(resp => resp.json())
      .then(resp => success(resp.country))
      .catch(() => success('us'));
    },
    preferredCountries: ['us', 'gb', 'in'], // Optional: list of preferred countries
    utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@17.0.8/build/js/utils.js" // For formatting/validation
  });
`

![image](https://github.com/user-attachments/assets/d5be34f8-8376-4fd6-afe3-88950fd55737)

**Comment by Eli-Imran** [comment]
@idris @fayland @defro @kek

**Comment by jackocnr** [comment]
You need to upgrade to the latest version of the plugin.
