### ISSUE TITLE
Phone number showing placeholder text instead of value

### ISSUE THREAD

**Issue by jaggaer-epastoor** [jackocnr/intl-tel-input#1803]
### Plugin version
v24.5.0

### Steps to reproduce
1.  I have reproduced this on React Storyboard in demo mode: [Initial value example](https://intl-tel-input.com/storybook/?path=/docs/intltelinput--initialvalue)
2.  Enter in phone number: +375152450911
3.  See that displayed value is: 8 0152 45-09-11

### Expected behaviour
Actual number should be displayed

### Actual behaviour
Placeholder value is displayed but in the inspector the 'value' attribute is correct
When form is submitted, the real value is submitted and not the placeholder value

### Initialisation options
formatOnDisplay = true (default); however, turning this off fixes the value
or:
separateDialCode = true also fixes the issue

**Comment by jackocnr** [comment]
This is working as intended.

By default nationalMode is enabled, which means we format the number in national format, which is "8 0152 45-09-11". If, for some reason you want to show the number in international format, you can set nationalMode to false.

**Comment by jaggaer-epastoor** [comment]
So the number +375152450911 in national mode is a completely different number which happens to match the placeholder text 8 0152 45-09-11?
