### ISSUE TITLE
safari 13 and webp

### ISSUE THREAD

**Issue by lekoala** [jackocnr/intl-tel-input#1824]
I've tried to use your wonderful library on a website that has, unfortunately, safari 13 users

It works pretty well, except the flags are not displayed because they use webp
https://caniuse.com/webp

It's easy to override the css to fix this.

i don't know which versions you are supporting but maybe it's worth noting this somewhere
(i only saw https://github.com/jackocnr/intl-tel-input/blob/master/README.md#browser-compatibility => so it should add safari >= 14)

have a great day,

**Comment by jackocnr** [comment]
That's updated now, thanks for the heads up.
