### ISSUE TITLE
Vue import trouble: cannot find module or its corresponding type declarations

### ISSUE THREAD

**Issue by seasonedtofu** [jackocnr/intl-tel-input#1841]
![image](https://github.com/user-attachments/assets/1d2186d0-c10b-4c2b-b6fd-680d0b20b482)

Hi, I am having trouble trying to import the Vue component and am not sure if I am doing it correctly.

I am getting a `Cannot find module 'intl-tel-input/vue' or its corresponding type declarations.` error.
I have also tried importing just like from the demo/readme with `import IntlTelInput from 'intl-tel-input/vueWithUtils';` and same issue.

The version I am on is 24.6.0

Is there any way to fix this? Here is my tsconfig.json below:

```
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"],
    },
    "lib": [
      "ESNext",
      "dom",
      "dom.iterable",
      "scripthost"
    ],
  },
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ],
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ],
  "exclude": [
    "node_modules",
    "packages/**/dist/**"
  ]
}
```

**Comment by jackocnr** [comment]
Unfortunately, the vue component doesn't have types yet: https://github.com/jackocnr/intl-tel-input/issues/1794

As I say in that thread, the [Vue Component](https://github.com/jackocnr/intl-tel-input/blob/master/vue/src/intl-tel-input/IntlTelInput.vue) is actually very simple - it should be easy to add them. I don't have time to implement this myself, but would welcome a pull request.

**Comment by jackocnr** [comment]
Hi @seasonedtofu I have just released [TypeScript support](https://github.com/jackocnr/intl-tel-input/pull/1920) for the Vue component in v26.0.0-beta.0 - please give it a try and let me know if you have any issues.

EDIT: btw you can see a list of all breaking changes in this release here: https://github.com/jackocnr/intl-tel-input/releases/tag/v26.0.0-beta.0
