### ISSUE TITLE
Contributing to previous versions. Upgrading a previous version of intl-tel-input [ Discussion ] 

### ISSUE THREAD

**Issue by Ryan-Boustany** [jackocnr/intl-tel-input#1844]
With regards to how my repository is set up I am looking update libphonenumber library on version 17.0.21. I checked and it is indeed possible to make that upgrade. It'll be much more effective and require much less change to the overall structure of my project. How am I able to go about achieving this change?/How can i contribute to previous versions?

Any Advice is greatly appreciated!

**Comment by jackocnr** [comment]
v17 was a long time ago, so I would strongly recommend you upgrade for all sorts of bug fixes and improvements.

With that said, it should be possible to stay with that version and upgrade libphonenumber, if that's what you want to do.

First you'll need to fork the repo, so you have your own copy which you can push changes to, and then switch your project to use that repo instead of this one.

After you've forked the repo, you can clone it, and then checkout v17.0.21. Then, you should be able to follow the instructions in .github/CONTRIBUTING.md on how to update libphonenumber from there.

For reference, here's a link to the [contributing instructions](https://github.com/jackocnr/intl-tel-input/blob/v17.0.21/.github/CONTRIBUTING.md) at v17.0.21

**Comment by Ryan-Boustany** [comment]
@jackocnr Just had a questions: 
1. Does that mean that in my package.json I will be including my newly forked repo instead of this one (intl-tel-input)? 
2. To follow, my changes wont be included in a 17.0.22 tag in this repo?

**Comment by jackocnr** [comment]
> Does that mean that in my package.json...

That's right, in your package.json you'll be loading the plugin from Ryan-Boustany/intl-tel-input instead - I can't remember the exact syntax - it should be easy to google how to load a package from a custom fork.

> To follow, my changes wont be included in a 17.0.22 tag in this repo?

That's correct. You'll create a new tag in your forked repo, which you can then load in your package.json to get the updated version, but that wont impact this repo at all (jackocnr/intl-tel-input).

**Comment by Ryan-Boustany** [comment]
@jackocnr Hey Tried to follow the steps and got up to the build section. I encountered this error:

Any advice would be greatly appreciated :) 

`SYDMAC116:closure-compiler boustry$ bazelisk build :all
2024/10/15 16:34:28 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
INFO: Call stack for the definition of repository 'google_bazel_common' which is a git_repository (rule definition at /private/var/tmp/_bazel_boustry/287eb8ada5cb1ef597fcf96f64786701/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - <builtin>
 - /Users/boustry/Desktop/workspace/libphonenumber-tools/closure-compiler/WORKSPACE.bazel:5:1
ERROR: An error occurred during the fetch of repository 'google_bazel_common':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_boustry/287eb8ada5cb1ef597fcf96f64786701/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
		_clone_or_update(ctx)
	File "/private/var/tmp/_bazel_boustry/287eb8ada5cb1ef597fcf96f64786701/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_boustry/287eb8ada5cb1ef597fcf96f64786701/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_boustry/287eb8ada5cb1ef597fcf96f64786701/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
		fetch(ctx, git_repo)
	File "/private/var/tmp/_bazel_boustry/287eb8ada5cb1ef597fcf96f64786701/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 129, in fetch
		_git_maybe_shallow(ctx, <5 more arguments>)
	File "/private/var/tmp/_bazel_boustry/287eb8ada5cb1ef597fcf96f64786701/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 171, in _git_maybe_shallow
		_error(ctx.name, <2 more arguments>)
	File "/private/var/tmp/_bazel_boustry/287eb8ada5cb1ef597fcf96f64786701/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(<1 more arguments>)
error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @google_bazel_common:
fatal: unable to connect to github.com:
github.com[0: 4.237.22.38]: errno=Operation timed out`
