### ISSUE TITLE
getNumber not including country code after editing initial value

### ISSUE THREAD

**Issue by jaggaer-epastoor** [jackocnr/intl-tel-input#1849]
### Plugin version
v24.6.0
### Steps to reproduce
1.  Go to my codepen: https://codepen.io/HokiEJP/pen/BagXGJQ?editors=1111 
2.  Delete the existing phone number
3.  Use the drop down to select Bolvia
4. Enter in this number: 69433
5. In the codepen js console, type: iti.getNumber()

### Expected behaviour
getNumber should return +591 69433

### Actual behaviour
getNumber returns only 69433

### Initialisation options
strictMode: true,
  nationalMode: false,
  initialCountry: 'us',
  separateDialCode: false,
  hiddenInput: function(telInputName) {
    return {
      phone: telInputName + "_phone_full",
      country: telInputName + "_country_code"
    }
  },

**Comment by jackocnr** [comment]
As per the readme, getNumber only works with valid numbers, so you need to check if it's valid first.
