### ISSUE TITLE
Flag Images sizes 

### ISSUE THREAD

**Issue by kdbbrown** [jackocnr/intl-tel-input#1852]
I installed the package and i'm currently using it in a project , 
I am trying to increase the flag sizes , 
I have forked the project and have modified the https://github.com/jackocnr/intl-tel-input/blob/master/grunt/generate-sprite.js#L11-L12 file  , TARGET_WIDTH and TARGET_HEIGHT , 
what do i do next , do i make a PR to the root project how can i use the modified widths in my current projects ?

**Comment by jackocnr** [comment]
You run `npm install` and `npm run build:img` to generate the new images/CSS, and then you commit that and push that to your (forked) repo. Then in your main project, you switch out the intl-tel-input package for your forked version e.g. something like this: `npm install https://github.com/YOUR_ACCOUNT/intl-tel-input`
