### ISSUE TITLE
Selected class on current country item

### ISSUE THREAD

**Issue by MaartenPetiet** [jackocnr/intl-tel-input#1855]
### Plugin version
v24.6.0

### Steps to reproduce
N/A

### Expected behaviour
We would like to add some additional styling to the country dropdown item that is currently active (so not the selected by mouse/keyboard but selected in the dropdown value). It seems we now have to add some JS to check the value. Could you add some sort of class to this item to make a css-only solution possible? Thank you for the awesome package!

### Actual behaviour
No way of adding styling for the country item that is selected in the dropdown with only css.

### Initialisation options
N/A

**Comment by jackocnr** [comment]
I'm confused. Currently we use the `.iti__highlight` class for the selected dropdown item, which is how we colour it differently. But do you mean something else?

> not the selected by mouse/keyboard but selected in the dropdown value

Please can you provide more specific details of what you mean here?

**Comment by MaartenPetiet** [comment]
@jackocnr thank you for your reply. Yes so basically we want a class on the `li.iti__country` that is currently the active value of the dropdown:

![image](https://github.com/user-attachments/assets/875a495e-f8f6-481a-9493-291668c61745)

Hope this is clear.

**Comment by jackocnr** [comment]
Thanks for explaining. I understand now. Sure, I would be open to adding this - it should be fairly straight forward. I don't have time to look into it myself right now, but I would be open to a pull request implementing this feature.
