### ISSUE TITLE
Following older update steps for libphonenumber

### ISSUE THREAD

**Issue by Ryan-Boustany** [jackocnr/intl-tel-input#1869]
Hey,

Trying to follow the steps below and get some clarification. 

Copy `intl-tel-input/src/js/utils.js` to `libphonenumber/javascript/i18n/phonenumbers/demo.js`

Does that refer to just copying the contents of utils.js over to demo.js? aka replacing the contents of the file but not the name? or does it refer to replacing the name as well.

Same with Step 3 :) 
<img width="1074" alt="image" src="https://github.com/user-attachments/assets/44276b08-d217-4254-94ca-8482061d1547">

**Comment by jackocnr** [comment]
In both cases, you just want to copy the contents of the file
