### ISSUE TITLE
Add new operator codes for Ukrainian operators

### ISSUE THREAD

**Issue by shevchun** [jackocnr/intl-tel-input#1870]
need to add two new codes for Ukrainian operators Vodafone - 75 and KyivStar 77

### Plugin version
v24.6.1

### Steps to reproduce
1.  entered +380 75 173 9933 validation error
2.  entered +380 77 173 9933 validation error

### Expected behaviour
+380 77 173 9933 valid number
+380 75 173 9933 valid number

### Actual behaviour
+380 77 173 9933 validation error

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please [file an issue](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md) with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).
