### ISSUE TITLE
Error with update to v24.6.1

### ISSUE THREAD

**Issue by christine927t** [jackocnr/intl-tel-input#1872]
### Plugin version
v24.6.1

### Steps to reproduce
1.  update to v24.6.1
2.  run server and navigate to page using this package
3.  console in browser shows TypeError

### Expected behaviour
No error should appear

### Actual behaviour
Error appears on page load
![Screenshot 2024-11-05 at 12 43 32 PM](https://github.com/user-attachments/assets/2e944dda-6fc3-42cb-9cca-e8e1513f2b76)

### Initialisation options
none

**Comment by jackocnr** [comment]
I can see from your error message that you're using a very old version of utils.js - you need to update this to the same version of the plugin you're using.

**Comment by christine927t** [comment]
@jackocnr Ah thank you for pointing this out!
