### ISSUE TITLE
Existing number not choosing the correct country flag

### ISSUE THREAD

**Issue by tbarmann** [jackocnr/intl-tel-input#1873]
### Plugin version
e.g. v24.6.1 (please try latest version)
24.6.1
### Steps to reproduce
1.  Input is set to US as default country.
2.  Choose UK flag and enter a valid UK number and save
3.  Reload form to edit phone number

### Expected behaviour
Tell us what should happen
UK flag should be selected

### Actual behaviour
Tell us what actually happens
US flag is selected

### Initialisation options
List any options you're using e.g. utilsScript or onlyCountries
Using stimulus js on Rails framework. Here is the intialization in the connect method:
```
    this.phoneInput = intlTelInput(this.phoneNumberTarget, {
      initialCountry: "US",
      countryOrder: ["US", "CA", "ES", "GB", "PH"], // these appear first. country codes: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
      loadUtilsOnInit: () => import("intl-tel-input/utils"),
      hiddenInput: () => ({
        phone: "full_phone[][number]",
        country: "country_code",
      }),
    });
```

**Comment by tbarmann** [comment]
Never mind. My database was not saving the country code. When I add the +44 country code to the UK number, it works as expected. However, since US and Canada share the +1 country code, how does the library distinguish between those two countries when choosing which flag to select?

**Comment by jackocnr** [comment]
Based on Canada's [area codes](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intl-tel-input/data.ts#L191)
