### ISSUE TITLE
Does it allow setting the initial country via code (e.g +92)? or only setting via country initial ('pk') is allowed?

### ISSUE THREAD

**Issue by nidamunir-extreme** [jackocnr/intl-tel-input#1875]
### Plugin version
e.g. v24.7.0 (please try latest version)

### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or onlyCountries

**Comment by jackocnr** [comment]
This method only works with the iso2 country code, e.g. "pk" as you say.

If you really wanted to, you could use `getCountryData` to map your dial code to the country code.
