### ISSUE TITLE
Intl-tel input fires change event on initialisation with setNumber. How do I listen to it? 

### ISSUE THREAD

**Issue by nidamunir-extreme** [jackocnr/intl-tel-input#1879]
### Plugin version
e.g. v24.7.0 (please try latest version)

### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or onlyCountries

**Comment by jackocnr** [comment]
See the [Events](https://github.com/jackocnr/intl-tel-input?tab=readme-ov-file#events) section of the readme for an example.
