### ISSUE TITLE
Placeholder is not set

### ISSUE THREAD

**Issue by lukecharle** [jackocnr/intl-tel-input#1905]
### Plugin version
v25.2.0

### Steps to reproduce
1.  Use the example from https://intl-tel-input.com/examples/lookup-country.html
2.  Placeholder isn't set

### Expected behaviour
The placeholder should be added to the input, and also change on country change

### Actual behaviour
No placeholder is set

### Initialisation options
```javascript
const input = document.querySelector("#phone");
window.intlTelInput(input, {
  initialCountry: "auto",
  geoIpLookup: callback => {
    fetch("https://ipapi.co/json")
      .then(res => res.json())
      .then(data => callback(data.country_code))
      .catch(() => callback("us"));
  },
  loadUtils: () => import("https://cdn.jsdelivr.net/npm/intl-tel-input@25.2.0/build/js/utils.js"),
});
```

Have also replicated in a [codepen](https://codepen.io/lukecharle/pen/dPbzEdv)

**Comment by rashadmehtab** [comment]
You're using an outdated version of the plugin CDN for `intl-tel-input` (v18.2.1) along with the latest version of the utils CDN (v25.2.0). This mismatch could be causing issues. 

To resolve this, please update both the CSS and JS files to version 25.2.0 by replacing the old URLs with the following:

- **CSS**: `https://cdn.jsdelivr.net/npm/intl-tel-input@25.2.0/build/css/intlTelInput.css`
- **JS**: `https://cdn.jsdelivr.net/npm/intl-tel-input@25.2.0/build/js/intlTelInput.min.js`

**Comment by jackocnr** [comment]
@lukecharle your codepen is working fine for me - showing a placeholder, and updating it when I change the country. Maybe this is because you updated the version numbers, according to @rashadmehtab's comment? Either way, I'll close this for now, but do let us know if you're still experiencing problems.
