### ISSUE TITLE
Problems when using with WordPress admin

### ISSUE THREAD

**Issue by tripflex** [jackocnr/intl-tel-input#205]
WordPress core CSS sets `arrow` class CSS values, because your class for arrow is specifically that, arrow, it causes issues if you want to use this in WordPress admin

**Comment by jackocnr** [comment]
Thanks for raising this issue. We could replace all instances of the `arrow` class with `iti-arrow`? Unfortunately I don't have time to implement this myself right now, but I'm open to pull requests.

**Comment by tripflex** [comment]
Yeah unfortunately i'm in the same boat, so it was quicker to override CSS, but if I do have some time soon I will see what I can come up with

**Comment by iamstarkov** [comment]
Considering class-prefix, which is postcss plugin aiming to fix this kind of problem https://github.com/thompsongl/postcss-class-prefix

**Comment by tripflex** [comment]
:+1:

**Comment by jackocnr** [comment]
Renamed arrow class in v7.0.0
