### ISSUE TITLE
Issues with mobile dropdown

### ISSUE THREAD

**Issue by jackocnr** [jackocnr/intl-tel-input#244]
We use a hidden native `<select>` element on mobile - positioned above the selected-flag with `opacity: 0`. This is great for that native feel, but is very limited:

* No country flags or dial codes
* No `preferredCountries` (see https://github.com/Bluefieldscom/intl-tel-input/pull/201)
* Still openable when input is disabled/readonly (see https://github.com/Bluefieldscom/intl-tel-input/issues/243)

I propose we just use the same dropdown as on desktop, but make it full screen (with some margin). Some early notes here: https://github.com/Bluefieldscom/intl-tel-input/issues/86

Unfortunately I won't have time to work on this any time soon, but I'm open to pull requests!

**Comment by Dineshrajaa** [comment]
I couldn't see any country flags dropdown shown while using the latest version of this plugin in my Jquerymobile based phonegap application, is there any fix for this @jackocnr

**Comment by jackocnr** [comment]
This thread is for a proposed new type of dropdown on mobile. You issue is unrelated to that proposal - please create a new issue for your problem. Please read the Troubleshooting section of the readme, and also search the existing issues to make sure your question hasn't already been answered.

**Comment by Dineshrajaa** [comment]
Ok sorry for the trouble, I have removed my comment will open a new issue if i couldn't figure out the solution.

**Comment by jackocnr** [comment]
Fixed in master. Will be in v8.0.0.

**Comment by Dineshrajaa** [comment]
Thank you so much was waiting for the exact fix will give it a try.
