### ISSUE TITLE
Country Display Modes

### ISSUE THREAD

**Issue by jackocnr** [jackocnr/intl-tel-input#248]
I've seen a few people using the plugin by setting `onlyCountries` to a single country, which looks terrible. I propose we have a new initialisation option e.g. `countryMode`, which could be "full" (normal), "single" (no dropdown/arrow), or "none" (no selected country or dropdown - just a normal input).

**Comment by caseyjhol** [comment]
I was also thinking about having an `excludedCountries` option for cases where you require most of the countries on the list, but would like to remove some of the more obscure countries. If `onlyCountries` is set that would take precedence, of course.

**Comment by jackocnr** [comment]
There's another issue for that: https://github.com/Bluefieldscom/intl-tel-input/issues/200

**Comment by fishman1986** [comment]
Do you mean a country flag + input when `countryMode = single`?

**Comment by jackocnr** [comment]
Yes: we would display the flag next to the input, but no arrow, and no dropdown.

**Comment by fishman1986** [comment]
That's exactly what I need. Anyone working on this? If not, I'm going to do this

**Comment by fishman1986** [comment]
Hi there, what do you think about the 'none' mode? I'm a little confused.

**Comment by jackocnr** [comment]
Hmm I suppose you would still get the auto placeholder functionality, and the auto format functionality. But I'm not sure how useful it is any more - I'd definitely be happy to release this feature without it for now.

**Comment by fishman1986** [comment]
In my use case, I keep a country select when I use 'single' mode, in that way, I don't want the '_updateFlagFromNumber' work. What do you think about this? I think, when someone use 'single' mode, he must want to keep the country value under control, but updateFlagFromNumber will break this.

Then, for the 'none' mode, if we keep the auto placeholder and format functionality, user must have a country select or set a default country. How about just hide the flag, dropdown, and the arrow?

**Comment by jackocnr** [comment]
Re: single mode: I don't see any reason to change the behaviour of updateFlagFromNumber - the flag would only change if the user typed a plus and then a different country calling code - and if they do that  then I think it would be wrong to leave the old flag displaying - it wouldn't make sense - the plugin would be in an inconsistent state. I think we should change as little as possible for this feature - keep it simple - just a visual change.

**Comment by jackocnr** [comment]
Ok I ended up implementing something similar as a new option called `allowDropdown` which is `true` by default (normal behavior), but if you set it to `false`, it will remove the dropdown arrow, hover states and click listener (as well as the actual dropdown markup). Finally, it displays the flag on the right of the input because it's now just a visualization of state rather than an action. Release in v8.1.0.
