### ISSUE TITLE
Option to rename "ext."

### ISSUE THREAD

**Issue by RizziCR** [jackocnr/intl-tel-input#262]
Add a option to be able to rename the prefix of the extension.
For example, in Germany the most time the extension is separated with a minus (-)

Thanks

**Comment by jackocnr** [comment]
Good idea. I would suggest we rename the existing option `allowExtensions` to `extensionSuffix`, and have it default to empty string (disabled), but if you set it to a string (suggested: "ext.") then it adds support for extensions. Unfortunately I don't have time to implement this, but I'm open to pull requests.

**Comment by jackocnr** [comment]
This is now moot as I've removed the autoFormat feature as of v8.0.0.
