### ISSUE TITLE
source missing license header

### ISSUE THREAD

**Issue by KelseyBlodgett** [jackocnr/intl-tel-input#278]
I noticed that the JavaScript file doesn't have a license header. This seems to be a common practice amongst JavaScript libraries.
Would it be possible to add the information to the file so users can easily adhere to the project's license?
Something like:
Licensed under the MIT License

**Comment by jackocnr** [comment]
Sure I'm open to pull requests. You would just add a line in grunt/uglify.js and run `grunt js`.

**Comment by jackocnr** [comment]
This change is now in master and will be included in the next release.
