### ISSUE TITLE
Show Country dial code instead of flag

### ISSUE THREAD

**Issue by rockom** [jackocnr/intl-tel-input#317]
Hey
Would be great to have the option of to show in the dropdown the country dial code instead of the flag.

Thank you,
Roy

**Comment by jackocnr** [comment]
Hi Roy, can you tell me why you'd like to do this?

**Comment by nickovruchsky** [comment]
+1
This is really useful feature. For now my client want no flags but only code. So I should implement this by myself I think.

**Comment by rockom** [comment]
Hi,

I have the same issue.
I have clients who prefer flags and clients who prefer dial code only.

Thank you,
Roy

**Comment by jackocnr** [comment]
Why don't you just hide the flags using CSS? The dropdown already shows dial codes.

**Comment by rockom** [comment]
I am not sure it looks good but I will try to do so.

**Comment by nickovruchsky** [comment]
The main idea is to show the codes in input while it unselected.

**Comment by rockom** [comment]
Hiding the flags using CSS provide bad user experience.
It is much better to show the dial code or flags based on the options.

**Comment by caseyjhol** [comment]
@rockom Not quite sure what you're referring to. Can you make a mockup in Photoshop of what you want the menu to look like?

```css
.intl-tel-input .country-list .iti-flag {
    display: none;
}
```

Seems to accomplish what you're asking. Then, set `nationalMode: false`.

**Comment by nickovruchsky** [comment]
For me it's look like this - 
![tel](https://cloud.githubusercontent.com/assets/7410355/10981022/be3db878-840d-11e5-9558-a6e4a7aed321.jpg)

**Comment by rockom** [comment]
@nickovruchsky , This is exactly what i am looking for.
@caseyjhol , When applying your css i get:
![number-dropdown](https://cloud.githubusercontent.com/assets/3122712/11019148/859746aa-85f3-11e5-92ab-15fcc239617c.png)

**Comment by nickovruchsky** [comment]
@rockom try this 
```scss
      .intl-tel-input { 
        .form-control {
          padding-left: 25px;
        }
      .flag-dropdown {
        .selected-flag {
          width: 20px;
        }
        .iti-flag {
          background: none;
          .arrow {
            left: 0; 
          }
        }
      }
    }

**Comment by jackocnr** [comment]
@rockom @nickovruchsky if enough people want this, then I would welcome a pull request which added a `showSelectedDialcode` option, which when enabled would show the country dial code next to the selected flag. If enabled, it should also force `autoHideDialCode` to be false, so it doesn't automatically insert the country dial code into the input.

BUT: you would have an issue with the auto formatting in lots of countries where there are differences between national and international numbers e.g. UK: a sample international number would be "+44 7733 123456", but the national format is "07733 123456" - notice the extra 0. But if we do what you want, we would be showing the +44 next to the input, so the user would type "7733 123456" which is not a valid number, so the formatting wouldn't work. One potential solution would be to prefix the country dial code to the entered number before passing it to libphonenumber for formatting, and then remove it again afterwards.

**Comment by hirefrank** [comment]
:+1:

**Comment by Karthickgreets99** [comment]
Question : If i am assigning a international number to input (+44 7425234345), it auto select the flag, based on the country code provided, but what is the idea behind showing both flag and also country code in the input filed.
If i don't want to show the country code , do i have any option ?

**Comment by jackocnr** [comment]
@Karthickgreets99 the flags merely act as a simple way to help users select their country.

As for displaying the intl dial code: if you have `nationalMode` enabled (which it is by default), and you have the utils script loaded, then when you set a number with an intl dial code, it should automatically display just the national number.

If you have any other questions about how to use the plugin that are not directly related to this issue, please open a separate one.

**Comment by AndrewIngram** [comment]
I think more generally the ability to customise the display of the selected country individual dropdown items would be welcomed. Essentially I'm going to be styling it from scratch to suit my code architecture and brand guidelines, and the decision of whether to use flags and what graphics to use for flags is one i'd like to defer. In my case i'd just like to show the 2 digit country code. Though given that my timeline for building this is within the next 24 hours, i'm probably going to have to fork and modify it anyway.

**Comment by jackocnr** [comment]
@AndrewIngram I know it is related, but please can you open a separate issue for that. And please outline exactly how you think it should work. (and also mention why it's not enough to just override the CSS)

Ok this "separate dial code" feature has now been requested aprx 7 times, so I'm officially open to a pull request, as outlined in [my comment](https://github.com/jackocnr/intl-tel-input/issues/317#issuecomment-156264036) above.

**Comment by jackocnr** [comment]
Ok this was implemented as a new option called `separateDialCode` in v8.2.0. Thanks for your input and let me know if you have any issues/suggestions.

**Comment by craigcosmo** [comment]
+

**Comment by arup872** [comment]
@rockom 
in you css file place below code to hide the country flag.

**ngx-intl-tel-input .iti__flag {
    display: none;
}**
