### ISSUE TITLE
How to change dropdown list

### ISSUE THREAD

**Issue by PineSmokes** [jackocnr/intl-tel-input#326]
I read quite a bit and tried a bunch but failed all over the place.  I just want the dropdown to be vertical like yours.  At the moment mine is horizontal and appears slightly too large with no overflow.  I just want to copy the example but it's not as easy as it seems :)

Any help would be greatly appreciated, thanks

My sample: http://www.golden-wand.com/pages/booking-test.php

**Comment by jackocnr** [comment]
This is just your own CSS interfering with the plugin - you need to find the conflicting rules in your own code fix them (make them more specific to your site, or override them for the plugin).
