### ISSUE TITLE
Submitting formated / international number as POST data

### ISSUE THREAD

**Issue by mik3e** [jackocnr/intl-tel-input#330]
Hi there,

I´ve written a short jQuery script which automatically submits the formated / international number as POST data. Maybe it helps some of you to save some time - Enjoy! :)

English: 
https://www.wolkenkraft.com/en/post/sending-international-formated-phone-number-as-post-data-with-the-international-phone-number-plugin
German: 
https://www.wolkenkraft.com/de/post/international-formatierte-nummer-als-post-daten-uebertragen-mit-dem-international-phone-number-plugin

Best,
Michael

**Comment by jackocnr** [comment]
Thank you for sharing!
