### ISSUE TITLE
how to get this running in wordpress

### ISSUE THREAD

**Issue by zynis** [jackocnr/intl-tel-input#331]
has anyone been able to get this running in wordpress? 

i have a custom registration plugin, added the following

    wp_register_style( 'tel-input-style', ajax_PLUGIN_WP . 'libs/intl-tel-input-master/build/css/intlTelInput.css' );
    wp_register_script('telinput-jquery-script', '//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js' ); 
    wp_enqueue_script('telinput-jquery-script');
    wp_register_script('telinput-script', ajax_PLUGIN_WP . 'libs/intl-tel-input-master/build/js/intlTelInput.min.js' ); 
    wp_enqueue_script('telinput-script');
    wp_register_script('telinput-utils-script', ajax_PLUGIN_WP . 'libs/intl-tel-input-master/lib/libphonenumber/build/utils.js' ); 
    wp_enqueue_script('telinput-utils-script');

and added this into the form:

            <input type="tel" id="mobile-number" name="user_phone_number">
            <script>
                $("#mobile-number").intlTelInput();
                //allowExtensions: true,
                autoFormat: true,
                //autoHideDialCode: false,
                //autoPlaceholder: false,
                //defaultCountry: "auto",
                //geoIpLookup: function(callback) {
                //   $.get('http://ipinfo.io', function() {}, "jsonp").always(function(resp) {
                 //    var countryCode = (resp && resp.country) ? resp.country : "";
                 //    callback(countryCode);
                 //  });
                // },
                //nationalMode: false,
                //numberType: "MOBILE",
                //onlyCountries: ['us', 'gb', 'ch', 'ca', 'do'],
                //preferredCountries: ['cn', 'jp'],
                utilsScript: "lib/libphonenumber/build/utils.js"
            </script>

All I get is a standard input field.

**Comment by zynis** [comment]
okay i think i'm getting somewhere, someone else posted that  the final scrip should be in the head and not body.  however theirs is a bit different and it's difficult for me to see which one I should use:

<script>
$(function() {
$("#mobile-number").intlTelInput({
allowExtensions: true,
autoFormat: false,
autoHideDialCode: false,
autoPlaceholder: false,
defaultCountry: "auto",
ipinfoToken: "yolo",
nationalMode: false,
numberType: "MOBILE",
//onlyCountries: ['us', 'gb', 'ch', 'ca', 'do'],
//preferredCountries: ['cn', 'jp'],
preventInvalidNumbers: true,
utilsScript: "lib/libphonenumber/build/utils.js"
});
});
</script>

**Comment by zynis** [comment]
here is the final code

phoneflagscript.js
"(function( $ ) {
	$(document).ready(function() {
	  $("#mobile-number").intlTelInput({
	    //allowExtensions: false,
	    //autoFormat: false,
	    //autoHideDialCode: false,
	    //autoPlaceholder: false,
	    //defaultCountry: "auto",
        //geoIpLookup: function(callback) {
        //   $.get('http://ipinfo.io', function() {}, "jsonp").always(function(resp) {
        //    var countryCode = (resp && resp.country) ? resp.country : "";
        //    callback(countryCode);
        //  });
        // },
	    //nationalMode: false,
	    //numberType: "MOBILE",
	    //onlyCountries: ['us', 'gb', 'ch', 'ca', 'do'],
	    //preferredCountries: ['cn', 'jp'],
	    //preventInvalidNumbers: true,
	    utilsScript: "/wp-content/plugins/ipl-extended-login/libs/intl-tel-input-master/lib/libphonenumber/build/utils.js"
	  });
  	});
})(jQuery);"

    wp_register_script('telinput-jquery-script', '//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js' ); 
    wp_enqueue_script('telinput-jquery-script');
    wp_register_script('telinput-script', ajax_PLUGIN_WP . 'libs/intl-tel-input-master/build/js/intlTelInput.min.js' ); 
    wp_enqueue_script('telinput-script');
    wp_register_script('telinput-utils-script', ajax_PLUGIN_WP . 'js/phoneflagscript.js' ); 
    wp_enqueue_script('telinput-utils-script');

haven't tested if it actually works on submission as i have a pre-existing form

**Comment by otaviobps** [comment]
Hi! Could you make it work?

Where did you put this:

```
wp_register_script('telinput-jquery-script', '//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js' ); 
wp_enqueue_script('telinput-jquery-script');
wp_register_script('telinput-script', ajax_PLUGIN_WP . 'libs/intl-tel-input-master/build/js/intlTelInput.min.js' ); 
wp_enqueue_script('telinput-script');
wp_register_script('telinput-utils-script', ajax_PLUGIN_WP . 'js/phoneflagscript.js' ); 
wp_enqueue_script('telinput-utils-script');
```

In your functions.php?

Thanks
