### ISSUE TITLE
Tab in dropdown should select country

### ISSUE THREAD

**Issue by nlwillia** [jackocnr/intl-tel-input#332]
Several times while using this widget, I've had focus on the country list, scrolled or typed to a country and hit Tab intending to select the highlighted entry.  But instead of choosing the entry I had reached, it just closed the dropdown and focused the phone input.  I had to go back, find the country again and remember to hit Enter (or click) instead of Tab.

The country list is not a "real" select control, but users will expect it to perform similarly.  In a native select, the Tab behavior is not universal across browsers, but it's consistent enough that I think there's a case to be made for making Tab select.  In Firefox and IE, selecting with the arrow keys visibly changes the item in the control and commits that change when you tab.  However, those browsers don't select when you tab from a mouseover.  Chrome on the other hand doesn't preview a change to the item, but Tab selects the highlighted item whether you arrowed to it or moused over it.

It'd be nice if there were a standardized behavior to track, but in the absence of one, I think that adding select-on-tab is a reasonable compromise that's going to surprise fewer people than the current behavior.  (Previewing the selection is not necessary and would be more complicated to emulate.)

This would be a very minor change.  I will submit a PR for it.

**Comment by jackocnr** [comment]
I just did a check in Chrome, and tab doesn't do anything while a native select is open.

**Comment by nlwillia** [comment]
Chrome's behavior may be platform specific as well.  [Screencast (.mp4) of me tabbing out of a select in Chrome on Win 8.1.](https://drive.google.com/file/d/0B1hZo8ynXmJ3dnM0SXotY3o5cVU/view?usp=sharing)

The main inconsistency I observed between browsers was what happened with mouseover.  With keyboard navigation (arrow keys), it's pretty consistent that Tab selects, and find-as-you-type while not browser-standard is also a keyboard-driven behavior that would make sense if it responded the same way.  Browsers actually seem to be changing the value as you go, but that's a bit more expensive/complicated for intl-tel-input given the associated masking and formatting that happens.  So all I'm proposing is that Tab should do the same thing as Enter.  Thinking bimanually, if I have a hand on the keyboard and mouse, I'm much more likely to hit Tab than Enter.

**Comment by jackocnr** [comment]
So the current behavior is consistent using Chrome on my computer (OSX), but not on yours (Windows 8). This is not enough reason to change it. Can you link to some specification/standard that states how tab is supposed to work with native selects? Or maybe check what some other industry standard is doing, e.g. Bootstrap with their custom selects?

**Comment by nlwillia** [comment]
The standard is [frustratingly silent](https://html.spec.whatwg.org/multipage/forms.html#the-select-element) on a lot of finer points of interaction which is why there is so much variation.  (Let's not even talk about when the change event should fire.)

The terms "select" and "tab" are pretty much impossible from an SEO perspective (the only specific discussion I found was [this issue](https://github.com/brianreavis/selectize.js/pull/258)), but I surveyed some popular JS select controls in the browsers available to me on Windows to see whether they selected the highlighted option on Tab.

| Implementation | Gesture | Firefox | IE | Chrome |
|--------------------------|------------|---------|--------|--------|
| Native | mouseover | No | No | Yes |
| intl-tel-input | mouseover | No | No | No |
| [jQuery UI selectmenu](https://jqueryui.com/selectmenu/) | mouseover | No | No | No |
| [jQuery Mobile selectmenu](https://api.jquerymobile.com/selectmenu/#entry-examples) | mouseover | No | No | Yes |
| [Select2](https://select2.github.io/examples.html) | mouseover | No | No | Yes |
| [Selectize](https://brianreavis.github.io/selectize.js/) | mouseover | [Option](https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md#user-content-options) | Option | Option |
| [ui-bootstrap typeahead](https://angular-ui.github.io/bootstrap/#/typeahead) | mouseover | Yes | Yes | Yes |
| Native | arrow keys | Yes | Yes | Yes |
| intl-tel-input | mouseover | No | No | No |
| jQuery UI selectmenu | arrow keys | Yes | No | No |
| jQuery Mobile selectmenu | arrow keys | Yes | Yes | Yes |
| Select2 | arrow keys | Yes | Yes | Yes |
| Selectize | arrow keys | Option | Option | Option |
| ui-bootstrap typeahead | arrow keys | Yes | Yes | Yes |

It's a bit of a mess.  There's a general division between an option that's moused over and an option that's arrow keyed to, but it's not absolute.  The dividing factor for the arrow gesture tends to be whether the widget paints the top part of the control with the focused option as you go, but it depends on the widget.

For intl-tel-input, compared to the other examples from a consistency standpoint it's debatable.  It doesn't change the country as you arrow through or type-to, but there's a good reason for that as you don't want to be applying random masks to whatever may be in the field already.  However, for find-as-you-type or arrow keys, it's fairly conventional for what you've navigated to to remain chosen when you tab to the next input.  Keeping the mouseover selection is less conventional, but not unprecedented, and in terms of implementation, separating the behavior of the gestures in intl-tel-input would be a fair bit harder.

I think the principle of least surprise is that you honor what the user has chosen (particularly from a long list), but maybe what I'm expecting is influenced by the select behavior I've seen as a Windows user.  All I can say is that this keeps biting me as I test phone numbers in the context of my own application.  I could update my PR to make it a configurable option too, but it's not clear to me from a usage perspective why the "tab-selects" behavior wouldn't always be preferable.

**Comment by jackocnr** [comment]
Thank you very much for doing that research. It is useful now, and it will be a useful reference in the future. A little bit of feedback:

- I'm guessing the second "intl-tel-input" row in your table should have Gesture=arrow keys?
- Your Chrome column should say "Chrome on Windows" because as I have stated: that is not the behavior I see on OSX. If you wanted to add a "Chrome on OSX" column, it would say No for both gestures.
- Your Firefox column can say "Firefox on Windows/OSX" because I just checked and I see the same behavior as you on OSX.
- Safari behaves the same as Chrome (tab doesn't do anything at all while the select dropdown is open).

**Comment by jackocnr** [comment]
My goal with this plugin is for it to be intuitive, which means striving for consistency, and seeing as how we are already consistent with some of the major browsers/platforms (namely, Chrome and Safari on OSX) I don't see any reason to change it at this point.

Also TBH, if there's no established standard, then I would tend to side with OSX over Windows, and Chrome over any other browser.

**Comment by nlwillia** [comment]
I fixed some copypasta and added headings/extrapolation to the table.

Would you allow {{selectOnTab}} as a (non-default) option for people who would prefer to side with Windows over OSX (based on their web analytics)?  It shouldn't be an issue of code size; we're talking maybe half-a-dozen lines here.

**Comment by jackocnr** [comment]
Hmm is there any way to detect if it's windows, and if so, enable it?

**Comment by nlwillia** [comment]
Some sort of User-Agent detection is the only way I'm aware of.  This isn't really something you can feature detect.  I wouldn't recommend trying to bake agent detection into the library itself as it's something of an anti-pattern; however, someone for whom platform specific consistency is very important could leverage an option flag in combination with their own preferred external detection scheme to achieve the desired effect.

**Comment by jackocnr** [comment]
Some thoughts:

- I can't speak for the IE implementation, but the FF implementation on OSX actually visually changes the selected item as you scroll through the list, which is why it makes sense to keep that selection when the user tabs away.
- Your current pull request would select the item even if the user had just done a mouseover, which according to our tables is very uncommon and so would most likely not be the expected behavior.
- There are probably a million of these little papercuts - small UX issues with using a non-native dropdown, and I don't want to bloat out this plugin by trying to fix every issue on every platform.

Again, I thank you for your research and input, and I hope you understand my decision.
