### ISSUE TITLE
Azerbaijan city code should be 2 instead of 3

### ISSUE THREAD

**Issue by oyasumimasen** [jackocnr/intl-tel-input#336]
Hi,

In 2011 in Azerbaijan telephone numbers has changed. After the +994 country code, all city codes became 2 digits instead of 3. In this js it is still 3. Is there any plan for the next update to fix this?

Thanks.

**Comment by jackocnr** [comment]
Hi there, we use [libphonenumber](https://github.com/googlei18n/libphonenumber) for all formatting/validation. I just updated to their latest version (v7.2.2), so you could see if that fixes the problem, else you'll need to file an issue with them.
