### ISSUE TITLE
Non jq use

### ISSUE THREAD

**Issue by abunsen** [jackocnr/intl-tel-input#337]
Do you know if there is a version of this that is not dependent on jq and runs in pure js? or is that yet to be done?

**Comment by jackocnr** [comment]
No official version, but if you search you will find an unofficial version. (There are no plans to add an official version BTW)

**Comment by abunsen** [comment]
@jackocnr can you point me in the right direction by chance? Google searches have not been fruitful.

**Comment by jackocnr** [comment]
I meant search in this repo. There is a link in this pull request: https://github.com/jackocnr/intl-tel-input/pull/301
