### ISSUE TITLE
intl-tel-input input.iti-invalid-key css - minor issue and fix

### ISSUE THREAD

**Issue by joeycrash135** [jackocnr/intl-tel-input#339]
intl-tel-input input.iti-invalid-key{transition:background-color 0;background-color:#FFC7C7} 
throws an error.

the transition:background-color 0 requires an s after the 0, ex: "transition:background-color 0s"

keep up the good work!

**Comment by jackocnr** [comment]
Interesting - it works fine in Chrome, but yes after some reading it seems like it may not be accepted by some browsers. Fixed in v7.0.1. Thanks!
