### ISSUE TITLE
dial code editable

### ISSUE THREAD

**Issue by RevathiArunachalam** [jackocnr/intl-tel-input#345]
If we edit the dial code it shows invalid mobile number. but dial code should be like as cannot editable

**Comment by jackocnr** [comment]
Please can you tell me which initialization options you're using, and give me precise steps to reproduce your issue?

**Comment by RevathiArunachalam** [comment]
I wanna be do as dial code of country will not be editable. Can you help me
?

Thanks for your reply

Revathi A

**Comment by jackocnr** [comment]
If you set `nationalMode

**Comment by RevathiArunachalam** [comment]
if I set 'nationalmode': true or false dial code is editable. I want to set
dial code should not be editable.

Revathi A

**Comment by RevathiArunachalam** [comment]
if I set 'nationalmode': true or false dial code is editable. I want to set
dial code should not be editable.

My options like this,

               autoFormat: true,
              autoHideDialCode: true,
            autoPlaceholder: true,
            defaultCountry: "in",
            nationalMode: true,
            numberType: "MOBILE",

Revathi A

**Comment by jackocnr** [comment]
This is not currently possible, but we are discussing a potential solution here: https://github.com/jackocnr/intl-tel-input/issues/317
