### ISSUE TITLE
Country name and Dialcode position adjustment

### ISSUE THREAD

**Issue by Dineshrajaa** [jackocnr/intl-tel-input#348]
Hi all,
 I am using this plugin in a Jquery Mobile based phonegap app the problem I am facing is in few pages the dialcode and country name dropdown is getting placed below the Telephone number input please see the screenshot.

I am using International Telephone Input v7.1.1,Jquery Mobile 1.4.5

Kindly help me to fix this issue I just only need the mobile number validation even I will be happy if the flag gets hided but still validation works.
![screenshot_2016-01-20-13-30-10](https://cloud.githubusercontent.com/assets/7291567/12443476/12dac92e-bf7e-11e5-8c1c-9e973b1b8046.png)

**Comment by jackocnr** [comment]
On mobile, we use a native `<select>` element for the dropdown, and we hide it using CSS: `opacity: 0;` - perhaps you have some CSS that is overriding this?

**Comment by Dineshrajaa** [comment]
I have written a wrapper class with the following styles is that disturbing the UI?

.ui-custom-form_wp {
    border-radius: 0 !important;
    color: #cacaca !important;
    font-size: 12px !important;
    border-color: #ff !important;
    box-shadow: none;
    -webkit-box-shadow: none;
    padding: 2px;
}

**Comment by jackocnr** [comment]
No it wont be that, but there could easily be some other CSS that is conflicting - you would have to use Chrome devtools to inspect the select element and see what rules are being applied.

**Comment by Dineshrajaa** [comment]
I have fixed it by including the input(Telephone) inside a Jquery Mobile Grid View now that select menu is not being shown I couldn't understand why it is happening if we use this plugin in a input without Grid view.

**Comment by jackocnr** [comment]
All right, well I'm glad you fixed your issue. Hopefully this will be useful for other people who have a similar problem.

**Comment by Dineshrajaa** [comment]
I just tried using the latest code from git now the above mentioned issue doesn't persist but the numbers entered is getting hided by the country flag how could we prevent it @jackocnr ?
![screenshot_2016-02-04-23-12-36](https://cloud.githubusercontent.com/assets/7291567/12824000/08c1082c-cb95-11e5-8595-64b40cf47c5f.png)

**Comment by jackocnr** [comment]
Please only use the latest stable release (v7.1.1). If you're still having trouble, it must be a clash in your CSS. Looks like an issue with padding-right on the input...

**Comment by Dineshrajaa** [comment]
@Jackocnr thanks for the suggestion I solved the issue by adding "padding-left:2em" to the text boxes now everything is fine
