### ISSUE TITLE
Enabled country selection in readonly input

### ISSUE THREAD

**Issue by onyx1337** [jackocnr/intl-tel-input#352]
I think it will be useful if it will be some option to enable readonly mode for input while country dropdown continue working.
Why I need this ? 
In my case I use 2 inputs with intlTelInput . 
First only for country code (that must be change only trough dropdown ) and use this settings 

        nationalMode: false,
        autoHideDialCode: false,

and second for mobile number 

      nationalMode: true,
      autoHideDialCode: false,

So to make first input disabled for editing we need to remove 

     !that.telInput.prop("readonly")

from this lines

			selectedFlag.on("click" + this.ns, function(e) {
					// only intercept this event if we're opening the dropdown
					// else let it bubble up to the top ("click-off-to-close" listener)
					// we cannot just stopPropagation as it may be needed to close another instance
					if (that.countryList.hasClass("hide") && !that.telInput.prop("disabled") && !that.telInput.prop("readonly")) {
						that._showDropdown();
					}
				});

**Comment by sbsurf** [comment]
+1. Would be very useful to use this control as a country + country code dropdown only.

**Comment by jackocnr** [comment]
We're discussing this issue here: https://github.com/jackocnr/intl-tel-input/issues/317

**Comment by sbsurf** [comment]
As long as what's being discussed includes an option to just use this control as a dropdown, with no text input necessary. From the comments on that thread I'm not 100% sure that's part of it.

Thanks!

**Comment by jackocnr** [comment]
I don't understand what you mean by "no text input necessary". Issue 317 will display the country code next to the selected flag, and adapt the plugin so that when it deals with numbers (e.g. formatting/validation), it treats the number as if it had that country code at the beginning.

**Comment by sbsurf** [comment]
Imagine you have a model __company__ with a field __country_code__, or something like that. To let someone select the country/country code from a list you just need a dropdown. Pretty much the dropdown you have created, but without the text part. Make sense?

**Comment by jackocnr** [comment]
Well then yes issue 317 will solve your problem because it will display the selected country code, and the user wont be able to edit it, and you'll be able to use `getSelectedCountryData` to get the value. You can just hide the input as you wont need it.
