### ISSUE TITLE
list all countries

### ISSUE THREAD

**Issue by adeiry** [jackocnr/intl-tel-input#355]
I'm using this plugin, and I want to list all countries with their flags before
My code is:
![mycode](https://cloud.githubusercontent.com/assets/9880387/12549163/0710a908-c364-11e5-9ef3-0c3aeef2bc32.PNG)

I want a result like shown below:
![result](https://cloud.githubusercontent.com/assets/9880387/12549195/3b1f6e5a-c364-11e5-8f78-c152e484bda1.PNG)

but my result looks like: 
![myresult](https://cloud.githubusercontent.com/assets/9880387/12549203/4eaed7bc-c364-11e5-9983-efff218b88ee.PNG)

Please anyone can help me with that issue !!

**Comment by jackocnr** [comment]
You must have a separate div for the flag, and that div must have the class iti-flag and also the country code in lower case.

**Comment by adeiry** [comment]
Thank you very much, it works. This is a perfect plugin !
