### ISSUE TITLE
Implement support for Angular.js

### ISSUE THREAD

**Issue by slavafomin** [jackocnr/intl-tel-input#360]
Hello guys!

First of all, thank you for your great work, I really appreciate it!

I'm using this plugin in Angular.js application and I've created a small integration library to make it compatible with Angular.js framework (two-way data binding, forms, validation, etc). I have two options: 1). release this integration library as a separate library installed via bower/npm, 2). introduce my integration library to this repository as an additional JavaScript-file.

I think the second approach would be better: it will remove extraneous work on my part (no need to support entire repository) and the end users will be able to install everything from one module instead of several ones.

Integration library is really small right now and I will be happy to support it's development along the way.

What do you think?

Cheers!

**Comment by jackocnr** [comment]
Hi @slavafomin, thanks for your work on this. There are so many different [integrations](https://github.com/jackocnr/intl-tel-input/wiki/Integrations) that we can't include them all in the core repo, so feel free to start your own repo and I will add a link on the wiki.

**Comment by slavafomin** [comment]
That makes sense, thank you = )

**Comment by slavafomin** [comment]
I've created a repo, please add it to the list of integration libraries:
https://github.com/betsol/ng-intl-tel-input

Thank you!

**Comment by jackocnr** [comment]
Did you check out the other Angular integrations? There's even one with the exact same name!

**Comment by slavafomin** [comment]
- The [international-phone-number][https://github.com/mareczek/international-phone-number] is broken and author is not responding to the the issues
- The [ng-intl-tel-input][https://github.com/hodgepodgers/ng-intl-tel-input] is better, I didn't knew about it initially. However it's API is kinda strange and it doesn't support all the features of `intl-tel-input`.

In my opinion, my implementation has more features and is better documented. We're going to use it in all projects of our own and will gladly support it along the way. If you are planning some new features which will require integration change or update, please let me know!

Have a great day! Cheers!

**Comment by jackocnr** [comment]
Sounds good! Added!
