### ISSUE TITLE
Listen for country change?

### ISSUE THREAD

**Issue by slavafomin** [jackocnr/intl-tel-input#361]
Hello!

Is there a way to listen for country change event?

I need it in order to implement proper two-way data binding in Angular.js and it seems like normal events are not working on the input field in this case.

Thank you!

**Comment by jackocnr** [comment]
I added an [Events](https://github.com/jackocnr/intl-tel-input#events) section to the readme. You can find what you need in there. Let me know if you have any questions.

**Comment by slavafomin** [comment]
Thank you, this really helps!

However, when country is changed via `$element.intlTelInput('setCountry', 'ru');` the event is not triggered.

**Comment by jackocnr** [comment]
Good point. There are two other occasions when the internal `_setFlag` is called: firstly during initialization (which I don't think should trigger a `countrychange` event), and secondly, it's called from `_updateFlagFromNumber` which itself is called whenever the number changes (on `keyup` and the public method `setNumber`). What do you think about those last two cases? I think I would lean towards triggering the `countrychange` event in those cases.

**Comment by slavafomin** [comment]
I'm using this event in order to update bi-directional binding. For some reason it's not updated automatically when input value changes (when another country is selected), maybe you have some clues about that.

From the higher perspective this event should be triggered every time the country is actually changed from one value to another, i.e. `newCountry != oldCountry`, so your proposition make sense in my opinion.

**Comment by jackocnr** [comment]
I just pushed a fix for this to master. Note there are a lot of breaking changes in master right now - I will do a new major release soon.

**Comment by slavafomin** [comment]
Yeah, I've noticed. That's cool, thanks )
