### ISSUE TITLE
isValidNumber assumes that number is invalid

### ISSUE THREAD

**Issue by slavafomin** [jackocnr/intl-tel-input#362]
Hello!

The `isValidNumber` API method uses `intlTelInputUtils.isValidNumber` function to actually validate the phone number. However, when `utils.js` is not loaded, it [assumes that number is incorrect](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js.ejs#L1070).

I think that library shouldn't make such assumptions without any base. So in case when `utils.js` is not available it should fallback to some other internal validation method, e.g. simple RegExp or just return `null` instead of `false`.

I believe that `null` is more correct result when you can't came up with the actual result.

What do you think? Thank you.

**Comment by jackocnr** [comment]
Yer I guess returning `null` would be an improvement because it wouldn't actually change the current behavior (e.g. if devs are doing `if (isValidNumber) {...} else {...}`), but then devs could add an explicit check for `null` if they wanted. I would welcome a pull request for this change. Thanks.
