### ISSUE TITLE
Validation onkeydown not working on 8.0.1

### ISSUE THREAD

**Issue by ibarral** [jackocnr/intl-tel-input#365]
Hello,

I have installed version 6.4.4, but when I update to the lastest 8.0.1, I lost the auto validation onkeydown (example: on version 6.4.4, if I try to enter a letter on the input field, the field blinks red and no letter is entered).

That feature is lost on newer versions or I missed something?

Thanks!

**Comment by jackocnr** [comment]
Unfortunately we had to remove the `autoFormat` feature in v8.0.0. More info here: https://github.com/jackocnr/intl-tel-input/issues/346
