### ISSUE TITLE
min file has js error

### ISSUE THREAD

**Issue by larsinsd** [jackocnr/intl-tel-input#366]
The min.js file is generating an error for me in Chrome.  The full .js file works fine.

**Comment by jackocnr** [comment]
Yes it's under development. Please use the latest stable release for now.

**Comment by larsinsd** [comment]
Yes - this is with the latest stable release.

The error is:

Uncaught SyntaxError: Unexpected token this
jquery-migrate-1.3.0.js:43

**Comment by jackocnr** [comment]
Are you sure I just checked out v8.0.1 and it works fine for me. And all the tests pass.

**Comment by larsinsd** [comment]
I just downloaded the master.zip file from the link on the text on your main github page.

Lars Helgeson

**Comment by jackocnr** [comment]
My bad - that link was just pointing to the latest code in master, not the latest stable version. I have updated the link.

**Comment by larsinsd** [comment]
Looks great!  Thank you for making this plugin - it's a great UI tool!
