### ISSUE TITLE
preventInvalidNumbers,  formatAsYouType not working

### ISSUE THREAD

**Issue by 5arif** [jackocnr/intl-tel-input#368]
i update to International Telephone Input v8.1.0 but preventInvalidNumbers,  formatAsYouType not working

`var phoneCtrl = $('#elementId');
              var  telInput = phoneCtrl.intlTelInput({
                    preferredCountries: ['id'],
                    preventInvalidNumbers: true,
                    formatAsYouType: true,
                    utilsScript: "scripts/intlTelInput/utils.js"
                });`

i try to find doc about formatAsYouType configuration but i can't find it,.. please help

**Comment by jackocnr** [comment]
Unfortunately `formatAsYouType` (AKA `autoFormat`) was removed in v8.0.0 - see discussion here: https://github.com/jackocnr/intl-tel-input/issues/346
