### ISSUE TITLE
Detect Office Extension 

### ISSUE THREAD

**Issue by seroche** [jackocnr/intl-tel-input#371]
Hello,

I saw you removed the autoFormat and allowExtension methods starting from version 8.0.0. 

What am I supposed to use to replace "allowExtension" parameter. 

Indeed, If i understand correctly a number that was appearing as +852 9999 9999 Ext. 1234 will now appear as +852999999991234. Am I correct? 

If yes, does this mean I need to add new txtboxes to store the extension? Do you plan to modify your control by adding a new textbox next to the phone number for this purpose? We would get two textboxes (one for phone, another one for extension)

Thank you,
Seb

**Comment by jackocnr** [comment]
It depends how you stored the numbers. If you stored them as "+852 9999 9999 ext. 1234" then they will appear exactly like that. How do you have them stored?

**Comment by seroche** [comment]
I parse the phone number and extract the phone and its extension. Both fields are stored in different fields in my DB. 
When the form is open again, i just concat the two strings.

**Comment by jackocnr** [comment]
Ok well when you concatenate them, add " ext. " in the middle and then the plugin will recognize that and format accordingly.

No need for an extra textarea for the extension :)

I suppose there's still the problem of extracting the extension (by default, `getNumber` returns the E.164 standard, which apparently cuts off any extension), so I've re-added the getExtension method, which now uses libphonenumber's implementation, which should work in a lot more situations (so far I have checked and it works for the following extension prefixes: "x", "ext." and "#").

Please let me know if you have any issues!
