### ISSUE TITLE
Demo html's dont work 

### ISSUE THREAD

**Issue by firativerson** [jackocnr/intl-tel-input#374]
Could not get this to work. Even demo htmls dont work on my computer. Is there anything wrong with the latest release?

**Comment by jackocnr** [comment]
I need more information - please follow the template for new issues: exact steps to reproduce, what is expected to happen, what actually happens.

Also, do the examples work on the demo site? http://jackocnr.com/intl-tel-input.html

**Comment by firativerson** [comment]
Everything is working on the demo site. 
I am not experienced on adding plug-ins and javascript. I followed your quick start . Added the css and js files except jquery.min becuse it was already in my project. Changed the png file url's in the css as well. But there were no flags showing, all of the country flags were default gray image. 
Can you make a quick start for dummies? :)

**Comment by jackocnr** [comment]
Are there any errors in the Dev Tools console?

So is anything working? Is the dropdown working? Can you see all the country names?

**Comment by firativerson** [comment]
No dropdown is not showing as well. Thanks a lot for your help. I don't
wanna bug you so I ll ask a friend.

**Comment by jackocnr** [comment]
Right, so the plugin is not initialising. Most likely there will be an error in the Dev Tools console - I will need to know what this is in order to help...

**Comment by firativerson** [comment]
I dont even know what Dev console is. I'm developing a website with html
css and js

**Comment by jackocnr** [comment]
I'm sorry but there's no way for me to help you without this information. I suggest you read up on Chrome Dev Tools. I'm going to close this for now, but feel free to post back here when you have more information.
