### ISSUE TITLE
If the underlying control is not empty, use it as setNumber when initialising. 

### ISSUE THREAD

**Issue by thawkins** [jackocnr/intl-tel-input#376]
This will allow the control to be used to support editing of data in prefilled forms. 

### Steps to reproduce
1.  create a control using an underlying `<input type="text name="phone" id="phone" value="+44 172 234 2345"/>`
2.  initialise the control as an intl-tel-input controls

### Expected behaviour
The control should initialize with the "value" as though setNumber had been called. 

### Actual behaviour
The control is empty 

### Initialisation options
  ```
  $("#phone").intlTelInput({
        initialCountry: "auto",
        geoIpLookup: function(callback) {
            $.get('http://ipinfo.io', function() {}, "jsonp").always(function(resp) {
                var countryCode = (resp && resp.country) ? resp.country : "";
                callback(countryCode);
            });
        },
        utilsScript: "<?php echo $this->asseturl;?>/assets/bootstrap/intl-tel-input/js/utils.js"
    });
    $('#phoneform').submit(function() {
        $('#phoneintl').val($('#phone').intlTelInput("getNumber"));
    });


```

**Comment by jackocnr** [comment]
It seems to work fine for me: http://codepen.io/jackocnr/pen/yedMdM?editors=1010

Does that work ok for you?

FYI you having a missing quote in your HTML.

**Comment by thawkins** [comment]
It's not working on out site, I had to put a form ready function on that
took the value from the underlying control and the did a set number on it
before the user starts interaction, I'm probably missing something.

I have another issue which may be related, ie stuff not getting initialized
properly,  if you look at http://ph.klikable.com/adverts/create  on both a
desktop and a mobile device, it shows the flags on a desktop machine, but
shows a gray box on a mobile device, it works, but the flags are missing. .

I was going to setup chrome remote debugging to see what was going on
tomorrow.

**Comment by thawkins** [comment]
forget the above comment, i found the problem, it was a strange css tag attached to the body that was pushing the coordinate system down. presumably it was interfering with the sprite setup.
