### ISSUE TITLE
Preferred Countries doesn't work

### ISSUE THREAD

**Issue by danielgasser** [jackocnr/intl-tel-input#379]
### Steps to reproduce
1. `<input type="tel" id="mobile-number" name="mobile-number">`
2.  `var fon = $('#mobile-number');`
3.      
```
fon.intlTelInput({
    utilsScript: 'myjsfolder/lib/libphonenumber/build/utils.js',
    defaultCountry: 'ch',
    preferredCountries: ['at', 'de', 'fr', 'en', 'dk', 'hr', 'pl', 'pt']
}); 
```

Also when defining `onlyCountries` as this:
```
fon.intlTelInput({
    utilsScript: 'myjsfolder/lib/libphonenumber/build/utils.js',
    defaultCountry: 'ch',
    onlyCountries: ['at', 'de', 'fr', 'en', 'dk', 'hr', 'pl', 'pt']
}); 
```

The following error occurs: `Uncaught Error: No country data for 'ch'`

### Expected behaviour
the countries defined in `preferredCountries` should appear at the top of the list.

### Actual behaviour
The countries starting with the same letter (S) for Switzerland => `ch` are shown on top

### Initialisation options
```
fon.intlTelInput({
    utilsScript: 'myjsfolder/lib/libphonenumber/build/utils.js',
    defaultCountry: 'ch',
    preferredCountries: ['at', 'de', 'fr', 'en', 'dk', 'hr', 'pl', 'pt']
}); 
```

**Comment by jackocnr** [comment]
Note: `defaultCountry` is now called `initialCountry`

And those `preferredCountries` work for me: http://codepen.io/jackocnr/pen/yehvE?editors=0010

(though note that "en" is not a valid country code)

Could you try and create a Codepen to repro the issue?

**Comment by danielgasser** [comment]
Now it seems to work. Maybe a cache issue. Sry for that. I'll close the issue
