### ISSUE TITLE
Not auto formatting while entering data.

### ISSUE THREAD

**Issue by wcomartin** [jackocnr/intl-tel-input#380]
Example in plnkr https://plnkr.co/edit/UIoh1yhuSBfAIP2WfNlb?p=preview

### Expected behaviour
I expect that while you type a north american number (ex. 8005550932) it would auto format the number to (800) 555-0932

### Actual behaviour
no formatting is applied

### Initialisation options
```javascript
$.fn.intlTelInput.loadUtils("https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/8.4.3/js/utils.js");

$("#phone").intlTelInput({
  preferredCountries: ['us', 'ca', 'mx'],
  initialCountry: 'ca'
});
```

**Comment by wcomartin** [comment]
It looks like the Demos are not formatting either, is this intentional?

**Comment by jackocnr** [comment]
Unfortunately the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346.
