### ISSUE TITLE
Wrong country when input control has a national value

### ISSUE THREAD

**Issue by evorine** [jackocnr/intl-tel-input#382]
If the control has a national phone number and I call the function `intlTelInput`, I got a bugged control. But if I try it with an international number or initialize a control without any value, it works without any problem.
Here is a fiddle to show it: https://jsfiddle.net/bqf07gj5/
I also put the code here to make it easily accessible:

```
<input id="phone1" type="tel" value="" />
<input id="phone2" type="tel" value="+33521461278" />
<input id="phone3" type="tel" value="0521451278" />

<script>
$('#phone1,#phone2,#phone3').intlTelInput({
    defaultCountry: "fr",
    preferredCountries: ['fr']
})
</script>
```

As I'm initializing the phone input with a *default country*, I thought if I register the plugin on a control with a national number, the plugin would assume the number is from that default country.

**Comment by jackocnr** [comment]
A while ago the `defaultCountry` option was renamed to `initialCountry`. This should fix your issue.
