### ISSUE TITLE
Cannot override country list before initialize plugin

### ISSUE THREAD

**Issue by lorenzorad** [jackocnr/intl-tel-input#384]
### Expected behaviour
I'm trying to override the list of countries with a custom set. 

### Actual behaviour
Seems that it's not working, even if I update the array of countries before init the plugin. What's wrong in my code?

As you wrote in the pull request [https://github.com/jackocnr/intl-tel-input/pull/325](https://github.com/jackocnr/intl-tel-input/pull/325), the array should be updated by reference:

```javascript
  var pluginCountries = $.fn.intlTelInput.getCountryData();
  pluginCountries = myCountries;
  $("#phone").intlTelInput();
```

Here is a demo:
https://jsfiddle.net/lorestar/pjLr9q49/3/

### Initialisation options
no custom options

### Versions
Tried with 8.4.3 and 8.4.5

**Comment by jackocnr** [comment]
This is not how JavaScript works - objects are stored by reference, so looking at your code: the first line creates a new variable which points to the plugin's country data, then in the second line you change that variable to point to a different object, which doesn't do anything to change the plugin's data.

You need to iterate over the country data object you get back from `getCountryData` and modify that object, or alternatively, remove all of the existing countries and add all of your own, but the key is that you need to manipulate the object you get back from `getCountryData`. Here's an example: http://jackocnr.com/node_modules/intl-tel-input/examples/gen/modify-country-data.html

**Comment by lorenzorad** [comment]
Thanks, you are perfectly right. I was pointing to the wrong reference, the reference of array `myCoutries`.  Thus I emptied the original array and inserted my list of countries in its reference:

```javascript
var pluginCountries = $.fn.intlTelInput.getCountryData();
pluginCountries.length = 0;
  
$.each(myCountries, function(i, country) {
  pluginCountries.push(country);
});
```

I have updated the jsFiddle to show my solution:
https://jsfiddle.net/lorestar/pjLr9q49/5/

Thanks

**Comment by jackocnr** [comment]
Great I'm glad you got it working. Out of interest, can I ask why you want to use your own country data?

One of the reasons we got rid of the `setCountryData` static method was because it's quite complicated to provide your own country data - you have to provide the name, international dial code, and [iso2 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2), and then also the priority (if two countries have the same international dial code e.g. USA and Canada) as well as any national dial codes - see this comment in data.js: https://github.com/jackocnr/intl-tel-input/blob/master/src/js/data.js#L36.

**Comment by lorenzorad** [comment]
I need to filter some countries and, more important, I want to show the label near the prefix translated in 1 language only (the locale language). I mean, instead of:

```
var allCountries = [
  [
    "Afghanistan (‫افغانستان‬‎)",
    "af",
    "93"
  ], [
    "Israel (‫ישראל‬‎)",
    "il",
    "972"
  ], [
    "Italy (Italia)",
    "it",
    "39",
    0
  ],
...
```


For english locales I would like to have this kind of data:
```
var allCountries = [
  [
    "Afghanistan",
    "af",
    "93"
  ], [
    "Israel",
    "il",
    "972"
  ], [
    "Italy",
    "it",
    "39",
    0
  ],
...
```

And for Italian locales (e.g.: it_IT, it_CH) I would like to have:
```
var allCountries = [
  [
    "Afghanistan", // "Afghanistan" in Italian is the same of English
    "af",
    "93"
  ], [
    "Israele", // "Israel" in Italian
    "il",
    "972"
  ], [
    "Italia",
    "it",
    "39", 
    0
  ],
...
```

**Comment by jackocnr** [comment]
Ok thanks for letting me know. In that case I think the best thing to do is to get the country data using `getCountryData` then iterate over that array, and update the name for the country using your data.

You can do this anyway you like, but the most efficient way would be to have your data stored as an object, with a different property for each country, where the country code (e.g. "af") is the key and the country name is the value e.g.
```js
var yourCountryData = {
    "il": "Israele",
    "it": "Italia",
    // etc...
};
```
Then you could do something like this:
```js
var countryData = $.fn.intlTelInput.getCountryData();
for (var i = 0; i < countryData.length; i++) {
    var countryCode = countryData[i].iso2;
    countryData[i].name = yourCountryData[countryCode];
}
```
