### ISSUE TITLE
Canadian phone format incorrect

### ISSUE THREAD

**Issue by JasonMrX** [jackocnr/intl-tel-input#385]
This issue happens only when separateDialCode option is on

### Steps to reproduce
1.  select canada(+1)
1.  input 519497xxxx(a Canadian phone number)
2.  save after internationalization => +1519497xxxx
3.  formatOnInit

### Expected behaviour
Should be formatted to 519 497 xxxx

### Actual behaviour
Formatted to 497 xxxx (3 digits NPA is cut off)
Place holder format is also problematic

### Initialisation options
formatOnInit: true,
separateDialCode: true,
utilsScript: "path/to/utils.js"

**Comment by jackocnr** [comment]
Thanks for this. I can confirm two bugs when `separateDialCode` is enabled:

1. Setting `initialCountry` to `"ca"` will show an invalid Canadian placeholder (234-5678)
2. Having the input's initial value as `"+15194971234"` will display an invalid number (497-1234)

**Comment by JasonMrX** [comment]
I am still digging into the code. Seems to be an issue related to the areaCode. First time raising issue in Github.. May I try to fix this and make a pull request?

**Comment by jackocnr** [comment]
Don't worry I'm on it.

**Comment by jackocnr** [comment]
Should be fixed in v8.4.6. Let me know if you have any other issues.

Thanks again.

**Comment by JasonMrX** [comment]
That's fast! Works perfectly. Thanks.
