### ISSUE TITLE
dropdown not working on mobile browser

### ISSUE THREAD

**Issue by maverickpogi** [jackocnr/intl-tel-input#386]
i have followed getting started. im using v7.1.1
it works on web, but in mobile, it just displays the plugin but when i click on it, the dropdown does not display .please help

**Comment by jackocnr** [comment]
Please use the latest version and see if that helps.

**Comment by maverickpogi** [comment]
now it works! thanks. mwah

**Comment by dangvp2021** [comment]
i have followed getting started. im using v17.0.13 and i the dropdown flag on real mobile device it not working. Although in devtool and web dropdown works perfectly

**Comment by furkankaraca96** [comment]
> Hello @jackocnr, i have followed getting started, im using v17.0.13 and the dropdown flag on real mobile device and devtool on firefox it not working. Although in devtool on google chorme and website dropdown works perfectly. Please help :((

Were you able to solve it? I have the same problem. Dropdown does not work on iPhone Safari (haven't tried for android)

**Comment by SergiuszR** [comment]
@furkankaraca96 I managed to solve this problem. I updated the library to the latest version, but this had no effect. I slightly don't understand the approach of the library's creator, who specifically for the mobile version creates a completely separate logic that links the dropdown simply to the body element (which has its own class for mobile...). But oh well. 
The way I managed to solve the problem:

1. Waiting for the document to be ready before executing the code.
2. attaches the click event handler to any form element that matches the specified class selectors: ".iti.iti--allow-dropdown.iti--separate-dial-code.iti--show-flags". (I use it in a form/modal)
3. inside the click event handler function, checks if the window width is less than 992 pixels.
4. if the width of the window is less than 992 pixels, finds an element with class ".iti.iti--container".
5. checks if the container element exists and is not already a sub element of the clicked element.
6. if the container element exists and is not a sub element of the clicked element, sets the CSS properties for the container (top, left, position and height).
7. appends the container element as a second child of the clicked element.

I hope this helps 😄

**Comment by frank-hexgit** [comment]
How I solved this problem is just passing in `useFullscreenPopup: false,` into the **options**. 

Here's the relevant documentation
**useFullscreenPopup**
**Type**: Boolean **Default**: true on mobile devices, false otherwise.

So just disabling this behavior would be the simplest fix. It worked quite well in my case.
