### ISSUE TITLE
(Suggestion) Include a clear (x) button

### ISSUE THREAD

**Issue by szukaiLee** [jackocnr/intl-tel-input#389]
Include a clear button to clear the field for non compulsory field.

**Comment by jackocnr** [comment]
This is not specific to this plugin. There must already be plugins that add a clear button to any input - you should find and use one of those.

**Comment by szukaiLee** [comment]
I mean to clear the drop down. Maybe put a placeholder for it after clear the drop down

**Comment by jackocnr** [comment]
What do you mean by "clear the dropdown"? It doesn't have an empty state. By default it has a country selected.
