### ISSUE TITLE
isValidNumber() API function returns positive result for incorrect phone numbers

### ISSUE THREAD

**Issue by slavafomin** [jackocnr/intl-tel-input#390]
Hello!

It looks like `isValidNumber()` returns positive result for incorrect phone numbers. For example, when I enter the following value: `фывфывфывфывфыв+79031234567фывфывфывфывфыв` it returns `true`.

I'm using default options with `utils.js`.

However, the `getNumber()` function returns the correct value. Looks like it's trimming the input from both sides before processing it or something.

**Comment by jackocnr** [comment]
It seems libphonenumber thinks it's a valid number - you can try it on their demo page: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

If you think this is a bug, you should [file it with them](https://github.com/googlei18n/libphonenumber).
