### ISSUE TITLE
Expose low-level phone number validation function?

### ISSUE THREAD

**Issue by slavafomin** [jackocnr/intl-tel-input#391]
Hello!

As you know, I'm developing an [integration module](https://github.com/betsol/ng-intl-tel-input) between this plugin and Angular.js.

However, [I've been asked](https://github.com/betsol/ng-intl-tel-input/issues/5) to implement support for legacy version of Angular.js, which has some limitations and a certain expected workflow. To be exact, it uses array of formatting functions that are called internally before value is actually propagated from Angular controller code to the underlying input element. And during the formatter execution we have to call `isValidNumber()` API function in order to validate the input. The problem is that the concrete value is not yet propagated to the input element, and your plugin doesn't have an actual value to operate on. I'm asking you to introduce and expose some low-level API function that will accept an input value, validate it using `utils.js` and return the result.

Right now, I've introduced a workaround that updates the value manually then calls the `isValidNumber()` and then changes the value back to the original value. But it's somewhat of an ugly hack and I will prefer to remove it. Of course, I can call `utils.js` directly myself, but I don't want to pull this low-level details in the integration library, cause it will create a hard dependency.

Will you be able to expose this functionality please? Thank you!

**Comment by jackocnr** [comment]
Hi there,

I don't understand why you don't want to just call `formatNumber` from [utils.js](https://github.com/jackocnr/intl-tel-input/wiki/utils.js) directly? Seems to be exactly what you need.

If you're worried about things changing - either they will change in utils.js or in the main plugin - either way you will have to update the call on your end.

I'll make sure to do a major release if I do any breaking changes in utils.js, so that should be a heads up.

Does that make sense?

**Comment by slavafomin** [comment]
That was exactly my point. If you would extract all validation logic into a separate function available in the API, I will be able to code against it, and you will be able to change the validation however you want without breaking any loose-dependencies and without doing a major version release. This is a contract between `intl-tel-input` and other third-party code that depends on it. That will make both of our lives (and other developers probably) more easy and predictable.

We could add an optional argument to the `isValidNumber (value: string): boolean` function to preserve the backward-compatibility. If value is passed, it will be used, if not, the value will be obtained from the element directly.

I think that will be a pretty clean and robust solution.

**Comment by jackocnr** [comment]
I see the utils.js functions as being part of the API, and if I want to change the internals of those functions I still can without breaking anything. And I'm happy to do a major release if I end up wanting to change the utils.js API.
