### ISSUE TITLE
How to implement autoFormat into the last release or downloading the last release before it removed

### ISSUE THREAD

**Issue by Rezker** [jackocnr/intl-tel-input#392]
Hi,
I want know how to implement AutoFormat into the actual release ?
If i can't do it, where i can find the last release supporting this option ?

Thank's.

**Comment by jackocnr** [comment]
As per the new issue template:

IMPORTANT: please note that the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

**Comment by Rezker** [comment]
I know it's removed.

You didnt understood my question, anyway thank's.
