### ISSUE TITLE
Wrap up this plugin into a ruby gem

### ISSUE THREAD

**Issue by JasonMrX** [jackocnr/intl-tel-input#395]
Hi Jack,

I am really impressed by your plugin and I really want to spread it among the Rails community. Therefore I wrapped it up as a [ruby gem](https://github.com/GoWang/intl_tel_input_rails), integrating the plugin into the Rails asset pipeline, so that people can simply bundle the gem without worrying about how to install and config the plugin. I was hoping if we could put the above link in README so that Rails users can easily find the gem and use it. I will keep the gem up to date with your newest release.

Have a good day

Jason

**Comment by ispyropoulos** [comment]
Hello @JasonMrX. This seems to me a little bit *non-standard*, to put it politely. There's no indication that the [intl-tel-input-rails](https://github.com/ispyropoulos/intl-tel-input-rails) gem is no longer maintained. Did you try sending a pull request with your suggested updates first?

I also noticed that you already published the gem, without even attempting to contribute to the repo that has 17.5K downloads and has been around for some time. What about all those people that won't be getting these updates, until they realise that there's another gem in play, with no obvious reason?

**Comment by JasonMrX** [comment]
Hi @ispyropoulos, First I would like to apologize for my non-standard way of handling this issue. I am new to this community and I am very grateful for you kind advice. I will find a way to un-publish the gem if it is necessary.

I was also wondering if I could open up a pull requests to update the plugins in your gem?

Jason

**Comment by varun-raj** [comment]
@JasonMrX I should appreciate for your efforts about building the gem for rails. I don't there is nothing wrong about writing a gem for the same plugin multiple times on your own way. There are popular projects which also has multiple implementations, so nothing wrong about your work and keep pushing fixes :)

**Comment by JasonMrX** [comment]
@varun-raj thank you for your kind words of encouragement!
