### ISSUE TITLE
initialCountry do not work for me

### ISSUE THREAD

**Issue by onigetoc** [jackocnr/intl-tel-input#396]
initialCountry do not work for me.
But If i go to ipinfo.io it give me the right infos.
http://jackocnr.com/node_modules/intl-tel-input/examples/gen/default-country-ip.html

**Comment by onigetoc** [comment]
Ok, i just discover that my Chrome extension uBlock Origin also block ipinfo.io and Google analytics.
first time i see something like this.

**Comment by jackocnr** [comment]
There's nothing we can do if the user blocks it. That's why we use the `always` handler in that demo page you linked to - because it will fire even if the request fails.
