### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'valueGet.call') issue

### ISSUE THREAD

**Issue by ottomen** [jackocnr/intl-tel-input#397]
Hi.

I have an error only at mobile browser (Chrome or other kind of browser). On desktop all seemed to be all right. 

I invoke plugin in this way 

```
$('input[name="phone"]').intlTelInput({
 'separateDialCode': true,
 'preferredCountries': [ "ru", "ua" ],
});
```

Console writes this stuff "TypeError: undefined is not an object (evaluating 'valueGet.call')".

**Comment by jackocnr** [comment]
Can you please setup a codepen to isolate the problem, and tell me which device you're using, which version of Android, and which version of Chrome for Android?

**Comment by ottomen** [comment]
I figured out what went wrong. I'm using https://github.com/RobinHerbots/jquery.inputmask plugin, and the combination of this plugin with your intlTel is breaking the js on the mobile devices.
