### ISSUE TITLE
Number dialcode

### ISSUE THREAD

**Issue by AKFourSeven** [jackocnr/intl-tel-input#398]
Hi,

Love the plug-in it is very easy to use and simple. I had a question though.
I need to make sure that the number entered in the input is of the correct country (corresponds to the current locale).
However I did not see any public of the type getDialCode, is there a way to achieve that or should I find some sort of trick to achieve this ?

Thanks,
AK

**Comment by jackocnr** [comment]
I'm sorry I don't understand - can you explain with an example?

**Comment by AKFourSeven** [comment]
Okay I will try to make this clearer with an example.
Let's say that my locale, on my website, is "FR".
I have a users on this website that can change the language of the website (it thus changes the locale). 
There is a form with the your plug-in and a user enters an american number, with the dial code (+1xxx).
What I would like to do is to get the dial code part of the number the user entered and check that it is the correct one for the locale of the website.

Does this sound clearer ?

**Comment by jackocnr** [comment]
You can use `getSelectedCountryData`.
