### ISSUE TITLE
Country code doesn't get updated if the last action is switching the dropdown country code

### ISSUE THREAD

**Issue by awei1001** [jackocnr/intl-tel-input#400]
IMPORTANT: please note that the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

### Steps to reproduce
1.  Select a country code that isn't yours (e.g., France +33).
2.  Enter your phone number (e.g., ###-###-####).
3.  Correct the country code to what is yours (e.g., US +1).
4. Be sure to not edit your phone number from here. Doing so will properly update the country code.

### Expected behaviour
The expected behavior is for the country code to be updated (e.g., to US +1), and once this call is made:
`phone = input.intlTelInput("getNumber");` it should send over phone = +1##########.

### Actual behaviour
The actual behavior is that the incorrect country code gets pushed through (e.g., phone = +33##########).

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries
	input.intlTelInput({
		utilsScript: '/html/assets/utils.js',
		preferredCountries: ['us', 'fr', 'gb'],
		autoPlaceholder: false,
		autoHideDialCode: false,
		nationalMode: false,
		formatOnit: true,
		separateDialCode: true,
	});

Is this a bug, or am I missing something?

**Comment by jackocnr** [comment]
I cannot reproduce: http://codepen.io/jackocnr/pen/pyLxbo

Can you fork that codepen and try to get it to reproduce the error? Have I done anything differently to you?

**Comment by awei1001** [comment]
Thanks so much for sending that over! That helped me debug my code. Apologies for my mistake!
