### ISSUE TITLE
autoHideDialCode only works on blur, but should also work on form submit

### ISSUE THREAD

**Issue by ehmicky** [jackocnr/intl-tel-input#401]
The option `autoHideDialCode` empties the input value on blur if it is invalid (e.g. if it is `+46`). However if the input is focused and the form is submitted without blurring (e.g. by hitting `Enter` key), the value is not emptied.

### Steps to reproduce
0.  Put the intl-tel-input widget inside a form
1.  Insert `+46125`
2.  Blur
2.  Edit to `+46`. Do not blur
3.  Submit form by hitting `Enter` key

### Expected behaviour
The input value should be emptied.

### Actual behaviour
The input value is not emptied.

### Initialisation options
Using default options.

### Possible fix
https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js.ejs#L552
The event handler here should be run not only on blur, but also `this.telInput.prop("form").on("submit")`, if form exists.

**Comment by jackocnr** [comment]
Good idea - I would welcome a pull request that does this!

**Comment by ehmicky** [comment]
Added a pull request at #404

**Comment by jackocnr** [comment]
Released in v8.5.0 thank you!
