### ISSUE TITLE
Do not load utils script

### ISSUE THREAD

**Issue by ostap0207** [jackocnr/intl-tel-input#402]
Right now if you specify the utilsScript it's separately loaded by main script, even if it's already a part of my application. This makes my application to be loaded twice.

### Expected behaviour
Would like to have an option to don't load a script if needed.

**Comment by jackocnr** [comment]
If you've already loaded utils.js using the `utilsScript` option, then the plugin keeps track of this internally (in `$.fn.intlTelInput.loadedUtilsScript`). If you're including utils.js manually in your build process (etc) then just don't set the `utilsScript` option at runtime.

Does that solve your problem?

**Comment by ostap0207** [comment]
Yes, thanks. Without `utilsScript` worked as expected.
