### ISSUE TITLE
setNumber includes country code even if separateDialCode enabled

### ISSUE THREAD

**Issue by aitormagan** [jackocnr/intl-tel-input#403]
`setNumber` is not working properly when `separateDialCode` is enabled.

### Steps to reproduce
1.  Enable `separateDialCode`
2.  Use `setNumber` to set a number (e.g. `+34600000000`)
3.  The country code will appear in both the input and next to the flag. As a consequence, the final number is not valid as the country code is repeated. 

### Expected behaviour
The number should only appear next to the flag.

### Actual behaviour
The number appears next to the flag and in the input.

### Initialisation options
separateDialCode: true
utilsScript: /path/to/utils.js

BTW: I think It will be worth hiding the country code when using `setNumber` even if `separateDialCode` is disabled. Otherwise, the user get the same information twice (the flag and the country code in the input).

**Comment by jackocnr** [comment]
I cannot reproduce: http://codepen.io/jackocnr/pen/JXZdNb

Please can you fork that codepen and find a way to reproduce the issue you're seeing?

**Comment by aitormagan** [comment]
You are right! The function is working perfectly! It is a problem with the AngularJS library that I have used to integrate this awesome library in my project! I am sorry! Thank you so much! ;)
