### ISSUE TITLE
Png Flags to Svg Flags

### ISSUE THREAD

**Issue by Suriv** [jackocnr/intl-tel-input#406]
Hello

One for that images have better support and for the different resolutions , is to pass the pngs to svgs .

svg with flags in more countries
https://lipis.github.io/flag-icon-css/

The only thing that would be nice doing so in a sprite as png

https://github.com/jkphl/svg-sprite

**Comment by jackocnr** [comment]
I would love to use SVGs instead of PNGs, but the last time we tried it the filesize was too big. There's some discussion here: https://github.com/jackocnr/intl-tel-input/issues/65

I'd love to be proven wrong tho, if you'd like to give it a shot?

**Comment by Suriv** [comment]
and svgz?

Example 97 flags in sprite with svg-sprite: 3,3MB
Open in Inkscape and save file svgz :1,1 MB

I am trying to create a horizontal sprite
[Archivo comprimido.zip](https://github.com/jackocnr/intl-tel-input/files/228902/Archivo.comprimido.zip)

**Comment by jackocnr** [comment]
Even 1.1MB is 6x larger than our current retina PNG sprite (181KB): https://github.com/jackocnr/intl-tel-input/blob/master/build/img/flags%402x.png

**Comment by Suriv** [comment]
It is correct

But SVG is a single file for current and future resolutions

While the PNG have to generate a sprite for each resolution, in this case you have two, but for new'd have to generate another sprite png.

But as I've said before, I am investigating to try to make this sprite of 92 flags and reduce the weight of a manually or try to remove this increase makes you svg sprite generator.

**Comment by jackocnr** [comment]
If you can find a way to get the SVG sprite filesize down to something similar to our current retina PNG sprite then I will gladly make the change, but otherwise 1.1MB is just too big for this little plugin!
