### ISSUE TITLE
Incorrect display for russian phone numbers

### ISSUE THREAD

**Issue by rxd2** [jackocnr/intl-tel-input#409]
Steps to reproduce:  Create an input field with a value (922) 555-1234 and run intlTelInput
Expected outcome: 922 555-12-34
Actual outcome: 8 (922) 555-12-34
When dialing internationally, prefix 8 should not be used for Russian numbers

Version 8.5.0
Options: nationalMode: true,  autoPlaceholder: false,  separateDialCode: true

**Comment by jackocnr** [comment]
We use libphonenumber for formatting, and I've just checked on their [demo page](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) and if you enter that number and the country code "ru" for Russia, then the national format indeed has the added 8.

So feel free to [open an issue with them](https://github.com/googlei18n/libphonenumber).

Also see the option `formatOnInit` to stop the plugin from formatting the number during initialisation as a workaround for now!

**Comment by rxd2** [comment]
Jack, the issue is in _updateValFromNumber function. If separateDialCode is true, than intlTelInputUtils.numberFormat.INTERNATIONAL should be used, not intlTelInputUtils.numberFormat.NATIONAL

**Comment by jackocnr** [comment]
Ooops, you are right, thank you! I was looking at the number with national formatting instead of the one with international formatting. Fixed in v8.5.2.

**Comment by rxd2** [comment]
OK, thanks!
