### ISSUE TITLE
tabindex does not work properly

### ISSUE THREAD

**Issue by PerchHero20** [jackocnr/intl-tel-input#415]
Hi 
I have notice that still the tabindex order does not work as expected and I was wondering if there is a way to make this work without hacking the js file.
Right now if I se tab index to "selected-flag" when this div becomes selected, I make a selection from the list and I lock it with enter, then tabindex stopes working tab does not go to the next field. If I though open the dropdown list and while it is open I click tab, It goes to the next field.
I have also tried to add tabindex to ul country-list this didnt work at all it didnt do anything.
Could you please provide any hints fixes about this?

**Comment by jackocnr** [comment]
Hi there. You should not need to set tab index yourself - the plugin does it for you. Does it work for you on the [demo page](http://jackocnr.com/intl-tel-input.html)? If not please can you provide clear steps to reproduce the problem?

**Comment by PerchHero20** [comment]
Hi,

Yes I believe it works on the demo page I will try to reproduce it on mine using demo page as guide thanks!
