### ISSUE TITLE
ISD code missing for Abkhazia country

### ISSUE THREAD

**Issue by ramansharma89** [jackocnr/intl-tel-input#417]
Hi, Can you please add the country code for Abkhazia country. It's +7 840
Currently if we try to enter "+7 840" it automatically picks up Rusia's ISD code which is "+7"

It would be a big help if you can fix it.

Thanks,
Raman.

**Comment by jackocnr** [comment]
Hi there, this plugin uses [iso alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes under the hood, and unfortunately Abkhazia doesn't seem to be listed, so there's no way to add it right now sorry.
