### ISSUE TITLE
Possibly GTM (Google Tag Manager) conflict

### ISSUE THREAD

**Issue by christianesperar** [jackocnr/intl-tel-input#418]
1.  Add GTM to a page 
2. Execute scripts $(your_elements).intlTelInput();
3. $(...).intlTelInput is not a function error on console will show

**Comment by christianesperar** [comment]
Is dataLayer name also use in this plugin? When I change it to other name this plugin works well.

 <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MGRC8L"
      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
      <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='**dataLayer**'?'&l='+l:'';j.async=true;j.src=
      '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','**dataLayer**','GTM-XXXXXX');</script>

**Comment by jackocnr** [comment]
No this plugin doesn't define `dataLayer` - you can check by searching the source code!

I can't see any reason why this plugin would not be compatible with GTM.

Are you sure you're including jQuery and then this plugin in the page before you initialise it?

**Comment by christianesperar** [comment]
Hi, thanks for the feedback, just found out that the problem is on the gtm side on which they add jquery scripts.
