### ISSUE TITLE
number validation seems to fail

### ISSUE THREAD

**Issue by al404** [jackocnr/intl-tel-input#420]
### Steps to reproduce
1.  i open this example page linked in readme page: http://jackocnr.com/node_modules/intl-tel-input/examples/gen/national-mode.html
2.  i enter "test" on Safari on latest OS X version, i also try on latest firefox
3.  i get International: test, i aspect Please enter a number below since is not even a number

### Expected behavior
get an error message

### Actual behavior
the number seems to be OK even is a string

### Initialisation options
i didn't change the example page

**Comment by jackocnr** [comment]
That example just uses `getNumber` which will try to format the number, but if it can't it just returns the current value. If you want to validate the number you need to use `isValidNumber`.
