### ISSUE TITLE
BUG: Bootstrap input groups

### ISSUE THREAD

**Issue by pjebs** [jackocnr/intl-tel-input#424]
I have an input in a bootstrap input-group.
Your solution: Adding: `.intl-tel-input {display: table-cell;}` to css didn't seem to work.
It looks fine BUT when you click on the box and it gets the focus, the flags (and dialcode in separate dialcode mode) disappear.

**Comment by pjebs** [comment]
They reappear once the input loses focus.

**Comment by jackocnr** [comment]
Would you be able to setup a codepen to reproduce the problem?

**Comment by pjebs** [comment]
I couldn't get codepen to work properly so I will write my code here:

**Normal (Blur)**

![screen shot 2016-06-09 at 12 30 12 pm](https://cloud.githubusercontent.com/assets/5377970/15917232/23d17cb2-2e3e-11e6-96cd-aada496d5ba6.png)


**Dropdown**
![screen shot 2016-06-09 at 12 30 18 pm](https://cloud.githubusercontent.com/assets/5377970/15917230/16a2323e-2e3e-11e6-94f3-cdbf554df340.png)

**When textbox has the focus**
![screen shot 2016-06-09 at 12 30 30 pm](https://cloud.githubusercontent.com/assets/5377970/15917227/0d8626ba-2e3e-11e6-94e5-5100e13f8737.png)

**Comment by pjebs** [comment]
You can see that when the textbox has focus, the flags disappear.

**Comment by pjebs** [comment]
The code is using React so here is the render function:

**Render function:**
```
<ul className="task-list">
	<li>
		<a href="javascript:void(0)" onClick={this.remove} className="task-close"><i className="fa fa-times"></i></a>
    	<div className="form-group">
		    <div>
		        <div className="input-group">
		        	<input type="tel" onChange={this.validate} ref="input" className="form-control" placeholder={placeholderText} />
		            <span className="input-group-addon"><i className={image}></i></span>
		        </div>
		        <span className="help-block">{helpText}</span>
		    </div>
		</div>
	</li>
</ul>
```

**componentDidMount function:**
```
$(this.refs.input).intlTelInput({autoHideDialCode: false, preferredCountries:['au'], nationalMode: false, separateDialCode: false});
$('.intl-tel-input').css({display: 'table-cell'});
```

**Comment by pjebs** [comment]
I tried your line of code directly in the CSS file as well as:

`$('.intl-tel-input').css({display: 'table-cell'});`

**Comment by jackocnr** [comment]
I'm sorry but I can't help you debug this without a live example. Either codepen, or https://hyperdev.com or just hosting your website yourself somewhere?

**Comment by jackocnr** [comment]
BTW here is a working example with the table-cell fix: http://codepen.io/jackocnr/pen/EyPXed

**Comment by pjebs** [comment]
Very strange. In your working example it is not working. It suffers from same thing

**Comment by pjebs** [comment]
Maybe onFocus, you can increase the flag's zIndex and reset it again onBlur.

**Comment by jackocnr** [comment]
A ha! I updated the codepen with a z-index fix.
