### ISSUE TITLE
preventInvalidNumbers option is not working

### ISSUE THREAD

**Issue by vmore2015** [jackocnr/intl-tel-input#430]
IMPORTANT: please note that the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

Hi i have set 'preventInvalidNumbers: true' but still input allow me to enter alphabet in to the input.

**Comment by jackocnr** [comment]
This feature has been removed for the reasons listed here: https://github.com/jackocnr/intl-tel-input/issues/79#issuecomment-121799307

**Comment by vmore2015** [comment]
Hi Jackocnr,

Thanks for reply.

Thanks & Regards,
Vivek More
