### ISSUE TITLE
Implementation intl-tel-input  is broken after migrating to angular 1.5 version

### ISSUE THREAD

**Issue by smohanty0714** [jackocnr/intl-tel-input#431]
IMPORTANT: please note that the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

### Steps to reproduce
1.  After migrating to the angular 1.5 version the UI has been broken.
2.  
3.  

### Expected behaviour
the UI should not  broke

### Actual behaviour
UI broken

### Initialisation options
<input class="form-control" type="text"
                     name="phoneNumber"
                     autocomplete="off"
                     data-default-country="{{user.location.country.code}}"
                     ng-intl-tel-input
                     ng-model="user.location.phone" required>
![error_1](https://cloud.githubusercontent.com/assets/7791355/16091333/c8041e4a-3350-11e6-94df-5570e5924145.PNG)

**Comment by jackocnr** [comment]
This plugin has nothing to do with Angular. Perhaps you're using one of the [Angular integration projects](https://github.com/jackocnr/intl-tel-input/wiki/Integrations)?

**Comment by smohanty0714** [comment]
thank you @jackocnr  sorry to bother you .

regards,
Suve

**Comment by kotmatpockuh** [comment]
@jackocnr  utils.js is invalid, when using angular 1.5
@smohanty0714  how do you fixed it?
