### ISSUE TITLE
Typescript types definition support

### ISSUE THREAD

**Issue by fdnhkj** [jackocnr/intl-tel-input#433]
Hello!

This issue just to let you know I added Typescript definition file for this plugin in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo (see [merged PR](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/30bc34f9fc9e8587ae76081d30f94a5c3e16b28a)).

![intltelinput](https://cloud.githubusercontent.com/assets/5569608/16176114/5c2c9a96-3605-11e6-9803-21e0cacc1dc8.gif)

I just did a [PR](https://github.com/jackocnr/intl-tel-input/pull/432) to intl-tel-input repo to add this information to README.md .

**Comment by jackocnr** [comment]
Hi there! Thanks for putting this together. I don't understand your video example though. The second line doesn't make sense - it should start `$.fn.intlTelInput`, right?

**Comment by fdnhkj** [comment]
Indeed it doesn't look correct. I'll have a look later this week, thanks for your comment :)

**Comment by fdnhkj** [comment]
Fixed it - see [merged PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9792).
##### Note
$.fn.intlTelInput static methods are not typed because of jquery typings. 
As $.fn has type `any` ([jquery/jquery.d.ts#L958](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L958)), we cannot define types for those methods.

**Comment by jackocnr** [comment]
Thanks! So now I'm wondering - without static method support, what exactly does this do? Presumably it doesn't support the public methods e.g. `setNumber` because they are called with the method name as a string e.g. `$(".phone").intlTelInput("setNumber", "+44123");`

**Comment by fdnhkj** [comment]
#### Defines intlTelInput method in JQuery instance
Without the definition file, intlTelInput method would not be available in JQuery instances. It would give following error :
<img width="588" alt="capture d ecran 2016-06-25 a 08 22 06" src="https://cloud.githubusercontent.com/assets/5569608/16355119/f433eb30-3aad-11e6-936c-b38ff0f44df3.png">

#### Defines different signatures of the public API (parameters types, return type)
In that file, I defined the methods listed in the public API with correct param type and return type.
If you call i.e. `intlTelInput(options?: IntlTelInput.Options): JQueryDeferred<any>;`, then you will only be able to use properties, functions defined in JQueryDeferred type.
<img width="489" alt="capture d ecran 2016-06-25 a 08 06 22" src="https://cloud.githubusercontent.com/assets/5569608/16355049/c15c59a6-3aab-11e6-80c5-24a4467d111c.png">

Even if public methods are called with method name as a string, TypeScript allows you to have specialized overload signatures based on string constants. It allows you i.e. to specify correct return type depending on method name. That is what I did and what for example JQueryUI has also in its d.ts (see
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/741430a178043bfca40e3a343b8b6f7610104093/jqueryui/jqueryui.d.ts#L1009).
So indeed we cannot restrict people from calling `$('#phone').intlTelInput('xx');`, but when they use the correct method name, they will have the correct return type.
<img width="575" alt="capture d ecran 2016-06-25 a 08 34 13" src="https://cloud.githubusercontent.com/assets/5569608/16355187/a1d62194-3aaf-11e6-8630-31ef401e4f54.png">

### Defines the options
When you will provide options object, it will have to be compliant (property name and correct type) with the Options interface defined in the d.ts file. For example, it will restrict you from doing this :
<img width="581" alt="capture d ecran 2016-06-25 a 07 59 55" src="https://cloud.githubusercontent.com/assets/5569608/16355079/c69fcbb8-3aac-11e6-870e-77edb98ea903.png">
<img width="573" alt="capture d ecran 2016-06-25 a 08 00 10" src="https://cloud.githubusercontent.com/assets/5569608/16355082/ce22860a-3aac-11e6-8316-de7a227d156b.png">
But will allow :
<img width="214" alt="capture d ecran 2016-06-25 a 08 17 33" src="https://cloud.githubusercontent.com/assets/5569608/16355094/4b835868-3aad-11e6-818c-9e54ff04cd49.png">

### Defines intlTelInputUtils global variable and enums
I also defined intlTelInputUtils global var so TypeScript compiler will know that type it is; same for enums. Otherwise it will complain with such errors.
<img width="469" alt="capture d ecran 2016-06-25 a 08 54 41" src="https://cloud.githubusercontent.com/assets/5569608/16355279/8110993c-3ab2-11e6-8fbd-52dbce9369da.png">
<img width="429" alt="capture d ecran 2016-06-25 a 08 56 42" src="https://cloud.githubusercontent.com/assets/5569608/16355288/caea721c-3ab2-11e6-99b0-b85a2da9a4ad.png">

**Comment by jackocnr** [comment]
Very cool thank you!

**Comment by romelgomez** [comment]
First, sorry for up this old issue. I have small question about this types definitions. 

After install 
npm i intl-tel-input --save
npm i @types/intl-tel-input

I a new angular project,  I trying import the lib, like this: 

`import {  } from 'intl-tel-input';`

And this error show up:

`[ts] File '.... /sandbox/iti/node_modules/@types/intl-tel-input/index.d.ts' is not a module. [2306]`

I think this maybe happen because is never exported, in base a similar issue that I find: 

https://github.com/Microsoft/TypeScript/issues/11420#issuecomment-252113705

What I missing here?

**Comment by mahermali** [comment]
@romelgomez 
install Jquery type definitions helped me to overcome this issue
npm install --save-dev @typings/jquery

**Comment by jawadalnuaimi** [comment]
Dear I tried use this plugin on oracle apex but only value in item inserted how I can get the extension also .

**Comment by shrikantkalar023** [comment]
The newly added React component needs type definitions.
