### ISSUE TITLE
isValidNumber pass incorrect mobile number

### ISSUE THREAD

**Issue by wear** [jackocnr/intl-tel-input#434]
"+86 351 419 9072" will pass the _isValidNumber_ check, but I make sure that number was wrong

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for validation - ([demo here](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html)). If their demo shows the number as valid then please raise an issue with them.
