### ISSUE TITLE
How to change code of country? 

### ISSUE THREAD

**Issue by nikbabchenko** [jackocnr/intl-tel-input#436]
Hello, Jackocnr!
Thank you for you plugin.

Please, help! I need to change the code of country, my country is Ukraine  and the code of my country is +380 ... , but we prefer to type our telephones from (0...), so the number '0' in code is odd. 

How can I change it?

**Comment by jackocnr** [comment]
Please can you give an example of a full telephone number starting with 0?

**Comment by nikbabchenko** [comment]
Jack, you support is awesome. 

This is my country dialCode +380.

But we always write our number in format (099)999-99-99 
So the first "0" is odd, 
I would like to cut dialCode to +38. 

Help please)

**Comment by jackocnr** [comment]
I don't understand what the problem is. Please can you clearly explain the steps to reproduce, and what you expect to happen, and what actually happens? (And also tell me exactly what initialisation options you're using)

**Comment by nikbabchenko** [comment]
okay) 
![image](https://cloud.githubusercontent.com/assets/11876062/16738954/9e15c660-47a0-11e6-80a3-6dd48b2436b5.png)

and 

![image](https://cloud.githubusercontent.com/assets/11876062/16738960/a644723c-47a0-11e6-9337-85f19a90fcf7.png)

I want to change to +38 from +380, 

settings: {
      initialCountry: "auto",
      utilsScript: "js/utils.js",
      preferredCountries: ["ua", "ru", "by"],
      separateDialCode: "true"
}

**Comment by jackocnr** [comment]
You can't change it from +380 to +38 because lots of other country's international dial codes start with +38 (e.g. Montenegro has +382).

Why don't you just set `separateDialCode` to false, and then your users wont see the dial code?

Also FYI if you don't set a placeholder in the input then the plugin will display an example number (for Ukraine it is "039 123 4567" - see the [demo page](http://jackocnr.com/intl-tel-input.html)).

**Comment by nikbabchenko** [comment]
Of course you are right, but it's a little bit strange for our citizens. They accustomed to see the number in that way. 

so, I used your demo  in this way. 

Thank you so much. Your plugin is awesome.

  var countryData = $.fn.intlTelInput.getCountryData();
  $.each(countryData, function(i, country) {
    if (country.dialCode == "380" ) {
      country.dialCode ="38";
      }
   });
