### ISSUE TITLE
Auto assign selected data to input fields 

### ISSUE THREAD

**Issue by swapnilchincholkar** [jackocnr/intl-tel-input#438]
### Expected behaviour

I came at situation where I have to show countries drop down and on select of country, I need to assign its country code (eg. +1 for Canada) to my input field where I accept country code & phone number in 2 fields. We can have option where we provide hidden fields "id" and on change of country, code should be assigned to that hidden field. 

We can also have similar things like selected country name to any field, thoughts?

**Comment by jackocnr** [comment]
Please just use the `countrychange` event: https://github.com/jackocnr/intl-tel-input#events
