### ISSUE TITLE
Flag Images

### ISSUE THREAD

**Issue by Jtmichel** [jackocnr/intl-tel-input#439]
Awesome plugin! I love it, great work. 

Just one small issue I'm having. The 2x flag images are actually smaller than the standard ones. Am I missing something? Shouldn't they be larger for retina?

**Comment by jackocnr** [comment]
Glad you're enjoying the plugin!

Where are you looking exactly? In the [build directory](https://github.com/jackocnr/intl-tel-input/tree/master/build/img) the 2x are larger!

**Comment by Jtmichel** [comment]
You are right, I am wrong, please consider this resolved.

Seriously, thank you so much for this library. It was exactly what I needed and does what jquery validate doesn't do!
