### ISSUE TITLE
Phone number accepting special characters

### ISSUE THREAD

**Issue by umesh-naik** [jackocnr/intl-tel-input#442]
Hi, I have a doubt. Is there any built in option or method to remove special  characters from input field? For example, check this:: 

![plugin](https://cloud.githubusercontent.com/assets/11293361/16839626/b8fe1db6-49ed-11e6-857f-e54ef0636fb8.png)

Input is still validated even though minimum character length is valid only for 10 numbers. It gives correct result while working with numbers though.

**Comment by jackocnr** [comment]
Nothing in this plugin will alter what the user enters in the input. The reason this number is valid must be because libphonenumber is cleaning it internally during validation. I suggest you just clean the number in your code before saving it.
