### ISSUE TITLE
Problem with pre-filled values getting formatted

### ISSUE THREAD

**Issue by amrt0510** [jackocnr/intl-tel-input#444]
Hi there, 

Although the plugin works awesomely well, i have just unable to fix an issue on my side.
Great if you guide me. 

What is happening is when i am passing a value attribute to the input field. It shows formatted values with no configurations set what so ever. 
My configuration is --
` $("#phone").intlTelInput({ utilsScript: "build/js/utils.js"});`
If I am not wrong autoFormat is something which is not integrated in the current build. 

Screenshot: http://screencloud.net/v/o7bQ

Please tell me how i can show users the same value they have entered. (Non-formatted)
Thanks!

**Comment by jackocnr** [comment]
See `formatOnInit` option.
