### ISSUE TITLE
Access utils script for carrier details etc 

### ISSUE THREAD

**Issue by amrt0510** [jackocnr/intl-tel-input#445]
Hi,

Your plugin provides quite a few handy info about a number, but i am unable to get carrier info about the number entered , from your plugin. However Google's libphonenumber has the option to get carrier too.
http://screencloud.net/v/zWNu

Could you tell me a way how I would be able to access that info.  
I have tried accessing if any global object if any, but didn't succeeded.

Thanks!

**Comment by jackocnr** [comment]
Hi there,

We just do a custom build of libphonenumber that only includes the bare minimum needed for formatting and validation. This is to keep the filesize down. It is already over 200KB, so I'm very reluctant to add any new features unless they're very popular.

My advice would be: if you only need this on the backend, then use a backend port of libphonenumber (there are links from their github page). If you really need this functionality on the frontend, then you could do your own custom build of libphonenumber to add this - see our custom build source file: https://github.com/jackocnr/intl-tel-input/blob/master/src/js/utils.js

Hope that helps!
