### ISSUE TITLE
United kingdom flag code issue

### ISSUE THREAD

**Issue by lakshmiaswath** [jackocnr/intl-tel-input#448]
hey , i m trying to set defaultCountryCode . Previously i had used flag as "us" ,"hk" and tried couple of other flag names too .It worked for all .But when i tried giving 'gb' for united kingdom it didn't work .
What's the issue ? Is the flag code wrong what i have given for united kingdom ,if so what's the flag code for united kingdom.

**Comment by jackocnr** [comment]
Are you using the latest version of the plugin? (if not then please do). There is no `defaultCountryCode` option - there is an `initialCountry` option, and I just checked and setting it to `"gb"` worked. I'm going to close this issue but feel free to re-open if you're having problems with the latest version of the plugin.
