### ISSUE TITLE
How to use flags elsewhere?

### ISSUE THREAD

**Issue by avimar** [jackocnr/intl-tel-input#457]
I'm currently using the awesome https://github.com/gosquared/flags set elsewhere on my site, in both the 24px and 16px size, depending.
It has a separate file for each flag, though, and since I was already loading intl-tel-input's flag -- in one file -- maybe I should just re-use them.

I was able to re-use it with this: `<div class="iti-flag us"></div>`  but it didn't work with `<span>`  so it breaks the line... and doesn't look very nice on it's own: somehow it looks "duller" than the flag in the drop-down.  I Also wasn't able to figure out how to adjust the size.

Is there a way to simply and reliably re-use the flags?

Also, can I force the retina usage if I know I'll be using a larger size?

Thanks!

p.s. this plugin is _awesome_ and has enabled me to provide a _great_ interface for validating your number, saving speed dials, sending faxes, looking up prices, etc at https://panel.bestfone.com

**Comment by jackocnr** [comment]
Hi there, I'm glad you're enjoying the plugin!

Re: not working with spans - try adding the CSS `display:inline-block`

Re: flags looking "duller" - not sure about that - can you re-create in a codepen for me to take a look?

Re: adjusting the size, we display the images using background-image in CSS, and unfortunately it would be impossible to change the size without changing the CSS background-position rules for all 250 countries... If you really need this, you can change the build settings and rebuild the assets yourself, see an example here: http://codepen.io/jackocnr/full/ONXWgQ/

Re: forcing retina styles - yes you would just need to override a couple of CSS statements: `background-image` and `background-size` to be the retina versions. I would advise you to go to the demo page, look at the CSS file (intlTelInput.css) in chrome dev tools, prettify it, and search for "@media only screen" to find the exact retina statements.

Does that answer your questions?

**Comment by avimar** [comment]
1) spans -- it worked on that single tag, I hadn't thought to just add it to the class as you did http://codepen.io/jackocnr/pen/VjdJqa probably testing it for me: `span.iti-flag {  display: inline-block; }`
Thanks!

... continued in #65
