### ISSUE TITLE
Way to set initial country via dial code e.g. "44"

### ISSUE THREAD

**Issue by kelvinrd** [jackocnr/intl-tel-input#458]
So I have a string of the dial code I want to set the default dial code to be.
How can I use this string to set the default? Or can this only be set through a country string like "GB".

Example:
Use string "+44" to default dial code picker to U.K. +44

**Comment by jackocnr** [comment]
Can you explain exactly what you mean by "set the default dial code"? Do you mean just the initial country selection?

And is nationalMode enabled or not?

**Comment by kelvinrd** [comment]
nationalMode is not enabled.

Yes I mean the ability to set the initial country selection via a dial code number. Is this possible?

**Comment by jackocnr** [comment]
It will automatically select GB if you have "+44" in the input when you initialize the plugin.

**Comment by kelvinrd** [comment]
Sorry for the confusion.

The desired effect is the below screenshot.

On page load, armed only with a dial code, i want to default the initial country selection to the country associated witht dial code I have without filling the input at all.

![image](https://cloud.githubusercontent.com/assets/19665240/17553630/c8585300-5efe-11e6-978c-1fd7f22c351e.png)

**Comment by jackocnr** [comment]
So the way to do that is with the `initialCountry` option, which only takes a 2 letter country code like "GB". You can however get the country code by using `getCountryData` and then iterating over that array until you find the country with your dial code.

**Comment by kelvinrd** [comment]
Thank you for your help.

**Comment by hellohasan** [comment]
@kelvinrd are you find the solution for that 
Use string "+44" to default dial code picker to U.K. +44
