### ISSUE TITLE
Using getExtension without a jQuery selector?

### ISSUE THREAD

**Issue by hornetnz** [jackocnr/intl-tel-input#459]
question rewrite:
I see I can use $.fn.intlTelInputUtils.getExtension to pull the extension out, but how can I get the main phone # without the extension?

**Comment by jackocnr** [comment]
So first of all, if you're actually initializing the plugin and dealing with numbers in the input, you can use the public method `getExtension` to get just the extension, and `getNumber` to just get the rest of the number (BTW it has to be a valid number for this part to work properly).

But if you're not initializing the plugin, and you just have a number in a string somewhere and you want to use the utils to manipulate it, you can use `intlTelInputUtils.getExtension` to get the extension, or `intlTelInputUtils.formatNumber` to just get the rest of the number. See [the utils.js wiki page](https://github.com/jackocnr/intl-tel-input/wiki/utils.js) for more info.

Does that answer your question?

**Comment by hornetnz** [comment]
Yeah that helps. It might be good to update the docs to show what methods will return when the # has an extension. I couldn't tell given whats there that formatNumber wont include the ext. Easy enough to find out once I get the app working, but beforehand not so much. :)

My main issue now is figuring out how to get loadUtils to ref the file correctly, since the module is loaded via bower and therefore lives outside the apps source folder. Anyway, thanks for pointing me to the correct methods!
