### ISSUE TITLE
IE8 input focus issues

### ISSUE THREAD

**Issue by mynamesleon** [jackocnr/intl-tel-input#461]
This is two issues rolled into one as they are related.

In IE8, if the telephone input is empty, when focusing on it, the country code is added as expected, but the cursor position is then reset to the beginning of the input. This also happens when changing the country dropdown (and applies in that instance regardless of whether the input had a value or not)
### Steps to reproduce
1.  Load IE8 (emulated or native - I've been able to reproduce this in both)
2.  Initialise intlTelInput on an input
3.  Focus on the input when it is empty, or, when the input is empty or not, change the country dropdown to another option.
### Expected behaviour

The cursor should be set to the end of the input so that the user can easily start typing
### Actual behaviour

The cursor always ends up at the beginning of the input value 
### Initialisation options

preferredCountries: ['gb'],
nationalMode: false,
formatOnInit: false
### Suggestion

Change the setTimeout function inside your focus listener from:

``` javascript
setTimeout(function() {
    var input = that.telInput[0];
    if (that.isGoodBrowser) {
        var len = that.telInput.val().length;
        input.setSelectionRange(len, len);
    }
});
```

to:

``` javascript
setTimeout(function () {
    var input = that.telInput[0];
    if (that.isGoodBrowser) {
        var len = that.telInput.val().length;
        input.setSelectionRange(len, len);
    } else if (input.createTextRange) {
        var range = input.createTextRange();
        range.moveStart("character", input.value.length);
        range.select();
    }
});
```

and include the same `else if` block at the end of the `_selectListItem` method (obviously replacing the `input` var for `this.telInput[0]`)

I did make this fix for the local copy for the project I'm working on, but when I then compressed the file using jscompress.com I was getting a "Expected identifier, string or number" error in IE8. However when minifying it using javascript-minifier.com it worked fine. Perhaps something to look out for after running the uglify task after making a similar change.

**Comment by jackocnr** [comment]
Hi there, thank you for reporting the issue. According to this snippet: [Move Cursor To End of Textarea or Input](https://css-tricks.com/snippets/jquery/move-cursor-to-end-of-textarea-or-input/) we can just replace the input contents with itself.

I don't have time to look into this myself, but I'm open to a pull request 👍

**Comment by jackocnr** [comment]
Closing as we no longer support IE8 (see readme).
