### ISSUE TITLE
initialCountry requires lowercase ISO code

### ISSUE THREAD

**Issue by JoeWoodward** [jackocnr/intl-tel-input#463]
I just had a head scratching moment for 

$('#phone').intlTelInput({initialCountry: "MY"})

error: unknown country info for MY

$('#phone').intlTelInput({initialCountry: 'my'})

👍 🆗 

Maybe either add a note to the README or use toLowerCase on the value

**Comment by jackocnr** [comment]
Good catch. We do `toLowerCase` in all other situations, but I missed it in this case. Unfortunately I don't have time to work on this myself right now, but I would gladly accept a pull request :)
