### ISSUE TITLE
formatOnInit is removes appended 0 if number too short or too long

### ISSUE THREAD

**Issue by JoeWoodward** [jackocnr/intl-tel-input#464]
When you input a number that is shorter or longer than the formatOnInit expects then the 0 is not appended

Typing +441234567890 then running `$('#phone').intlTelInput()` formats the number to 01234567890
Typing +44123 then running `$('#phone').intlTelInput()` formats the number to 123
Typing +4412345678901 then running `$('#phone').intlTelInput()` formats the number to 12345678901

Ideally the national format would just replace the international dialling code regardless of the validity of the number

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, so if you're having any issues I suggest you raise it with them.

**Comment by jackocnr** [comment]
FYI you can try out their [demo page](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) to see how their formatting works. I'm afraid we're stuck with the way they do it.
