### ISSUE TITLE
-99 error when calling isValidNumber after initialization

### ISSUE THREAD

**Issue by GNUletik** [jackocnr/intl-tel-input#465]
Hi,

I got a -99 Validation Error while trying to validate a number just after I loaded intl-tel-input.

But I think the code will be more explicit. So you can reproduce it with

1.  `git clone --recursive https://github.com/GNUletik/bug-intl-tel-input && cd bug-intl-tel-input`
2.  Then launch a web server (http-server or python -m http.server)
3. Then load the page in your browser

The number is valid so, we shouldn't have an error.

I know this bug is about validation so about https://github.com/googlei18n/libphonenumber but It seems to be about the way it's loaded in intl-tel-input.
It seems that when the number is checked, the complete library is not loaded and I can't see any events in the documentation to know when the library is loaded.

How is it possible to solve this ?

Thanks !

**Comment by jackocnr** [comment]
Are you using the `utilsScript` option? If so, please read the readme about that - it mentions using a `done` callback.

**Comment by GNUletik** [comment]
Yes I am, and using the .done(callback) method is working. Sorry, I completely missed it. Thanks for your help ! :)

**Comment by jackocnr** [comment]
You're welcome :)

**Comment by pptyasar** [comment]
@where to place done callback? @jackocnr

**Comment by jackocnr** [comment]
Chain it after initialising the plugin e.g. `$('.phone').intlTelInput(...).done(function() {...});`

**Comment by pptyasar** [comment]
Still Issue
`$('#user-phone_no').intlTelInput({
            // allowDropdown: false,
            // autoHideDialCode: false,
            // autoPlaceholder: 'off',
            // dropdownContainer: 'body',
            // excludeCountries: ['us'],
            formatOnDisplay: true,
            geoIpLookup: function(callback) {
              $.get('http://ipinfo.io', function() {}, 'jsonp').always(function(resp) {
                var countryCode = (resp && resp.country) ? resp.country :'';
                callback(countryCode);
              });
            },
            hiddenInput: 'full_number',
            initialCountry: 'auto',
            nationalMode: false,
            //autoPlaceholder:'aggressive',
            // onlyCountries: ['us', 'gb', 'ch', 'ca', 'do'],
            // placeholderNumberType: 'MOBILE',
            preferredCountries: ['in','us'],
            separateDialCode: true,
            utilsScript: '../js/utils.js'
        }).done(function() {
            $('#user-phone_no').change(function()
            {
                var telInput = $('#user-phone_no');
                if ($.trim(telInput.val())) 
                {
                    if (telInput.intlTelInput('isValidNumber')) 
                    {
                    console.log(telInput.intlTelInput('getNumber'));
                    alert('Valid');
                    }
                    else 
                    {
                    console.log(telInput.intlTelInput('getNumberType'));
                    console.log(telInput.intlTelInput('getValidationError'));
                    alert('invalid');
                    }
                }
            });
        });`

**Comment by jackocnr** [comment]
@pptyasar please describe the steps you're taking, what you expect to happen, and what actually happens.

**Comment by pptyasar** [comment]
Working when replacing this 
https://github.com/jackocnr/intl-tel-input/blob/master/build/js/utils.js
to this
https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/12.0.1/js/utils.js

**Comment by jackocnr** [comment]
I'm afraid I can't help figure out the issue until you provide the above information about your problem.

**Comment by pptyasar** [comment]
Now working but  I don't know how this is working now??
I checked all changes...

**Comment by rob101** [comment]
I get this error when using the current jquery version (v.16.0.11). However error -99 only occurs when there is a single digit input validated.

The docs no longer appear to have reference to a "done" proceedure and calling the above code results in:

`intlTelInput(...).done is not a function`
