### ISSUE TITLE
$.fn.intlTelInputUtils vs window.intlTelInputUtils

### ISSUE THREAD

**Issue by hornetnz** [jackocnr/intl-tel-input#469]
I seem to be having an issue accessing the utils via $.fn. 

I've added the loadUtils to the index Run service that loads at startup (because running it later ran into async issues since the load utils ajax doesnt return anything, hence I can't use a promise .then) I've verified it is loaded, as the validation and formatting is working.

In my model deserializer I'm attempting use the utils to getExtension...but when I hit that breakpoint, intlTelInputUtils is only available off of window. $.fn.int... doesn't work. Why would that be?

**Comment by jackocnr** [comment]
`intlTelInputUtils` is never available on `$.fn` - it is only ever available on `window`.
