### ISSUE TITLE
CDN Down

### ISSUE THREAD

**Issue by wjthomas9** [jackocnr/intl-tel-input#471]
Just noticed after your update today that the CDN link seems to be broken. Not sure if they're related. https://cdnjs.com/libraries/intl-tel-input

<img width="218" alt="screen shot 2016-08-30 at 6 45 03 pm" src="https://cloud.githubusercontent.com/assets/986696/18111032/e2ba546c-6ee1-11e6-96e0-d6027a5f545b.png">

**Comment by jackocnr** [comment]
Yes their other libs are still up, so I would guess it is related. I would suggest you raise an issue with  them: https://github.com/cdnjs/cdnjs

cc: @piuccio

**Comment by jackocnr** [comment]
It's back up now.
