### ISSUE TITLE
Add Country code to input when submit button is clicked

### ISSUE THREAD

**Issue by adnanmayo** [jackocnr/intl-tel-input#472]
Hi this an awesome plug in ...i want to add a country code in a input field when submit pressed...is there a way arround?

**Comment by Gorgethelastheir** [comment]
add a hidden input for country code on submit do this 
$('#user_data').on('submit', function(ev) {

			var code = $("#fieldPhoneID").intlTelInput("getSelectedCountryData");
			$('#fieldcodePhoneID').val('+'+code['dialCode']);
			var newphone = $('#fieldcodePhoneID').val() + $('#fieldPhoneID').val()
			$('#fieldPhoneID').val(newphone)
.
.
.
.

**Comment by jackocnr** [comment]
See this example: http://jackocnr.com/node_modules/intl-tel-input/examples/gen/hidden-input.html
