### ISSUE TITLE
Consider using pngquant for flag images optimizing

### ISSUE THREAD

**Issue by tinovyatkin** [jackocnr/intl-tel-input#477]
Flags PNG becomes huge, and image quality not very important here, I managed to compress with `pngquant` the `flags.png` to 24Kb from original 66Kb and `flags@2x.png` to 67KB from original 165KB

**Comment by jackocnr** [comment]
I disagree that "image quality is not very important here" - I think a lot of devs using this plugin will expect crystal clear flag images.

That said, you're free to reduce the quality of the images in your own personal build process. And it would be great if you could document here an easy way to do that in case others would like to do the same.
