### ISSUE TITLE
Add setNumberType public method

### ISSUE THREAD

**Issue by iustind** [jackocnr/intl-tel-input#480]
Is it possible to expose a public method setNumberType similar to setNumber in order to set the phone number type on the fly? A typical case scenario would be when the end user has to fill out a contacts form where a contact can have multiple (but different) phone types, like Mobile, Office, etc.

**Comment by jackocnr** [comment]
That's an interesting idea. And what exactly did you want to happen when you called this new `setNumberType` method?

**Comment by iustind** [comment]
Well, as per documentation, the numberType property is only used to set the placeholder to the right type of a number. In such a cas, I would expect to see the placeholders changing each time I switch from one numberType to another (by calling setNumberType).

**Comment by jackocnr** [comment]
Ok that makes sense. I could be onboard with this, except let's call it `setPlaceholderNumberType` to distinguish it from the `getNumberType` method (related: https://github.com/jackocnr/intl-tel-input/issues/481).

Unfortunately I don't have time to implement this myself right now, but I would be open to a pull request :)

**Comment by iustind** [comment]
Thanks for the quick answers! I'm looking fwd to seeing this implemented some day... And I forgot to mention the most obvious fact: nice work!

**Comment by jackocnr** [comment]
Thanks! Glad you're enjoying the plugin.

Why don't you have a go at implementing the new feature? It's easy!

**Comment by iustind** [comment]
For the same reason as you mentioned: I am currently busy with finishing a project. But I will give it a try ASAP.

**Comment by jackocnr** [comment]
Good man.

**Comment by jackocnr** [comment]
Actually on second thought, I don't think this is worth the extra weight in the plugin. I'm trying really hard not to let this project get too bloated, and TBH, the point of the placeholder is to show the user they can type a phone number in the input - I think that is conveyed no matter what type the number is, let alone having to update it in real time!
