### ISSUE TITLE
How to hide Flags dropdown?

### ISSUE THREAD

**Issue by Dineshrajaa** [jackocnr/intl-tel-input#485]
Hi All,
 Is there anyway to hide flag dropdown is there any option available for that? I am using this plugin for Mobile number validation alone.

**Comment by jackocnr** [comment]
Did you look at the options in the readme?

**Comment by Dineshrajaa** [comment]
Yes I did, even tried this `allowDropdown:false` but the problem is Flag dropdown is getting disabled but it's still visible.

**Comment by jackocnr** [comment]
You could either hide it with CSS. Or do you even need to initialise the plugin at all? Instead could you just use the intlTelInputUtils validation method directly? (See the wiki page)

**Comment by raimonika20** [comment]
.iti__flag-container {
	display: none;
}
Just use this to hide the whole container in the '.css' file. The drop down will be gone.
