### ISSUE TITLE
Angular2  - How do i use this in my angular2 web application?

### ISSUE THREAD

**Issue by SnehaAwasthi** [jackocnr/intl-tel-input#488]
How do i implement this in my angular2 web application?

**Comment by jackocnr** [comment]
I'm sorry I've never used Angular. I think your best bet would be to search Google for an angular version of this plugin. Or there are a few listed on our Integrations page: https://github.com/jackocnr/intl-tel-input/wiki/Integrations

**Comment by SnehaAwasthi** [comment]
Thanks allot..:)
