### ISSUE TITLE
Create changelog/release notes

### ISSUE THREAD

**Issue by johnjiang** [jackocnr/intl-tel-input#490]
I can't seem to find release notes anywhere. The version numbers keep on getting bumped up but I have no idea whether I should be upgrading or not.

**Comment by jackocnr** [comment]
You can find the release notes in the [releases section](https://github.com/jackocnr/intl-tel-input/releases), but yes I have been thinking we should move those into a CHANGELOG.md. Unfortunately I'm too busy to do that myself, but I would welcome a pull request!
