### ISSUE TITLE
International format issues

### ISSUE THREAD

**Issue by myrsk** [jackocnr/intl-tel-input#493]
### Steps to reproduce
1.  select United Arab Emirates
2.  fill number as 0502467321 
3.  Post the form and get output of $_POST array

### Expected behavior
Should be outputting +971502467321 where it adds the country code, and removes the zero

### Actual behavior
Outputs as 0502467321

### Initialisation options
Using utils script, and custom options are as follows

```
<script>
    $('#phone').intlTelInput({
       autoPlaceholder: 'polite',
       geoIpLookup: function(callback) {
         $.get('https://ipinfo.io', function() {}, 'jsonp').always(function(resp) {
           var countryCode = (resp && resp.country) ? resp.country : '';
           callback(countryCode);
         });
       },
      initialCountry: 'auto',
       nationalMode: true,
       separateDialCode: false,
      utilsScript: '../modules/addons/module/includes/tel/js/utils.js'
    });
    $('#phone').intlTelInput('getNumber', 1);
  </script>
```

This is using all the latest version files

Thanks for the help.

**Comment by jackocnr** [comment]
The plugin does not automatically handle submit formatting for you. I recommend using a hidden input for this - you can see an example of this technique here: http://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/hidden-input.html
