### ISSUE TITLE
Adblocker causing ipinfo not to load

### ISSUE THREAD

**Issue by joeynimu** [jackocnr/intl-tel-input#494]
This is caused by AdBlocker plugins and disabling it solves the problem but i am just curious if there is a work around this? A normal user who isn't a developer and can't inspect their console won't be able to know what is the problem and know that they need to disable their Adblocker. It would be nice if there was a workaround.

```
http://ipinfo.io/?callback=jQuery112004917939850800388_1476774648454&_=1476774648455 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by jackocnr** [comment]
I don't think there is a way around this.

This is another reason why you must use the `always` callback when performing the ipinfo request, because it is still called even if the ipinfo lookup fails.

**Comment by joeynimu** [comment]
I am using the `always` callback but it still gets blocked. Thanks though.

**Comment by jackocnr** [comment]
What do you mean it gets "blocked"? What happens? Have you tried stepping through the JS using devtools?

**Comment by joeynimu** [comment]
Below is the code I am using.
```js
$.get("http://ipinfo.io", function() {}, "jsonp").always(function(resp) {
    var $defaultCodeField = $('div.country-code');
    var countryCode = (resp && resp.country) ? resp.country : "";
```

But it doesn't load the country/dial codes. On inspecting the console I see the below error.
```
http://ipinfo.io/?callback=jQuery112004917939850800388_1476774648454&_=1476774648455 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by jackocnr** [comment]
> But it doesn't load the country/dial codes

What exactly do you mean by this?

If the plugin fails to load the user's country info, then it should just default to America.

**Comment by BenJackGill** [comment]
@joeynimu and @jackocnr, I'm having the exact same problem.

When the plugin fails to load the user's country (due to them using an ad blocker) it does not default back to America. It shows an empty grey rectangle where the flag should be.

Did you manage to find a solution?

**Comment by jackocnr** [comment]
If you want it to default to a specific country in this case, e.g. US, then return that instead of empty string e.g. 

```js
jQuery.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
    var countryCode = (resp && resp.country) ? resp.country : "us"; // <-- here
    callback(countryCode);
});
```

**Comment by taher24** [comment]
If you want it to default to a specific country in this case, e.g. US, then return that instead of empty string e.g.
 
$.get('https://ipinfo.io', function(resp) {
                    var countryCode = (resp && resp.country) ? resp.country : "us";
                    callback(countryCode);
                })
                    .fail(function() {
                        var countryCode = "us";
                        callback(countryCode);
                    });
