### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by simonnilsson** [jackocnr/intl-tel-input#495]
In order for this plugin to work with webpack and npm it needs to know about the css. The easiest way I found is to require it in the index.js like this:

``` javascript
/**
 * Exposing intl-tel-input as a component
 */
require("./build/css/intlTelInput.css");
require('./build/js/utils');
module.exports = require("./build/js/intlTelInput");
```

_Edit: **utils.js** also needs to be included for the plugin to work_

**Comment by jackocnr** [comment]
Thanks for reaching out. I don't have much experience with webpack, any chance you could link to some more information about this approach?

**Comment by simonnilsson** [comment]
Here is a discussion about it https://github.com/webpack/webpack/issues/1789 most of the propossed solutions there involves the user having to add extra requires in their code in the style 
```javascript
require('intl-tel-input/build/css/intlTelInput.css'); 
```
This defeats the purpose of webpack according to me as one would need to now what files each dependency needs included. 

I'm not really sure if requiring a css-file in the index.js would cause compatibility issues with other tools however.

**Comment by jackocnr** [comment]
Sorry for the delay. Thanks for sharing the link. I have to say I agree with all of the comments there - it is your job to require whatever CSS files you need from your node modules.

Also regarding the edit to your original comment:

> utils.js also needs to be included for the plugin to work

My advice would be not to include utils.js in your main bundle because it is very large (>200KB), but to instead lazy load it when initializing the plugin, using the `utilsScript` option.

**Comment by the94air** [comment]
@simonnilsson That helped so much. Thanks

**Comment by mecampbellsoup** [comment]
@jackocnr regarding this comment:

> My advice would be not to include utils.js in your main bundle because it is very large (>200KB), but to instead lazy load it when initializing the plugin, using the `utilsScript` option.

Is it possible to load the utils script from webpack; or is that flag a URL only?

**Comment by jackocnr** [comment]
@mecampbellsoup the `utilsScript` option takes a URL only. But you're welcome to load that file (utils.js) anyway you like - it just declares a global window.intlTelInputUtils which is used by the plugin if available.
