### ISSUE TITLE
README /path/to/flags

### ISSUE THREAD

**Issue by aaronblenkush** [jackocnr/intl-tel-input#496]
The readme says that in the CSS the "/path/to" needs to be replaced with, but the release just uses a relative path "../img/flags.png" / "../img/flags@2x.png". It seems this step can be removed from the instructions.

**Comment by jackocnr** [comment]
Most projects that use this plugin will have their own asset directory structure, and likely their own routing system that doesn't link directly to directories, so that default path will not work.
