### ISSUE TITLE
Remove + sign from number?

### ISSUE THREAD

**Issue by gunn3rfourlif3** [jackocnr/intl-tel-input#501]
How do I go about remove the plus from the input value. I want only numerics returned?

**Comment by jackocnr** [comment]
Do you mean you want the national number (e.g. 07733312345 in the UK)? Then see the `getNumber` documentation in the readme.

If you want the international number without the plus (e.g. 447733312345), then you will just have to remove the plus yourself because that's not a standard format.

**Comment by nguyenj** [comment]
Is there a way for `formatOnDisplay` to format the input if it returns without the `+` sign?

**Comment by jackocnr** [comment]
What do you mean by "it returns"? Please give me the steps, and the expected outcome and the actual outcome.

**Comment by nguyenj** [comment]
Apologizes for the lack of clarity.

The current state:

`formatOnDisplay` will properly format this value from the database `+14155552671`. However, if the database strips all characters except for integers, `formatOnDisplay` doesn't format `14155552671` this properly in the input with the proper country code via the dropdown.

With `+`:
![simple text message voting poll everywhere 2017-01-25 07-15-47](https://cloud.githubusercontent.com/assets/1127677/22296092/1c910bd0-e2ce-11e6-8dd2-b914857cfdfd.jpg)

Without `+`:
![simple text message voting poll everywhere 2017-01-25 07-17-13](https://cloud.githubusercontent.com/assets/1127677/22296214/4eeb70fc-e2ce-11e6-8b00-96fd1ea284ff.jpg)

**Comment by jackocnr** [comment]
Well firstly I would say you should change your database structure so it doesn't strip any characters! The way I recommend you use the plugin is: when you're saving numbers, you should use the plugin's `getNumber` which returns it in a standard valid format (strips all non-numeric chars except for the leading `+`).

But if you can't do that, then why don't you just add the `+` back in manually when displaying the number?

**Comment by nguyenj** [comment]
I have a js helper function to deal it with prepending the `+`. But seem a little cumbersome until the database is patched to accept valid characters.

Thanks for your insights.
