### ISSUE TITLE
North American Toll Free telephone numbers show with US Flag

### ISSUE THREAD

**Issue by tmorehouse** [jackocnr/intl-tel-input#503]
## Steps to reproduce

1. Select Canada (+1)
2. Type a number such as '8005551212'

## Expected behaviour

Either the flag stays as selected when international code is +1 or it should show a blank flag.

## Actual behaviour

Flag in dropdown immediately changes to USA Flag

## Suggestion

For non-geographics codes (specifically toll free 8xx numbers in North America), implement a +1 "flagless" dropdown option.

https://en.wikipedia.org/wiki/List_of_North_American_Numbering_Plan_area_codes#NANP_non-geographic

**Comment by jackocnr** [comment]
Thanks for filing this. I think my preference would be the same as when you type `+1` - which is to stay on the currently selected flag if it's a NANP country, else default to US.

Anyway I'm afraid I'm too busy to implement this myself right now, but I would welcome a pull request :)

**Comment by tmorehouse** [comment]
@jackocnr The thing about it only being dealt with when typing in the number, would be if the control was later used to present the number to a user (say in their account settings).  When pre-loading the control with a toll free number, the flag showing up would be for the USA again.

My preference would be to show just the "+1" and a blank for the flag.

**Comment by tmorehouse** [comment]
I wouldn't really flag this as a bug, but rather an "annoyance" ;-)

**Comment by jackocnr** [comment]
Hmm if when you later present the number to the user, do you really think it would be confusing if it defaulted to US?

Can I ask: what exactly is your use case?

**Comment by tmorehouse** [comment]
The use case would be for user's account settings.

Client can update their phone number on their user account page settings.  When prompted to change their phone number, the current phone number would be in the field. (say they need to fix on digit in it).

It would come up in the control as being USA.

The only option would be to prompt them for a new number without presenting the current number, which doesn't really work well for in place editing (i.e. swapping out the display string number for a phone number input control).

Not many of my customers use toll free numbers, but some do, and 75% of them are not in the USA.

**Comment by jackocnr** [comment]
Ok then, in the case of initialising the plugin with an 800 number: I agree we should leave the flag grey (unless you specify an initialCountry option). But if the user selects a NANP country and types an 800 number, we should leave that country selected.

Then if you're the kind of website were you might have users entering 800 numbers, and you really care about displaying the right flag when presenting the number, then when the user first submits their 800 number, you can record which flag is selected, and then set that as the `initialCountry` when presenting the number.

Does that make sense?

**Comment by tmorehouse** [comment]
So your saying store the country in the database? and use that value when a person is editing their number? Doesn't that go against the opinion (from the docs) of only storing the international version of the number in the database?

**Comment by jackocnr** [comment]
I'm not saying everyone has to store the country in the database, I'm just saying that if it's important to you to display the correct flag for 800 numbers, then there is a way to do it. By default, when showing 800 numbers, it will just be a grey default state.

**Comment by tmorehouse** [comment]
Showing a grey/blank flag when pre-loading the control with a toll free number would work though. I just don't really want it defaulting to a US flag.

**Comment by jackocnr** [comment]
Yes I agree. So I think the implementation should be as per my previous comment:

> in the case of initialising the plugin with an 800 number: I agree we should leave the flag grey (unless you specify an initialCountry option). But if the user selects a NANP country and types an 800 number, we should leave that country selected.

**Comment by jackocnr** [comment]
Fixed in v9.2.6.

**Comment by jackocnr** [comment]
@tmorehouse we've realised it causes errors to leave the flag unselected (see linked issue), so I have proposed that if the plugin is initialised with nationalMode=true and an input value with a regionless NANP number, and no initialCountry option, then we should default to the US flag. Does that work for your use case?

**Comment by tmorehouse** [comment]
If no initial country, then I think that would work.
