### ISSUE TITLE
Reliance Jio mobile number not supported

### ISSUE THREAD

**Issue by jjt1bece** [jackocnr/intl-tel-input#505]
### Steps to reproduce
1.  Enter Reliance Jio mobile number 7990881369

### Expected behaviour

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: IN
Result from getNumberType(): MOBILE

### Actual behaviour
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: IN
Result from getNumberType(): UNKNOWN

**Comment by jackocnr** [comment]
Is this issue meant for [libphonenumber](https://github.com/googlei18n/libphonenumber)?
