### ISSUE TITLE
Adding an extra zero when getNumber method is called on keyup

### ISSUE THREAD

**Issue by ozanhazer** [jackocnr/intl-tel-input#506]
### Steps to reproduce
1.  Go to [demo page](http://intl-tel-input.com/)
2. Add this event handler:`$('#phone').on('keyup', function() { console.log($('#phone').intlTelInput("getNumber"));});`
3. Pick "Turkey" as the country
4. Start typing a phone number and watch the console.log.

### Expected behaviour
The output should be like
+905
+9050
+90505
+905053
+9050534
+90505345
+905053456
+9050534565
+90505345654

### Actual behaviour
The output is:
+9005
+90050
+900505
+9005053
+90050534
+900505345
+905053456  --> correct after this point ?!?
+9050534565
+90505345654

You can observe that the method works fine if enough characters are entered.

### Notes
Prefix for Turkey is +90, +90505345654 is the international form.

Locally the number is expressed like 0505345654 so while converting to international form the 0 at the beginning should be removed but it's not up to some length. I can't say if this is a libphonenumber issue or not since I don't know the internals of this library...

**Comment by jackocnr** [comment]
Thanks for reporting this. I checked with the [libphonenumber javascript demo](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html), entering "tr" for the country, and "05" for the number, and for the E164 formatting, it just says "invalid", so I've concluded that `getNumber` should only be used with valid numbers (e.g. after validation with `isValidNumber`). I have updated the readme accordingly.
