### ISSUE TITLE
Enhancement: Support pre-compiling, pre-loading of utils.js 

### ISSUE THREAD

**Issue by manur** [jackocnr/intl-tel-input#508]
See pull request:
https://github.com/jackocnr/intl-tel-input/pull/507

**Comment by jackocnr** [comment]
Firstly I'd like to point out that the compiled utils.js is large (>200KB) so it is not recommended that you bake this into your main JS bundle. But if you decide that you still want to, then it should just work without this change. Did you try it and experience an issue?

**Comment by manur** [comment]
I understand that it's large. I was reluctant at first, but after gzip, it's much smaller than that, and we were comfortable with including it.

Also, pre-compiling is preferential for any users who want to embed this in a node desktop app, as we also plan to do at a later point. JS isn't used solely in browsers anymore, so I think it'd be really useful for users of this project to see documentation for pre-compiling/pre-loading.

I didn't try it separately, since there was no documentation to support usage of `utils.js` in any other way. I read through the code, and it didn't seem like `handleUtils()` would get called unless there was an explicit reference to it, no? Which is what this adds.

Secondly, I think the documentation changes here are worthwhile, for anyone (like me) that didn't presume things would "just work" by loading `utils.js` before and relying on a shared global. If this change is rejected, I think some replacement documentation would be helpful...

**Comment by jackocnr** [comment]
Ok thanks for raising the issue. I updated the Utilities Script section of the readme to mention that you can include it yourself however you want.

I'll close this for now, but if you find any problems doing it that way please let me know!
