### ISSUE TITLE
Why is not selected country prefix code added to submitted phone number?

### ISSUE THREAD

**Issue by skorunka** [jackocnr/intl-tel-input#512]
How do I get a country code prefix selected by user on the server side?

**Comment by jackocnr** [comment]
You need to use `getNumber` to get the full number before the form submits. You can see an example using a hidden input here: http://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/hidden-input.html

**Comment by skorunka** [comment]
Works. Thank you.
