### ISSUE TITLE
Missing Countries

### ISSUE THREAD

**Issue by MohammadDayeh** [jackocnr/intl-tel-input#513]
Here is a list of missing countries to add:

### Missing Countries List
1.  Netherlands Antilles  (an)
2.  Bouvet Island (bv)
3.  France, Metropolitan (fx)
4.  South Georgia and the South Sandwich Islands (gs)
5.  Heard and Mc Donald Islands (hm)
6.  Pitcairn (pn)
7.  French Southern Territories (tf)
8.  East Timor (tp)
9.  United States Minor Outlying Islands (um)
10.  Yugoslavia (yu)
11.  Zaire (zr)

**Comment by jackocnr** [comment]
Unfortunately they don't meet the required criteria: https://github.com/jackocnr/intl-tel-input/blob/master/src/js/data.js#L3
