### ISSUE TITLE
Update libphonenumber?

### ISSUE THREAD

**Issue by SDIS83Loic** [jackocnr/intl-tel-input#514]
Hello,
France to add 3 or 5 years on 07 XX XX XX XX for new mobiles.
When I do a validation test (Result from isValidNumber (): false) when it is a valid number.
I also have an error on the line type (Result from getNumberType (): UNKNOWN).

Is there an update to be made?

Thank you
Loic #

**Comment by jackocnr** [comment]
We use libphonenumber for formatting and validation - please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by SDIS83Loic** [comment]
It's ok
Thank you
