### ISSUE TITLE
isValidNumber function returning false for some valid indian numbers

### ISSUE THREAD

**Issue by ajainguru** [jackocnr/intl-tel-input#515]
IMPORTANT: please note that the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

### Steps to reproduce
1. Use isValidNumber function to check validity of India number starting with 73411.
2.  Not able to share exact number as it is client's number.
3.  Same API works for most of the other numbers I tried with.

### Expected behaviour
As number is valid. It should return true.

### Actual behaviour
It returns false.

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries
I'm using for India. Same works for other indian numbers be it cell or landline.

**Comment by jackocnr** [comment]
Did you try the libphonenumber demo? Please see the second IMPORTANT notice at the top of your issue.

**Comment by ajainguru** [comment]
Thanks. I was using old version. With latest it works.

**Comment by ajainguru** [comment]
Today, we found that isValidNumber fails for some JIO service provider numbers. I'm using 9.2.0 version.

**Comment by jackocnr** [comment]
Again, please read the following important notice when creating new issues:

> IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
