### ISSUE TITLE
+22579262*** being shown as invalid

### ISSUE THREAD

**Issue by kunalsethiya** [jackocnr/intl-tel-input#516]
### Steps to reproduce
1.  enter the phone no. of the type +22579262***
2.  It shows as invalid, however some of customers are using them as valid phone nos. 

### Expected behaviour
The no. should be passed as valid

### Actual behaviour
they are shown as invalid. 

I tested this phone no. on the live demo as well, and it is showing invalid there as well. please help and provide support on this as soon as possible.

Thanks 
Kunal

**Comment by jackocnr** [comment]
Please see this important notice when creating new issues:

> IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
