### ISSUE TITLE
New util.js build please with libphonenumber v8.0.0 or v7.7.5

### ISSUE THREAD

**Issue by erwanc-thx** [jackocnr/intl-tel-input#517]
The current intl-tel-input util.js uses [libphonenumber 7.7.3](https://github.com/jackocnr/intl-tel-input/commit/30d7ab10e76dfcf66972f2cf8ed6ca9fb3bdad59)
The current version is 8.0.0 [https://github.com/googlei18n/libphonenumber/releases](https://github.com/googlei18n/libphonenumber/releases)

The process to compile the Google library and then compile it into intl-tel-input seems awfully complicated and out of reach for me.
I have added intlTelInput.min.js and util.js in my current project but spotted dialing rules out of date already :-(

Would you kindly be able to include the latest compiled in the repo?
Or maybe have a build process that would do that from this project pulling the latest libphonenumber ?

Thank you so so much!
E

**Comment by jackocnr** [comment]
Thanks for letting me know. They had made a change that meant that my notification script wasn't working, so I didn't know about the new versions!

I've just released v9.2.7 which updates the libphonenumber build to v8.0.0.
