### ISSUE TITLE
International Numbers with hidden input stripping zeros?

### ISSUE THREAD

**Issue by jimmiejackson414** [jackocnr/intl-tel-input#519]
IMPORTANT: please note that the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

### Steps to reproduce
The code for my phone input looks like this: 
HTML:
```
<div class="col-md-6">
	<input type="tel" class="form-control tc-custom-focus" id="inf_field_Phone1" minlength = '10' maxlength="14" data-parsley-error-message='Must be minimum of 10 digits' data-parsley-trigger='change' data-parsley-required autofocus>
	<input id="hidden-number" name='inf_field_Phone1' type="hidden" name="phone-full">
</div>
```

JS: 
```
<script>
  	$("#inf_field_Phone1").intlTelInput({
  				utilsScript: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/9.2.7/js/utils.js'
  			});
  	$("#become-partner-form").submit(function() {
  	$("#hidden-number").val($("#inf_field_Phone1").intlTelInput("getNumber"));
  	console.log($('#hidden-number').val());
  			});
</script>
```

### Expected behaviour
I'm trying to submit to the server, and when I console log the value of #hidden-number, it shows correctly. 

### Actual behaviour
When actually submitting, the zeros are stripped for some reason. I entered the UK number 09876123456, the +44 is being automatically applied (as it should), but again the zero is getting stripped out. 

Not sure if this is actually an issue with intl-tel-input, libphonenumber or Parsley (my form validation), but any help would be greatly appreciated!

**Comment by jackocnr** [comment]
That's how phone numbers work in the UK: in international format (with the +44) you strip out the 0.

**Comment by jimmiejackson414** [comment]
Fascinating, had no idea! Thanks for your response.

**Comment by toedoro** [comment]
Hi any updates for this leading zero is missing? or does any knows how to get the original Mobile No that is not formatted?
example: Mobile No. 07809687219 formatted: +447809687219
because when passing the mobile data to server from angular js it is formatted not the original, id like to get the original for this :(
