### ISSUE TITLE
Cook Island Phone Number Detected as Regionless Nanp Number

### ISSUE THREAD

**Issue by toddca** [jackocnr/intl-tel-input#520]
### Steps to reproduce
1.  Create an input with a value of '+68223661'
2.  Call .intlTelInput(); on that input.
3.  Note the flag for Cook Island (ck) is not detected.

### Expected behaviour
The flag and formatting for Cook Island should be visible.

### Actual behaviour
Formatted for Cook Island is not detected because the call to _isRegionlessNanp() returns true as it is detecting the number '822' - the broken line of code is:
this._getNumeric(number).substr(1, 3);

I believe it should be:
this._getNumeric(number).substr(0, 3);

So the code as it is is formatting the original number as '68223661' via a regex and then using a zero based substr you are skipping past the first element (6) and taking the next 3 values which is '822', I think you mean to take 682.

I have tested with the updated code and it works.

**Comment by jackocnr** [comment]
Thanks for reporting this. Fixed in v10.0.2.
