### ISSUE TITLE
Incorrect country code on mobile

### ISSUE THREAD

**Issue by sgkhode** [jackocnr/intl-tel-input#525]
When we open http://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/default-country-ip.html on mobile, it takes US as default country rather than user's country. I have tested on desktop and mobile from the same IP
Is there any fix for this issue?

**Comment by balexandre** [comment]
there's no issues with that code, it's just calling a 3rd party `ipinfo.io` website with the IP ... check with them why your IP is pointing to US instead the original country, and most likely, you're passing the wrong IP? 

for example, if the connection is made thru a proxy, on in production, if the site is behind cloud-flare.

what I did was pass my own as I get the country from [CloudFlare injected header](https://support.cloudflare.com/hc/en-us/articles/200168236-What-does-CloudFlare-IP-Geolocation-do-)

**Comment by jackocnr** [comment]
Yeah this sounds like a problem either with your device setup, or with ipinfo. Feel free to re-open if you can confirm that your geoIpLookup function is calling the callback with the correct country code.
