### ISSUE TITLE
The below link is showing 404 error

### ISSUE THREAD

**Issue by jatasya** [jackocnr/intl-tel-input#527]
[http://jackocnr.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html]

and I'm trying to implement isValidNumber functionality, but I'm getting confused with all the google's isValidNumber function. It would be of great help if I could get a simple implementation or a link to that implementaion of it.

**Comment by jackocnr** [comment]
Sorry all the links to examples were broken. Fixed now.
