### ISSUE TITLE
IP location is wrong.

### ISSUE THREAD

**Issue by krahamath** [jackocnr/intl-tel-input#528]
http://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/default-country-ip.html (Auto detect is not working)
When i viewing from my location its alway shown US or blank flag. 
i am from France and using firefox latest browser but working from chrome, opera browsers

**Comment by jackocnr** [comment]
It works fine for me in Firefox. If you look at the ipinfo request in Dev Tools, what country does the response contain?

And what country do you see if you go directly to http://ipinfo.io ?

**Comment by krahamath** [comment]
The problem from myside, my Kaspersky Internet Security blocked ipinfo.io (Web beacons).
