### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by Basek** [jackocnr/intl-tel-input#530]
Hi,

There is any possibility to turn off full screen mode on iPad?

**Comment by jackocnr** [comment]
Hmm good point. For some reason we show the full screen popup on both iPhone and iPad, when we only show it on Android mobile and not on Android tablets. We just need to remove the `iPad` part on this line: https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js.ejs#L85

Unfortunately I don't have time to implement this myself right now, but would welcome a pull request.

**Comment by jackocnr** [comment]
Fixed in v10.0.4
