### ISSUE TITLE
Calling setNumber results in invalid number for some valid international numbers

### ISSUE THREAD

**Issue by darrenoshea** [jackocnr/intl-tel-input#535]
### Steps to reproduce
1.  Call setNumber with a valid Bahamas phone # in international format, i.e. +1 242-359-1234

or

1.   Go to the [Validation Demo](http://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html) and execute the following in console and observe the result:
```
$('#phone').intlTelInput('setNumber', "+1 242-359-1234");
$('#phone').intlTelInput('isValidNumber');
```

### Expected behaviour
Phone number is valid.

### Actual behaviour
Phone number is invalid.

### Initialisation options
From the [Validation Demo](http://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html):
```
$("#phone").intlTelInput({
  utilsScript: "../../build/js/utils.js"
});
```

**Comment by jackocnr** [comment]
Good catch! Fixed in v10.0.6.
