### ISSUE TITLE
getNumber produces unexpected results for certain formatting.

### ISSUE THREAD

**Issue by datasage** [jackocnr/intl-tel-input#536]
### Steps to reproduce
1.  Enter a number for St. Lucia so that its formatted +1 758-456-1000
2.  Call getNumber

### Expected behaviour
It should return +17584561000

### Actual behaviour
Instead it returns 758+1 758-456-1000

It looks like the problem will be pretty easy to fix. In `_getFullNumber` you are doing the following comparison `dialCode.substr(1) != normalizedVal.substr(0, 3)` The issue at this point is that normalizedVal starts with a space character. The code to normalize the value should trim any spaces.

**Comment by jackocnr** [comment]
Good catch! Fixed in v10.0.6.
