### ISSUE TITLE
auto flag change when type number in Canada selected flag

### ISSUE THREAD

**Issue by muzamil301** [jackocnr/intl-tel-input#537]
when i select Canada flag and type number without 204 country code, flag automatically change into Us flag and input passes +1 in country code with number.thanks for your response. you can test this scenario at intl-input-official-site

**Comment by pooja-mane** [comment]
For both countries dial code is **+1**, but placeholders are different as follow :
For Canada : placeholder= "(204) 234-5678"
For US : placeholder = "(201) 555-0123"
so when you select Canada and start with 201 then flag changes to US and when you select US and write 204 it changes to Canada.
its a validation for phone number for both countries.You can try for this.

**Comment by jackocnr** [comment]
Thanks @pooja-mane!

@muzamil301 you can see a list of all Canada's area codes here: https://en.wikipedia.org/wiki/List_of_North_American_Numbering_Plan_area_codes#Canada

If you type a non-Canadian area code, it will change the flag accordingly. Does that answer your question?

**Comment by muzamil301** [comment]
thanks @pooja-mane and @jackocnr thanks for your response and feedback. i have gotten your point.

**Comment by zohaib055** [comment]
i just typed the phone with area code from canada but it happens to me same after 3 digits

**Comment by JackmanBR** [comment]
i have this problem too, solution dont exists ?

**Comment by jackocnr** [comment]
@JackmanBR what is the problem?
