### ISSUE TITLE
grunt build issue

### ISSUE THREAD

**Issue by jatasya** [jackocnr/intl-tel-input#538]
Hi 
I tried installing the environment in the **vagrant ubuntu 14.04** 
 when the command "Running "exec:evenizer" (exec) task" is being run it is getting automatically killed

                       vagrant@vagrant-ubuntu-trusty-64:/vagrant/code/intl-tel-input$ grunt build
                        Running "responsive_images:retina" (responsive_images) task
                        Resized 257 files for 40x30

                        Running "exec:evenizer" (exec) task
                        Killed
                   
 I tried this "If when building, you get an error in the "exec:evenizer" task, you may need to temporarily increase the ulimit by running this command: ulimit -S -n 2048" even then also I'm getting the command getting killed.

In **vagrant** I have below packages\
                   /usr/lib
                 ├── bower@1.8.0
                 ├── evenizer@0.1.17
                 ├── grunt-cli@1.2.0
                 └── npm@3.10.10

 and in  **windows** i'm getting below error 

                         λ grunt img
                             Running "responsive_images:retina" (responsive_images) task
                             Resized 257 files for 40x30

                             Running "exec:evenizer" (exec) task
                         >> C:\Users\Vikas VP\AppData\Roaming\npm\node_modules\evenizer\lib\evenizer.js:43
                         >>         throw err;
                         >>         ^
                         >>
                         >> Error: Command failed:
                         >>     at ChildProcess.<anonymous> (C:\Users\Vikas  VP\AppData\Roaming\npm\node_modules\evenizer\node_modules\imagemagick\imagemagick.js:88:15)
                          >>     at emitTwo (events.js:106:13)
                          >>     at ChildProcess.emit (events.js:191:7)
                          >>     at maybeClose (internal/child_process.js:877:16)
                          >>     at Socket.<anonymous> (internal/child_process.js:334:11)
                           >>     at emitOne (events.js:96:13)
                           >>     at Socket.emit (events.js:188:7)
                            >>     at Pipe._handle.close [as _onclose] (net.js:498:12)
                           >> Exited with code: 1.
                           >> Error executing child process: Error: Command failed: evenizer --resize -i src/img/flags/@2x/*.png
                             >> C:\Users\Vikas VP\AppData\Roaming\npm\node_modules\evenizer\lib\evenizer.js:43
                             >>         throw err;
                             >>         ^
                              >>
                              >> Error: Command failed:
                              >>     at ChildProcess.<anonymous> (C:\Users\Vikas VP\AppData\Roaming\npm\node_modules\evenizer\node_modules\imagemagick\imagemagick.js:88:15)
                              >>     at emitTwo (events.js:106:13)
                              >>     at ChildProcess.emit (events.js:191:7)
                              >>     at maybeClose (internal/child_process.js:877:16)
                              >>     at Socket.<anonymous> (internal/child_process.js:334:11)
                               >>     at emitOne (events.js:96:13)
                              >>     at Socket.emit (events.js:188:7)
                              >>     at Pipe._handle.close [as _onclose] (net.js:498:12)
                         
                              Execution Time (2017-01-12 18:54:21 UTC+5:30)
                              responsive_images:retina  36.5s      ████████████████████████████████████████████████████████████████████ 88%
                            exec:evenizer              4.8s  █████████ 12%
                            Total 41.3s

IN **windows** I have intalled imagemagick and below packages
       λ npm list -g --depth=0
         C:\Users\Vikas VP\AppData\Roaming\npm
          +-- bower@1.8.0
          +-- evenizer@0.1.17
          +-- express-generator@4.14.0
          +-- grunt-cli@1.2.0
          +-- gulp@3.9.1
           `-- windows-build-tools@0.6.1

Is there anything I'm doing wrong

**Comment by jackocnr** [comment]
Well firstly I would say don't spend too much time worrying about the evenizer task - you only need that if you want to change the flag images. Assuming you don't need that, you can just remove it from the "build" task in [the Gruntfile](https://github.com/jackocnr/intl-tel-input/blob/master/Gruntfile.js#L11).

If you do need it, then it's worth noting that by using the exec task, all we're doing is running that command in the terminal, so you should see if running [that command](https://github.com/jackocnr/intl-tel-input/blob/master/grunt/exec.js#L5) in the terminal yourself causes problems, and if so, report them to the evenizer team.

**Comment by jatasya** [comment]
@jackonr I want to make the flags bigger for the input. So can I skip the
eveniser. Will it be fine.

**Comment by jackocnr** [comment]
That would be changing the images, so you would need evenizer!

**Comment by jatasya** [comment]
Ok I have raised the issue to the evenizer  developer will let you know if
I get a solution from them, Thank you for fast reply:-)
