### ISSUE TITLE
utils.js issue when deployed to prod environment

### ISSUE THREAD

**Issue by AbdulZaid** [jackocnr/intl-tel-input#540]
So everything works fine with me until I create a build for my app using gulp.

When the build is deployed I get this error: 

```bower_components/intl-tel-input/lib/libphonenumber/build/utils.js 404 ()```

it seems that the file isn't included or something! Anyone has a solution for this?

Thanks.

**Comment by jackocnr** [comment]
If you're using the `utilsScript` option, then you must host that utils.js file at the URL you provide, as it is loaded via ajax after the initial page load. Alternatively you can just point it to the file on a CDN - see the readme. I have updated the readme to be more clear.

**Comment by sentiasa** [comment]
@jackocnr I am trying to fetch the utilsScript from CDN however, I couldn't understand how to achieve it either.
```
 $("#number").intlTelInput({
       initialCountry: "us",
});

$.get( "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/12.1.12/js/utils.js" ).done(function() {
         $('#number').intlTelInput.loadUtils("https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/12.1.12/js/utils.js");
 });
```
I couldn't figure out how to make this approach work (with CDN)
