### ISSUE TITLE
Content Security Policy blocks unsafe-eval

### ISSUE THREAD

**Issue by kahuna76** [jackocnr/intl-tel-input#541]
Hi,

We have a strict CSP on our website that doesn't allow for eval calls. Somewhere in your code it must be doing just that: Without 'unsafe-eval' in the script-src section of the Content-Security-Policy header below code flags a valid number like +32477112233 as invalid. When you add 'unsafe-eval' it flags it as valid. I had a quick look through the code but can't immediately see calls that trigger eval.

Any idea where this would be ?

### Steps to reproduce

<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="/js/intltelinput/intlTelInput.min.js"></script>
<link type="text/css" rel="stylesheet" href="/css/intltelinputcss/intlTelInput.css" />	
<input type="text" id="phone">
<script>
$("#phone").intlTelInput({
	utilsScript: "/js/intltelinput/utils.js"
});
$("#phone").bind('blur',function(){
	if ($("#phone").intlTelInput("isValidNumber")) {
		alert('yay');
	} else {
		alert('boo');
	}
});
</script>

Now enter +32477112233 and blur

### Expected behaviour
alert(Yay)

### Actual behaviour
alert(Boo)

And in Firefox console:
Content Security Policy: The page’s settings blocked the loading of a resource at self

**Comment by jackocnr** [comment]
Ha that's weird. Neither intlTelInput.js or utils.js contain an eval statement. Hmm but a brief look at the minified jQuery in your example code there DOES include a call to eval. Could that be it? Not much we can do about that...

**Comment by yang-jandro** [comment]
Any solution for this?

**Comment by jackocnr** [comment]
A quick Google of "unsafe-eval jquery" shows this is a common problem and unrelated to this plugin.

**Comment by koczkatamas** [comment]
Well, it's a shame that jQuery is buggy, but you could avoid this behavior if you would replace this code:

```
    $.ajax({
      type: 'GET',
      url: path,
      complete: function() {
        // tell all instances that the utils request is complete
        $(".intl-tel-input input").intlTelInput("handleUtils");
      },
      dataType: "script",
      cache: true
    });
```

with this one or something similar (I am not sure about cross-browser support):

```
      let scriptEl = document.createElement("script");
      scriptEl.onload = function() {
        // tell all instances that the utils request is complete
        $(".intl-tel-input input").intlTelInput("handleUtils");
      };
      scriptEl.onerror = e => function() { /* TODO */ };
      scriptEl.src = path + "?_=" + Math.random();
      document.head.appendChild(scriptEl);
```
