### ISSUE TITLE
Inconsistent behaviour on update with getNumber method

### ISSUE THREAD

**Issue by sylfabre** [jackocnr/intl-tel-input#542]
I've noticed that `getNumber` method give inconsistent behaviour when your remove the last digit.

Using French phone number 0123456789 and then removing the last digit may returns the following numbers:
- +3312345678 (expected behaviour)
- +33012345678 (issue)
=> notice the 0 at the beginning

I've created two JSFilddles as a demo:
https://jsfiddle.net/sylfabre/fz3gcdxp/1/
https://jsfiddle.net/sylfabre/9p5gw430/1/

**Comment by jackocnr** [comment]
As per the readme for `getNumber`:

> Also note that this method expects a valid number, and so should only be used after validation.

**Comment by sylfabre** [comment]
@jackocnr Ok but method `isValidNumber` requires an international number: how may I get this number without `getNumber` method?

**Comment by jackocnr** [comment]
> Ok but method `isValidNumber` requires an international number

No, it works fine with national numbers too!

**Comment by sylfabre** [comment]
@jackocnr ok thanks and sorry for the trouble.

Actually I think this inconsistent behavior comes from `googlei18n/libphonenumber` as I can reproduce it here: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
`isPossibleNumber()` returns `true` for `012345678` + `fr` but `false` for `+3312345678`

**Comment by sylfabre** [comment]
https://github.com/googlei18n/libphonenumber/issues/1539

**Comment by jackocnr** [comment]
Good spot!
