### ISSUE TITLE
How to get Country Code after submitting the phone number by using POST request?

### ISSUE THREAD

**Issue by Mohayder** [jackocnr/intl-tel-input#543]
I've installed the plugin and Its displaying the countries correctly and working fine, but when I submit the form that has the input of type = "tel", the form does not submit the country code, I don't know how this works, but I did read all of instructions in [https://github.com/jackocnr/intl-tel-input](url) page, but I didn't understand how to get the full number + code country together so I can insert them into MySQL data base.

I'm so beginner, and just confused how to get this to work fine.
Sorry if the question is not that hard, but I really don't know how this works.
_______
The jQuery code I have:-

`$("#telephone").intlTelInput({
    initialCountry: "sd", // Sudan
    separateDialCode: true
});`

**Comment by jackocnr** [comment]
Please see the "Submitting the full international number when in nationalMode" section under Troubleshooting in the readme.
