### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by pjebs** [jackocnr/intl-tel-input#545]
I am currently using v9.0.9 direct from a javascript file.
I have now revisited the project and all the changes are overwhelming me.

Is v10 still backwards compatible? What are the advantages of moving over?
Is jQuery now removed as a dependency (since I'm using it in a react based project)?

**Comment by jackocnr** [comment]
Have you looked at the changelog (in the root dir of this project) - that should contain notes about any major changes. This project follows the semver convention, so any major version updates mean that there has been a breaking change. We still use jQuery.
