### ISSUE TITLE
Letters in the phone number are converted to numbers

### ISSUE THREAD

**Issue by snice1981** [jackocnr/intl-tel-input#548]
Hi

I would like to know if it's possible to tell the control to not interpret letters as numbers, but just show that it's an invalid number.
 
Today, if I do this:  $("#phone").intlTelInput("setNumber", "+32486123456 (GSM)") it will show +32486123456476 because I convert letters to numbers.

![image](https://cloud.githubusercontent.com/assets/25153628/22589418/8b9e85e6-ea0a-11e6-9412-5ef6a73b0c3a.png) 

Someone can help?

Thanks

**Comment by jackocnr** [comment]
If you set `formatOnDisplay` to false, then it will not do any formatting on init, or on `setNumber`

**Comment by snice1981** [comment]
So easy! Thanks!!
