### ISSUE TITLE
how to remove the + (plus) from the number?

### ISSUE THREAD

**Issue by pivotmobileapp** [jackocnr/intl-tel-input#551]
IMPORTANT: please note that the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
12687848783

### Actual behaviour
+12687848783

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
I don't understand - is this question related to the plugin? If so, please fill in the Steps to Reproduce...

**Comment by pivotmobileapp** [comment]
see photo link https://www.dropbox.com/s/60ss777zf1ts1su/plus.png?dl=0

**Comment by jackocnr** [comment]
So you want to hide the pluses in the dropdown? You can't hide just the pluses, but you could hide the whole international dial code using CSS with something like this:

`.intl-tel-input .dial-code {display: none;}`

**Comment by pivotmobileapp** [comment]
not just the dropdown, but when the user click on it it must not provide the plus in the input field, JUST the the numbers, without the plus

**Comment by pivotmobileapp** [comment]
1800 instead of +1800

**Comment by jackocnr** [comment]
But then it would not be a valid number. Why do you want that?

**Comment by pivotmobileapp** [comment]
when the user submit the numbers. it should not have + with it

**Comment by pivotmobileapp** [comment]
the sms server im in using to send to a saint lucia.. only works without +

**Comment by jackocnr** [comment]
well then why don't you just remove the plus on your backend, after the user submits the number?

**Comment by pivotmobileapp** [comment]
thats the thing, i dont know how to do that

**Comment by pivotmobileapp** [comment]
i just want to customise it for Saint Lucia

**Comment by jackocnr** [comment]
Well what language are you using on the backend to handle the form submission?

**Comment by pivotmobileapp** [comment]
its an app build with javascript.... phonegap... and backend is php

**Comment by pivotmobileapp** [comment]
www.mealoop.com
app: http://smarturl.it/mealoop

**Comment by jackocnr** [comment]
Ok then google "php substring" and figure out how to create a substring of all but the first character.
