### ISSUE TITLE
Add pattern to input to make it easyer to input on mobile

### ISSUE THREAD

**Issue by erikandershed** [jackocnr/intl-tel-input#552]
How do I add mobile numbers keyboard to the input, the pattern="[0-9]*?. This will make a nicer the user experience

**Comment by jackocnr** [comment]
Probably by using the right input type in the markup.

**Comment by erikandershed** [comment]
No it do not work. Where in the code do you change the input?

**Comment by erikandershed** [comment]
Sorry. It do work! :)
