### ISSUE TITLE
cant see placeholder

### ISSUE THREAD

**Issue by ilyapashkov** [jackocnr/intl-tel-input#553]
Hello, i want use plugin< but placeholder dont work, can u help me?

**Comment by jackocnr** [comment]
Please show me your `<input>` HTML and tell me which initialisation options you're using.

**Comment by M-Veselinov** [comment]
I kinda have the same issue. There is no place holder set on my input and still the plugin does not add his own.
Here is how I initialize it.

` var $comp = $('<tr>' +
                '<td>' +
                '<input class="separateInput" value=""/>' +
                '</td>' +
                '</tr>');

        var $input = $("input", $comp);

        $input.intlTelInput({
            nationalMode: false,
            initialCountry: ""
       });`

**Comment by jackocnr** [comment]
Closing due to lack of response from the op.
