### ISSUE TITLE
how to get country code and mobile no diffrently

### ISSUE THREAD

**Issue by manojkumar7488** [jackocnr/intl-tel-input#554]
how to get country code and mobile number differently
eg. country code : 91
and mobileno : 889898**********
like this please help me out

**Comment by jackocnr** [comment]
You can get just the national number with `getNumber` by passing in `intlTelInputUtils.numberFormat.NATIONAL` as an argument.

And you can get the intl dial code with `getSelectedCountryData`.

**Comment by manojkumar7488** [comment]
thanks
