### ISSUE TITLE
Use emoji flags when it's available

### ISSUE THREAD

**Issue by tinovyatkin** [jackocnr/intl-tel-input#555]
Hello,

I'd love to share my emoji flags use, just don't sure how to do it correctly at current project step.

I do it at the build step, having emoji as default ('mobile first' approach), below it's a fragment of my build script, that basically replacing your sprites with native emoji (it's simplified version of my script, just for the idea):

```javascript
const countries = require('world-countries');

function rejector(url, file) {
  if (url === 'sprite' && file.endsWith('intlTelInput.scss')) {
    // we will replace sprites with our flags
    // Originally is like
    /*
    .iti-flag {
      width: 20px;
        &.ca {
        height: 10px;
        background-position: -834px 0px;
      }
    }

    We should replace with compiless CSS code, like

    .iti-flag.ca::before { content: '🇨🇦' }
    */
    return {
      contents: [].map.call(countries, ({ cca2 }) => `.iti-flag.${cca2.toLowerCase()}::before { content: '${flag(cca2)}' }`).join('\n'),
    };
  }
  return null;
}

const sassOptions = {
  importer: [rejector],
};
```
So, basically I strip out your implementation of flags at build level.

Then at the client script I'm checking if client have good support for colored emoji flags (for example, Microsoft Edge supports a lot of color emoji, less flags):

```javascript
// global detection if we could use emoji for flags
const tino = {
  goodEmoji: (({ platform, vendor, userAgent }) => {
    // Apple OSes supports emoji as well as Androin
    if (/Apple/i.test(vendor) || /Android/i.test(userAgent)) return true;
    // Firefox starting version 50 supports color emoji on all platforms via EmojiOne
    // const match = /Gecko.*Firefox\/(\d+)/.exec(userAgent);
    // return match && parseInt(match[1], 10) >= 50;
    return false;
  })(navigator),
}

// fallback detection for other platform that MAY have good emoji flags - we just draw chineese flag and check how red it is
  // test emoji
  if (!tino.goodEmoji) {
    const pixelRatio = window.devicePixelRatio || 1;
    const offset = 16 * pixelRatio;
    const node = document.createElement('canvas');
    const ctx = node.getContext('2d');
    ctx.fillStyle = '#f00';
    ctx.textBaseline = 'top';
    ctx.font = `${offset * 2}px "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiOne Color", "EmojiSymbols"`;
    ctx.fillText('🇨🇳', 0, 0); // chineese flags should be more or less red
    const { data: [color] } = ctx.getImageData(offset, offset, 1, 1);
    // if it's not a gray
    if (color > 100 && color < 255) tino.goodEmoji = true;
  }
```

then at moment of initialising your script I do fallback:
```javascript
  // Load full CSS and flags on platforms without good emojii flags support
  // Currently flags are looking great on all Apple OSes and Android
  if (!tino.goodEmoji) {
    // Injecting CSS to remove flags emoji generated content
    document.head.insertAdjacentHTML('beforeend', "<style>div.iti-flag::before{content:''!important;}</style>");
    tino.loadCSS(`${basepath}/css/intlTelInput.css`);
    // Preload flag image, using media query from intlTelInput sources
    const flagsImage = new Image();
    if (window.matchMedia('(-webkit-min-device-pixel-ratio: 2), (min--moz-device-pixel-ratio: 2), (-o-min-device-pixel-ratio: 2 / 1), (min-device-pixel-ratio: 2), (min-resolution: 192dpi), (min-resolution: 2dppx)').matches) flagsImage.src = `${basepath}/img/flags@2x.png`;
    else flagsImage.src = `${basepath}/img/flags.png`;
  }
```

So, it may looks complicated, but it's mostly because of workarounds... Anyway, I'm sure that Unicode 9 and flags emoji are the future and must be adopted at some stage, even if we don't want to count on additional download emoji can save...

Production working example is at last step of https://transfers.do/book/

**Comment by jackocnr** [comment]
Thank you for providing this - very interesting indeed!

Yes it is great that this avoids the large flag sprite download (currently 170KB for the retina image). And it's great that emoji are vectors, so they look great at any size. (on this topic, I think you could actually display the flag emoji on your website a bit bigger as they're currently kinda hard to see)

Also you seem to be missing 3 flags: Caribbean Netherlands (🇳🇱), Central African Republic (🇨🇫) and Saint Helena (🇸🇭).

Can I ask: when you do `flag(cca2)` where does the `flag` function come from?

Just a note to myself/others: it looks like in your fallback situation, you're loading the CSS via some custom `loadCSS` method - I'm not sure how this works internally, but all you would need to do would be to inject a new `<link rel="stylesheet" href="...">` element.

My main concerns with this approach are:

1. Maybe people don't like the way the emoji look, with the curved edges.
2. It's a pain to have to generate a separate fallback stylesheet and host it to be loaded separately.
3. Emoji support on different platforms. You mention it works fine on iOS and Android, and I'm can see it works on MacOS, but what about Windows/Linux?

**Comment by jackocnr** [comment]
Further to my first concern about how the flags look, they look very different on different platforms - you can see a breakdown here: http://emojipedia.org/flag-for-united-states/

<img width="289" alt="screen shot 2017-02-18 at 10 20 39 am" src="https://cloud.githubusercontent.com/assets/1186883/23095748/f28adb5a-f5c3-11e6-8d25-00c1c0a6a78d.png">

**Comment by jackocnr** [comment]
And on my Android phone, unfortunately they're all really wavey, which I don't like:

![screenshot_20170218-101806](https://cloud.githubusercontent.com/assets/1186883/23095765/420453aa-f5c4-11e6-8e3d-a3bc151a8dbc.png)

**Comment by tinovyatkin** [comment]
Well, they look 'native' on every platform - and that is very good approach at UI design as far I understand. And they are gorgeous on retina without any downloads...
The thing is, that they can be optional - my approach is lazy loading full CSS/PNG sprites after smaller retina version download... 80% of your CSS size - it's sprites...

**Comment by jackocnr** [comment]
Yes I agree there are some great advantages.

That said, I have just come across a new issue: as well as the flags displaying different on different platforms, they also have different flags missing, so on my mac it was just those 3 flags I mentioned above were missing, but now that I check on my Android phone, there are loads more that display the initials of the country instead of the flag:

![screenshot_20170218-105439](https://cloud.githubusercontent.com/assets/1186883/23096025/779441a6-f5c9-11e6-8939-b06fade0c993.png)

**Comment by tinovyatkin** [comment]
Flag emoji currently can be enabled in Chrome on Linux (that why I have last detection with Chinese flag), but no way for Windows yet (Edges supports all color emoji less flags).

loadCSS in my example is my global function for non-blocking CSS load, it's a little bit complicated (I do XHR load and localStorage caching for CSS), but you rights, it can be simplified to just Link injection

**Comment by jackocnr** [comment]
The latest Android phone/version has the same missing flags, but handles them better:

<img width="300" src="https://cloud.githubusercontent.com/assets/1186883/23096282/a98b9bba-f5cd-11e6-8a1b-5ef2214dfa4f.png">

I also tested in the latest iPhone/iOS and it's similar to on my mac: it has all flags except for Caribbean Netherlands and Saint Helena.

**Comment by tinovyatkin** [comment]
I think that with dropping IE8 users you are cutting away even more user base than with these countries... OS default fallback to two letters is not such bad... and emoji gets updated constantly...

**Comment by tinovyatkin** [comment]
I forgot to respond your question regarding country code - it comes from `world-countries` require on top of my example, but there is a lot of similar libraries and you need it only at build stage

**Comment by jackocnr** [comment]
Ok you have convinced me! I would be happy to review a pull request to add this functionality to the plugin, as an option that people can enable e.g. `emojiFlags`.

I think that for now it should only be for Apple and Android, because those are the only platforms where we can be confident that the experience is good enough. Then we'll open it up to other platforms whenever we've done the research and we're confident the support is there.

So I guess we should modify the CSS build process to output 3 stylesheets: (1) the current one, (2) this new emoji one, and (3) the slimline fallback one, to be lazy loaded, which just contains the flag styling.

Then it's up to the user to choose which stylesheet to include in their project, and we'll need a new initialization option to pass in the URL for the fallback stylesheet e.g. `nonEmojiStylesheet`.

Thanks Tino!

**Comment by tinovyatkin** [comment]
i hope to do that in next couple of days!

**Comment by Samb102** [comment]
Hello, is that possible to share the emoji flags .PNG ?

**Comment by jordanful** [comment]
Another vote for an emoji flag option! It'd be great.
