### ISSUE TITLE
getNumberType with utilsScript  and done(callback) giving different answers

### ISSUE THREAD

**Issue by didididi2** [jackocnr/intl-tel-input#556]
this is the script
```
telInput.intlTelInput(
	{utilsScript :'/vendor/intl-tel-input/js/utils.js',
	allowDropdown:false,
	}).done(function() {
		var numberType = $("#formatphone").intlTelInput("getNumberType");
		console.log (numberType);
	});
```
i'm using the plugin to display a int number in a formated way. i want to display also the type of the line.
so i'm using utilsScript and waiting for it to load by the done(callback).
the problem is for exemple mobile number some times it dispays 1(mobile) and some times it dispalys -99 (broken)

**Comment by jackocnr** [comment]
You're instantiating the plugin on `telInput` and then calling `getNumberType` on `$("#formatphone")`. Is that a different instance?

**Comment by didididi2** [comment]
same instance 
didn't copy this in the post
var telInput = $("#formatphone");

**Comment by jackocnr** [comment]
Hmm. What mobile number do you have in the input?

And can you put a JavaScript breakpoint in the `done` callback, and check that window.intlTelInputUtils exists when it's failing?

**Comment by didididi2** [comment]
that was my fault.
the number is stored in a session and populated the `$("#formatphone")` in another function. that's why there was an error of 2/10 depending on which function executes first :-(
just wrote them in the same function and all working like a charm.
thanks a lot for your help
