### ISSUE TITLE
 Not working using AJAX call (ajax form)

### ISSUE THREAD

**Issue by osamaJetawe** [jackocnr/intl-tel-input#563]
Hi There,

I have an issue , if you can help me.
when I use this widgets inside a from loaded using AJAX (modal) , the onchange event on input not working and the form submitting with empty phone number field. 

all form loaded using ajax call.

Do you have any suggestion?

Thanks
Osama

**Comment by hdehal** [comment]
What's your code? 

I created an AJAX call on submit using intl-tel-input-11.0.0 last night and it worked fine.

**Comment by romankubis** [comment]
Hi,
I am using version 12.1.15 and I have same problem. I am loading part of form with ajax with phone input. Validating works only on first call of ajax. If I call ajax second time, plugin returns error "The string supplied did not seem to be a phone number.".
