### ISSUE TITLE
Country doesn't change from pre-entered international dial code

### ISSUE THREAD

**Issue by lucasket** [jackocnr/intl-tel-input#564]
### Steps to reproduce
1.  Pre-fill the input with an international congolese number: +242066637556
2.  Initialise intl-tel-input on the input element
3.  Once utils.js has been loaded during the initialisation, call a function that validates the input.  The function uses the boolean `$('#phone').intlTelInput('isValidNumber')` to display (or not) error messages. It is called afterwards on each `'blur'` event.
```javascript
$('#phone').intlTelInput({
	utilsScript: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/11.0.4/js/utils.js',
	nationalMode: true,
	autoPlaceholder: "off",
	onlyCountries: [
		"cm", "td", "cg", "ga"
	],
	dropdownContainer: "body"
}).done(function() { // Once utils.js, necessary for validation, is loaded
	preValidateForm(); // Run the function on page load to detect whether the pre-entered number is valid
});
```

### Expected behaviour
From what I understand, intl-tel-input is supposed to use the international dial code to change the country.

### Actual behaviour
Congolese international dial code is removed, the displayed flag remains the one of the first country in the list (Cameroon). When no warning is displayed, it means `$('#phone').intlTelInput('isValidNumber') = true` has been verified.

![peek 09-03-2017 16-35](https://cloud.githubusercontent.com/assets/24525512/23757211/74021014-04e6-11e7-826b-abef5c74e3b4.gif)

**Comment by jackocnr** [comment]
Well first of all, let's deal with one issue at a time. If you remove the `.done()` validation stuff and just init the plugin - does it select the right country?

**Comment by lucasket** [comment]
No, it still takes the first country from the list.

**Comment by lucasket** [comment]
Problem solved, using `setNumber` to set the country instead of `.val()`. Sorry I didn't read the doc more thoroughly.
