### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by ajoudeh** [jackocnr/intl-tel-input#565]
Ho i can set validation to phone to be Mobile Or Landline?

**Comment by jackocnr** [comment]
Use `getNumberType`.

**Comment by ajoudeh** [comment]
Dear, i use this code to validation:

[['phone'], PhoneInputValidator::className(), 'type' => PhoneNumberType::MOBILE]

this allow only Mobile, when  i use PhoneNumberType::FIXED_LINE_OR_MOBILE, it not working as we expect. 
Ex:
* (Mobile) +962797986466  => not valid ==> type = 1
* (Landline) +96265403949 => not valid ==> type = 0

so any solution?

Thanks,

**Comment by jackocnr** [comment]
I don't understand your code - you must be using some other lib/framework, but you can see all of the [number type enums here](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/utils.js#L119) and so if you want to allow mobile or landline then you need to use `getNumberType` and check that the result is equal to either `intlTelInputUtils.numberType.MOBILE` or `intlTelInputUtils.numberType.FIXED_LINE` or `intlTelInputUtils.numberType.FIXED_LINE_OR_MOBILE`.

**Comment by ajoudeh** [comment]
Yes i used Yii framework. i will contact them to solve this issue. 

Thanks
