### ISSUE TITLE
Internationalization for "Wallis and Futuna"

### ISSUE THREAD

**Issue by Mastersnes** [jackocnr/intl-tel-input#577]
Hi,
There is some country which have not there name in the country language (for example Wallis and Futuma which is a french overseas country, has not "Wallis-et-Futuma" in his name)

### Steps to reproduce
1.  Click on the flag select
2.  Find "Wallis and Futuma" country

### Expected behaviour
The name should be "Wallis and Futuma (Wallis-et-Futuma)

### Actual behaviour
The name is "Wallis and Futuma"

![wallis and futuma](https://cloud.githubusercontent.com/assets/14359450/24556213/f05451e6-1633-11e7-9372-29b55766e979.jpg)

**Comment by jackocnr** [comment]
Thanks for pointing this out. I will gladly accept a pull request to add a translation to any country where the local name is different to the English name. Also I think we could remove a few where the translation is the same e.g. Saint Barthélemy. All you would have to do is update the right line in src/js/data.js.

**Comment by jackocnr** [comment]
@Mastersnes the first step would be writing a list of all countries that need a translation (where the local name is different to the English name), and posting it here. Oh, and maybe also include any countries that currently have a translation that is unnecessary (it is the same as the English). Is that something you would be willing to do?

**Comment by Mastersnes** [comment]
@jackocnr Sorry but i don't have the time to do that now, maybe this weekend.

**Comment by jackocnr** [comment]
Any update on this?

**Comment by Mastersnes** [comment]
No sorry, really don't have the time.

**Comment by willashley23** [comment]
I can make those two changes (removing redundant Saint Barthelemy and adding translation for Wallis and Futuna).

**Comment by jackocnr** [comment]
Thanks @willashley23 - I look forward to your pull request!

**Comment by willashley23** [comment]
@jackocnr Take out two birds with one stone. https://github.com/jackocnr/intl-tel-input/pull/605

**Comment by jackocnr** [comment]
Fixed in v11.1.2, thanks @willashley23!
