### ISSUE TITLE
Need Country Dropdown Open and Close Event

### ISSUE THREAD

**Issue by Sundarasan** [jackocnr/intl-tel-input#579]
Need events for country dropdown open and close.

I need to make few style changes on parent div on opening and closing of country dropdown.
So it would be great if I get event on those.

Something like this...
```javascript
$phoneNumberInput.on('open:countrydropdown', function () {
  // Do stuffs here...
});

$phoneNumberInput.on('close:countrydropdown', function () {
  // Do stuffs here...
});
```

**Comment by jackocnr** [comment]
Sure. This has been requested a few times now. 

I don't have time to implement this myself, but would be open to a pull request 👍

**Comment by jackocnr** [comment]
Thanks @willashley23 for adding the close event! Would you be up for adding the open event as well?

**Comment by willashley23** [comment]
@jackocnr Yeah I'd love to. I'll try to get to it some time this week.

**Comment by jackocnr** [comment]
Added in v11.1.6
