### ISSUE TITLE
Feature: Search input

### ISSUE THREAD

**Issue by akkhan20** [jackocnr/intl-tel-input#584]
any plans for search input like [select2](https://select2.github.io/). i understand the plugin can search even now but a lay man doesn't recognize this functionality and goes down the list to find desired country, geo ip is a fine feature but that is not the case in every scenario.

**Comment by jackocnr** [comment]
Certainly no plans on my part. That said, I would be open to a pull request that didn't add too much weight to the plugin.

**Comment by jackocnr** [comment]
See new option `countrySearch` in v18.5.1. Let me know what you think!
