### ISSUE TITLE
NPM is broken on last version

### ISSUE THREAD

**Issue by HawkonDK** [jackocnr/intl-tel-input#585]
The `$ npm i intl-tel-input` is broken, keep getting error:`no such file or directory` 
works fine with `$ bower` btw

**Comment by jackocnr** [comment]
Works fine for me. Not sure what to suggest. Maybe try it in another directory?

**Comment by HawkonDK** [comment]
have contact npm support to ask if this is a problem they know or it the package

**Comment by jackocnr** [comment]
We get 1000 downloads a day from the NPM repo, and no one else has complained, so I'm afraid this must be a problem with your setup.
