### ISSUE TITLE
Uneditable dial code ?

### ISSUE THREAD

**Issue by pepe643** [jackocnr/intl-tel-input#586]
Hi, 

Love this plugin works great, good work. I like to know how to make the dial code uneditable after inserted when is set like below.
 
// if there is just a dial code in the input: remove it on blur, and re-add it on focus
        autoHideDialCode: true, 

Thanks;
pepe643

**Comment by jackocnr** [comment]
Try the option `separateDialCode` - does that do what you want?

**Comment by pepe643** [comment]
Hi,

Thanks for your prompt response and sure I have try that and is the same thing I want but it has to be inside the input so it would be added to the cart when is submit. I'm using woocommerce. 

Thanks;
pepe643

**Comment by jackocnr** [comment]
You could use JavaScript to put the full number (using `getNumber`) in the input (or into another hidden input) when the form is submitted.

But otherwise, no there is no way to have the dial code in the input and prevent it from being edited.
