### ISSUE TITLE
Not working when used in scope of ng-repeat. 

### ISSUE THREAD

**Issue by MirzaHammad** [jackocnr/intl-tel-input#588]
Hi, 
I used this plugin many times, every thing worked well for till now. I am facing a problem while loading phone field inside `<ng-repeat>` tag. The default flag (based on ip) is listed but field is not clickable. 

I need this `<ng-repeat>` tag because I want to allow user to enter multiple contacts.
here is HTML code 

`<div` ng-repeat="emergencyContact in emergencyContacts | orderBy:'-emergencyContact.Order'" class="col-md-12 no-gutter">
`<ng-form` name="urlForm">
`<input`  name="employee_add_emergency_mobile_number1" ng-model="emergencyContact.ContactNumber"  type="text" class="form-control phone-flag" placeholder="Mobile number" ng-required="true" >

Here is script. 

`$(".phone-flag").intlTelInput({`
            utilsScript: $.fn.intlTelInput.loadUtils `("<?php` echo base_url('assets/scripts/angular/countries/js/utils.js'); ?>")
        });
and one more thing all the countries are listed in HTML. just lick event is not working. 

Kindly help how can I make this field clickable.

**Comment by jackocnr** [comment]
I'm sorry but this sounds like an Angular issue which is outside the scope of this plugin.

**Comment by yasirrafiq33** [comment]
I am also facing the same issue.
