### ISSUE TITLE
destroy method question

### ISSUE THREAD

**Issue by Dcatfly** [jackocnr/intl-tel-input#591]
When I use the destroy method of the component, the component does not destroy his internal stored data, especially the [autoCountry](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js#L443) attribute and the [startedLoadingAutoCountry](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js#L445) attribute, which results in a second initialization without going into the geoIpLookup method.

**Comment by jackocnr** [comment]
Yes we assume that your country has not changed between initializations! Is that not a fair assumption? What exactly is the problem?

**Comment by Dcatfly** [comment]
Thank you for your reply. Your assumption is right, I was wrong. I thought the destroy method should destroy all the data, but according to your ideas, indeed the country should not be changed, I only need to get the selected country data can be in the component after initialization. Thank you.

**Comment by jackocnr** [comment]
👍
