### ISSUE TITLE
Show ISD code instead of Flags once selected

### ISSUE THREAD

**Issue by ramansharma89** [jackocnr/intl-tel-input#592]
Is there a way to show ISD codes instead of country flag when that country is selected from dropdown?

**Comment by jackocnr** [comment]
You can use the `separateDialCode` option to show the dial code in the flag area, and then if you really wanted to hide the selected flag you could do it with CSS.

**Comment by ramansharma89** [comment]
Thanks a lot bro. :)

**Comment by jackocnr** [comment]
Just to let you know, we've recently added a showFlags option, which you can set to false to hide all flags. (still recommend using it with separateDialCode option to show the selected dial code instead of the flag)
