### ISSUE TITLE
initialCountry overridden when international dialcode is present in phone number

### ISSUE THREAD

**Issue by johnwnowlin** [jackocnr/intl-tel-input#593]
### Steps to reproduce
1.  set initalCountry to "ca"
2.  intlTelInput("setNumber", "+11234567890")

### Expected behaviour
the candian flag should be the default for the closed dropdown

### Actual behaviour
the us flag is there

### Initialisation options
allowDropdown: true,
                    initialCountry: countryAbbreviation(),
                    onlyCountries: [_countryEnumerations.usa, _countryEnumerations.ca],
                    separateDialCode: true,
                    autoPlaceholder: "off",
                    utilsScript: intlTelInputUtils

my current workaround is to remove the +1 from the phone number in the setNumber function.

**Comment by jackocnr** [comment]
The problem is that you're calling `setNumber` with a non-Canadian number!

If you're storing the number in full international format (which it looks like you are), then you shouldn't need to use `initialCountry` - it should automatically set the country based on the provided dial code.
