### ISSUE TITLE
NGINX 405 method not allowed while loading utils.js using utilsScript crossDomain

### ISSUE THREAD

**Issue by ajoyoommen** [jackocnr/intl-tel-input#595]
## Problem
I have embedded a script that loads JS from my server. This JS script initializes the plugin like this:

            telInput.intlTelInput({
                initialCountry: country_code,
                utilsScript: '/static/js/utils.js'
            });

This code fails on the browser with `405 Method not allowed` (Method shown on browser network log is `OPTIONS`).

## Solutions tried

* Added `error_page 405 = $uri`, browser raises: Header Access-Control-Allow-Origin missing
* Added header `Access-Control-Allow-Origin` but now browser refuses to open the file saying:

      XMLHttpRequest cannot load http://site.com/static/js/utils.js. Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.

How can this be solved?

**Comment by jackocnr** [comment]
It uses a GET request: https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js#L1310

But sorry I have no experience with NGINX so I cannot help.

**Comment by ajoyoommen** [comment]
Until I figure out the actual problem, this is a workaround:

Serve `utils.js` using the webserver instead of NGINX

**Comment by ajoyoommen** [comment]
Cross-domain AJAX GET might have be interpreted incorrectly by NGINX which might be causing this issue, however, I am not sure if that is the case.

**Comment by jackocnr** [comment]
BTW if the included `loadUtils` function (linked above) does not fulfil your needs, you can override that function yourself and make changes to the Ajax call and keep the rest the same.

Any new information to contribute to this issue, or can I close it?

**Comment by tinovyatkin** [comment]
`OPTIONS` is a part of browser CORS preflight checking, so, you probably servicing `int-tel-input` from a different domain and need to configure CORS in NGINX. There is a lot of documentation regarding that in the internet, but basically it's two headers to be added: `Access-Control-Allow-Headers: *` and `Access-Control-Allow-Origin: *`

**Comment by jackocnr** [comment]
Thanks @tinovyatkin. Closing this for now.
