### ISSUE TITLE
Uncaught ReferenceError: allCountries is not defined

### ISSUE THREAD

**Issue by zpwebbear** [jackocnr/intl-tel-input#596]
### Steps to reproduce
1.  install 
2.  set up
3.  dont working

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries
no options

**Comment by jackocnr** [comment]
I'm afraid this is not enough information to help you. Please try to reproduce your issue in a codepen and post a link here.

**Comment by DavidCain** [comment]
@zpwebbear - odds are quite good that you're mistakenly including `src/js/intlTelInput.js` as the complete dependency. If you do this, the absence of the variable `preferredCountries` should be the first error that arises.

`preferredCountries` is a variable defined in `js/data.js`, but referenced in `js/intlTelInput.js`. When the package is distributed, these files are concatenated - the error won't arise there.

What you probably want to do is include the complete build of `intl-tel-input`, which can be found at `build/js/intlTelInput.js`.

**Comment by zpwebbear** [comment]
Ohhhh! What a stupid mistake! :( I'm sorry for taking your time. Thanks!!!

**Comment by jackocnr** [comment]
Good catch @DavidCain, thanks!

**Comment by investlim** [comment]
@DavidCain, Thanks a lot =) Very helpfull
