### ISSUE TITLE
Bigger flags please

### ISSUE THREAD

**Issue by ionatower** [jackocnr/intl-tel-input#597]
How can we use bigger flags? Tried to look at https://github.com/behdad/region-flags but I guess this gets compiled specifically for intl-tel-input?

**Comment by jackocnr** [comment]
On the demo site there is a link to a Large flags example.

**Comment by ionatower** [comment]
Thank you, we will try that - by the way, your example doesn't show the large flags, just really big writing at: https://codepen.io/jackocnr/full/ONXWgQ

**Comment by jackocnr** [comment]
Thanks for pointing that out - I think it's broken because Codepen now force everything to be HTTPS, and so it wont load my non-HTTPS assets... I'll fix it soon.

**Comment by jackocnr** [comment]
Fixed!
