### ISSUE TITLE
Readme flag size change suggestion

### ISSUE THREAD

**Issue by ionatower** [jackocnr/intl-tel-input#598]
I had a bit of trouble updating the flag sizes and eventually figured it out. I made a fork at https://github.com/ionatower/intl-tel-input with a readme to explain and a spreadsheet to work out the retina and normal flag sizes. I hope this helps.

Add to readme:
## Resize flag images on Mac
1. Check out this repo and go to folder
2. install at command line: `brew install imagemagick`
3. install at command line: `brew install graphicsmagick`
3. Use spreadsheet to calculate the image dimensions based on your design
4. Update retina numbers in grunt/responsive_images.js
5. Update the $flagHeight and $flagWidth variables in src/css/intlTelInput.scss
6. if you are checking out for the first time run command in folder: `npm install`
7. Install `npm install evenizer -g`
8. run command: `grunt build`

**Comment by jackocnr** [comment]
Thanks for posting this here. I'm not going to add it to the readme as it is not a common use case, but you could potentially add a wiki page if you wanted to. Anyway, I'll close this for now, but people can still find it if they search for it.

**Comment by padu** [comment]
This seems to be a common usecase, as plugin uses png for flags and background positions for style. plugin restricts common users to use default flag size
