### ISSUE TITLE
Difficulty to get both the country code and the phone number. Only the phone number is getting sent.

### ISSUE THREAD

**Issue by eddywm** [jackocnr/intl-tel-input#599]
### Expected behaviour
I was expecting to get both the **country code** and the **phone number**.

### Actual behaviour
I am only getting the phone number  when making a post request http submission, but the country code is not showing up. I have tried to follow with the manual but with no success.

### Initialisation options
```

$("#phone").intlTelInput({
      utilsScript: "build/js/utils.js"
    });
```

**Comment by bntzio** [comment]
Are you getting the full number with `.intlTelInput("getNumber")`?

Example: `const fullNumber = $("#phone").intlTelInput("getNumber")`

**Comment by jackocnr** [comment]
The plugin does not create any extra inputs for you. Please see the [Recommended Usage](https://github.com/jackocnr/intl-tel-input#recommended-usage) section of the readme.

**Comment by eddywm** [comment]
Problem solved. Thanks
