### ISSUE TITLE
validation not working when form is loaded through Ajax

### ISSUE THREAD

**Issue by Codist2** [jackocnr/intl-tel-input#600]
When the form is not loaded through Ajax it works fine but when loaded through Ajax i.e jQuery('#theform').load('myform.html'); only the flag for the default country initializes. 

### Expected behaviour
telInput.intlTelInput("isValidNumber") to provide the Boolean answer true/false 

### Actual behaviour
telInput.intlTelInput("isValidNumber") is always false 

### Initialisation options

telInput.intlTelInput({
	 allowDropdown: false,
	onlyCountries: ['bw'],
	nationalMode: false,
  utilsScript: '//cdnjs.cloudflare.com/ajax/libs/intl-tel-input/8.5.2/js/utils.js'
});

**Comment by jackocnr** [comment]
Can you confirm that the utils script is loading successfully? i.e. if you type window.intlTelInputUtils in the JS console, does it exist?

**Comment by Codist2** [comment]
Its **not** loading, it does not exist, What could I be missing? 
but when I test myform.html without loading it through jquery  everything works perfectly, and if  I type window.intlTelInputUtils in the JS console, sure the utils exists?

**Comment by jackocnr** [comment]
Are you waiting until after the form HTML has loaded to initialise the plugin?

If you look in Chrome devtools, under the network tab, is it making the request to load utils.js?

**Comment by Codist2** [comment]
I have tried to wait, but it never loads, no request at all. also tried to initialise the plugin within $( document ).ready(function() but no change at all

**Comment by jackocnr** [comment]
Initialising the plugin in the `document.ready` callback will not work if you're loading the form html asynchronously. You just need to make sure you're only initialising the plugin AFTER you have loaded and displayed the form html.

If you're still having problems, please try to replicate the problem in a codepen.

**Comment by Codist2** [comment]
I have put it on codepen, the link is https://codepen.io/codist/pen/rwezbx

**Comment by jackocnr** [comment]
I don't understand - the link says "Click to load the form" but it doesn't seem to do that?

**Comment by jackocnr** [comment]
Also instead of pasting jQuery into the JS section, it's better to click the cog icon at the top and add jQuery in those settings instead. Then your custom JavaScript code is much more readable!

**Comment by Codist2** [comment]
Now working fine ,
I think something was wrong with the old scripts which I had, When I used
the cdn in codepen it started working fine thank you.
I have also managed to cleanup my code in codepen thanx

**Comment by jackocnr** [comment]
Glad you got it working 👍
