### ISSUE TITLE
question about your intl-tel-input flag in drop down

### ISSUE THREAD

**Issue by sarwatw** [jackocnr/intl-tel-input#601]
Thanks for this library.  I am wondering if there is a way to hide the flag from the drop down?

![phonelibraryquestion](https://user-images.githubusercontent.com/22648606/26899359-bc557674-4b83-11e7-941e-1b96d7adb8ad.PNG)

**Comment by jackocnr** [comment]
This question has been answered before - please search existing issues before posting a new one.
