### ISSUE TITLE
Can the flag be replaced by the iso-2/iso-3 country code?

### ISSUE THREAD

**Issue by sarwatw** [jackocnr/intl-tel-input#602]
Hi 

I am wondering if there is an easy way to replace the flag and in the drop down and instead insert a 3 letter country code in its place.  Basically anywhere we see a flag in the drop down, it gets replaced by the 3 letter country code.  I tried searching the issues section for this but didn't find anything.  Sorry if this has already been answered.

**Comment by jackocnr** [comment]
No the plugin does not provide this functionality, and furthermore, we use 2 letter country codes, not the 3 letter codes.

It wouldn't be hard to write some JavaScript to iterate over the dropdown items and pull out the 2 letter country code and inject that in place of the flag.
