### ISSUE TITLE
+91 79099 86459 shows as invalid number?

### ISSUE THREAD

**Issue by kmrritesh** [jackocnr/intl-tel-input#603]
I tried this number on libphonenumber demo. It says it is a valid number. However intlTelInput.js gives it as invalid number. Please look into the issue. It's a number from India. Network provider is reliance Jio. You can see the result in libphonenumber demo from below link :- 
https://giggsey.com/libphonenumber/?phonenumber=%2B917909986459&country=&language=&region=

**Comment by jackocnr** [comment]
Works for me: https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html

Please make sure you're using the latest version.
