### ISSUE TITLE
Set initialCountry by dial code

### ISSUE THREAD

**Issue by Abhi0725** [jackocnr/intl-tel-input#607]
### Expected behaviour
The initialCountry option should accept dial code too. For e.g if I get '+91' I can easily set the initial country as India instead of giving it 'IN'.

### Actual behaviour
Currently we need to mention country code instead of dial code to select default/initial country.

**Comment by jackocnr** [comment]
Please can you explain your use case? How do you get just the dial code '+91'? Are you storing that separately in the database?

**Comment by Abhi0725** [comment]
Actually I need to store the mobile number of the user along with the dial
code, but don't need the country code. So if the user adds his/her detail I
will store just the mobile number and the dial code. Now when the user
opens the profile in edit mode I have to show the dial code as saved in the
database. AFAIK the plugin only supports initial country by country code
only instead of the dial code.

**Comment by jackocnr** [comment]
Have you read the [Recommended Usage](https://github.com/jackocnr/intl-tel-input#recommended-usage) section of the readme? If you use `getNumber` to get the full international number, then that one string is all you need to store in your database. Then when the user opens the edit page, you just set the input to that number and the plugin will automatically select the right country.

**Comment by Abhi0725** [comment]
Oh! My apologies. I will check.
