### ISSUE TITLE
Sri Lanka Number starting with +94197 doesn't validate

### ISSUE THREAD

**Issue by rassvetdk** [jackocnr/intl-tel-input#610]
### Steps to reproduce
1.  Try to validate the following number +94197 11 1111
https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html
2. Please take a look on the following source for real phone numbers http://www.srilankan.com/en/flying-with-us/contact-us

### Expected behaviour
It should be a valid number

### Actual behaviour
Shows as invalid number

**Comment by jackocnr** [comment]
From the New Issue template:

> IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by rassvetdk** [comment]
@jackocnr but where to submit this issue, any ideas?

**Comment by jackocnr** [comment]
The libphonenumber Github page.
