### ISSUE TITLE
Input value doesn't bind to ng-scope

### ISSUE THREAD

**Issue by alecfullofmer** [jackocnr/intl-tel-input#612]
My code:
<input type="tel" class="form-control" id="requesterPhone" name="requesterPhone" ng-model="request.requester.phone" empty-to-null>

if I input (222)222-2222, $scope.request.requester.phone = null 
but $("#requesterPhone").val() = "(222)222-2222"

if I dont call 
el.intlTelInput({
          utilsScript: "/bower_components/intl-tel-input/build/js/utils.js"
        });

ng-model works correctly.

Any ideas?

**Comment by jackocnr** [comment]
I'm afraid questions about Angular are outside the scope of this plugin.

**Comment by gmiller-in-situ** [comment]
I know this is closed, but I came across a similar problem this week. I found that including the utilsScript option on initialization caused some strange problems. However, my precompiling steps were already including utils.js in the document, so they had already been loaded, and this option was not necessary to get the additional functionality.
