### ISSUE TITLE
Need to integrate it with PHP & MySQL

### ISSUE THREAD

**Issue by rameshkr92** [jackocnr/intl-tel-input#613]
Hi,

How can we manage countries and phone code with database, as we need to control countries iso and phone code from the admin.

Please guide me to get the desire result.

**Comment by jackocnr** [comment]
Please can you give an example of what you need to be able to do?

**Comment by joel-depiltech** [comment]
Hi @rameshkr92,
My company uses int-tel-input for view and we use [libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php) for insert phone number in our databases.
Maybe our choices can help you :-)
Regards

**Comment by simioluwatomi** [comment]
To do what @joel-depiltech is saying or what I think you want, you would have to collect the full international phone number a user enters through a hidden field in your html.

Everything you would need is available in this link. Read up

https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/national-mode.html

It is the variable the of the hidden input submits that you validate with the server side language of your choice and submit to the database if validation is successful.

@jackocnr can the plugin submit the full international phone number without the need for a hidden text input field?

**Comment by jackocnr** [comment]
> can the plugin submit the full international phone number without the need for a hidden text input field?

Not yet, but it will be able to handle the hidden input internally when this gets implemented: https://github.com/jackocnr/intl-tel-input/issues/575

Thanks for the input. Closing for now.

**Comment by rameshkr92** [comment]
Sorry for late response.
But i want to fetch countries data from database not from "utils.js".
because admin can create/modify countries data from control(admin) panel. or he can inactive any country in future. so we need to handle this accordingly.

**Comment by jackocnr** [comment]
Update: see `hiddenInput` option.
