### ISSUE TITLE
getNumber don't get me prefix

### ISSUE THREAD

**Issue by lippomano** [jackocnr/intl-tel-input#615]
### Expected behaviour
I'm using it with angular 4, I expect that when I call method getNumber `this.elInput.intlTelInput('getNumber')` gives me the full phone number

### Actual behaviour
I see only number typed in the input field and not with prefix

### Initialisation options
I use customPlaceholder exactly like your example
```
 this.elInput = jQuery('#landline');
    this.elInput.intlTelInput({
      nationalMode: true, placeholderNumberType: 'FIXED_LINE',
      customPlaceholder: function(selectedCountryPlaceholder, selectedCountryData) {
        return 'e.g. ' + selectedCountryPlaceholder;
      }
```

**Comment by jackocnr** [comment]
Are you loading utils.js successfully?

**Comment by lippomano** [comment]
Probably don't, so it's necessary to make it work?

**Comment by jackocnr** [comment]
Please read the readme section for the `getNumber` method.
