### ISSUE TITLE
intlTelInput("getNumberType") returns -99

### ISSUE THREAD

**Issue by alexey-sh** [jackocnr/intl-tel-input#618]
### Steps to reproduce
1.  initalize
2.  set number +12035556670 
3.  get number type

### Expected behaviour
return something from `intlTelInputUtils.numberType` 

### Actual behaviour
returns -99

### Initialisation options
I'm using utilsScript

Also `getNumber` command returns "+1+12035556679"

**Comment by jackocnr** [comment]
Seems to be working for me: https://codepen.io/jackocnr/pen/oeWYae

Remember that if you're using the `utilsScript` option to load the utils.js when initialising the plugin, then as per the docs: you need to wait for the `.done()` callback to execute any code that requires utils.js, like `getNumberType`, or `getNumber`.
