### ISSUE TITLE
Only one country loaded

### ISSUE THREAD

**Issue by renoirfaria** [jackocnr/intl-tel-input#619]
Hello guys, i am starting to use this jQuery plugin and i am having some troubles on the start. My input is loading just one country and the selectbox don't open when i click.

What should i do?

p.s.: console don't throw any errors.

**Comment by jackocnr** [comment]
Which initialisation options are you using?

Could it be a conflict with your site's CSS or JS?

The best thing to do is to try to recreate your problem in a codepen.

**Comment by renoirfaria** [comment]
@jackocnr thank you for your response. It was Laravel's stock app.js file that was conflicting with intl-tel-input.
