### ISSUE TITLE
Not allowing a series

### ISSUE THREAD

**Issue by sourabhjn** [jackocnr/intl-tel-input#622]
IMPORTANT: please note that the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

### Steps to reproduce
1.  Should allow number starts from 8788****** in india in jquery plugin.
2. isValidNumber is giving false.
3.  isValidNumber();

Check here: https://codepen.io/sourabhj123/pen/NvYMMB

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by sourabhjn** [comment]
I have checked, still can you send me the link. ?

**Comment by jackocnr** [comment]
There is a link included in your original post.

**Comment by sourabhjn** [comment]
I have tested there, its not working.

**Comment by jackocnr** [comment]
Ok so as per that message in your original post: "please file an issue with them instead".
