### ISSUE TITLE
Extract Country dial code on dropdown selection change event

### ISSUE THREAD

**Issue by ahmedhashmi21** [jackocnr/intl-tel-input#624]
Hi Team,

I have implemented this plugin in website and it is working find but what i need is to store country code in database. 
I have one registration form where people register their profile. they select country and enter phone number.
I need to insert phone in separate column of mysql database table and dial (eg, +91, +44, +1,etc) in separate column.

Please help me how extract dial on dropdown selection change event .

Thanks in advance.

**Comment by jackocnr** [comment]
See `getSelectedCountryData`.
