### ISSUE TITLE
How to put this functionalized in wordpress

### ISSUE THREAD

**Issue by aitorUdabe** [jackocnr/intl-tel-input#625]
Hello,

I want to add this functionality to my tel input from my wordpress form, the form is created in html. You can help me because it does not reliably function. I have copied the css in my son theme and the js too and I have changed the url to point to the new ones.

regards

**Comment by jackocnr** [comment]
This is not an issue with the plugin, this is an issue with Wordpress. I personally have no experience with Wordpress so I cannot help. The only thing I will say is that I found this: [International Telephone Input for Contact Form 7](https://wordpress.org/plugins/international-telephone-input-for-contact-form-7/), which might help, though I personally have never used it.
