### ISSUE TITLE
Country Code Validator

### ISSUE THREAD

**Issue by Wr4i7h** [jackocnr/intl-tel-input#626]
Hi,

Im wondering if someone could help me, the phone number validators contained in the utils.js marks ext(085) numbers as invalid for country code ZA. 

How can I amend them to add in support for 085 cellphone numbers of length 10?

            ZA: [, [, , "[1-79]\\d{8}|8(?:[067]\\d{7}|[1-4]\\d{3,7})", "\\d{5,9}"],
                [, , "(?:1[0-8]|2[0-378]|3[1-69]|4\\d|5[1346-8])\\d{7}", "\\d{9}", , , "101234567"],
                [, , "(?:6[0-5]|7[0-46-9])\\d{7}|8[1-4]\\d{3,7}", "\\d{5,9}", , , "711234567"],
                [, , "80\\d{7}", "\\d{9}", , , "801234567"],
                [, , "86[2-9]\\d{6}|90\\d{7}", "\\d{9}", , , "862345678"],
                [, , "860\\d{6}", "\\d{9}", , , "860123456"],
                [, , "NA", "NA"],
                [, , "87\\d{7}", "\\d{9}", , , "871234567"], "ZA", 27, "00", "0", , , "0", , , , [
                    [, "(860)(\\d{3})(\\d{3})", "$1 $2 $3", ["860"], "0$1"],
                    [, "(\\d{2})(\\d{3})(\\d{4})", "$1 $2 $3", ["[1-79]|8(?:[0-47]|6[1-9])"], "0$1"],
                    [, "(\\d{2})(\\d{3,4})", "$1 $2", ["8[1-4]"], "0$1"],
                    [, "(\\d{2})(\\d{3})(\\d{2,3})", "$1 $2 $3", ["8[1-4]"], "0$1"]
                ], , [, , "NA", "NA"], , , [, , "NA", "NA"],
                [, , "861\\d{6}", "\\d{9}", , , "861123456"], , , [, , "NA", "NA"]
            ],

**Comment by jackocnr** [comment]
This is a validation issue - please check if your issue happens on the libphonenumber demo page, and if so, raise the issue with them instead.

**Comment by Wr4i7h** [comment]
Will do so thanks.
