### ISSUE TITLE
Thoughts on migratimg to es6/commonjs import/export 

### ISSUE THREAD

**Issue by jpgilchrist** [jackocnr/intl-tel-input#629]
It appears the google closure scope causes issues with webpack. There are loader libraries out there that are built to work with it https://www.npmjs.com/package/closure-loader, but that's just added complexity that I don't really want to incorporate. 

Didn't see it asked in past questions, so I figured I would ask.

**Comment by jackocnr** [comment]
Do you mean for the utils.js file? What do you want to be able to do?

**Comment by smilemoreall** [comment]
I have error after added utils.js 
It's maybe is similar error

> import utilsScript from 'intl-tel-input/build/js/utils.js'

> Uncaught SyntaxError: Unexpected token <

**Comment by jackocnr** [comment]
No that wont work - utils.js is just a simple JavaScript file which declares the global window.intlTelInputUtils - it does not export anything.

utils.js is aprx 215KB, so it is not recommended to build this file into your main bundle - instead we recommend you use the utilsScript option to lazy load the script after the initial page load.

**Comment by jackocnr** [comment]
@jpgilchrist does that answer your question? Can I close this issue?

**Comment by jpgilchrist** [comment]
@jackocnr yeah you can close this, I figured out a work around.

**Comment by trafium** [comment]
@jpgilchrist 
It would be very helpful if you shared your solution to the problem here, I am currently trying to figure it out myself.

**Comment by jpgilchrist** [comment]
@trafium it was to basically just use the utilScript option and specify the relative path to the file... 
```javascript
        $telInput.intlTelInput({
            utilsScript: "../../../../../../node_modules/intl-tel-input/build/js/utils.js"
        });
```

**Comment by laclance** [comment]
if I do this i get `Uncaught SyntaxError: Unexpected token '<'`

**Comment by katexue** [comment]
I'm getting the same error when using relative path in Nuxt3. Using CDN version can fix the error but it's no ideal. Would be great to know if there's a way to use relative path in Nuxt3.

> if I do this i get `Uncaught SyntaxError: Unexpected token '<'`
