### ISSUE TITLE
TypeError: $(…).intlTelInput is not a function

### ISSUE THREAD

**Issue by ryanandrews321** [jackocnr/intl-tel-input#631]
I'm trying to use intlTelInput for a HTML registration page but I am getting the following error:
`Uncaught TypeError: $(...).intlTelInput is not a function`

Here is the registration view code:
```

<html>
<head>
<!-- Page for customer registration and submit details to database to associate SSO with company etc -->
    <link rel="stylesheet" type="text/css" href="views/register.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link rel="stylesheet" href="../bower_components/intl-tel-input/build/css/intlTelInput.css">
    <script src="../bower_components/intl-tel-input/build/js/intlTelInput.js"></script>
    <script>
        $("#phoneNumber").intlTelInput();

        // get the country data from the plugin
        var countryData = $.fn.intlTelInput.getCountryData(),
            telInput = $("#phoneNumber"),
            addressDropdown = $("#country");

        // init plugin
        telInput.intlTelInput({
            utilsScript: "../bower_components/intl-tel-input/build/js/utils.js" // just for formatting/placeholders etc
        });

        // populate the country dropdown
        $.each(countryData, function(i, country) {
            addressDropdown.append($("<option></option>").attr("value", country.iso2).text(country.name));
        });
        // set it's initial value
        var initialCountry = telInput.intlTelInput("getSelectedCountryData").iso2;
        addressDropdown.val(initialCountry);

        // listen to the telephone input for changes
        telInput.on("countrychange", function(e, countryData) {
            addressDropdown.val(countryData.iso2);
        });

        // listen to the address dropdown for changes
        addressDropdown.change(function() {
            telInput.intlTelInput("setCountry", $(this).val());
        });
    </script>
</head>

<form name="page1" id="page1" role="form">

<div id="createCasePage1" class="container-fluid">

<div class="col-md-6 col-xs-12">
        <div class="form-group">
	      <label for="phoneNumber">Phone Number:</label>
          <input type="tel" id="phoneNumber" name="phoneNumber" ng-model="createUserObj[0].phoneNumber" class="form-control"  required>
      </div>
    </div>

    <div class="col-md-6 col-xs-12">
      <div class="form-group">
        <label for="country">Country:</label>
        <!--<input type="text" id="country" name="country" ng-model="createUserObj[0].country" class="form-control" placeholder="Country" required maxlength="100" /> -->
              <select id="country" name="country" ng-model="createUserObj[0].country" class="form-control" required></select>
      </div>
    </div>


    <!-- Check valid  inputs and patterns then submit to controller -->
    <button type="submit" id="register" class="btn btn-large" class="registerBtn" ng-click="page1.$valid && createUserFunc()">Register</button>
    <br>
    <br>
</div>
</form>
</html>

```

I think it's an issue with jQuery and Angular but I'm not really sure.

**Comment by jackocnr** [comment]
You're calling `$("#phoneNumber")` before the page has loaded, so that wont work. You need to wrap that code in jQuery's document ready callback. Or move that script code to the end of the body.

**Comment by ryanandrews321** [comment]
I have now moved it around to this:
```
<html>
<head>
    <link rel="stylesheet" type="text/css" href="views/register.css">
</head>
<body>
<form name="page1" id="page1" role="form">

<div id="createCasePage1" class="container-fluid">

	<div class="col-md-6 col-xs-12">
        <div class="form-group">
	      <label for="phoneNumber">Phone Number:</label>
          <input type="tel" id="phoneNumber" name="phoneNumber" ng-model="createUserObj[0].phoneNumber" class="form-control"  required>
      </div>
    </div>

    <div class="col-md-6 col-xs-12">
      <div class="form-group">
        <label for="country">Country:</label>
        <!--<input type="text" id="country" name="country" ng-model="createUserObj[0].country" class="form-control" placeholder="Country" required maxlength="100" /> -->
              <select id="country" name="country" ng-model="createUserObj[0].country" class="form-control" required></select>
      </div>
    </div>

    <!-- Check valid  inputs and patterns then submit to controller -->
    <button type="submit" id="register" class="btn btn-large" class="registerBtn" ng-click="page1.$valid && createUserFunc()">Register</button>
    <br>
    <br>
</div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link rel="stylesheet" href="../bower_components/intl-tel-input/build/css/intlTelInput.css">
    <script src="../bower_components/intl-tel-input/build/js/intlTelInput.js"></script>
    <script>
        $("#phoneNumber").intlTelInput();

        // get the country data from the plugin
        var countryData = $.fn.intlTelInput.getCountryData(),
            telInput = $("#phoneNumber"),
            addressDropdown = $("#country");

        // init plugin
        telInput.intlTelInput({
            utilsScript: "../bower_components/intl-tel-input/build/js/utils.js" // just for formatting/placeholders etc
        });

        // populate the country dropdown
        $.each(countryData, function(i, country) {
            addressDropdown.append($("<option></option>").attr("value", country.iso2).text(country.name));
        });
        // set it's initial value
        var initialCountry = telInput.intlTelInput("getSelectedCountryData").iso2;
        addressDropdown.val(initialCountry);

        // listen to the telephone input for changes
        telInput.on("countrychange", function(e, countryData) {
            addressDropdown.val(countryData.iso2);
        });

        // listen to the address dropdown for changes
        addressDropdown.change(function() {
            telInput.intlTelInput("setCountry", $(this).val());
        });
    </script>
</form>
</body>
</html>
```

Still throwing the same error?
Can you show a working way to do it?

**Comment by jackocnr** [comment]
If you reproduce the issue in a codepen I will take a look.

**Comment by ryanandrews321** [comment]
Can I send you a link to the github repository?

**Comment by jackocnr** [comment]
No, I need to see it up and running to debug it.

**Comment by fakerLinXiao** [comment]
same here, i used @types/intl-tel-input.

**Comment by newgenesys** [comment]
Facing the same issue

**Comment by simonsviper** [comment]
I'm also having the same issue.

**Comment by ignazas** [comment]
Same here.

**Comment by TomasHurtz** [comment]
I had this issue.  Just wrap the entire input code within;

`  jQuery(document).ready(function() {	

telInput.intlTelInput({
				  initialCountry: "auto",

                             stuff....

});	 '

**Comment by A-Sahrawat** [comment]
This is the **conflict issue with existing prototype**. Try with add below line of code, hope this will help:

 ```
<script>
        jq = jQuery.noConflict();
        <!-- Replace $ with jq and call intlTelInput() function ------->
         use :
        jq("#phoneNumber").intlTelInput();
        insteadof :
         $("#phoneNumber").intlTelInput();
</script>
```

**Comment by anupamadhuri** [comment]
Having same issue after jquery upgraded to 3.1.1

Urgent!

**Comment by jackocnr** [comment]
If you can reproduce the issue in a codepen (stripping down the code to the simplest possible form that reproduces the error), then I'm happy to take a look.

**Comment by A-Sahrawat** [comment]
May you please share your code sample.

**Comment by A-Sahrawat** [comment]
please share all code sample with html too.

**Comment by anupamadhuri** [comment]
<script src="/javascript/2015/jquery-3.3.1.js"></script>
<script src="/javascript/2016/jquery-ui-1.12.1.min.js"></script>
<script src="/javascript/angular.min.js"></script>
<link rel="stylesheet" type="text/css" href="/stylesheets/intlTelInput.css?version=43.1">
<script type="text/javascript" src="/javascript/intlTelInput.js?version=43.1"></script>
<form name="PanelMemberCustomForm" method="POST" action="/a/editPanelMember.do" class="form-horizontal" onsubmit="ajaxSubmitFormObject('PanelMemberEdit', this.action, this);return false;">
    <input type="hidden" name="ID" value="20061">
    <input type="hidden" name="userAction" value="save">


    <div class="col-sm-12">
        <div class="row col-sm-12">
            <div class="form-group  " style="" id="Field_728764624">
<label class="col-xs-12 col-sm-3 control-label " for="EmailAddress" style="">Email Address</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><input type="text" name="emailAddress" value="anupama.dhuri@questionpro.com" onblur="" class="form-control input-sm" id="EmailAddress"><div class="error QuestionError" id="Field_Message_728764624"></div></div></div>
        </div>
        <div class="row col-sm-12">
            <div class="form-group  " style="" id="Field_1773344315">
<label class="col-xs-12 col-sm-3 control-label " for="FirstName" style="">First Name</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><input type="text" name="firstname" value="s asdhh" onblur="" class="form-control input-sm" id="FirstName"><div class="error QuestionError" id="Field_Message_1773344315"></div></div></div>
        </div>
        <div class="row col-sm-12">
            <div class="form-group  " style="" id="Field_337012267">
<label class="col-xs-12 col-sm-3 control-label " for="LastName" style="">Last Name</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><input type="text" name="lastname" value="hasdha" onblur="" class="form-control input-sm" id="LastName"><div class="error QuestionError" id="Field_Message_337012267"></div></div></div>
        </div>

        <div class="row col-sm-12">
            <div class="form-group">
                <label for="mobileNumber" class="col-sm-3 control-label">
                    Mobile Number
                </label>
                <div class="col-sm-8 phone-parent-container">
                    <div class="phone-number-container" style="display: flex;">
                        <input type="text" name="countryCode" value="+1" class="form-control phone-code" id="PhoneCountryCode">
                        <input type="text" name="mobileNumber" value="" class="form-control" id="mobileNumber">
                    </div>
                </div>
            </div>
        </div>

        <div class="row col-sm-12">
            <div class="form-group  " style="">
<label class="col-xs-12 col-sm-3 control-label " for="MemberType" style="">Member Type</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><select name="moderator" class="form-control input-sm " id="MemberType" style="display: none;"><option value="0">Web/Standard User</option>
                <option value="1">Tester</option>
                <option value="99" selected="">Moderator</option></select><div class="qpchosen-container qpchosen-container-single qpchosen-container-single-nosearch" title="" id="MemberType_chosen" style="width: 148.352px;"><a class="qpchosen-single">
  <span>Moderator</span>
  <div><b></b></div>
</a>
<div class="qpchosen-drop">
  <div class="qpchosen-search">
    <input class="qpchosen-search-input" type="text" autocomplete="off" readonly="">
  </div>
  <ul class="qpchosen-results"></ul>
</div></div><div class="error QuestionError"></div></div></div><script type="text/javascript">$("select[name='moderator']").qpchosen({disable_search_threshold: 7});refreshSelects()</script>
        </div>

        <div class="row col-sm-12">
            <div class="form-group  " style="" id="Field_670817122">
<label class="col-xs-12 col-sm-3 control-label " for="Custom" style="">Custom 1</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><input type="text" name="custom1" value="" onblur="" class="form-control input-sm" id="Custom"><div class="error QuestionError" id="Field_Message_670817122"></div></div></div>
        </div>

        <div class="row col-sm-12">
            <div class="form-group  " style="" id="Field_670817123">
<label class="col-xs-12 col-sm-3 control-label " for="Custom" style="">Custom 2</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><input type="text" name="custom2" value="" onblur="" class="form-control input-sm" id="Custom"><div class="error QuestionError" id="Field_Message_670817123"></div></div></div>
        </div>

        <div class="row col-sm-12"><div class="form-group  " style="" id="Field_670817124">
<label class="col-xs-12 col-sm-3 control-label " for="Custom" style="">Custom 3</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><input type="text" name="custom3" value="" onblur="" class="form-control input-sm" id="Custom"><div class="error QuestionError" id="Field_Message_670817124"></div></div></div></div>
        <div class="row col-sm-12"><div class="form-group  " style="" id="Field_670817125">
<label class="col-xs-12 col-sm-3 control-label " for="Custom" style="">Custom 4</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><input type="text" name="custom4" value="" onblur="" class="form-control input-sm" id="Custom"><div class="error QuestionError" id="Field_Message_670817125"></div></div></div></div>
        <div class="row col-sm-12"><div class="form-group  " style="" id="Field_670817126">
<label class="col-xs-12 col-sm-3 control-label " for="Custom" style="">Custom 5</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><input type="text" name="custom5" value="" onblur="" class="form-control input-sm" id="Custom"><div class="error QuestionError" id="Field_Message_670817126"></div></div></div></div>
        <div class="row col-sm-12"><div class="form-group  " style="">
<label class="col-xs-12 col-sm-3 control-label " for="CurrentStatus" style="">Current Status</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><select name="status" class="form-control input-sm form-control input-sm " id="MemberType" style="display: none;"><option value="1">New (UnVerified)</option>
            <option value="2" selected="">Verified</option>
            <option value="4">Unsubscribed</option>
            <option value="8">Email Bounced</option>
            <option value="16">Pending Moderator Approval</option>
            <option value="32">Blocked/Banned</option>
            <option value="128">Inactive (0)</option>
            <option value="64">Pending Sign up</option></select><div class="qpchosen-container qpchosen-container-single" title="" id="MemberType_chosen" style="width: 197.443px;"><a class="qpchosen-single">
  <span>Verified</span>
  <div><b></b></div>
</a>
<div class="qpchosen-drop">
  <div class="qpchosen-search">
    <input class="qpchosen-search-input" type="text" autocomplete="off">
  </div>
  <ul class="qpchosen-results"></ul>
</div></div><div class="error QuestionError"></div></div></div><script type="text/javascript">$("select[name='status']").qpchosen({disable_search_threshold: 7});refreshSelects()</script></div>
        <div class="row col-sm-12"><div class="form-group  " style="">
<label class="col-xs-12 col-sm-3 control-label " for="EmailNotification" style="">Email Notification</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><select name="notification" class="form-control input-sm form-control input-sm form-control input-sm " id="MemberType" style="display: none;"><option value="0">None</option>
            <option value="1" selected="">Instant Email - As New Idea Posted</option>
            <option value="2">Weekly Email - Digest</option></select><div class="qpchosen-container qpchosen-container-single qpchosen-container-single-nosearch" title="" id="MemberType_chosen" style="width: 231.08px;"><a class="qpchosen-single">
  <span>Instant Email - As New Idea Posted</span>
  <div><b></b></div>
</a>
<div class="qpchosen-drop">
  <div class="qpchosen-search">
    <input class="qpchosen-search-input" type="text" autocomplete="off" readonly="">
  </div>
  <ul class="qpchosen-results"></ul>
</div></div><div class="error QuestionError"></div></div></div><script type="text/javascript">$("select[name='notification']").qpchosen({disable_search_threshold: 7});refreshSelects()</script></div>

        <div class="row col-sm-12">
            <div class="form-group  " style="" id="Field_749894925">
<label class="col-xs-12 col-sm-3 control-label " for="AddReducePoints" style="">Add / Reduce Points</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><input type="text" name="addQPointValue" value="0" onblur="" class="form-control input-sm" id="AddReducePoints"><span class="help-block text-right">0</span><div class="error QuestionError" id="Field_Message_749894925"></div></div></div>
        </div>
        
        <div class="row col-sm-12">
            <div class="form-group  " style="">
<label class="col-xs-12 col-sm-3 control-label " for="DefaultLanguage" style="">Default Language</label><div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><select name="defaultLanguage" class="form-control input-sm form-control input-sm form-control input-sm form-control input-sm " id="MemberType" style="display: none;"><option value="0" selected="">English</option>

                <optgroup label="Available Languages">
                    <option value="266">Afrikaans</option>
<option value="511">Albanian</option>
<option value="279">Amharic</option>
<option value="10">Arabic</option>
<option value="110">Armenian</option>
<option value="517">Assamese</option>
<option value="246">Azerbaijani</option>
<option value="501">Bahasa Indonesia</option>
<option value="50">Baltic</option>
<option value="261">Bangla</option>
<option value="244">Bulgarian</option>
<option value="267">Burmese</option>
<option value="230">Catalan</option>
<option value="70">Chinese (Simplified - gb2312)</option>
<option value="80">Chinese (Traditional - Big5)</option>
<option value="274">Chinese [Hong Kong]</option>
<option value="240">Croatian</option>
<option value="60">Cyrillic</option>
<option value="220">Czech</option>
<option value="160">Danish</option>
<option value="257">Dari</option>
<option value="3">Dutch</option>
<option value="508">English ( UK )</option>
<option value="255">Estonian</option>
<option value="150">Finnish</option>
<option value="190">Flemish</option>
<option value="2">French</option>
<option value="273">French [Canada]</option>
<option value="522">Georgian</option>
<option value="1">German</option>
<option value="210">Greek</option>
<option value="262">Gujarati</option>
<option value="278">Gurmukhi</option>
<option value="502">Haitian Creole</option>
<option value="521">Hausa</option>
<option value="40">Hebrew</option>
<option value="247">Hindi</option>
<option value="130">Hungarian</option>
<option value="241">Icelandic</option>
<option value="256">Indonesian</option>
<option value="515">IsiXhosa (Xhosa)</option>
<option value="6">Italian</option>
<option value="90">Japanese</option>
<option value="514">Kannada</option>
<option value="272">Kazakh (Kazakhstan)</option>
<option value="243">Khmer</option>
<option value="503">Klingon</option>
<option value="100">Korean</option>
<option value="520">Kurdish (Kurmanji)</option>
<option value="513">Laotian</option>
<option value="248">Latvian</option>
<option value="259">Lithuanian</option>
<option value="275">Macedonian</option>
<option value="254">Malay</option>
<option value="518">Malayalam</option>
<option value="519">Maltese</option>
<option value="525">Mandinka</option>
<option value="277">Marathi</option>
<option value="509">Mongolian</option>
<option value="512">Montenegrin</option>
<option value="200">Norwegian</option>
<option value="264">Odia</option>
<option value="258">Pashto</option>
<option value="252">Persian</option>
<option value="120">Polish</option>
<option value="5">Portuguese</option>
<option value="516">Portuguese [Brazilian]</option>
<option value="180">Romanian</option>
<option value="7">Russian</option>
<option value="249">Serbian</option>
<option value="504">Sinhala</option>
<option value="253">Sinhalese</option>
<option value="170">Slovakian</option>
<option value="242">Slovenian</option>
<option value="524">Somali</option>
<option value="4">Spanish</option>
<option value="271">Spanish [Latin America]</option>
<option value="260">Swazi</option>
<option value="140">Swedish</option>
<option value="268">Tagalog</option>
<option value="269">Tagalog [Philippines]</option>
<option value="276">Tamil</option>
<option value="265">Telugu</option>
<option value="30">Thai</option>
<option value="523">Tigrinya</option>
<option value="20">Turkish</option>
<option value="263">Ukrainian</option>
<option value="251">Urdu</option>
<option value="270">Urdu [Pakistan]</option>
<option value="245">Vietnamese</option>
<option value="507">Welsh</option>
<option value="510">Zulu</option>

                </optgroup></select><div class="qpchosen-container qpchosen-container-single" title="" id="MemberType_chosen" style="width: 211.08px;"><a class="qpchosen-single">
  <span>English</span>
  <div><b></b></div>
</a>
<div class="qpchosen-drop">
  <div class="qpchosen-search">
    <input class="qpchosen-search-input" type="text" autocomplete="off">
  </div>
  <ul class="qpchosen-results"></ul>
</div></div><div class="error QuestionError"></div></div></div><script type="text/javascript">$("select[name='defaultLanguage']").qpchosen({disable_search_threshold: 7});refreshSelects()</script>
        </div>
        <div class="row col-sm-12">
            
        </div>
        <div class="dashedSingleLine row">
            <input type="submit" name="submit" value="Save Changes" class="btn btn-sm btn-primary col-sm-offset-3 pull-left">
        </div>
    </div>


</form>

**Comment by anupamadhuri** [comment]
<script src="/javascript/2015/jquery-3.3.1.js"></script>
<script src="/javascript/2016/jquery-ui-1.12.1.min.js"></script>
<script src="/javascript/angular.min.js"></script>
<link rel="stylesheet" type="text/css" href="/stylesheets/intlTelInput.css?version=43.1">
<script type="text/javascript" src="/javascript/intlTelInput.js?version=43.1"></script>

<form name="PanelMemberCustomForm" method="POST" action="/a/editPanelMember.do" class="form-horizontal"
      onsubmit="ajaxSubmitFormObject('PanelMemberEdit', this.action, this);return false;">
    <input type="hidden" name="ID" value="20061">
    <input type="hidden" name="userAction" value="save">


    <div class="col-sm-12">
        <div class="row col-sm-12">
            <div class="form-group  " style="" id="Field_1773344315">
                <label class="col-xs-12 col-sm-3 control-label " for="FirstName" style="">First Name</label>

                <div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><input
                        type="text" name="firstname" value="s asdhh" onblur="" class="form-control input-sm"
                        id="FirstName">

                    <div class="error QuestionError" id="Field_Message_1773344315"></div>
                </div>
            </div>
        </div>
        <div class="row col-sm-12">
            <div class="form-group  " style="" id="Field_337012267">
                <label class="col-xs-12 col-sm-3 control-label " for="LastName" style="">Last Name</label>

                <div class="custom-form-control col-xs-12 col-sm-8" style="padding-left:0px;padding-right:0px;"><input
                        type="text" name="lastname" value="hasdha" onblur="" class="form-control input-sm"
                        id="LastName">

                    <div class="error QuestionError" id="Field_Message_337012267"></div>
                </div>
            </div>
        </div>

        <div class="row col-sm-12">
            <div class="form-group">
                <label for="mobileNumber" class="col-sm-3 control-label">
                    Mobile Number
                </label>

                <div class="col-sm-8 phone-parent-container">
                    <div class="phone-number-container" style="display: flex;">
                        <input type="text" name="countryCode" value="+1" class="form-control phone-code"
                               id="PhoneCountryCode">
                        <input type="text" name="mobileNumber" value="" class="form-control" id="mobileNumber">
                    </div>
                </div>
            </div>
        </div>

    </div>

</form>

**Comment by anupamadhuri** [comment]
Fixed
Solution:
In intlTelInput.js replace
.load(function() { ... });
To
.on('load', function() { ... });

**Comment by brada1703** [comment]
> Fixed
> Solution:
> In intlTelInput.js replace
> .load(function() { ... });
> To
> .on('load', function() { ... });

Where do you see this? I can't find this particular code in the file that you mentioned "intlTelInput.js". Note that I am using v14.0.4

**Comment by ronjb04** [comment]
> Fixed
> Solution:
> In intlTelInput.js replace
> .load(function() { ... });
> To
> .on('load', function() { ... });

i can't find this too in v14.0.5

**Comment by shafayshahid123** [comment]
Actually i'm using two input in form-group but when i'm going to use help-block it's working if any of two option is filled or select but i want it two working with particular input.

<div class="form-group">
    <div class="input-group">                  
        <span class="input-group-addon">
             <select class="form-control select2" name="calling_code" id="calling_code" required="">
                 <option>.....</option>
              </select>
         </span>
         <input name="mobile_number" class="form-control input-lg flat" placeholder="{{ trans('theme.placeholder.mobile_number') }}" type="text" required/>
     </div>
     <div class="help-block with-errors"></div>
</div>

I don't wanna use intlTelInput.js

**Comment by bala900** [comment]
$(document).ready(function()
    {       
         var countryData = window.intlTelInputGlobals.getCountryData();
         console.log(countryData);
 

          var input = document.querySelector("#phoneNumber");
          var iti = window.intlTelInput(input, {
              utilsScript:'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.0/js/utils.js',
              initialCountry:"auto",
              separateDialCode:true,
              dropdownContainer:null,
              geoIpLookup: function (callback) {
                  $.get({url:"https://ipinfo.io?token=6b83a9b0fc2862",cache:true}, function () {}, "jsonp").always(function (resp) {
                  var countryCode = (resp && resp.country) ? resp.country : "";                  
                  this.country+=resp.country;                  
                  callback(countryCode);
                  });
              }   
           });      
     
        var handleChange = function() {
          //HERE YOU CAN GET THE MOBILE NUMBER
          console.log(iti.getNumber());  
        }

        input.addEventListener('change', handleChange);
        input.addEventListener('keyup', handleChange);
           
      });



<input matInput type="tel" class="form-contrl" [(ngModel)]="user.phoneNumber" name="phone" id="phoneNumber" autocomplete="off"/>
