### ISSUE TITLE
Add country code to result

### ISSUE THREAD

**Issue by skazhikadyadya** [jackocnr/intl-tel-input#632]
Hello, thank you for nice script. 

I use it with that configuration:
```
orn('.inter-phone').intlTelInput({
    separateDialCode: true,
    preferredCountries: ["ua"]
});
```

Works well, but on server I get only entered number without country code. How I can fix that? Thank you.

**Comment by jackocnr** [comment]
See `getNumber`.

**Comment by jackocnr** [comment]
Update: see new `hiddenInput` option.
