### ISSUE TITLE
setNumber is not working in my case

### ISSUE THREAD

**Issue by yasir-rafiq** [jackocnr/intl-tel-input#634]
$("#phone").intlTelInput("setNumber", "+44 7733 123 456");
This is not working in my angular js code.

**Comment by jackocnr** [comment]
I just tested on the demo site, in the chrome dev tools console, and it worked fine, so most likely this is a problem with your code. I'm afraid issues with Angular code are outside the scope of this plugin.

**Comment by yasir-rafiq** [comment]
ok let me show you my code

HTML:
<input type="tel" id="phone" ng-model="profile.phone_number" class="form-control">


JS:
$("#phone").intlTelInput("setNumber", "+923224701887");


eve I try to test over here but it's still same issue
http://jsfiddle.net/LeslieOA/y03gb0qe/

**Comment by jackocnr** [comment]
I don't see the issue in that fiddle... you're not even calling setNumber?

In the meantime, here's a couple of thoughts:

Firstly: if you're setting the number immediately, have you considered just setting the number as the input's value in the markup? Then you don't need to call `setNumber`.

Secondly: if you're unable to set the number in the markup and you need to use `setNumber` immediately, if you're using asynchronous options like `geoIpLookup` or `utilsScript` then you need to wait for those to finish before calling `setNumber`, so you need to put your code in a `done` callback e.g.

```
$("#phone").intlTelInput().done(function() {
    $("#phone").intlTelInput("setNumber", "+923224701887");
});
```

**Comment by yasir-rafiq** [comment]
I created the fiddle for you.
But you are right I am using "geoIpLookup or utilsScript" so done function work for me.
Thanks for your quick help.
