### ISSUE TITLE
Hello I want to validate phone number without ID.

### ISSUE THREAD

**Issue by yasirrafiq33** [jackocnr/intl-tel-input#635]
I have phone number like "+92 3224701887" how can I validate it

can I use like this? or what ?
"92322".intlTelInput("getValidationError")

**Comment by jackocnr** [comment]
What do you mean "without ID"?

Have you looked at the Validation example on the demo page?

Have you read the readme sections about validation methods?

**Comment by jackocnr** [comment]
If you want to validate a number without initialising the plugin, you can load utils.js and use those methods directly - see the utils.js wiki page.

**Comment by dodomui** [comment]
@jackocnr mind to share more about how to load utils.js directly?
Cannot figure how to do..
Appreciate if you could advise.

**Comment by jackocnr** [comment]
It's just a JavaScript file, load it however you load the rest of your scripts.
