### ISSUE TITLE
Phone number validations

### ISSUE THREAD

**Issue by yasir-rafiq** [jackocnr/intl-tel-input#638]
If I have one number in string format how can I validate this number can you help me?
 Like I have "+923224701887" now I want to validate it how is this possible?

**Comment by jackocnr** [comment]
If you want to validate a number without initialising the plugin, you can load utils.js (however you like - it's just a normal JS file) and use those utils methods directly - see the utils.js wiki page.

**Comment by yasir-rafiq** [comment]
@jackocnr can you explain it little more with some code because I am stuck with this.

**Comment by jackocnr** [comment]
Ok where are you getting your string phone number that you want to validate? Do you have the intl-tel-input plugin initialised on an input on the page?

**Comment by yasir-rafiq** [comment]
No its just a phone number that come from db I want to validate it.

**Comment by yasir-rafiq** [comment]
any progress?

**Comment by jackocnr** [comment]
Ok so you just need to add a script tag to your page, with the src pointing to wherever your utils.js file is.

Then do something like this:

`var isValidNumber = intlTelInputUtils.isValidNumber(number);`

**Comment by yasir-rafiq** [comment]
ok I'll try and update you.
