### ISSUE TITLE
nice to have

### ISSUE THREAD

**Issue by lxraysor** [jackocnr/intl-tel-input#640]
Its really just a nice to have.  508 compliance would be nice. being able to use the tab/arrow keys to select the country and validation for numeric characters only up to x characters

**Comment by jackocnr** [comment]
Please can you provide links to more information about 508 compliance and how it would apply to this plugin?

**Comment by lxraysor** [comment]
The biggest issue is allowing the user to tab the drop down and use the
arrow keys to select a country flag. Without using the mouse.

**Comment by jackocnr** [comment]
You can already use tab to focus the flag selector, then use arrow keys to choose which flag you want, then enter to select. No mouse needed! This is the same behaviour as native HTML `<select>` elements. What exactly is missing?

**Comment by genlaroche** [comment]
how about adding support to pageUp/pageDown and home/end keys to navigate the list with the keyboard?

**Comment by jackocnr** [comment]
Users can already type the name of their country. Adding the ability to jump to the very start/end of the list doesn't seem useful to me given the context, and I'm really anxious to keep this plugin as lightweight as possible.
