### ISSUE TITLE
Input mask for phone numbers

### ISSUE THREAD

**Issue by hfougere** [jackocnr/intl-tel-input#641]
It would be nice to have built in masking based on the selected country. So as you type the phone number, the input could add the mask for you (212) 123-4567 for US. Adding the optional international mask automatically would be nice too. So as you type 2121234567 it displays as +1 (212) 123-4567

Something like this https://igorescobar.github.io/jQuery-Mask-Plugin/

**Comment by hfougere** [comment]
I was able to integrate with the mask plugin. I just used the placeholder as a mask by replacing any number in the mask with a 0, and applying that as the mask for the plugin. 

`
this.telInput = $("#phone");
      this.telInput.intlTelInput({
      utilsScript: "/js/utils.js"
    });
this.placeholder = this.telInput.attr("placeholder");
this.mask = this.placeholder.replace(new RegExp("[0-9]", "g"), "0");
this.telInput.mask(this.mask);

`

**Comment by jackocnr** [comment]
Please read the notes you see when creating a new issue. We had this functionality before - it was called autoFormat, but we decided to remove it for various reasons - see the readme.
