### ISSUE TITLE
Language on there own 

### ISSUE THREAD

**Issue by HawkonDK** [jackocnr/intl-tel-input#643]
I think that language should be spelled on its own language then maybe the English as a suffix

E.g

- Danmark - Denmark
- Deutschland - Germany 
- Italia - Italy
- English - English

The reason why is that I think this is that people know what there language are named on there own language, but not all know what it are named in English

**Comment by jackocnr** [comment]
Yeah this is an interesting idea. I did consider this before, but I think I decided it was too weird/inconsistent when you have so many country names in other alphabets like Afghanistan (‫افغانستان‬‎), Armenia (Հայաստան), Bangladesh (বাংলাদেশ) and Belarus (Беларусь). Then there's no way to sort them alphabetically, which would then make it very hard to find a different language.

**Comment by HawkonDK** [comment]
it is posible, e.g https://www.jw.org/ have 918 language ordet after ABC and still use special charchar like افغانستان‬‎ not sure how but I think it will see and be more natural if your own language was write on your own language instead of English. but just a idea

**Comment by HawkonDK** [comment]
I think you can use [Collator](http://php.net/manual/en/class.collator.php) to order it alphabetically

**Comment by jackocnr** [comment]
No ordering would make sense to users if it's in all different alphabets.

Also the list just wouldn't make sense to anyone, unless you could read every alphabet in the world!

**Comment by HawkonDK** [comment]
but do you need to understand what the name of other countrys is as a user?

**Comment by jackocnr** [comment]
I think so yes. I think it's a bad experience to open a dropdown and potentially not understand any of the initial countries that you can see.

Here's a good litmus test: can you find a major website that does this?

**Comment by HawkonDK** [comment]
jw.org

**Comment by jackocnr** [comment]
Right, which is what this plugin currently does.
