### ISSUE TITLE
Incorrect utils array for Georgia

### ISSUE THREAD

**Issue by Dmatafonov** [jackocnr/intl-tel-input#646]
### Steps to reproduce
1.  Try to input Georgia phone number with utils enabled: +995 91706162 
2.  Only first 5 numvers pass through validation

### Expected behaviour
It is valid numver, should be accepted.

### Initialisation options
Utils enabled.

### Question
Is there a way to change compiled utils.js to fix it? libphone @ google doesnt work any more.

Changing GE values in utils.js, I could not figure out how to correctly change it to accept the number.

Tbilisi number passes ok (+995 322 XXXXXX)

**Comment by jackocnr** [comment]
As per the "New Issue" instructions:

> we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by Dmatafonov** [comment]
I saw that message and filled issue here because http://libphonenumber.googlecode.com/ is not supported anymore by google. Test site is outdated.

So I tryed to fix their regex arrays hardcode and did not succeed.

I think you should deprecate usage of libphonenumber or support the code yourself since you recommend it (and it actually works pretty good for most countries);

**Comment by jackocnr** [comment]
The libphonenumber project is still alive and strong, it's just moved to Github.

**Comment by Dmatafonov** [comment]
OK, thanks, submitted an issue there. Change links to their project to gitlab.
