### ISSUE TITLE
Problem with z-index when using multiple

### ISSUE THREAD

**Issue by mpeay-edify** [jackocnr/intl-tel-input#647]
### Steps to reproduce
1.  Use with multiple inputs on the same form
2.  Click on pop-up

### Expected behaviour
Pop up menu should be above all content

### Actual behaviour
Pop up appears below country flag, code, and arrow
![screen shot 2017-10-12 at 1 13 24 pm](https://user-images.githubusercontent.com/13967741/31516969-2f1cc99e-af4f-11e7-9f8f-bb87ef589051.png)

**Comment by mpeay-edify** [comment]
This is primarily for code improvement purposes. I worked around my problem by adding z-index values to each div (5, 4, 3).

**Comment by jackocnr** [comment]
Hmm that's strange, it's working for me: https://codepen.io/jackocnr/pen/OVJodz

Are you sure it's not something else in your code? A stray z-index somewhere perhaps?

**Comment by mpeay-edify** [comment]
Confirmed. It ended up being caused by the bootstrap workaround code you've mentioned (https://codepen.io/jackocnr/pen/EyPXed). Removing that and my explicit z-index statements allows things to work properly.
