### ISSUE TITLE
GeoIpLookup is down, country flag is blank

### ISSUE THREAD

**Issue by kunleawotunbo** [jackocnr/intl-tel-input#651]
The GeoIpLookup has been working fine but now country flag shows blank because http://ipinfo.io is unreachable.

Can I use another Iplookup site instead of ipinfo.io
### Steps to reproduce
1.  Please see the screenshot https://www.screencast.com/t/HhJgHqD9fEr
2.  
3.  

### Expected behaviour
It should show the country flag based on the IP lookup

### Actual behaviour
1. Country flag is blank.
2. http://ipinfo.io not accessible from the browser.

Please help look into it.
Thanks

**Comment by jackocnr** [comment]
You can use any ip lookup service you want - you code it yourself using the `geoIpLookup` option.
