### ISSUE TITLE
Multiple input selected flag showing when dropdown is open

### ISSUE THREAD

**Issue by kevin-cpi** [jackocnr/intl-tel-input#652]
IMPORTANT: please note that the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

### Steps to reproduce
1.  https://codepen.io/besingamkb/pen/VreMJw
2.  open dropdown on the first input
3.  see the selected flag on the second input is still howing

### Expected behaviour
Tell us what should happen
selected flag on second input should not show on the dropdown when the other input dropdown is open
### Actual behaviour
Tell us what actually happens
selected flag on the second input is showing when the dropdown is open

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries
utilsScript

**Comment by jackocnr** [comment]
Thanks for raising this. I've updated the original codepen here with a fix in the CSS: https://codepen.io/jackocnr/pen/EyPXed

**Comment by kevin-cpi** [comment]
@jackocnr thanks.
