### ISSUE TITLE
Validation Phone number

### ISSUE THREAD

**Issue by AKFourSeven** [jackocnr/intl-tel-input#657]
I wonder if anyone ever came across this kind of issue and how it was solved.
I have an input that is supposed to take national number depending on the country they are in:
e.g. The country of the user is set to France => only French numbers are validated
The country of the user is set to Spain => only Spanish numbers are validated.

My issue is that using international input both national numbers (e.g. 01443234xx and 09883344xx)  are perceived as valid regardless of them being in France or in Spain.
I was expected one to be accepted while the other would be rejected.

Was this made by design, is it a bug or am I missing something ?

**Comment by jackocnr** [comment]
Did you check this? From the New Issue instructions:

> IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

Note that when we perform validation, we use libphonenumber to get the full international number, including the country code, and then we check if that is valid.

**Comment by AKFourSeven** [comment]
Nope I haven't seen this, I should have read it thoroughly.
I'll do that then
