### ISSUE TITLE
update phone number validation rules?

### ISSUE THREAD

**Issue by eidng8** [jackocnr/intl-tel-input#658]
We're having difficulties using this plugin. For instance, Hong Kong has mobile numbers starting with 4, 7, and 8. But the plugin won't allow us to enter such phone numbers.

Any suggestion?

**Comment by jackocnr** [comment]
The plugin shouldn't prevent you from entering any numbers. Are you using the latest version?

**Comment by eidng8** [comment]
Thanks for your time. It is not an issue on this project, as clarified by googlei18n/libphonenumber#2023

**Comment by eidng8** [comment]
sorry to bother again, google has updated their library, will you update your port a bit?
googlei18n/libphonenumber#2023

**Comment by jackocnr** [comment]
Done 👍

**Comment by eidng8** [comment]
on cndjs yet?

**Comment by jackocnr** [comment]
Yup

**Comment by hfougere** [comment]
@jackocnr would it be possible to have the utils.js build of Google's libphonenumber be built in to your module instead of having it as a separate file to be added? The fact that it's separate makes it more difficult to bundle into my project.

**Comment by jackocnr** [comment]
@hfougere that's off-topic - please search existing issues first and if you can't find what you're looking for then open a new issue.
