### ISSUE TITLE
End of phone cut on paste

### ISSUE THREAD

**Issue by zyxel** [jackocnr/intl-tel-input#662]
### Steps to reproduce
1. Select country X which has max phone length less than your country Y.
2. Paste phone.

[https://www.screencast.com/t/tUdmI2yLmSHq](https://www.screencast.com/t/tUdmI2yLmSHq)
Version 11.0.11

### Expected behaviour
Country will be changed. End of pasted phone will be retained according to max length of country Y.

### Actual behaviour
End of pasted phone will be removed according to max length of country X. Then country will be changed.

### Initialisation options
```
shouldSetInitialCountry: true,
ignoreInitialValidation: true,
initialCountryCode: "dk",
allowDropdown: true,
autoHideDialCode: true,
dropdownContainer: "",
excludeCountries: [],
formatOnDisplay: true,
geoIpLookup: function (callback) { ... },
initialCountry: "",
nationalMode: true,
onlyCountries: [],
placeholderNumberType: "MOBILE",
preferredCountries: ["dk"],
separateDialCode: false,
utilsScript: ""
```

**Comment by jackocnr** [comment]
Hmm I think there's been a mistake here - we don't have max lengths on phone numbers (we removed this functionality years ago), and we don't have those first two initialisation options you mentioned... Perhaps you've been using a fork of this plugin?

**Comment by zyxel** [comment]
Sorry, my mistake. It is indeed modified version.
Just tried clean last version.
It works different, but without issues.
