### ISSUE TITLE
Can you please fix the number for UAE they have also 971 [58]

### ISSUE THREAD

**Issue by nusret103** [jackocnr/intl-tel-input#663]
IMPORTANT: please note that the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
Please explain what you mean by "fix the number"? What problem are you having?

**Comment by nusret103** [comment]
One of our client has some problem to enroll one of its users living in UAE (United arab emirates).  He has a number in the range :  +97158... the our platform what is using this library doesn't recognize this phone number and accepts only in the range +97155....  or +97156...

**Comment by jackocnr** [comment]
> this library doesn't recognize this phone number and accepts only in the range +97155.... or +97156...

What do you mean by "doesn't recognize"? Do you mean you're using the validation method, and it's returning false?

**Comment by nusret103** [comment]
we are using the library also we are validating this number

**Comment by jackocnr** [comment]
From your initial issue text:

> IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

Did you try that?

**Comment by nusret103** [comment]
<img width="994" alt="screen shot 2017-12-12 at 5 19 52 pm" src="https://user-images.githubusercontent.com/11179442/33895406-baaee4e2-df60-11e7-9346-427f757f6da2.png">
please check the image above

**Comment by jackocnr** [comment]
Ok then it should work in this plugin. Are you using the latest version?

**Comment by jackocnr** [comment]
I just checked that same number on the [Validation example](https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html) on the demo page and it says it's a valid number, so I'm closing this.
