### ISSUE TITLE
Fail to load utils.js: `Preflight response is not successful` 

### ISSUE THREAD

**Issue by wtLau** [jackocnr/intl-tel-input#664]
XMLHttpRequest cannot load file:///Users/lana/Downloads/intl-tel-input-master/build/js/utils.js. Preflight response is not successful

I just downloaded the repo and `npm run build`, but there's this error message on demo.html. Should this error be ignored? I want to be able to formatting upon initialisation, as well as number validation.

**Comment by jackocnr** [comment]
Sorry I'm not familiar with getting the browser to load files directly from the file system like that. I would advise you to start a local webserver to serve the files e.g. using the npm package http-server.
