### ISSUE TITLE
how to 00 instead + 

### ISSUE THREAD

**Issue by ssadok** [jackocnr/intl-tel-input#665]
intl tel input cannot detect international number start with 00 how can i do to let him know this annotation ?

**Comment by jackocnr** [comment]
What exactly do you mean "cannot detect"? Please use the new issue template, and provide steps to re-create the problem, and what you expect to happen and what actually happens.

**Comment by ssadok** [comment]
the problem is simple when you prefix the number with 00 instead +

+following by country code the system detect the selected country

![image](https://user-images.githubusercontent.com/1891667/33967165-960bebaa-e062-11e7-853f-accbecbeed91.png)
 
But if i use 00 followed by country code the system desn't know this annotation

![image](https://user-images.githubusercontent.com/1891667/33967301-26d32cc0-e063-11e7-9412-279ab9b6fa35.png)

**Comment by jackocnr** [comment]
Please search the issues before posting - this question has already been answered.

**Comment by kamran-jabbar** [comment]
Better if you provide 00 feature for others. @jackocnr

**Comment by jackocnr** [comment]
For posterity:

> The 00 format is not standardised - it varies depending on which country you are dialling from. See https://github.com/jackocnr/intl-tel-input/pull/5
