### ISSUE TITLE
Focus on the flag div doesn't trigger focus

### ISSUE THREAD

**Issue by pablodgcatulo** [jackocnr/intl-tel-input#666]
Hello people! To be short, when the flag (the div that shows the flag) got focused by using the keyboard (tab key), the focus event is no triggered. 

There is anyway to capture this flag has focus? 

Thanks for your time ! You have done a great work with this plugin :+1: 

### Steps to reproduce
1.  Focus on an element before (according tabindex) intl-tel-input
2.  hit tab
3.  flag is focus

### Expected behaviour
$("#the_intl-tel-input").focus(...) event should be triggered.

### Actual behaviour
It is not triggered... :disappointed: 

### Initialisation options
```
{
        utilsScript: variable_tel_input_utils_path,
        initialCountry: 'ar',
        placeholderNumberType: "FIXED_LINE_OR_MOBILE",
        preferredCountries: ['ar','br', 'cl', 'uy', 'py'],
        geoIpLookup: function (callback) {
          $.get("https://ipinfo.io", function () { }, "jsonp").always(function (resp) {
            var countryCode = (resp && resp.country) ? resp.country : "";
            callback(countryCode);
          });
        },
        hiddenInput: variableHiddenInputName
      }
```

**Comment by jackocnr** [comment]
If you want to know when the user focuses the selected flag, then you need to listen for the focus event on the `.selected-flag` element.
