### ISSUE TITLE
Aria and Role attributes for accessibility

### ISSUE THREAD

**Issue by MorneL** [jackocnr/intl-tel-input#667]
This is less of an issue and more of a discussion before I submit a pr. Quite a few aria and role attributes are required to make this WCAG 2.0 compliant.

Expected:
on ul.country-list (aria-expanded: true/false, role: listbox)
on div.intl-tel-input (role: combobox)

There are a few more that I will point out, once I did the dev work.

@jackocnr would this be something you need?

**Comment by jackocnr** [comment]
@MorneL yes I would welcome a PR to add this stuff, thanks :)
