### ISSUE TITLE
Full number value for NANP countries is set incorrectly when number field is empty

### ISSUE THREAD

**Issue by Qakulukiam** [jackocnr/intl-tel-input#670]
### Steps to reproduce
1.  Go to the [hidden input example page](https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/hidden-input.html).
2.  Select any NANP country with a 4 digit dial code (for example American Samoa +1684).
3.  Submit the form with an empty value.

### Expected behaviour
The hidden input gets send with an empty full number value.

### Actual behaviour
It adds the dial code as the full number to the hidden input and sends it (see GET params in address bar).

### Initialisation options
hiddenInput (see example page)

### More info
It's not just the hidden input, running `.intlTelInput("getNumber")` on an initialized input field leads to the same result (this can be recreated via the dev tools in a browser on the same example page).

[Looks like this if statement might be the cause of this](https://github.com/jackocnr/intl-tel-input/blob/5600441113087150ace27bd8795e44b281965f33/src/js/intlTelInput.js#L1086)

related / possible cause: #529

**Comment by jackocnr** [comment]
Confirmed. Thanks for pointing this out.

Unfortunately I'm too busy to look into this right now, but welcome a pull request to fix this 👍

**Comment by jackocnr** [comment]
Fixed in https://github.com/jackocnr/intl-tel-input/commit/ee93f9189cdc87cc37907bfa458f0bd25e9062dc - will be included in next release. Thanks again.
