### ISSUE TITLE
i18n for english names

### ISSUE THREAD

**Issue by natcohen** [jackocnr/intl-tel-input#672]
It is probably obvious but I can't find anything about it.

Is there a way to change the default language of the country names? I need to be able to display those names in French, German and Italian instead of English.

Edit: I've seen this example: https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/modify-country-data.html but the problem is that the alphabetical order is not correct (it keeps the english alphabetical order, see Schweiz and Sverige). In addition, I really think it should be a JSON or XLF/XMB file with the list of all the names in one language so we can easily create support for new languages.

**Comment by jackocnr** [comment]
You can always edit the source in src/js/data.js and rebuild.

Otherwise, I'm open to a PR that updates the build process to pull in the country names from a given config file.
