### ISSUE TITLE
Canada flag automatically changes back to US

### ISSUE THREAD

**Issue by dbodenschatz** [jackocnr/intl-tel-input#673]
### Steps to reproduce
1. For a phone number, select Canada as the country.
2.  Start typing a phone number
3.  After you hit the 3rd digit, the flag will change from Canada to US. 

### Expected behaviour
The flag should stay as Canada

### Actual behaviour
After typing the 3rd digit, something happens and the flag changes from Canada to US. I'm assuming because they share a country code of 1.

### Initialisation options
You can use the demo page to see this happening:
https://intl-tel-input.com/

**Comment by jackocnr** [comment]
That is correct.

**Comment by leozhangFM** [comment]
Is it possible to change the behavior so that it doesn't automatically switch?
