### ISSUE TITLE
[FEATURE] Bootstrap support

### ISSUE THREAD

**Issue by subversivo58** [jackocnr/intl-tel-input#675]
Bootstrap in its latest development branch is in beta 3 which is a prelude to the release of stable version 4 (announced for the end of this January) and there were significant changes in the [structure of forms and inputs](https://getbootstrap.com/docs/4.0/migration/#forms).

I'm trying to get something close to the figure below using **"addons"** (now suffixed classes for **prepend** and **append**):

![intlinput](https://user-images.githubusercontent.com/6475273/34623026-af60dcba-f236-11e7-963f-df54e4a512fd.PNG)

However this input that by default Bootstrap receives 100% width, but as it is being enveloped in a `div`:

    <div class="intl-tel-input allow-dropdown">

Bootstrap does not recognize (does not apply width) ... to bypass this I tried to use the `w-100` class directly in the `<input>` but the library adds a `padding-right` that does not allow to reach 100% width in addition to not resize this measure using **"break-points"**.

![intlinput-2](https://user-images.githubusercontent.com/6475273/34624480-9af79704-f23c-11e7-8ae7-7ff07dec6c4e.PNG)

> My request

I know this library was not designed to be used specifically with Bootstrap but I wonder if it is possible for some extra class to be added to the `<input>` and correct this? Something like: set `padding-right` using **"break-points"**?

**Comment by subversivo58** [comment]
I tried to use Bootstrap classes and custom classes by following media queries the different **"break-points"** in the quest to regulate the `padding-right` but did not succeed.

In the change of resolution or in different devices visually the field did not occupy all the space or the icon was thrown down.

For the time being the approach that allowed me to make the field visually fluid (following the other elements in all the resolution changes) was to redefine the **css** and add the **"addon"** after starting the library.

The following example using `input-group-sm` (for small input):

```css
.input-group-sm > .intl-tel-input {
  display: flex;
  width: 100%;
}

.input-group-sm > .intl-tel-input > .input-group-append > .input-group-text {
  padding: .25rem .5rem;
  font-size: .875rem;
  line-height: 1.5;
}
```

```javascript

let telInput = $("#phone")

// initialize
telInput.intlTelInput()

// append "addon"
$('.intl-tel-input').append(`
    <div class="input-group-append">
        <span class="input-group-text rounded-0 fa fa-phone"></span>
    </div>
`)
```

Visually satisfying in all changes:

<img src="https://user-images.githubusercontent.com/6475273/34661091-59f87b1c-f42e-11e7-9593-f9cdff9b0b65.PNG" width="100%" >


<img src="https://user-images.githubusercontent.com/6475273/34661099-64f21f28-f42e-11e7-9cca-8a67f668e769.PNG" width="67%"><img src="https://user-images.githubusercontent.com/6475273/34661105-6b264ee6-f42e-11e7-9f1a-e587e523bd29.PNG" width="33%">

----

There is not much effort to get to the result by following the new Bootstrap forms standard.

As the library captures this `<input>` and adds it to a `div` one could check if there is a later element with the `input-group-append` class and add it too ... maybe a flag in the startup options?

**Comment by jackocnr** [comment]
Sorry this is a bit too much information! Please can you create a really simple Codepen with (A) a vanilla Bootstrap 4 input, with the icon at the side how you want it. And then (B) the same thing, but you initialise intl-tel-input on the input? Then I can have a play and try to get it working. Cheers.

**Comment by subversivo58** [comment]
Hmmm ... I really struggled trying to make a CODEPEN with this library from CDNJS.

    https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/12.1.6/js/intlTelInput.min.js

It simply is not loaded.

I will try to play on a GitHub page the template I am using (testing)

**Comment by jackocnr** [comment]
Here's my standard template: https://codepen.io/jackocnr/pen/yehvE

**Comment by subversivo58** [comment]
Thanks for your model helped a lot.

This is a cleaner codepen that contemplates my second comment: [PEN](https://codepen.io/Subversivo58/pen/ypxRpZ)

**Comment by jehad1990** [comment]
I have implemented this with BS4 by doing the following and it works just fine so far:

1. Add the following custom CSS:
`.intl-tel-input.allow-dropdown{
    -webkit-box-flex: 1;
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    width: 1%;
}
.flag-container {
	z-index: 4;
}`

2. Add the class `w-100` as you mentioned to your `<input>`

**Note,** in case you will add prepend to the right, add this inline CSS to your prepend `<div>` : `style="margin-left: -1px;"`

**Comment by subversivo58** [comment]
Personally since I'm using Bootstrap4-beta3 I was able to resolve the issue with the @jehad1990 suggestion (it's better than my previous approaches) ... a codepen of what I'm currently using

https://codepen.io/Subversivo58/pen/qpJMjy

But the question is whether the library could offer this "support"?

I believe that verifying that the user is using Bootstrap 4 would be redundant and unnecessary but something like a **"flag"** in the constructor (initialization) would be a more direct approach.

Something like:

**main.js**

```javascript
let telInput = $('#phone')

telInput.intlTelInput({
    bootstrap4: true
})
```

This could be checked in the prototype in the `_generateMarkup` function to add a **"css"** class:

**intlTelInput.js**

```javascript
if (this.options.bootstrap4) {
    parentClass += " bootstrap4-input"
}
```

In **"css"** append this class would overwrite the previous rules (default):

**intlTelInput.css**

```css
.bootstrap4-input {
  -webkit-box-flex: 1;
  -ms-flex: 1 1 auto;
  flex: 1 1 auto;
  width: 1%;
}
.bootstrap4-input > input {
  width: 100%!important;
}
.bootstrap4-input > .flag-container {
  z-index: 4;
}
```

This seems more consistent.

In advance I apologize for prolonging the issue and the unnecessary information set.

**Comment by jackocnr** [comment]
Thanks for your solution @jehad1990. And thanks for all the info and thoughts @subversivo58. If I were going to add anything to the plugin, I would add something generic like an initialisation option called `containerClass`, which would be a string class name, which would be applied to the container, as this would allow people to make the plugin compatible with whatever version of whatever framework they want to use. I would accept a PR to add that functionality. Closing this for now.
