### ISSUE TITLE
Country flag is not set correctly if setNumber is called with RFC3966 format

### ISSUE THREAD

**Issue by rdicroce** [jackocnr/intl-tel-input#677]
### Steps to reproduce
1.  Call setNumber, passing a number in RFC3966 format.

See https://codepen.io/anon/pen/pppLBm

### Expected behaviour
Country flag is set appropriately based on the phone number's country code.

### Actual behaviour
Uses the default country.

**Comment by jackocnr** [comment]
Sorry this plugin does not support RFC3966. Please strip the `tel:` prefix before you call `setNumber` and it should work just fine.
