### ISSUE TITLE
URGENT: My number is the default number for Panama

### ISSUE THREAD

**Issue by nesbtesh** [jackocnr/intl-tel-input#678]
A lot of websites that are using your plugin, have my number as the default number for Panama: https://www.allcoin.com/

my number is +507-6002-2345

Can you please change it, thanks

**Comment by jackocnr** [comment]
Sorry to hear that! We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for those default numbers - you'll need to raise the issue with them.

**Comment by jackocnr** [comment]
I see libphonenumber have changed their issue tracking system - info here: https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md
