### ISSUE TITLE
Hong Kong Telephone Numbers

### ISSUE THREAD

**Issue by bs-thomas** [jackocnr/intl-tel-input#686]
Hello there,

Hong Kong have added a few telephone number headings.  Thought it would be a good idea to let you know in case validation fails at the moment.

http://news.rthk.hk/rthk/en/component/k2/1379205-20180205.htm?share=twitter

Thanks!

**Comment by jackocnr** [comment]
Hi, thanks. We use libphonenumber for validation, so best to check with them.
