### ISSUE TITLE
Bootstrap 4 Compatibility?

### ISSUE THREAD

**Issue by alexgarciab** [jackocnr/intl-tel-input#690]
Are there any plans to make this plugin compatible with Bootstrap 4?

### Steps to reproduce
1.  Get Bootstrap 4 library
2.  Use jQuery plugin Intl Tel Input

### Expected behaviour
Design should not break

### Actual behaviour
Design breaks

### Pictures

<img width="560" alt="4ctubbshzdutxiewji4qxjtbf_czdv346btau3sibl3ojz7c3su6gwp7cp48w3naqejnhqwkyq9k6twruvjbed0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85" src="https://user-images.githubusercontent.com/6924386/35825537-79b94398-0ab6-11e8-854f-d29d4791ad09.png">

**Comment by jackocnr** [comment]
Haha "design breaks". Can you give me a bit more detail?

**Comment by alexgarciab** [comment]
Figured out that with some CSS tweaks, it could be fixed.

**Comment by ronjb04** [comment]
> Figured out that with some CSS tweaks, it could be fixed.

do you mind sharing the css tweak you made?

**Comment by vidalweb** [comment]
Just add a CSS, example:
--- html input --- 
```
<div class="input-group">
    <input type="tel" id="telInput" name="phone" value="" class="form-control" placeholder="+41 312 345 6789">
     <div class="input-group-append" data-area="true">
         <span class="input-group-text"><i class="fa fa-phone fa-fw"></i></span>
      </div><!--/input-group-append -->
</div><!--/input-group -->
```

--- style css  ---
```
.input-group .intl-tel-input {
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    width: 1%;
}
```
