### ISSUE TITLE
Adding 0 at the beginning of the phone number input value.

### ISSUE THREAD

**Issue by vladi160** [jackocnr/intl-tel-input#692]
I have input with value `428603803` for phone number and code `61` for Australia and this for set the plugin for this input:

> `       telInput.intlTelInput({
            allowDropdown: false,
            initialCountry: ISO CODE HERE,
            utilsScript: "https://1cf5229636340d3e1dd5-0eccc4d82b7628eccb93a74a572fd3ee.ssl.cf1.rackcdn.com/testing/utils.js"
        });`

The problem is that when loads the page it adds `0` at the beginning of the phone number and the phone of the input value from `428603803` will be `0428603803`, with zero at the beginning. This is what i don't want.  Is there way to fix that ?

**Comment by jackocnr** [comment]
Well `428603803` is an invalid number, right? Why do you want to display just that?

You have 3 options:

- Leave `nationalMode` enabled (which it is by default), so it will display the national number, which starts with a `0`.
- Set `nationalMode` to false, so it will display the international number, with `+61`.
- Enable `separateDialCode` which displays the international dial code next to the flag, in which case it makes sense to display the rest of the international number next to it, in the input: `428603803`

**Comment by vladi160** [comment]
This will remove `416` from `4169190118` which is with code `1`. I have fixed it in another way with commenting `initialCountry` and manipulating the country select HTML element.

**Comment by narasimhakamath** [comment]
> This will remove `416` from `4169190118` which is with code `1`. I have fixed it in another way with commenting `initialCountry` and manipulating the country select HTML element.

Could you please provide the solution to this if you've found it?
