### ISSUE TITLE
Jio Numbers '877 918 9177', '8369299064', '8169470539'. showing invalid numbers.

### ISSUE THREAD

**Issue by VVNFERNANDES** [jackocnr/intl-tel-input#693]
IMPORTANT: please note that the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

### Steps to reproduce
1.  Have country india selected
2.  Type in '877 918 9177', '8369299064', '8169470539' any of these numbers
3.  Click submit.
4. Validation would give them invalid numbers

### Expected behaviour
Should be considered valid number
### Actual behaviour
Validation would give them invalid numbers

**Comment by jackocnr** [comment]
And did you check if libphonenumber considers them valid?

**Comment by VVNFERNANDES** [comment]
O yes sorry i checked opne of the closed ticket. That in the new version it does. I have an older version. Thanks a lot for prompt reply.

**Comment by jackocnr** [comment]
Those numbers show as valid for me on the [Validation demo](https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html). Are you sure you're using the latest version of the plugin?

**Comment by VVNFERNANDES** [comment]
Hi yes I was on older version . Now switched to new version and it validates now. But now the geolookup is giving issue. It is not selecting the country code base on geo lookup.
I am using the following code:

$('form :input[name=mobile]').each(function (index) {
$(this).intlTelInput("setCountry", "in");
$(this).intlTelInput({
geoIpLookup: function (callback) {
$.get('http://ipinfo.io', function () {
}, "jsonp").always(function (resp) {
var countryCode = (resp && resp.country) ? resp.country : "";
callback(countryCode);
});
utilsScript: "js/intlTelInput/js/utils.js"
});
});

**Comment by jackocnr** [comment]
Please use code formatting so it's readable.

And you can't call `setCountry` before you've initialised the plugin.

And do you have any JS errors in the console?
