### ISSUE TITLE
How to set the country code when opening a popup from edit link of a grid?

### ISSUE THREAD

**Issue by swapnilgopal** [jackocnr/intl-tel-input#695]
IMPORTANT: please note that the autoFormat feature (format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

### Steps to reproduce
1.  I am able to save the country code in database from a form
![image](https://user-images.githubusercontent.com/36505130/36295282-86c14654-130c-11e8-953a-e7f25b20cca9.png)

2.  I have a grid where there is a Edit button which opens a modal popup where I want to retrieve the country code
![capture](https://user-images.githubusercontent.com/36505130/36295343-19cbfc64-130d-11e8-8392-eb44f4f00142.PNG)

3. On click of edit the below pop-up opens up:
![image](https://user-images.githubusercontent.com/36505130/36295361-342f1776-130d-11e8-8bea-4489cc254671.png)

4.  Need to get the country code on the modal popup for the row that I select.

### Expected behaviour
Want to display the country code against each record

### Actual behaviour
Not able to display the country code with 
$("#inputContact").intlTelInput("setCountry", $("#inputCountryCode").val());
I need to call this on click of edit but it gives ".intlTelInput() is not a function" and only gets recognized on load.

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
I'm sorry, I'm totally confused. You say you want to retrieve the country code, and yet you're calling `setCountry`? Please break this down into really simple steps.

**Comment by swapnilgopal** [comment]
I have updated the details above, hope this helps in understanding the issue

**Comment by jackocnr** [comment]
Thanks. It seems in step 3 the plugin is in a broken state, with a grey flag - I'd like to solve this problem first. Please can you post the JS that you're using to initialise the plugin when the modal is opened. And tell me exactly what the phone number value is that you're setting in the input (does it include the international dial code?), and tell me how you're setting it - do you put the value in the input before you init the plugin, or do you call `setNumber` after you init the plugin?

Oh I just noticed from the table that under the "contact" column, you have the number starting 718. As mentioned in the readme, I highly recommend you store numbers in the full international format (which you get from calling `getNumber` when the user has selected a flag and entered their number. This way the number includes the international dial code e.g. `+44` for the UK, and so you dont have to store the country info separately. Then when you init the plugin with a full international number, it automatically displays the right country.

**Comment by swapnilgopal** [comment]
Thank you for the response.

I saved the data with the country code i.e., with the full international format but still on modal popup load I am not able to get the code.
I require it to be set on the click of the Edit link i.e., when the pop-up opens and retrieves data

![image](https://user-images.githubusercontent.com/36505130/36307110-8d6f445e-1340-11e8-9c67-59b65f5b02c4.png)

The data does change but only when I focus on the input field and take the cursor to the end of the field.
![image](https://user-images.githubusercontent.com/36505130/36307172-e4ca5694-1340-11e8-9b85-bf0c7617cedc.png)

Could you please help me with this?

**Comment by jackocnr** [comment]
> I saved the data with the country code i.e., with the full international format but still on modal popup load I am not able to get the code.

What do you mean when you say you are not able to get the code? What are you trying to do? In your screenshots it looks like the country is being selected correctly now. If you want to get the currently selected country data you can use `getSelectedCountryData` method.

**Comment by swapnilgopal** [comment]
I want to display the country for which I have saved the contact. 

For example, I have a number saved for UK as +447113456789 which is displayed in the row and I click on edit button of the grid for that respective row the modal pop-up opens but the country code is set as US by default which should be UK.

As per your suggestion, I tried using getSelectedCountryData method as well.

**Comment by jackocnr** [comment]
Haha this is all so confusing. Let's please stick to this one example of a UK number which includes the intl dial code. Please show me the code you're using to init the plugin when you open the modal, and a screenshot of the modal once the plugin has initialised.

**Comment by swapnilgopal** [comment]
[Doc2.docx](https://github.com/jackocnr/intl-tel-input/files/1736694/Doc2.docx)
Could you please take a look at the attached file

**Comment by nyeyint** [comment]
Hi @swapnilgopal 

I think you need to save "iso2" to database.So you can set country when you edit like
`
$('#country').intlTelInput("setCountry", iso2);
`

iso2 is country code from your database.

**Comment by jackocnr** [comment]
@swapnilgopal I can't read docx files. Please paste the code here directly.

**Comment by swapnilgopal** [comment]
Screen 1 when the record saves:
 

Screen 2 where we see the saved record:
 



Pop-up on Edit link button click: (default country is set)
 
After taking the cursor till the end: (country code changes whereas it should change on load of pop-up itself)
 




Code: I need to get the number on click of edit link button but if I write the code there it gives me not a function error. I am only able to write the code on load.

**Comment by swapnilgopal** [comment]
![image](https://user-images.githubusercontent.com/36505130/36425550-3109e73e-166d-11e8-8926-e8ce03478a60.png)
Screen 1 when the record saves:
![image](https://user-images.githubusercontent.com/36505130/36425570-42ddd682-166d-11e8-93b4-bc15ae52a0ce.png)

Screen 2 where we see the saved record:
![image](https://user-images.githubusercontent.com/36505130/36425582-484eec50-166d-11e8-9707-810a18e6a02d.png)

Pop-up on Edit link button click: (default country is set)
![image](https://user-images.githubusercontent.com/36505130/36425596-4d903b4c-166d-11e8-8425-490aa9aa406f.png)

After taking the cursor till the end: (country code changes whereas it should change on load of pop-up itself)
![image](https://user-images.githubusercontent.com/36505130/36425605-52e0a924-166d-11e8-8d4f-ac4c6902ee7c.png)

Code: I need to get the number on click of edit link button but if I write the code there it gives me not a function error. I am only able to write the code on load.
![image](https://user-images.githubusercontent.com/36505130/36425626-594d9786-166d-11e8-819d-6011a2e276b7.png)

**Comment by jackocnr** [comment]
In your ajax success callback, you're setting the phone number input value directly. Instead you should use the plugin's `setNumber` function.

**Comment by riliwanrabo** [comment]
@swapnilgopal  How were you able to get this to work in a mobile

**Comment by aruljayaraj** [comment]
@swapnilgopal  Please update your code on ajax success like `$("#inputContact").intlTelInput("setCountry", "gb"); `
Here **gb** is your country code from your database. It would work in mobile as well.

**Comment by aolamer** [comment]
You can use the option:

hiddenInput: Inject a hidden input with this name, and on submit, populate it with the result of getNumber.
hiddenInput: "mobile",
Where mobile is your input name.

**Comment by sumayyayellow** [comment]
Can i get the full code

**Comment by lil-id** [comment]
Hello [swapnilgopal](https://github.com/swapnilgopal)
I will give you my code sample, hope this can help you

index.html
```
<div class="form-group">
          <label>WhatsApp Reservation</label>
          <input id="wa_reservation" type="text" class="form-control" name="wa_reservation" value="{{ $agent->wa_reservation or old('wa_reservation')}}">
           <span id="valid-msg" class="hide" style="color: #00C900;">✓ Valid</span>
           <span id="error-msg" class="hide" style="color: #c90000;"></span>
</div>
```
javascript code

```
<script>
const phoneInputField = document.querySelector("#wa_reservation");
    const errorMsg = document.querySelector("#error-msg");
    const validMsg = document.querySelector("#valid-msg");
    const errorMap = ["Invalid number", "Invalid country code", "Too short", "Too long", "Invalid number"];

    const phoneInput = window.intlTelInput(phoneInputField, {
    preferredCountries: ["id"],
    utilsScript: "../../../../admin/js/utils.js",
    });

    const reset = function() {
        phoneInputField.classList.remove("error");
        errorMsg.innerHTML = "";
        errorMsg.classList.add("hide");
        validMsg.classList.add("hide");
    };

    phoneInputField.addEventListener('blur', function() {
    reset();
    if (phoneInputField.value.trim()) {
        if (phoneInput.isValidNumber()) {
        validMsg.classList.remove("hide");
        } else {
            phoneInputField.classList.add("error");
        const errorCode = phoneInput.getValidationError();
        errorMsg.innerHTML = errorMap[errorCode];
        errorMsg.classList.remove("hide");
        }
    }
    });

    // auto format country number e.g +62 for Indonesia
    $(document).ready(function() {
        $('.iti__flag-container').click(function() { 
          var countryCode = $('.iti__selected-flag').attr('title');
          var countryCode = countryCode.replace(/[^0-9]/g,'')
          $('#wa_reservation').val("");
          $('#wa_reservation').val("+"+countryCode+" "+ $('#wa_reservation').val());
       });
    });

    // on keyup / change flag: reset
    phoneInputField.addEventListener('change', reset);
    phoneInputField.addEventListener('keyup', reset);
</script>
```

**Comment by JBerriosG** [comment]
@jackocnr Excuse me, exist some way to change the dial code that appears in the dropdown? for example: instead of "+56" could be "+569" to Chile.

**Comment by etkinss** [comment]
$('.country').each(function () {
    var dialCode = $(this).attr("data-dial-code");
    var countryCde = $(this).attr("data-country-code");
    if ("+" + dialCode === "your country code") {
        $(".your input class").intlTelInput("setCountry", countryCde);
    }
});

**Comment by ask4alikhan** [comment]
Hi @jackocnr, Thank you for this wonderful plug-in! I am using this on a salesforce communities page. I have a list of countries and one of them is missing in intl-tel-input. How can I add them + their flags? 
Artsakh | 374 47, 374 97

**Comment by jackocnr** [comment]
@ask4alikhan your question is off-topic, please create a new issue for this.

**Comment by Steamed-remington** [comment]
i found the key https://opencodes.space/questions/what-is-the-best-way-to-display-data-from-a-dynamically-generated-table-in-a-popup-window
