### ISSUE TITLE
Country code does not appear

### ISSUE THREAD

**Issue by BlackWarHawk** [jackocnr/intl-tel-input#698]
Hi.

The country code does not appear where the country is selected, however, the flag is updated. 
The dropdown list works fine, but the code does not appear in the input field, so you still need to type it manually.
Is there a way to fix it?

![image](https://user-images.githubusercontent.com/25806665/36495653-dea54210-172d-11e8-9f54-c138d7ba5c71.png)

![image](https://user-images.githubusercontent.com/25806665/36495637-cf92fef2-172d-11e8-940b-e9cfac507214.png)

Thanks!

**Comment by jackocnr** [comment]
I recommend you leave it as-is, so your users can just enter their national numbers, and don't have to think about international dial codes. (to make this clearer, I'd suggest you remove your manual placeholder, and allow the plugin to automatically add a placeholder of an example number for the selected country).

If you really want international dial codes, you can either disable `nationalMode`, or you can try enabling `separateDialCode`.
