### ISSUE TITLE
when applying text to table cell

### ISSUE THREAD

**Issue by ko06** [jackocnr/intl-tel-input#700]
hi,
in my table cell, I have provided an edit option for this plugin.but options(country) list last row not opens out of table ...if I removed table responsive its working fine.

**Comment by jackocnr** [comment]
If your problem is that the plugin dropdown is getting cut off by it's container, have you tried the `dropdownContainer` option?

**Comment by ko06** [comment]
hi, it's working...thank you so much

**Comment by jackocnr** [comment]
👈 you got it
