### ISSUE TITLE
Adding the word "China" beside places that belong to "China"

### ISSUE THREAD

**Issue by bs-thomas** [jackocnr/intl-tel-input#706]
Not sure if I'm posting this at the right place, but seems like Mainland China is starting to ban places that call Hong Kong, Macau, or Taiwan itself a country and without the keyword "China" as it is misleading.

I was thinking if these countries should come with the keywords "China" beside them.

See attached news:
![whatsapp image 2018-03-07 at 13 08 38](https://user-images.githubusercontent.com/2464920/37079650-42851026-221e-11e8-8033-aeab0fc338af.jpeg)

**Comment by jackocnr** [comment]
Hmm interesting! Thanks for raising the issue. I'm in no position to make these kinds of political decisions, so I would just follow the lead of others. I notice Google signup doesn't do this yet: https://accounts.google.com/SignUp. Please let me know if you can find examples of major companies doing this, like Google, Facebook, Amazon etc, but until then, I'm going to close this issue.
