### ISSUE TITLE
Emoji Flags

### ISSUE THREAD

**Issue by Samb102** [jackocnr/intl-tel-input#709]
Hello,

Thank you for your works.

Have you ever think about implement emoji flags ?

**Comment by jackocnr** [comment]
Please search issues before creating a new one.

**Comment by Samb102** [comment]
I did. Nothing show up.

**Comment by jackocnr** [comment]
Search for "Emoji Flags" and click on "Issues"

**Comment by Samb102** [comment]
Thanks.
