### ISSUE TITLE
custom design for text 

### ISSUE THREAD

**Issue by bhargavcode** [jackocnr/intl-tel-input#711]
i'm unable to change IntlTelInput textColor and textHint color, textSize,
when im using setEmptyDefault()methode to show the default country on activity created this show ArrayOutOfBoundException, (-1) on "IND" String paraameter in setEmptyDefault()

and flag size and make space between flag and edit text ,
suggetion....
show the country code after selecting the flag reght side of the flag

**Comment by jackocnr** [comment]
Sorry I have no idea what this `setEmptyDefault` method is that you mention.

Everything is completely customisable in the CSS - just make sure your CSS overrides are loaded after the plugin CSS, or that they have a higher specificity.
