### ISSUE TITLE
Insert 2 items in the same page

### ISSUE THREAD

**Issue by avazquez89** [jackocnr/intl-tel-input#713]
First of all, great library!! Thanks a lot for sharing it.

My problem is: I need to use 2 fields in the same HTML, but I was looking at the code, and I think it's prepared for using it with only one field, because it uses ID reference ($"#...").

Somebody knows if it's possible to use it twice in the same page?

Thanks a lot.

**Comment by jackocnr** [comment]
Hi there, you're very welcome :)

Have you tried using it with multiple inputs? It should work fine. Just give them a class and then initialise the plugin on that class e.g. `$('.phone').intlTelInput();`

**Comment by avazquez89** [comment]
@jackocnr Thanks a lot for your answer!!! 
Problem solved!! I was doing something wrong in the Js code.
Closing the issue!!

**Comment by srikanth-paramkusam** [comment]
@avazquez89  Hi there, I am facing the similar issue. When I am using the 2 fields in same page 2nd field is not working properly. Can you please share the working model in plunkr or any other format. Will be a great help to me & my team.

Thanks in advance.
