### ISSUE TITLE
Get selected country code

### ISSUE THREAD

**Issue by lcaixeta-fixeads** [jackocnr/intl-tel-input#726]
How do I get only the chosen country code?

**Comment by lcaixeta-fixeads** [comment]
Done:
$("#phone").intlTelInput("getSelectedCountryData").dialCode;

**Comment by iamfaiz** [comment]
How do I do it now, with the new version (without jQuery)?

**Comment by jackocnr** [comment]
@iamfaiz see the readme for getSelectedCountryData
