### ISSUE TITLE
Valid number with letter ?!

### ISSUE THREAD

**Issue by psppro26** [jackocnr/intl-tel-input#729]
It's normal than number can be writed with letter ? like if i put 601391FRDD for an US number it's a valid number ? same on the demo ? its possible to desactivate this ??

![image](https://user-images.githubusercontent.com/25665778/39409377-3e1111ec-4be6-11e8-99d5-e43b0dd6f600.png)

**Comment by jackocnr** [comment]
As per the New Issue notes, formatting and validation is handled by an external lib called libphonenumber, so please direct any questions to them.
