### ISSUE TITLE
problem with safari browser

### ISSUE THREAD

**Issue by Parthadeep** [jackocnr/intl-tel-input#730]
Hi!

I have download the the project from "https://github.com/jackocnr/intl-tel-input#demo-and-examples" page.

After download I unzip the folder and open "demo.html" in different browser. But in safari browser it is not working.
I am using windows10 and safari browser version.
![image](https://user-images.githubusercontent.com/38977009/39621978-38bc99de-4fae-11e8-97e0-69312afb63f1.png)

Problem is there is no country code dropdown. But in other browser it is showing the dropdown.
![image](https://user-images.githubusercontent.com/38977009/39622047-709dcb7a-4fae-11e8-886f-6f5a1e1413d4.png)

Thank you

Parthadeep

**Comment by jackocnr** [comment]
You're using a really old version of Safari - please try using the latest version (v11.1). I'm going to close this for now, but if you get an error with the latest version, feel free to re-open it.

**Comment by jackocnr** [comment]
Ah ha, I've just read that Apple stopped supporting Safari for Windows in 2012.

**Comment by Parthadeep** [comment]
Hi!

Thank you for your kind reply.
We checked with Mac OS there we got the Safari(v11.1). It is working fine.
Actually for development purpose we use windows10, for windows only Safari (v5.1.7) is latest.

You don't have to re-open the issue. It is working fine in Mac OS with Safari(v11.1).

Thank you
Parthadeep

**Comment by kinkarso** [comment]
@Parthadeep Could you recommend a fallback for this? We are using this on an ecommerce site, and quite a few customers are unable to enter their phone numbers when using an older iPad or a Mac with Safari 9.

Asking them to instead input +61 234 567 etc doesn't seem to do it.

**Comment by jackocnr** [comment]
What error do you see in the console with Safari 9?

**Comment by kinkarso** [comment]
On load it gives this error message: https://d.pr/i/7hLUG2. After input in the Phone text field, this error is shown: https://d.pr/i/TBTLsD

**Comment by jackocnr** [comment]
If you look at the right hand side of those error messages you will see they are coming from jquery.validate
