### ISSUE TITLE
Indian number showing invalid though it is valid as per libphonenumber

### ISSUE THREAD

**Issue by Rinkuk1993** [jackocnr/intl-tel-input#731]
I have added same number in libphonenumber and intl-tel-input demo. The number is showing invalid in this plugin which is incorrect.

Please look into the below image and help me get it fixes ASAP.

<img width="759" alt="intl-tel issue" src="https://user-images.githubusercontent.com/14367488/39758426-71e88398-52ed-11e8-8ef1-1e0c2cac18a0.png">
<img width="869" alt="libphonenumber" src="https://user-images.githubusercontent.com/14367488/39758427-724010e0-52ed-11e8-9c1d-1e443bb0492f.png">

**Comment by jackocnr** [comment]
Hi there, thanks for raising this issue. Turns out it's just an issue with caching on the demo site. If you empty your cache it will work. I have created an issue to fix this: https://github.com/jackocnr/intl-tel-input/issues/732
