### ISSUE TITLE
Toll Free Number Not Showing Correctly

### ISSUE THREAD

**Issue by Sibgha228** [jackocnr/intl-tel-input#733]
### Steps to reproduce
1.  Select United States
2.  Enter this number 855-678-3030

### Expected behaviour
Either united states or blank flag should appear with full number in the field (855-678-3030)

### Actual behaviour
The number saves correctly (+18556783030). But while displaying its show a blank flag and only last four digits in the field. 
Also getNumberType returns -99.

![selection_094](https://user-images.githubusercontent.com/26971711/39866168-f71f840e-5468-11e8-85b8-88bac57d12f6.png)

#503 

### Initialisation options
formatOnInit: true,
separateDialCode: true,
 initialCountry: "auto"

### Already Tried
Setting the value in the done callback

**Comment by Sibgha228** [comment]
Thanks for the quick response. Can you please tell what's the normal behavior when we get a Toll free number. We just get a blank flag. ?

**Comment by jackocnr** [comment]
As per that issue you linked to:

> if the user selects a NANP country and types an 800 number, we should leave that country selected.

and

> if the plugin is initialised with nationalMode=true and an input value with a regionless NANP number, and no initialCountry option, then we should default to the US flag

**Comment by jackocnr** [comment]
Fixed by https://github.com/jackocnr/intl-tel-input/commit/734cfbb50ee5578db97f89e08ebfb06349cf6118. Will be included in next release.
