### ISSUE TITLE
Turkish phone number is recognized as invalid

### ISSUE THREAD

**Issue by inteloexo** [jackocnr/intl-tel-input#734]
### Steps to reproduce
1.  Enter phone number +903121234567

### Expected behaviour
I expected the number to be valid

### Actual behaviour
It is stated that the number is invalid

P.S. I have tried checking this number here: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html and it says it's valid. I used latest version v12.1.15.

**Comment by jackocnr** [comment]
Says it's valid on the validation demo page: https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html

Make sure utils.js is not loading some old cached version.
