### ISSUE TITLE
.on("countrychange", function(e, countryData) returning countryData as undefined.

### ISSUE THREAD

**Issue by Shelly-Thakur1** [jackocnr/intl-tel-input#742]
### Steps to reproduce
 $(".phone").on("countrychange", function(e, countryData) {
                        console.log("********", countryData); // undefined
});

### Expected behaviour
Country data should have correct data
### Actual behaviour
countryData is undefined

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
More information required. Please also provide your initialisation code. And what exactly are you doing that is triggering the countrychange event?

**Comment by Shelly-Thakur1** [comment]
Was just a version issue. Thanks!
