### ISSUE TITLE
What is wrong with your validator?

### ISSUE THREAD

**Issue by JILeXanDR** [jackocnr/intl-tel-input#744]
Those phones are valid:
  1. 0981234567dd "dd" // in the end of number
  2. 0981234d567 // "d" in the middle of number
  3. +3800981234567 // double "0"

Code https://jsfiddle.net/ve0w3adg/8/

**Comment by jackocnr** [comment]
From the New Issue template text:

> IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

Did you try that?

**Comment by JILeXanDR** [comment]
I've used this hack to prevent bad numbers
```
$('#phone').on('input', function (e) {
    $(this).val($(this).intlTelInput('getNumber'));
});
```


Method `getNumber` returs parsed phone without extra characters
