### ISSUE TITLE
New series Indian phone number is not validated in v12.1.0

### ISSUE THREAD

**Issue by balaanil77** [jackocnr/intl-tel-input#745]
Number starts with following series is not validated in v12.1.0.  but this has been handled in tag v12.1.15. 

> "+91 63xxxxxxxx"

So when can we expect the tag v12.1.15 to be released?

**Comment by jackocnr** [comment]
v12.1.15 has been released - what makes you think it hasn't?

**Comment by balaanil77** [comment]
We have a latest release tag for the version v12.1.0 as you can see in the below image.
<img width="927" alt="screen shot 2018-06-07 at 11 21 16 am" src="https://user-images.githubusercontent.com/34372451/41080609-00adb8fa-6a45-11e8-87fe-a54e2b55a76a.png">
But we don't have the same for the following (latest tag).
<img width="878" alt="screen shot 2018-06-07 at 11 21 38 am" src="https://user-images.githubusercontent.com/34372451/41080611-00df7688-6a45-11e8-8a33-e8902062191c.png">
So it is recommended to use the version v12.1.15 in production?

**Comment by jackocnr** [comment]
Oh that "Latest release" is just a Github thing - ignore that. Yes v12.1.15 is good for production. If you install the package using npm you will get v12.1.15.
