### ISSUE TITLE
Getting ReferenceError: allCountries is not defined

### ISSUE THREAD

**Issue by yash82** [jackocnr/intl-tel-input#749]
I am using intel-in-put JS library for my project and I am getting a reference error in my console like ReferenceError: allCountries is not defined. 

I have included main IntelInput.js and CSS files of latest version i.e. 12.3.0 but don't know why it'snot working. Although the lower version of intel input was working fine earlier but having an issue for mobile that on clicking at flag the drop down not working, so I move to use the latest version of this intel input library.

Please let me know what I am doing wrong here or what kind of issue is this.

Regards

**Comment by jackocnr** [comment]
Hi there, I'm afraid I would need to see some code to help debug this. Please can you create a codepen with the minimal code required to reproduce the error?

**Comment by yash82** [comment]
Hi Jackocnr

Thanks for your quick response.

I don't know how to use codepen and create a codepen. Can I share my site URL with you?

**Comment by jackocnr** [comment]
By all means share your URL, but if it's complicated then I'm afraid I probably wont have time to debug it properly. Codepen is easy to learn how to use and a very useful skill to have in this trade!

**Comment by yash82** [comment]
Ok, here is my site url as  https://dev.raiseitfast.com.

Also,i am going to learn how to create a codepen. Till then you can take a look at site and the Phone number field is under sign in button at create account tab.

**Comment by yash82** [comment]
Hey Jack

Please check this codepen for the code I have used at site

https://codepen.io/yash82/pen/NzvbqK

**Comment by yash82** [comment]
Yes, i am using the latest version of the intelInput plugin, the version is  12.3.0

I have download this latest plugin from this url resource  https://github.com/jackocnr/intl-tel-input/releases/tag/v12.3.0

**Comment by jackocnr** [comment]
You're using the src/ file instead of the build/ file!

**Comment by yash82** [comment]
Can you please explain which file I am using wrong here?

**Comment by jackocnr** [comment]
You're using src/js/intlTelInput.js but instead you should be using build/js/intlTelInput.js

**Comment by yash82** [comment]
Ok, I have just uploaded this file from build/js directory, will it work for mobile devices as well?

**Comment by jackocnr** [comment]
Yes. Does it work now?

**Comment by yash82** [comment]
Yes, it's working now at desktop and mobile too, but at mobile flag icons are not displaying.

**Comment by jackocnr** [comment]
They're also not displaying on desktop on your codepen. Have you added the CSS rules to update the paths to your flags image, as per the Getting Started section of the readme? https://github.com/jackocnr/intl-tel-input#getting-started

**Comment by yash82** [comment]
I can see flag icons at my desktop for codepen , you can check this screenshot here https://prnt.sc/juuwjq

No, I haven't used that 3rd step yet  i.e.  3. Override the path to flags.png in your CSS from your jquery reference. Is this due to which i am missing flag icons ?

**Comment by yash82** [comment]
I got it working now :)

Thanks a lot for all your help and getting time for me to help. I really appreciate you.

Thanks a lot Jack...

**Comment by jackocnr** [comment]
👍 glad you got it working
