### ISSUE TITLE
hiddenInput not passing via form

### ISSUE THREAD

**Issue by tmiecz** [jackocnr/intl-tel-input#751]
I honestly don't know what's the difference between my example, and the live one. Haha. But for some reason I just can't get the hiddenInput to work for me.

I recreated everything as in the sample provided, but when I submit the form, full_number comes up blank. I even tried downgrading jQuery and intl-tel-input down to the same versions, but to no avail.

The best thing I can think of to show you what I mean is if you go to this page:
https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/hidden-input.html

And save it to your desktop. Then run it and you'll see that after submit full_number is empty.

Anybody else had that issue?

**Comment by jackocnr** [comment]
Any errors in the JS console?

**Comment by tmiecz** [comment]
No errors, but it's obviously something on my end, I'm going to close this issue.

**Comment by DUAB-Johan** [comment]
I managed to get this error in safari on the iphone, if the form had a name or id. Not sure if it is browser-related though. Just for information...
