### ISSUE TITLE
Country list Scroll not working on Android phones

### ISSUE THREAD

**Issue by saimali9** [jackocnr/intl-tel-input#752]
Scroll dissapears when we switch to Mobile view in chrome. But its working perfectly on web view.

Scroll dosent work even on android phone too.

My country list css is below:

.intl-tel-input .country-list{
    top: 478px;
    position: absolute;
    z-index: 120;
    padding: 0;
    margin: 0 0 0 -1px;
    box-shadow: 1px 1px 4px rgba(0,0,0,0.2);
    background-color: white;
    border: 1px solid #CCC;
    white-space: nowrap;
    max-height: 200px;
    overflow-y: scroll;
    -webkit-overflow-scrolling: touch;
}

**Comment by saimali9** [comment]
If you switch to mobile view in chrom and hard reload the scroll disappears from country list drop down.

**Comment by jackocnr** [comment]
What exactly do you mean by "switch to mobile view"?

If I switch on the device toolbar, and select Pixel 2, refresh, click to open the country dropdown, I get a full screen scrollable list.

<img width="595" alt="screen shot 2018-06-20 at 10 27 38 am" src="https://user-images.githubusercontent.com/1186883/41649928-b2fd3fec-7474-11e8-9d81-a8455a47a873.png">

**Comment by saimali9** [comment]
Cant we have a scroll bar in the above screenshot? Like it is present in web view

**Comment by jackocnr** [comment]
For me, on Chrome on MacOS, there is no scrollbar on desktop - it only appears when you start scrolling. Same on Chrome on my Android phone. That's up to the browser I think. Can you link to an example where the scrollbar is visible the whole time?

**Comment by saimali9** [comment]
Im unable to scroll down on my android app. 

The platform im using is ionic1. 

it is working perfectly when i run it chrome. But when i make an APK for the app and run it on my phone the scroll stops working. 

![sss](https://user-images.githubusercontent.com/34023737/41656413-43d6ef8e-74a9-11e8-9334-34f353a5e282.jpg)

**Comment by jackocnr** [comment]
I'm afraid I don't have any experience with Ionic so I wont be able to help. But this works fine on the web, so this sounds like an Ionic specific problem. I'd try Stackoverflow. Please do post back here if you find a solution though. I see that [this exact issue has been raised before](https://github.com/jackocnr/intl-tel-input/issues/544) - perhaps you can ask there if they ever found a solution. Closing for now.

**Comment by saimali9** [comment]
It worked. Just had to play with the css classes. Thanks

**Comment by akdev96** [comment]
@kpman7 can you please tell me what did you changed in the css? I'm experiencing the same issue.
