### ISSUE TITLE
Phone placeholder in Mexico is wrong

### ISSUE THREAD

**Issue by ebarojas** [jackocnr/intl-tel-input#753]
When you choose Mexico from the list, the placeholder includes a "044" prefix, this is prefix is archaic and only used when dialing with landlines.

### Steps to reproduce
1.  Choose Mexico (MX) from dropdown

### Expected behaviour
It should have a 10 digit phone number ie: 55 5468 2345

### Actual behaviour
It shows 044 222 123 4567

### Initialisation options
Preferred country MX

**Comment by ebarojas** [comment]
I think it has to do with the custom build of Google's libphonenumber

**Comment by jackocnr** [comment]
Yeah we use libphonenumber to generate the example numbers - if there is a problem the best thing to do is to raise an issue with them. Cheers.

**Comment by Stern87** [comment]
libphonenumber has been updated to v8.10.17 so it includes the changes about Mexico number format https://github.com/google/libphonenumber/releases/tag/v8.10.17
Could you update the build folder and make new release, please?

**Comment by jackocnr** [comment]
Thanks for letting me know. It actually only takes 5 minutes to do this yourself, if you'd be willing to submit a Pull Request? Instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber). Thanks :)

**Comment by Stern87** [comment]
Excuse me. I was failed to make a release by instructions above.
Can anybody make an update, please?

**Comment by jackocnr** [comment]
I have now updated libphonenumber to v8.10.17.

Released in v16.0.3
