### ISSUE TITLE
intlTelInputUtils is not defined

### ISSUE THREAD

**Issue by jimlongo56** [jackocnr/intl-tel-input#754]
I can't seem to figure this out, bang my head as I might. 

The front end works as it should, the dropdowns, flags, placeholders, validation, etc., 

At the bottom of this script is the variable I'm trying to grab.
I can output it in the console - 
`$("#input_4_28").intlTelInput("getNumber", intlTelInputUtils.numberFormat.E164);`  
and it returns a properly formatted number.

Yet this code displays a warning and then an error `Uncaught ReferenceError: intlTelInputUtils is not defined` 

I'm hoping to pass this variable via ajax back to the php script (page).

```
        var telInput = $("#input_4_28"),
            errorMsg = $("#error-msg"),
            validMsg = $("#valid-msg");

        telInput.intlTelInput({
            separateDialCode: true,
            utilsScript: "//cdnjs.cloudflare.com/ajax/libs/intl-tel-input/12.3.0/js/utils.js",
            autoPlaceholder: true,
            preferredCountries: [ 'au','ca','fr','de','uk','mx','nz','no','ru','es','se','ch','us','gb'],
            geoIpLookup: function(callback) {
                $.get("https://ipinfo.io", function() {}, "jsonp").always(function(resp) {
                    var countryCode = (resp && resp.country) ? resp.country : "";
                    callback(countryCode);
                });
            },
            initialCountry: "auto",
            // autoFormat:false,
            // preventInvalidNumbers:true,
            // nationalMode:false
        });

        var reset = function() {
            telInput.removeClass("error");
            errorMsg.addClass("hide");
            validMsg.addClass("hide");
        };

        // on blur: validate
        telInput.blur(function() {
            reset();
            if ($.trim(telInput.val())) {
                if (telInput.intlTelInput("isValidNumber")) {
                    validMsg.removeClass("hide");
                } else {
                    telInput.addClass("error");
                    errorMsg.removeClass("hide");
                }
            }
        });
        // on keyup / change flag: reset
        telInput.on("keyup change", reset);

        var phoneNumberString = $("#input_4_28").intlTelInput("getNumber", intlTelInputUtils.numberFormat.E164);
        console.log(phoneNumberString);
```

**Comment by jackocnr** [comment]
Hi there. You need to wait for the utils script to load before calling `getNumber`. If you look at the readme for the `utilsScript` option you'll see:

> When instantiating the plugin, we return a deferred object, so you can use `.done(callback)` to know when initialisation requests like this have finished.

Does that make sense?

**Comment by jimlongo56** [comment]
Thanks, you'll have to excuse my ignorance of javascript . . . 

do you mean in the ajax call?   I can get the value in this `.done(function()` but how to use it to post the data is confounding me.  

```

    $('#input_4_28').submit(function() {
        $.ajax(this.href, {
            type: 'POST',
            data: phoneNumberString,  // how to get that value here??
            dataType: 'text',

        }).done(function(){
           console.log( $("#input_4_28").intlTelInput("getNumber", intlTelInputUtils.numberFormat.E164) );
        })
    })

```

**Comment by jackocnr** [comment]
The `done` callback was for if you wanted to call `getNumber` immediately after initialisation. If you only want to get the number on submit, then I think you can assume the utils script has loaded by that point. So you would do something like this:

```
$('#input_4_28').submit(function() {
    const number = $("#input_4_28").intlTelInput("getNumber");
    $.ajax(this.href, {...});
});
```

**Comment by jimlongo56** [comment]
Thanks again.
