### ISSUE TITLE
Create Option Place Country Country Code next to country flag

### ISSUE THREAD

**Issue by ayoubkhan558** [jackocnr/intl-tel-input#755]
Pleae make options like this so we can customize it according to our need.

Example image is here
![screenshot 42](https://user-images.githubusercontent.com/20210961/41836760-1ce82594-7875-11e8-8019-c6fad1099723.png)

Reference Links are:
https://codepen.io/meeraan/pen/weRyvj
https://codepen.io/jaguar07/pen/ZOozba

**Comment by jackocnr** [comment]
See `separateDialCode` option.

**Comment by ayoubkhan558** [comment]
I try to use it but do not get what i want, please help me.

**Comment by jackocnr** [comment]
Please adhere to the [New Issue template](https://github.com/jackocnr/intl-tel-input/issues/new) and provide the following information: Steps to reproduce, Expected behaviour, Actual behaviour, Initialisation options.

**Comment by ayoubkhan558** [comment]
ok

**Comment by ayoubkhan558** [comment]
I have created a new issue with template, Please check that.
