### ISSUE TITLE
The default placeholder for Belgium is an existing phone number which is linked to a sexshop

### ISSUE THREAD

**Issue by pjbaert** [jackocnr/intl-tel-input#757]
### Steps to reproduce
1.  Select country 'Belgium'
2.  Check if output is +32 470 12 34 56
3.  Call +32 470 12 34 56
4.  Notice you're calling to a sexshop called Michel

### Expected behaviour
A fake phone number as placeholder output.

### Actual behaviour
An existing phone number is placed as placeholder which leads to a grumpy/surprised customer who was testing our form.

**Comment by jackocnr** [comment]
Haha, thanks for reporting this. We use libphonenumber to generate example numbers, so you'll need to open an issue with them.
