### ISSUE TITLE
Country flag becomes blank on refresh using FireFox

### ISSUE THREAD

**Issue by pankopiotr** [jackocnr/intl-tel-input#758]
Link to demo https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/default-country-ip.html 
### Steps to reproduce
1.  Open demo using latest FireFox
2.  Fill input with valid phone number
3.  Refresh website

### Expected behaviour
Country flag should persist

### Actual behaviour
Country flag is blank

### Video
https://monosnap.com/file/xWWS2BgETcz0z7KRKN1XSgnF6wLoyS

**Comment by jackocnr** [comment]
The demo has no way of knowing which flag you selected. It must be a Firefox feature that it re-fills inputs with the same value if you refresh - it's not the plugin doing that.

If this were on your website, and you saved the number using `getNumber` (so you had the full international number saved in your database) then when the user visited that page again, you could pre-fill the input with that number (which would set the flag accordingly, and re-format to the national format). Note that in the case where you already have a phone number, you should not initialise the plugin with `initialCountry: "auto"` because if you do a country lookup it might not match the country of the phone number!

**Comment by pankopiotr** [comment]
Thanks for fast response.

So, the bug is that pre-filling input with value from database (full international number), does not set flag in exact same conditions as in ticket.

https://monosnap.com/file/XZWeL1ABx8qpUuHvBuhedr8Aeu7FH6

**Comment by jackocnr** [comment]
What initialisation options are you using in this case?

**Comment by jackocnr** [comment]
If you can create a codepen, initialising the plugin with no options (or ideally just the utilsScript option), and with a full international number in the input, and it doesn't select the flag correctly, then I will be happy to debug.

**Comment by ysheah** [comment]
Hi, Can I know is it you get the solution to solve this issue? I am facing the issue as well. Only happen for firefox

**Comment by Bokanovskie** [comment]
Hi, i found a solution.

Set `autocomplete="off"` attribute on the <form> element.
It seems Firefox doesn't interpret correctly `autocomplete` attribute on <input> element.

Solved it for me.

**Comment by joefreeman** [comment]
The `autocomplete` workaround seems to work for me. Appreciate this is a weird side effect from the browser, but I guess a better workaround might be to track the state of the selected country in another hidden input - I guess Firefox might then restore that too.

Also, to clarify, this is reproducible on the [Display an existing number](https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/display-number.html) example - you just need to hit reload on that page.

Before:

![Screenshot from 2019-09-17 11-08-09](https://user-images.githubusercontent.com/535128/65040936-7af38680-d94d-11e9-8e91-2f96d0d07381.png)

After:

![Screenshot from 2019-09-17 11-08-15](https://user-images.githubusercontent.com/535128/65040947-80e96780-d94d-11e9-9297-f417ec3e9f62.png)

**Comment by jackocnr** [comment]
Wow, that is crazy. But yeah this is definitely just an issue with Firefox. I checked and it works fine in Chrome, Safari, IE11 and Edge. I would complain to Firefox about this. If the other browsers start having this issue then maybe I'll consider adding a workaround for it.

**Comment by AegisFor** [comment]
> 哇，这太疯狂了。但是，是的，这绝对只是 Firefox 的一个问题。我检查了一下，它在 Chrome、Safari、IE11 和 Edge 中运行良好。我会就此向 Firefox 投诉。如果其他浏览器开始出现此问题，那么也许我会考虑为其添加解决方法。

Not a firefox problem, the same problem happened to me
I am used Laravel Blade {{ old('phone')}}
when i submit the form back to the page

**Comment by b0rum** [comment]
This is a quick fix but it's not a proper long-term solution

```
let iti = window.intlTelInput(input, {
  initialCountry: 'auto',
  geoIpLookup: function(callback) {
    const country_code = $('#user_country_code_field').val()
    callback(country_code == 'RD' ? 'GB' : country_code)
    setTimeout(() => { iti.setCountry(country_code) }, 500)
  }
})
```
