### ISSUE TITLE
Valid Israel number is not accepted

### ISSUE THREAD

**Issue by virtser** [jackocnr/intl-tel-input#761]
### Steps to reproduce
Phone number: +972-55-432-2571

1.  Enter this phone number in original Google 
 validation, and it passed: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
![image](https://user-images.githubusercontent.com/468590/42315642-a06f1eee-8050-11e8-93a3-a87f53e3da39.png)

2.  Enter the phone number in Itl-tel-input validation and its failed:
https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html
![example__validation](https://user-images.githubusercontent.com/468590/42315632-98abb1ae-8050-11e8-9d27-e6fe66b01ce8.png)

### Expected behaviour
The number should be valid.

### Actual behaviour
The number is invalid.

**Comment by jackocnr** [comment]
In your libphonenumber screenshot it says `isValidNumber: false` - I recommend you open an issue with them instead.

**Comment by virtser** [comment]
Oh, sorry, I didn't notice.
I will.
Thank you.
