### ISSUE TITLE
Scrolling on Mobile not behaving like Desktop, no Inertia (including a fix)

### ISSUE THREAD

**Issue by hornwijaya** [jackocnr/intl-tel-input#765]
### Steps to reproduce
1.  Load under iOS
2. Scroll the country list

### Expected behaviour
Supposed to scroll smoothly with inertia like desktop

### Actual behaviour
Scrolling is staggered without inertia, scrolling from A to S takes ages, it behaves like a page-down.

I fixed it by adding a CSS into existing: -webkit-overflow-scrolling: touch;

From:
.intl-tel-input .country-list{position:absolute;z-index:2;list-style:none;text-align:left;padding:0;margin:0 0 0 -1px;box-shadow:1px 1px 4px rgba(0,
0,0,0.2);background-color:white;border:1px solid #CCC;white-space:nowrap;max-height:200px;overflow-y:scroll}

To:
.intl-tel-input .country-list{position:absolute;z-index:2;list-style:none;text-align:left;padding:0;margin:0 0 0 -1px;box-shadow:1px 1px 4px rgba(0,
0,0,0.2);background-color:white;border:1px solid #CCC;white-space:nowrap;max-height:200px;overflow-y:scroll;-webkit-overflow-scrolling: touch;}

**Comment by jackocnr** [comment]
Hi there, thanks for reporting this, but seeing as how it's not a [non-standard browser feature](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling) I don't want to include it in the core of the project, but as you've noted, it's east to add this yourself if you like.

**Comment by bartoszhernas** [comment]
Hi, awesome project but I do not understand your reasoning behind not including this fix.

The input is definitely broken on iOS. I just have finished writing similar issue when stumbled here.

At least adding this issue to README should help others. I bet 100% of users of this project want it to work on all major browsers, even if it's non-standard feature.

If your idea was to make your project worse and broken on over 1 bilion devices, then you have definitely succeed. 👍

**Comment by jackocnr** [comment]
> If your idea was to make your project worse and broken on over 1 bilion devices, then you have definitely succeed. 👍

🤣 

God is it still the case in iOS 12 that the web feels broken unless you add a non-standard styling rule? It seems Apple are really determined to break the web. Ok fine, I will re-open this issue, and happily accept a pull request to add this workaround. Thanks.

**Comment by bartoszhernas** [comment]
Apple is the new Microsoft and Safari Mobile is new Internet Explorer 😂. Thanks, 🙏 I will open PR in a moment.

**Comment by jackocnr** [comment]
Released in v14.0.6.
