### ISSUE TITLE
getCountryData not filtered by onlyCountries

### ISSUE THREAD

**Issue by AlanFors** [jackocnr/intl-tel-input#766]
### Steps to reproduce
1.  Using the sample country sync code from the demo page
2.  initializing intlTelInput with utilsScript
3.  specify short list of "onlyCountries"

### Expected behaviour
I'd expect 'address-country' list to contain the same list as 'phone' for country selection

### Actual behaviour
All possible countries are listed in address-country list. Please add a "getOnlyCountries" function or option on getCountryData() that pays attention to initialization options. Or provide sample to achieve same if it can be done as is.

### Initialisation options
utilsScript, or onlyCountries

**Comment by AlanFors** [comment]
FYI, I worked around the issue by filtering country dropdown when populated, but that means I need to specify "onlyCountries" in two places.

**Comment by jackocnr** [comment]
`getCountryData` is a static method, which means it can be called before the plugin is initialised, so unfortunately it is incompatible with any initialisation options.
