### ISSUE TITLE
Update libphonenumber to v8.9.10

### ISSUE THREAD

**Issue by ishaan1995** [jackocnr/intl-tel-input#768]
IMPORTANT: please note that the auto-format feature (AKA format-as-you-type) was removed in v8.0.0 - read more here: https://github.com/jackocnr/intl-tel-input/issues/346. Please do not open any new issues about this topic.

IMPORTANT: we use libphonenumber for formatting and validation - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html. Please also check the intl-tel-input validation demo page to make sure it's not a problem with your code: https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html.

### Steps to reproduce
1.  Use a new series Indian Reliance Jio number starting with 63

### Expected behaviour
Should be a valid number

### Actual behaviour
Number is invalid

### Initialisation options
None specific

**Comment by jackocnr** [comment]
Ah, I was using a notification service to watch for new versions and it stopped working! Thanks for this. I have just released a new version with this included.

**Comment by ishaan1995** [comment]
Thanks.
@jackocnr Try https://github.com/googlei18n/libphonenumber/releases.atom for notifications instead.It always works.
