### ISSUE TITLE
Cannot insert some digits on input

### ISSUE THREAD

**Issue by miguelleitevieira** [jackocnr/intl-tel-input#769]
Hi,

I have a strange behavior using the intlTelInput library.

Somecases I cannot insert the digit "6" and "+" on the element rendered with the intlTelInput mechanism.

Someone knows this issue?

**Comment by jackocnr** [comment]
A while ago we had a feature that prevented you from entering what it considered incorrect numbers, but that was removed years ago. Please make sure you're using the latest version.

**Comment by jackocnr** [comment]
I don't think we have any other code that limits what the user can type in the input, so I'm going to close this for now, but do let me know if you're still having issues after updating to the latest version.
