### ISSUE TITLE
RTL Support 

### ISSUE THREAD

**Issue by emadrashad** [jackocnr/intl-tel-input#771]
is there any support for RTl using this plugin

**Comment by jackocnr** [comment]
No. If you search the issues you will see various discussions. The last comment was that this could be achieved manually, just by wrapping the input in a div with the attribute `dir="rtl"`: https://github.com/jackocnr/intl-tel-input/issues/300#issuecomment-394662923

If that doesn't work for you, I'd be interested to hear more about your use case and what issues you're having, and if you have any proposed solutions. Cheers.

**Comment by emadrashad** [comment]
Okay , i fixed the Rtl , by writing my own css classes that helps my needs ,  but i have another problem here if i select usa flag  , and put my number and forget to fill other fields , while am using laravel framework , when validation  happens and it get back to the same page , the flag disappears , like this screen  : 
`https://ibb.co/kRjHrK`

so any help ?

**Comment by jackocnr** [comment]
I'm glad you fixed the RTL issue. Please open a separate issue for this, filling in the New Issue template, including what initialisation options you're using etc, and also please specify exactly what value you're giving the input (hint: it should start with a plus).

**Comment by jackocnr** [comment]
We now have full RTL support - see the RTL demo page here for reference: https://intl-tel-input.com/examples/right-to-left.html
