### ISSUE TITLE
Change initial country depending on the phone number

### ISSUE THREAD

**Issue by remcowesterhoud** [jackocnr/intl-tel-input#775]
When I set my initial country this will always be the country shown by default. So if my initial country is the US and I set the input with a UK phone number it will still consider this a US phone number.
Is there any way set the initial country to the country that correlates to the phone number that I've set initially? So when I fill it with a UK phone number the initial country will be UK, and if I fill it with a US number the initial country will be US.

**Comment by jackocnr** [comment]
If you already have the phone number ready to display, you should omit the initial country option (or set it to null).
