### ISSUE TITLE
Lookup user's country not working on Firefox 61+ 

### ISSUE THREAD

**Issue by andreikostusev** [jackocnr/intl-tel-input#776]
Open https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/default-country-ip.html with Firefox 61+ over Win10 64-bit and you'll notice that the flag is not loaded. 

Inspect element reveals Javascript error:
Loading failed for the <script> with source “https://ipinfo.io/?callback=jQuery19103452894293998091_1534361018121&_=1534361018122”.

Exactly same URL works fine with Chrome 68 and Edge 41 on the same PC
It works also fine with Firefox for Android (tested with version 61 over Android 7.1.1)

**Comment by jackocnr** [comment]
Hmm. It's working fine for me on Firefox v61 and v62 beta on Browserstack. Can anyone else reproduce this?

**Comment by andreikostusev** [comment]
Tested some more. And shame to say, it is not Firefox, but its adblocking addon that fails ipionfo.io call.
Sorry to have wasted your time!
