### ISSUE TITLE
Auto Formatting not working

### ISSUE THREAD

**Issue by endresh97** [jackocnr/intl-tel-input#780]
Auto formatting not working in this plugin.

I want the phone number validation with the country code. but if i used this plugin. This shows only placeholder for the country code.

I want the auto formatting for country code. 

Ex. If I select india, 
+91 should be automatically generated and 
it should allow me to enter max valid number like 10 number is valid for India.
+91 769-685-6889

**Comment by jackocnr** [comment]
Please read the New Issue template before posting.

**Comment by walkwel-tech** [comment]
Same issue
