### ISSUE TITLE
Phone number validation with country code

### ISSUE THREAD

**Issue by endresh97** [jackocnr/intl-tel-input#781]
Could any one help for phone number validation with country code.
Ex. Suppose i have selected the country code india.
![image](https://user-images.githubusercontent.com/29000073/44856561-62a1c280-ac8b-11e8-82cd-7b96368da6de.png)

It automatically update country flag with country code like +91
It would restrict me to enter max length number for phone number (79078788976)
result should be like this
![image](https://user-images.githubusercontent.com/29000073/44856752-d17f1b80-ac8b-11e8-9a77-761516d6f850.png)

If any one having solution, please provide me the link for the same.
I want the functionality in angular4.

Thank you.

**Comment by jackocnr** [comment]
This plugin does not limit what the user can type into the input in any way. If you want this functionality you will have to code it yourself.
