### ISSUE TITLE
How to show selected country code near flag and correct the phone placeholder

### ISSUE THREAD

**Issue by Artgit** [jackocnr/intl-tel-input#782]
Hello, 

Is it possible to also show selected country code near the flag, something like this(I have created this image in photoshop):

![tel](https://user-images.githubusercontent.com/2064812/44956174-548cb580-aec8-11e8-8a45-3e6d51fe907b.png)

Also, as you may see we have a duplication of redundant "0" in the selected country code and the phone placeholder because in case of +380 the correct placeholder should look like "39 123 4567". Is there also the way to fix the placeholder?

Thanks,
Alex

**Comment by jackocnr** [comment]
See `separateDialCode` option. Does that do what you want?

**Comment by Artgit** [comment]
Yes, thank you!
