### ISSUE TITLE
Add dial code near flag to default select box

### ISSUE THREAD

**Issue by AlexKutkanych** [jackocnr/intl-tel-input#786]
Hi guys,

I wonder if we can customize this select via standard API.
I need to add a selected country dial code right to the flag (see the screenshot below).

Is it possible to do?

Thank you!

![image](https://user-images.githubusercontent.com/22956226/45215920-942c1680-b2a7-11e8-9530-4d13ca0702fd.png)

**Comment by jackocnr** [comment]
Hey Alex, did you try the readme? Under the section on Options?

**Comment by AlexKutkanych** [comment]
thank you, but I need to put it between flag and arrow

**Comment by jackocnr** [comment]
See `separateDialCode` option. I added a screenshot in the readme to make it clearer.
