### ISSUE TITLE
Upgrade to latest libphonenumber v8.9.14

### ISSUE THREAD

**Issue by ishaan1995** [jackocnr/intl-tel-input#790]
https://github.com/googlei18n/libphonenumber/releases/tag/v8.9.14

**Comment by jackocnr** [comment]
Sorry I'm quite busy at the moment, but I'd be open to a pull request. It's easy to re-compile the utils script yourself - see the instructions at the top of src/js/utils.js.

**Comment by jackocnr** [comment]
Done in v14.0.1.
(Note: that's a major update in v14 - see release notes)
