### ISSUE TITLE
separateDialCode appends new value to the old one

### ISSUE THREAD

**Issue by rcpedro** [jackocnr/intl-tel-input#792]
### Steps to reproduce
1.  Use the option separateDialCode and set it to true.

### Expected behaviour
When changing the current flag, the old dial code should be cleared and replaced with a new one.

### Actual behaviour
The new dial code is appended to the old one, resulting in strings like "+61+63".

### Initialisation options
{ separteDialCode: true }

**Comment by jackocnr** [comment]
Thanks for reporting this. Fixed in v14.0.2.

**Comment by mkpasala** [comment]
Please post an example of it in angular 4 using stackblitz.com.
