### ISSUE TITLE
CDN implementation?

### ISSUE THREAD

**Issue by noahkconley** [jackocnr/intl-tel-input#794]
We've had to make some code updates due to new area codes not being available in older versions of the utility.  Updating isn't difficult, but it would be awesome if there was an up to date CDN we could pull from since we don't push updates to production right away and our users aren't able to submit forms with the phone number field on it when it's invalid.

**Comment by jackocnr** [comment]
https://cdnjs.com/libraries/intl-tel-input

**Comment by noahkconley** [comment]
Thanks, but that still specifies the version, so a code change is required to stay up to date, what about one that just says “latest”?

**Comment by jackocnr** [comment]
I'm afraid I don't think that's possible.
