### ISSUE TITLE
Placeholder does not work in pure JS version

### ISSUE THREAD

**Issue by maxshuty** [jackocnr/intl-tel-input#796]
### Steps to reproduce
1. Follow setup in the pure-js readme.

### Expected behaviour
The placeholder should show with formatted phone numbers for the country that is selected.

### Actual behaviour
No placeholder shows up. Here is a fiddle to demonstrate (my apologies for pasting the entire JS file in the fiddle, but I couldn't find it hosted anywhere and was getting a bunch of console errors when trying to reference the raw JS from github) http://jsfiddle.net/maxshuty/3ckdyw90/

### Initialisation options
None (as demonstrated in the fiddle). I have tried `autoPlaceholder=true` but that had no effect.

**Comment by jackocnr** [comment]
Hi there, thanks for writing this up, but if you check the readme, under the `autoPlaceholder` option, you'll see that it requires the `utilsScript` option to work.

**Comment by maxshuty** [comment]
@jackocnr - like this? http://jsfiddle.net/maxshuty/3ckdyw90/19/ 

If that's the proper usage then I'm still unable to get it working. Do you have a fiddle setup without the jQuery dependency by any chance?

**Comment by jackocnr** [comment]
Yes like that - except something in that fiddle is blocking the utils file from loading - you can tell because if you run this in the JS console `window.intlTelInputUtils` you will see it's undefined.

> Do you have a fiddle setup without the jQuery dependency by any chance?

I don't have a fiddle, but it's up and running on the demo site: https://intl-tel-input.com
