### ISSUE TITLE
Repeated prefix

### ISSUE THREAD

**Issue by fencer** [jackocnr/intl-tel-input#799]
### Steps to reproduce
1.  focus in the textbox
2.  Clear any numbers in the textbox
3.  Keep pressing the backspace even after no more numbers are left in the field.

### Expected behaviour
Textbox value should be cleared and prefix left visible

### Actual behaviour
![20181010_131526](https://user-images.githubusercontent.com/620966/46732759-b0e4b100-cc8e-11e8-8bd4-53fad6e5df02.gif)

Prefix for the selected country is added for every time the user presses the backspace button.

### Initialisation options
separateDialCode: true

**Comment by jackocnr** [comment]
Confirmed. Thanks for reporting this. Must be an issue with the keyup handler. I don't have time to look into this right now, but I'd welcome a pull request.

**Comment by jackocnr** [comment]
Oh, actually you just need to update to the latest version.

**Comment by SoftCreatR** [comment]
@jackocnr Just installed 14.0.0 and still experiencing this issue.

**Comment by timothymarois** [comment]
> Oh, actually you just need to update to the latest version.

Using version **v14.0.0** did not solve the problem for me. 

![screenshot 2018-12-10 10 49 19](https://user-images.githubusercontent.com/2489333/49760609-eb6cc900-fc92-11e8-8fae-73f09cff7d17.png)

**Comment by SoftCreatR** [comment]
I had the same problem until noticing, that v14.0.0 isn't the latest version, but v14.0.6 is ;)

**Comment by timothymarois** [comment]
@SoftCreatR I see.

Thanks for pointing that out, odd that it wasnt published as the latest release.

_This needs to be updated:_ 
![screenshot 2018-12-10 15 55 39](https://user-images.githubusercontent.com/2489333/49761133-27545e00-fc94-11e8-85d0-abeedb1cfc06.png)

I can confirm that it has been fixed with **14.0.6**

**Comment by SoftCreatR** [comment]
I guess, they only tag major versions as new release.

**Comment by jackocnr** [comment]
I've tagged 14.0.6 as the latest. I don't know why this doesn't happen automatically.
