### ISSUE TITLE
Retrieve English country names only

### ISSUE THREAD

**Issue by yagamidev** [jackocnr/intl-tel-input#801]
IMPORTANT: please read the New Issue Checklist before creating a new issue: https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist

### Steps to reproduce
1.  Retrieve English country names only

### Expected behaviour
 Retrieve English country names only

### Actual behaviour
Local Country name

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
If you want to change how the country names are displayed, you can either manipulate the existing country data (see "Modify country data" example on the demo site), or use `localizedCountries` option to provide your own names.

**Comment by niclm** [comment]
The following will remove all alternative names that are within parentheses:

```javascript
window.intlTelInputGlobals.getCountryData().forEach((country) => {
  country.name = country.name.replace(/\(.*\)/, "").trim();
})
```
