### ISSUE TITLE
Plugin shows 1234567890 as Valid number (India) by getNumber()

### ISSUE THREAD

**Issue by Anuju** [jackocnr/intl-tel-input#808]
### Steps to reproduce
1.  Select India as Country. 
2.  Provide input as 1234567890 and check using isValidNumber()

### Expected behaviour
Plugin must not allow 1234567890 as valid number, false should be returned from the isValidNumber().

### Actual behaviour
Plugin shows 1234567890 as valid number by selecting India as country and isValidNumber() returns true
Please check into this!

**Comment by jackocnr** [comment]
Please read the New Issue Checklist before posting. We use libphonenumber for validation, so you'll need to raise the issue with them.
