### ISSUE TITLE
iti.isValidNumber returning null

### ISSUE THREAD

**Issue by MrMooky** [jackocnr/intl-tel-input#812]
Aside from the difference that my function call happens on a button click, I implemented `intlTelInput.js` the same as in the demo:

**Input:**

`<input type="tel" id="phonenumber" placeholder="{settings.text.callARideNumber}">`

**Button onclick:**

```
$.getScript("typo3conf/ext/siteway/Resources/Public/Javascript/extra/prism.js", function( data, textStatus, jqxhr ) {
    $.getScript("typo3conf/ext/siteway/Resources/Public/Javascript/extra/intlTelInput.js", function( data, textStatus, jqxhr ) {
      validatePhoneNumber();
    });
});
```

**Function being called:**

```
function validatePhoneNumber()
{
	console.log('validation started... ');

	var input = document.querySelector("#phonenumber");
	var errorMsg = document.querySelector("#error-msg");
	var validMsg = document.querySelector("#valid-msg");

	// here, the index maps to the error code returned from getValidationError - see readme
	var errorMap = [ "Invalid number", "Invalid country code", "Too short", "Too long", "Invalid number"];

	// initialise plugin
	var iti = window.intlTelInput(input, {
		utilsScript: "typo3conf/ext/siteway/Resources/Public/Javascript/extra/utils.js"
	});

	var reset = function() {
		input.classList.remove("error");
		errorMsg.innerHTML = "";
		errorMsg.classList.add("hide");
		validMsg.classList.add("hide");
	};

	if (input.value.trim()) {
		reset();
		console.log(iti.isValidNumber());
		if (iti.isValidNumber()) {
			validMsg.classList.remove("hide");
		} else {
			input.classList.add("error");
			var errorCode = iti.getValidationError();
			console.log(errorCode);
			errorMsg.innerHTML = errorMap[errorCode];
			errorMsg.classList.remove("hide");
		}
	}
}
```

The line `console.log(iti.isValidNumber());` returns null. And `console.log(errorCode);` returns `-99`.

I've tested with various numbers. The script initialises and correctly recognises the german phone number:

<img width="798" alt="screen shot 2018-10-25 at 13 50 56" src="https://user-images.githubusercontent.com/3603346/47498323-2fc81500-d85d-11e8-9023-1754025578d1.png">

**Comment by jackocnr** [comment]
It's probably because you're calling isValidNumber straight after initialising the plugin, so the utils script might not have loaded yet. You can use `iti.promise.then(callback)` to know when the plugin has completely finished initialising. Does that fix it?

**Comment by MrMooky** [comment]
Got me in the right direction. Thanks. :)
