### ISSUE TITLE
Wrong country at top of list

### ISSUE THREAD

**Issue by MrMooky** [jackocnr/intl-tel-input#814]
### Steps to reproduce
1.  Create instance
2.  Define default country.

### Expected behaviour
Selected, default country is set to active, which is fine. UK appears at the top of selection, also on the bottom.

### Actual behaviour
I don't understand why UK is at position 1 and also on the last position. 

<img width="255" alt="screen shot 2018-10-30 at 11 46 44" src="https://user-images.githubusercontent.com/3603346/47713189-f2d39800-dc39-11e8-992d-1781c2a2da16.png">

### Initialisation options
```
$.getScript("typo3conf/ext/siteway/Resources/Public/Javascript/extra/intlTelInput.min.js", function() {
    iti = window.intlTelInput(document.querySelector("#phonenumber"), {
        onlyCountries: ["de", "gb", "es", "it", "pl", "pt", "se", "ie", "at"],
        placeholderNumberType: "MOBILE",
        initialCountry: 'de',
        utilsScript: "typo3conf/ext/siteway/Resources/Public/Javascript/extra/utils.js"
    });
});
```

**Comment by jackocnr** [comment]
See `preferredCountries` option for defining which countries appear at the top of the list.
