### ISSUE TITLE
Hidden Input not being created

### ISSUE THREAD

**Issue by ImClarky** [jackocnr/intl-tel-input#818]
I'm trying to create a hidden input using the library as I will be posting to PHP.

I have looked at the example [here](https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/hidden-input.html) and tried to replicate locally, but I am unable to do so. The field itself seems to work okay, however the hidden input does not get created. There is nothing in Chrome DevTools.

My setup:

```html
<form action="">
  <input type="tel" name="foo" id="foo">
  <button type="submit">Test</button>
</form>
```

```js
var input = document.querySelector('#foo'),
    config = {
        hiddenInput: 'full_test',
        utilsScript: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/14.0.4/js/utils.js'
    };

intlTelInput(input, config);
```

The output:

```html
<form>
    <div class="intl-tel-input allow-dropdown">
        <div class="flag-container"><!-- flag stuff --></div>
        <input type="tel" name="foo" id="foo" autocomplete="off" placeholder="(201) 555-0123">
    </div>
</form>
```

I have replicated the issue here: https://codepen.io/anon/pen/Xymeom

I have tested with v14.0.3 and v14.0.4 both with the same results. It appears to be the same issue as https://github.com/jackocnr/intl-tel-input/issues/736

**Comment by jackocnr** [comment]
Thanks for reporting this and providing a codepen. I can confirm this is a bug, only present in the minified version, which means likely it's to do with the grunt replace task.

UPDATE: fixed in v14.0.5. Thanks again.
