### ISSUE TITLE
show country as number of mobile

### ISSUE THREAD

**Issue by MahmoudAdham** [jackocnr/intl-tel-input#819]
Hi,
Thank you for this plugin.
Ho I can show the country as the number display in the field, Like if I get number form database?

**Comment by jackocnr** [comment]
Hi there, I'm sorry but I don't understand. Can you explain in more detail?

**Comment by MahmoudAdham** [comment]
Hi, thank you for your reply.
I mean if I want to update data for the user, I get mobile number from database how can I set the country code for this mobile?
please see attached file, I have a number for Palestine country, but the default code for the UK.
![capture](https://user-images.githubusercontent.com/30972004/48193494-41c4b000-e353-11e8-9c35-b91f5bf66599.PNG)

**Comment by jackocnr** [comment]
See [Recommended Usage](Recommended Usage) section of readme - if you always handle numbers in full international format then the plugin will handle setting the country for you.

If for some reason you want to store numbers in national format, then you'd have to store the country separately, and either use the initialisation option `initialCountry`, or use `setCountry` method after the plugin has initialised.
