### ISSUE TITLE
Mobile Validation....

### ISSUE THREAD

**Issue by Naresh1636** [jackocnr/intl-tel-input#821]
IMPORTANT: please read the New Issue Checklist before creating a new issue: https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist

 
https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html
check this url 

### Expected behaviour
mobile number shoud not accept characters.
![bug_intl](https://user-images.githubusercontent.com/40858383/48410052-8beace80-e763-11e8-9cd9-f0b59da56de0.png)

### Actual behaviour

1.  Can you Please check Validation for **solomon islands** 

     It showing validate number even it contain characters.
 Ex::
  **7412345ff** it showing this is valid number.

  @jackocnr

**Comment by jackocnr** [comment]
Please read the New Issue Checklist before posting.

> We use libphonenumber for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead.
