### ISSUE TITLE
iti returns a number including country code twice

### ISSUE THREAD

**Issue by AHgPuK** [jackocnr/intl-tel-input#823]
intlTelInput.getNumber returns a phone number with double country code
(Reproduced from 14.0.0 up to 14.0.6)

### Steps to reproduce
1.  Enter +78639222222
2.  Press "Submit"

### Expected behaviour
iti.getNumber should return +78639222222

### Actual behaviour
+7+78639222222

### Initialisation options
separateDialCode: true, initialCountry: 'auto', geoIpLookup included
preferredCountries: [
			'ae'
		],
		separateDialCode: true,
		initialCountry: 'auto',
		utilsScript: '/js/utils.js',
		autoPlaceholder: 'polite',
		geoIpLookup: function () {}

**Comment by jackocnr** [comment]
Well the idea of `separateDialCode` is that the user doesn't need to type the dial code. But I suppose it would be worth handling the situation if they do. I would be open to a pull request to fix this - namely to check in `_getFullNumber` if the `val` starts with a plus, in which case don't add the dial code: https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js#L1160

**Comment by jackocnr** [comment]
Fixed in v14.0.8.
