### ISSUE TITLE
The dropdown arrow for country code is not visible (browser specific issue)

### ISSUE THREAD

**Issue by vivatum** [jackocnr/intl-tel-input#827]
### Steps to reproduce
!!! Browser specific issue: Firefox 63.0 (64-bit),  Ubuntu 16.04.

Angular CLI: 6.1.5
MatInput, React Form.

### Expected behaviour
The input should looks like: country flag_country code_dropdown arrow.

### Actual behaviour
The last character of country code is overlaps a dropdown arrow. The dropdown arrow is almost not visible. It is not relevant to:
- Browser window size;
- Page zoom;
- Country code length.

### Initialisation options

```
 private initIntTelInput() {
    this.inputTel = document.querySelector('#phone');
    this.iti = intlTelInput(this.inputTel, {
      initialCountry: 'gb',
      preferredCountries: ['gb', 'il', 'pl'],
      utilsScript: '../../../../node_modules/intl-tel-input/build/js/utils.js',
      separateDialCode: true
    });
    this.countryChangeListener();
  }
```

Thank you!

**Comment by vivatum** [comment]
`jlknjn
kink
lkjn`

**Comment by jackocnr** [comment]
Have you tried reducing the font size of the dial code element?

**Comment by vivatum** [comment]
Yes, you are right. The font size changing can fix this issue. But I have to do it for Firefox only.
Thanks!
