### ISSUE TITLE
How to display an existing number ?

### ISSUE THREAD

**Issue by dheeraj26** [jackocnr/intl-tel-input#830]
How do I display an existing number in input field.

Suppose I select +1 (Canada) dial code and saves it, but when I try to display the number it selects US as country but I want to display Canada. 

Jamaica, Canada & United States have same dial code

How I achieve this using country iso code ? Please let me know.

**Comment by jackocnr** [comment]
> How do I display an existing number in input field.

You can either have it already set as the input value when you initialise the plugin, and the plugin will handle it automatically, or if you want to set the number in the JS, you can use the plugin's `setNumber` method. In both cases, we recommend using full international numbers (inc international dial code) and then the plugin will set the flag accordingly, and re-format the number to the national format, if you leave `nationalMode` enabled.

> Jamaica, Canada & United States have same dial code

They have the same international dial code, but they have different area codes and the plugin should handle this and select the right flag automatically.

**Comment by dheeraj26** [comment]
Thanks It works...... :+1:
