### ISSUE TITLE
How to set initialCountry based on domain?

### ISSUE THREAD

**Issue by creativedevs** [jackocnr/intl-tel-input#831]
IMPORTANT: please read the New Issue Checklist before creating a new issue: https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist

### Steps to reproduce
1.  I have different domains based on country.
2.  so, I want to set initialCountry based on domain name. e.g., co.uk => 'uk', com => 'us', 'com.au' => 'au'
3.  Existing is allowed based on ip but not on domain 

### Expected behaviour
Allow to set initialCountry based on domain

### Actual behaviour
No option to set initialCountry based on domain

### Initialisation options
preferredCountries

**Comment by jackocnr** [comment]
Hi there, thanks for writing this up, but this is not something that I would want to bake into the plugin at this point - it's too niche. But this should be easy for you to code yourself - as you say, you just need a map from domain name to 2-char country code. Cheers.
