### ISSUE TITLE
intlTelInputUtils.formatNumber is not working

### ISSUE THREAD

**Issue by akvaliya** [jackocnr/intl-tel-input#832]
### Steps to reproduce
intlTelInputUtils.formatNumber("+12012136191", "us")

### Expected behaviour
"+1 201-213-6191"

### Actual behaviour
"+12012136191"

### Initialisation options
utilScripts

I am using utilscripts to format number by country code.

I have used https://github.com/jackocnr/intl-tel-input/blob/master/build/js/utils.js

I am not sure what am i doing wrong?

Can anyone assist me here?

**Comment by jackocnr** [comment]
See API on this wiki page: https://github.com/jackocnr/intl-tel-input/wiki/utils.js
