### ISSUE TITLE
How to enable / disabled the dropdown click funtion with a initialised  <input />?

### ISSUE THREAD

**Issue by FindSunny** [jackocnr/intl-tel-input#834]
Good afternoon,

  Thanks for the great plugin, but i have a problem, how to enable / disabled the dropdown click-funtion after initialised a input,  and the input is still enable?

Thank you very much!

**Comment by tarrel** [comment]
You have to put window.onload : 
window.onload = function() {
        var input = document.querySelector("#phone");
        intlTelInput(input);
      };

Kind regards.

**Comment by FindSunny** [comment]
Emmm. Let me put it more clearly,  I hope there is a way to use a `<button/>` to enable/disable the drop-down country list (or the icon),  and it should be after the `intlTelInput(input);`method executed. 
What do you think?

Any way, thanks a lot.
Faleminderit!

**Comment by tarrel** [comment]
You dont have to make an extra button to open and close options.

First you have to follow instructions , include all files.
Don't forget to include jquery !
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="node_modules/intl-tel-input/build/js/intlTelInput.js "></script>`

After including files write:
`var input = document.querySelector("#phone");
window.intlTelInput(input, {
  utilsScript: "node_modules/intl-tel-input/build/js/utils.js?15",
});`

or : 
`window.onload = function() {
        var input = document.querySelector("#phone");
        intlTelInput(input);
      };`
I think all it would go good.
Kind regards.

**Comment by FindSunny** [comment]
Wa! Wonderful Answer! Thanks vary much! 

And, actually I want to do something more.

**_Step_ 1:**   Initialise a  _`input`_ using `intlTelInput(input);`  (like your answer up there)

**_Step_ 2:**   Use a button to switch the status (enabled/disabled) of the options, but do not use the `intlTelInput(input);`  method again.

is there anyway to do that?

**Comment by jackocnr** [comment]
I'm afraid there is no method to do what you want baked into the plugin. I guess you could use the destroy method and then re-initialise the plugin with `allowDropdown` set however you want? Or maybe you could try dynamically setting the `pointer-events` CSS rule to prevent clicks? Or alternatively you could just show/hide a transparent div over the selected flag to capture all the clicks.
