### ISSUE TITLE
Split Area Code from getNumber?

### ISSUE THREAD

**Issue by Tarcisiofl** [jackocnr/intl-tel-input#835]
Hello,

I have a problem trying to split the area code from the `getNumber()` as I need each part of the phone independently. Is there a posibility to get just the code area?

**Comment by jackocnr** [comment]
Please can you give an example of what you're trying to achieve and why, so I can understand better?

**Comment by jackocnr** [comment]
This is not possible with the plugin. I recommend doing this on your backend. The libphonenumber project is the best for this, and has been ported to several languages.
