### ISSUE TITLE
Add input in dropdown for filtering countries

### ISSUE THREAD

**Issue by dunox** [jackocnr/intl-tel-input#839]
I wonder if it is possible to add an input in dropdown list?

 I need to make a search thought the list(by tapping in input)
Thanks a lot

**Comment by jackocnr** [comment]
The plugin does not provide this functionality, but you could listen for the `open:countrydropdown` event and inject your own input element into the dropdown and add your own JS to listen for a keyup and filter the country list.

**Comment by jackocnr** [comment]
See new option `countrySearch` in v18.5.1. Let me know what you think!
