### ISSUE TITLE
US Areacode 463 shows invalid number

### ISSUE THREAD

**Issue by ifahadashraf** [jackocnr/intl-tel-input#841]
### Steps to reproduce
1.  (463) 555-5555

### Expected behaviour
This is a valid number and should not produce an error

### Actual behaviour
But instead it shows 'Please enter valid phone number.'

Kindly look into this. Thanks

**Comment by jackocnr** [comment]
As stated in the New Issue template, validation is handled by the libphonenumber library, so if you have an issue with validation which you can reproduce on their demo page, then you should open an issue with them.
