### ISSUE TITLE
Update New Malaysian Phone Number Validation

### ISSUE THREAD

**Issue by minhhoangvhit** [jackocnr/intl-tel-input#842]
### Steps to reproduce
1.  +601170334885 

### Expected behaviour
Check as a valid phone number

### Actual behaviour
Showed invalid phone number

**Comment by jackocnr** [comment]
Validation is handled by the libphonenumber library, so if you have an issue with validation which you can reproduce on their demo page, then you should open an issue with them. If you can't reproduce the error with them and you think the error is with this plugin then please say so and I will look into it further.
