### ISSUE TITLE
autoHideDialCode - Browser form validation message gets hidden after dial code re-added

### ISSUE THREAD

**Issue by bencergazda** [jackocnr/intl-tel-input#847]
### Steps to reproduce
See https://codepen.io/bencergazda/pen/bOLpra, the issue should appear on Chrome.

### Expected behaviour
The browser's default validation error message should be shown when submitting the form with an empty value.

### Actual behaviour
The validation error message is actually shown on the empty input, but instantly gets hidden after the input gets the focus and the dial code gets re-added (see https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js#L587)

### Initialisation options
    {
        nationalMode: false,
        formatOnDisplay: true,
        utilsScript: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/13.0.4/js/utils.js', // just for formatting/placeholders etc
    }

I can send a PR with a possible fix.

**Comment by jackocnr** [comment]
Hmm good catch! Honestly I wonder if we should just remove that auto-insert-dial-code-on-focus functionality all together - there are probably other issues like this that we're not aware of - it's probably just bad practice to mess with the input value automatically like that. What do you think?

**Comment by bencergazda** [comment]
@jackocnr I like the original idea of trying not to submit useless values (especially if the input has been set to required). I created a PR with my proposal (#848), cannot decide whether it is too hack-ish or not. What is your opinion?

**Comment by jackocnr** [comment]
(Added comment in the PR)

Thanks for raising this issue. I'm going to keep this issue open, as a reason to look into removing the auto-hide/insert-dial-code functionality altogether.

**Comment by jackocnr** [comment]
In the end I didn't remove `autoHideDialCode`, I just changed it so it still hides the dial code on blur, but it doesn't re-add it on focus. See commit for more details.

Released in v15.0.0. Thanks again for raising this.
