### ISSUE TITLE
InitialCountry adds a "0" for Germany

### ISSUE THREAD

**Issue by maxshuty** [jackocnr/intl-tel-input#850]
### Steps to reproduce
1.  Set the `initialCountry: 'de'` when initializing the plugin, like this: http://jsfiddle.net/maxshuty/asf5jmwb/

### Expected behaviour
intl-tel-input should not add a "0" to the value for German ('de') phone numbers when initializing using the `initialCountry` initialization option.

### Actual behaviour
intl-tel-input adds a "0" before the default value for the input when the `initialCountry` is set to `de`. This bug occurs in both the vanilla JS version and the jQuery version which I forked an example of for the jsfiddle above.

### Initialisation options
`initialCountry: 'de'`

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting (which is what is adding the zero), validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.
