### ISSUE TITLE
Extensions are limited to 7 digits

### ISSUE THREAD

**Issue by joechrisman** [jackocnr/intl-tel-input#852]
IMPORTANT: please read the New Issue Checklist before creating a new issue: https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist

### Steps to reproduce
1.  enter a phone number with an extension >7 digits

### Expected behaviour
Should validate

### Actual behaviour
Getting an error that the phone number is invalid because it is too long.  I would guess that it should only be validating the phone number instead of the phone number and extension?

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

The fact that they accept and correctly interpret numbers with extensions up to 7 digits means they do support extensions in their validation. So the best thing to do is open an issue with them.
