### ISSUE TITLE
is valid and is valid

### ISSUE THREAD

**Issue by mymoney2772** [jackocnr/intl-tel-input#856]
IMPORTANT: please read the New Issue Checklist before creating a new issue: https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist

### Steps to reproduce 
1.  typing - 9088682772, everything is OK - Valid
2.  typing - 89088682772, and also everything is OK - Valid!

in the end it turns out that it is true and +79088682772
and +78908682772
where 8 is superfluous

### Expected behaviour
+79088682772 - is valid
+789088682772 - is invalid

### Actual behaviour
+79088682772 - is valid
+789088682772 - is valid

### Initialisation options
 we have such settings:
allowDropdown: true,
autoHideDialCode: false,
nationalMode: false,
initialCountry: "auto",

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

**Comment by mymoney2772** [comment]
Yes, the problem is there
