### ISSUE TITLE
I want two intl-tel-input on one page means i want to access both by using class name rather than id while trying this either of them is working at a time but not both

### ISSUE THREAD

**Issue by arpitalopa** [jackocnr/intl-tel-input#860]
IMPORTANT: please read the New Issue Checklist before creating a new issue: https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist

### Steps to reproduce
1.  
2.  
3.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a [CodePen](https://codepen.io), then I'd be happy to take a look.

**Comment by arpitalopa** [comment]
hi,
Please find codepen link: https://codepen.io/arpitalopa/pen/omXryG

**Comment by jackocnr** [comment]
Please see the note at the top of the readme - this is no longer a jQuery plugin - it is now a pure JavaScript plugin by default.

**Comment by arpitalopa** [comment]
I just want to know that whether i can use to input type tel in a single
page and access it throw classname.

**Comment by arpitalopa** [comment]
I just want to know that whether i can use two input type tel in a single
page and access it throw classname.

**Comment by jackocnr** [comment]
Yes you can, but you need to stop using jQuery and use pure JavaScript. You can select all of the inputs you need with `document.querySelectorAll('.name')` and then cycle through those and initialise the plugin on each one.
