### ISSUE TITLE
how to get the iti object of an already initialized instance

### ISSUE THREAD

**Issue by pmcquay** [jackocnr/intl-tel-input#861]
if I have an already-initialized instance of ITI on my page, and another part of the code needs the object, how do I get the ITI object, now that the jquery dependency has been removed?

Previously I would just do $(selector).intltelinput("function") and could assume that it would not re-initialize the control. What is the equivalent of that without jquery?

**Comment by pmcquay** [comment]
perhaps something like this? where phoneInputObject is a DOM object.

```
    for (var i = 0; i < window.intlTelInputGlobals.instances.length; i++) {
        if (window.intlTelInputGlobals.instances[i].telInput === phoneInputObject) {
            return window.intlTelInputGlobals.instances[i];
        }
    }
```

**Comment by jackocnr** [comment]
There's currently an open PR for this: https://github.com/jackocnr/intl-tel-input/pull/845 but I haven't found the time to review it yet - I just want to make sure the approach is standards compliant and works in all browsers.

**Comment by pmcquay** [comment]
ahh. Didnt think of using an expando property for that. Seems the right way to go I suppose.

**Comment by jackocnr** [comment]
I think we'll continue the conversation in that thread, so I'll close this for now. Thanks.

**Comment by ngocphamm** [comment]
I think there might be a bug with this new `getInstance()` method.

If I use the jQuery version of the script, `$("#phoneNum").intlTelInput();` will NOT put the `data-intl-tel-input-id` attribute to the DOM element for some reason, thus later on the piece `var id = input.getAttribute("data-intl-tel-input-id");` won't return anything.

Non-jQuery version works fine.

**Comment by jackocnr** [comment]
If you're using the jquery version then you can just do `$('#phoneNum').intlTelInput(...)`

**Comment by pmcquay** [comment]
Seems I missed the jquery version. Figured it out by storing the instance somewhere else anyway. This can be closed.
