### ISSUE TITLE
preferredCountries function

### ISSUE THREAD

**Issue by stgrdk** [jackocnr/intl-tel-input#862]
Hi, would it be possible to use a function with preferredCountries to fetch country_codes from a database?
I have a lot of customers with country code on them, and i would like to arrange the list based on total count of country_codes descending..
but i'm not that good with javascript/jquery

**Comment by jackocnr** [comment]
I'm sorry but this is outside the scope of this plugin. If you're having trouble using the plugin I would recommend asking for help on StackOverflow.
