### ISSUE TITLE
Using with jquery validation 

### ISSUE THREAD

**Issue by TheMurseL** [jackocnr/intl-tel-input#864]
Hello,

I have a problem. i couldn't solve this problem.

Uncaught TypeError: $(...).intlTelInput is not a function.  Exception occurred when checking element site-phone, check the 'intlTelNumber' method.
    at $.validator.<anonymous> (1dabdf0487bbd9409effa79e8a16689b.js:2982)
    at $.validator.check (1dabdf0487bbd9409effa79e8a16689b.js:2012)
    at $.validator.element (1dabdf0487bbd9409effa79e8a16689b.js:1776)
    at $.validator.onkeyup (1dabdf0487bbd9409effa79e8a16689b.js:1631)
    at HTMLInputElement.delegate (1dabdf0487bbd9409effa79e8a16689b.js:1716)
    at HTMLFormElement.dispatch (jquery-min.js:1)
    at HTMLFormElement.r.handle (jquery-min.js:1)

/*  FORM INLINE CONTROL */

GLOBAL_PHONE: {
	required: true,      // field is mandatory
	intlTelNumber: true  // must contain a valid phone number
},

/* FORM INLINE CONTROL */

/* ADDEVENT */

	// create a custom phone number rule called 'intlTelNumber'
	jQuery.validator.addMethod("intlTelNumber", function(value, element) {
	    return this.optional(element) || $(element).intlTelInput("isValidNumber");
	}, "Please enter a valid International Phone Number");

/* ADDEVENT */

**Comment by jackocnr** [comment]
What is `$.validator`? Is that a plugin you're using? I'm not familiar with that. I'm afraid this is outside the scope of this plugin - I'd recommend you ask for help on StackOverflow.

**Comment by TheMurseL** [comment]
i am using https://jqueryvalidation.org/ script. 

this is rule;

$(this).parents('form').validate({
	rules: {				
		GLOBAL_PHONE: {
			required: true,
			intlTelNumber: true // must contain a valid phone number
		},				
	},
	...
	...
	...
	...
	...
});

**Comment by jackocnr** [comment]
Thanks for clarifying, but yeah as I say, I'm afraid this is outside the scope of this plugin - I'd recommend you ask for help on StackOverflow.
