### ISSUE TITLE
Flags are displayed in half for smaller screens

### ISSUE THREAD

**Issue by adityahparikh** [jackocnr/intl-tel-input#868]
I am getting half cut flags for many countries for smaller screens. 

![edit](https://user-images.githubusercontent.com/10240440/52563626-004b1180-2e28-11e9-9df9-db8aa68cc3df.png)
![edit1](https://user-images.githubusercontent.com/10240440/52563630-02ad6b80-2e28-11e9-9d2d-c343a12e0fdd.png)

**Comment by jackocnr** [comment]
This sounds like a conflict between your CSS and your flags sprite. Perhaps a caching issue?

If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by adityahparikh** [comment]
I can see here that the flag background position in shifted in the sprite. Changing the background position from sprite solves the problem. Few countries have proper flat display although. I haven't given any other CSS this this also.

Also it works fine when opened on larger screens. This occured when I updated to version 14.0.7.

**Comment by jackocnr** [comment]
Please make sure you're on the latest version, and as I say, if you provide a codepen I will be happy to take a look. It's impossible to debug without that.

**Comment by adityahparikh** [comment]
The problem is solved.

I updated the library to 14.0v few days back and I forgot to update the flag images which caused the conflict. It is working fine on all devices now. 

Thanks a lot
