### ISSUE TITLE
flag dropdown not closing upon clicking on selected flag

### ISSUE THREAD

**Issue by eddr** [jackocnr/intl-tel-input#869]
v15

### Steps to reproduce
1.  loading the css file and js file
2.  init for specific field
3. Clicking on the selected flag to open the dropdown. Then reclicking

### Expected behaviour
The dropdown should close

### Actual behaviour
Not closing

### Initialisation options
none

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by eddr** [comment]
OK, the problem is with WooCommerce (Wordpress plugin) and it stops propagation of events. I'll contact them

**Comment by jackocnr** [comment]
There's no exposed API for this, but depending on what WooCommerce is doing you could programmatically trigger a click on the selected flag element.

**Comment by eddr** [comment]
WC has their reason:
https://github.com/woocommerce/woocommerce/issues/22720

Can you please add the event on the input explicitly?

**Comment by jackocnr** [comment]
> please add the event on the input explicitly

Sorry not sure what you mean here. Please expand, and link to code/examples if you can.

**Comment by pramodjodhani** [comment]
I was able to fix it with this code:

```
var iti_open = false;
jQuery('.iti__flag-container').click(function() {
    iti_open = !iti_open;
    if ( !iti_open ) {
        intlTelInputGlobals.instances[ 0 ]._closeDropdown();
    }
});
```
