### ISSUE TITLE
International Telephone Not working properly

### ISSUE THREAD

**Issue by liuwenik** [jackocnr/intl-tel-input#872]
// Vanilla Javascript		
		var input = document.querySelector("#telephone");		
		var iti = intlTelInput(input)
		window.intlTelInput(input,({		
		  // options here		
			initialCountry: "auto",
			geoIpLookup: function(success, failure) {
				$.get("https://ipinfo.io", function() {}, "jsonp").always(function(resp) {
				  var countryCode = (resp && resp.country) ? resp.country : "";
				  success(countryCode);
				});
			  },
		}));
		
		
		
		 
Hi, could someone help me ?
From the code above i got nothing or blank flag from auto initialize country.
What mistake that i have done ?

and from this code : 

```
// Vanilla Javascript		
		var input = document.querySelector("#telephone");		
		var iti = intlTelInput(input)
		window.intlTelInput(input,({		
		  // options here		
			initialCountry: "au",
			
		}));
```
		
		input.addEventListener("countrychange", function() {
			var countryData = iti.getSelectedCountryData();
			/*
			{
			  name: "Afghanistan (‫افغانستان‬‎)",
			  iso2: "af",
			  dialCode: "93"
			}
			*/
			var numberType = iti.getNumberType();

			var extension = iti.getExtension();
			alert(countryData.name);
			alert(countryData.dialCode);
			
		  // do something with iti.getSelectedCountryData()
		
		});
		
i have initialize selected country australia, but when i try to iti.getSelectedCountryData() i still get the United State country. 

Please help me.

**Comment by jackocnr** [comment]
In both cases you need to remove this line `var iti = intlTelInput(input)` which is initialising the input without any options. Does that help?

**Comment by liuwenik** [comment]
Hi jackocnr,

Thank you for your response.
If i remove that line var iti = intlTelInput(input)

How i should get the countrydata from getinstance ?

**Comment by liuwenik** [comment]
Hi jackocnr,

Thank you for your response.
If i remove that line var iti = intlTelInput(input)

How i should get the countrydata from getinstance ?

**Comment by jackocnr** [comment]
So `intlTelInput` is the same function as `window.intlTelInput` and so you were calling that twice, and so instantiating the plugin twice which will cause problems. You should just call it once, but when you do, you can assign the result to your iti variable e.g. `var iti = window.intlTelInput(...`

**Comment by liuwenik** [comment]
Hi jackocnr,

It seem  clear now. I will try it tomorrow. If you dont mind i will ask here again if i get a problem.

Thanks a lot. This plugin is very useful for a developer.

**Comment by liuwenik** [comment]
Hi jackocnr,

I got error in the console while running auto country :
```
var iti1 = window.intlTelInput(input,({		
  // options here		
	initialCountry: "auto",	
	
	geoIpLookup: function(success, failure) {
		$.get("https://ipinfo.io", function() {}, "jsonp").always(function(resp) {
		  var countryCode = (resp && resp.country) ? resp.country : "";
		  success(countryCode);
		});
	  },
	
}));

the error :
jquery-latest.min.js:4 GET https://ipinfo.io/?callback=jQuery111101933554092143417_1550706186972&_=1550706186973 net::ERR_ABORTED 429

I dont know what error is this ?
Why i got this error ?
```

**Comment by jackocnr** [comment]
Sorry I don't really have time to look into these basic usage issues for you. I recommend you try searching/asking on [StackOverflow](https://stackoverflow.com/).

**Comment by alok108** [comment]
> Hi jackocnr,
> 
> I got error in the console while running auto country :
> 
> ```
> var iti1 = window.intlTelInput(input,({		
>   // options here		
> 	initialCountry: "auto",	
> 	
> 	geoIpLookup: function(success, failure) {
> 		$.get("https://ipinfo.io", function() {}, "jsonp").always(function(resp) {
> 		  var countryCode = (resp && resp.country) ? resp.country : "";
> 		  success(countryCode);
> 		});
> 	  },
> 	
> }));
> 
> the error :
> jquery-latest.min.js:4 GET https://ipinfo.io/?callback=jQuery111101933554092143417_1550706186972&_=1550706186973 net::ERR_ABORTED 429
> 
> I dont know what error is this ?
> Why i got this error ?
> ```
Hi liuwenik

Try putting your file on a live server and verify. I also had the 429 error in local but it was gone after I made the site live.
