### ISSUE TITLE
Is there a way to detect when initialized?

### ISSUE THREAD

**Issue by ryanguill** [jackocnr/intl-tel-input#873]
I am looking for an event to listen to or method to use to detect when the initialization is complete and it is safe to call `isValidNumber`.  Trying to do it on document ready or even setTimeout of 100ms isnt enough.  In looking through old issues it looks like the jquery version had a `done` callback that you could use, is there something like that now? In looking through the code I didn't see anything but may be missing it or it is named differently?

**Comment by ryanguill** [comment]
I just found this https://github.com/jackocnr/intl-tel-input/blob/master/src/spec/tests/static/loadUtils.js#L136 which uses `instance.promise` is that the correct way to handle this?

**Comment by jackocnr** [comment]
https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/init-promise.html

**Comment by ryanguill** [comment]
Thanks! would you be interested in a PR that mentions this on the main readme?

**Comment by jackocnr** [comment]
Hmm where would you put it?

It's actually already mentioned in the descriptions of the two features which make the initialisation asynchronous, namely geoIpLookup and utilsScript.

**Comment by ryanguill** [comment]
I looked through it multiple times and didnt notice that - I guess because I didnt realize that the isValidNumber was dependent on that.  My use case is that I am populating the value with a number I already have, but don't know if it is valid, and need to do something on load if it is or isnt.  Maybe we could add something to the Public Methods that already say "Requires the `utilsScript` option" that they are not available until after it is loaded and you can check for that using the promise?

If I am the only one that's been confused maybe not worth it though.

**Comment by jackocnr** [comment]
Well I don't want to add all that text about handling the promise to every method that relies on utilsScript. I think it's enough that we mention the utilsScript option, then if you read the description of that one then you will see the promise info. Thanks tho.
