### ISSUE TITLE
Viet Nam Phone number validations

### ISSUE THREAD

**Issue by minhhoangvhit** [jackocnr/intl-tel-input#874]
### Steps to reproduce
1.  input this phone number : +84867672687

### Expected behaviour
Show valid number

### Actual behaviour
Show invalid number
![image](https://user-images.githubusercontent.com/3954953/53329392-900bb800-391e-11e9-911b-2c45b9812eda.png)

![image](https://user-images.githubusercontent.com/3954953/53329359-7f5b4200-391e-11e9-9dcf-bb1e7072bb0d.png)

**Comment by jackocnr** [comment]
I've updated the demo site to use the latest version of the plugin and it works now 👍
