### ISSUE TITLE
Change belarusian phone number placeholder

### ISSUE THREAD

**Issue by MrBandaruk** [jackocnr/intl-tel-input#875]
### Expected behaviour
It would be great if you add have a possibility to change placeholders. 

Example: 
When I choose belarusian phone number (+375) there is **8 029...** placeholder. Is it possible to change it on the **+375...** placeholder?

**Comment by jackocnr** [comment]
Please read the [New Issue Checklist](https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist) before posting.

> We use libphonenumber for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check their test site first and if you see the problem there please file an issue with them instead.
