### ISSUE TITLE
Latest google libphonenumber v8.10.6 changes to be added

### ISSUE THREAD

**Issue by ishaan1995** [jackocnr/intl-tel-input#876]
Release: https://github.com/googlei18n/libphonenumber/releases/tag/v8.10.6

#### Issue: 

- Not able to add new Myanmar phone series.

**Comment by jackocnr** [comment]
Hi there, thanks for raising this issue. Unfortunately I'm very busy at the mo, but it's very easy to update this yourself, and submit a Pull Request to help others! See the [Contributing Guide](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md) for instructions.

**Comment by jackocnr** [comment]
Released in v15.0.1
