### ISSUE TITLE
Add City

### ISSUE THREAD

**Issue by Tidada** [jackocnr/intl-tel-input#877]
Hi i hope that you are doing well

Actually i just saw your plugin it's so helpful thank you!!
And my question is i want to add cities to a select box that helps to switch country automaticaly

thank you!

**Comment by landsman** [comment]
@Tidada You have to find country from the city name by self. Probably Google Maps API will be great for that.

After them you can do:
```
iti.setCountry("gb");
```

**Comment by jackocnr** [comment]
Hi @Tidada, did you see the [Country sync](https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/country-sync.html) example? Sounds like just what you're looking for.

**Comment by Tidada** [comment]
@jackocnr yes i saw country sync and i m looking for city not country... :/ where should i edit exactly?

**Comment by jackocnr** [comment]
Ah well this plugin doesn't deal with cities, so I'm afraid I can't help with that.

**Comment by Tidada** [comment]
Ok Thank you anyway
