### ISSUE TITLE
initializing plugin with existing phone number

### ISSUE THREAD

**Issue by zerocarbthirty** [jackocnr/intl-tel-input#879]
### Steps to reproduce
When #phone has a value on page load the plugin doesn't automatically select the right country, the flag is blank. (jquery version) 

### Expected behaviour
It should automatically select the correct country/flag.

### Actual behaviour
it loads up with a blank flag and will not validate until the user clicks the dropdown and selects their country again

### Initialisation options
$("#phone").intlTelInput({
            utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/15.0.0/js/utils.js",
            hiddenInput: "phone-full"
        });

**Comment by jackocnr** [comment]
Hi there. What version of the plugin are you using? And what exactly is the phone number string you're putting in the input? It need to include the international dial code in order to set the country correctly.

**Comment by zerocarbthirty** [comment]
V 15. the phone number in #phone is the phone number that the control submits, what happens is if there is an error in the form it bounces them back and presents an error. is there a different way that I have to submit the prepopulated phone number than just putting it as the value on the form control? I know on the javascript native version there is a 
intlTelInput(input{ mentioned is there a way to do that on the jquery version?

Sorry if I am confused I can't find the documentation to the jquery version anymore.
