### ISSUE TITLE
How do I open or close the list using <input onclick="showMode()"> showMode()

### ISSUE THREAD

**Issue by XiaoSprit** [jackocnr/intl-tel-input#880]
### Steps to reproduce
1.  <input id="phone" class="row-input" placeholder="xxxx" onclick="showMode()">
2.  var input = document.querySelector("#phone");
        var iti = window.intlTelInput();
3. function showMode(){
            console.log("xxxx");
            $("#country-listbox").removeClass("hide");
        }

### Expected behaviour

How do I open or close the list using <input onclick="showMode()"> showMode()

**Comment by XiaoSprit** [comment]
![image](https://user-images.githubusercontent.com/42344858/53677435-b351b100-3cea-11e9-935d-ec0ce4ced9a3.png)

**Comment by jackocnr** [comment]
If I understand correctly, you want to toggle the country dropdown every time the user clicks the input? Can I ask why you want to do that? I think that would make a very confusing experience. Have you considered that users sometimes click at different places in the input to edit the value they have types? Each time that would be toggling the dropdown.

**Comment by XiaoSprit** [comment]
Yes, I'm going to dropdown the country of the user's choice in the input box without the user editing it

**Comment by XiaoSprit** [comment]
Yes, I will put the country and area code that the user entered into the input box without requiring the user to click.I want users to be able to select a country when they click on the input box

**Comment by XiaoSprit** [comment]
Thanks!  I will put the country and area code that the user entered into the input box without requiring the user to click.I want users to be able to select a country when they click on the input box

**Comment by jackocnr** [comment]
There is no direct API to control the plugin's dropdown, but the best thing you can do is trigger a click event on the selected flag, which will tell the plugin to toggle the dropdown.
