### ISSUE TITLE
Indian new Phone number serices is not validated v15

### ISSUE THREAD

**Issue by bhmb2000** [jackocnr/intl-tel-input#881]
New mobile series started in India 6400 which is not validating by v15.
Will you please add it so it gets validated.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.
