### ISSUE TITLE
Everything

### ISSUE THREAD

**Issue by knight-warrior7** [jackocnr/intl-tel-input#882]
Pretty much the worst peace of shit ever created.Horrible design with 10x css class declaration on every selector+positioning,hard-coded javascript,horrible performance. I spent a whole day reworking your css,removing all the shit "fixed" positioning on a fucking dropdown and etc. . Guess how i felt when my manager told me to "make the flag bigger"?The flags are a one very low resolution PNG, and to make them bigger i have to npm-grunt and do some other retarted, time wasting stuff :D 

Optimize the library? Why?I'd rather make a simple thing very complicated,load the repository with useless code, and bullshit README files...Man, I am so frustrated right now, i will just write my own.give the world a favour and don't write code anymore, or at least don't publish it, you will work better as a garbage collector.
First time i bothered writing something on github, take that as a note how horrible you are ;)

**Comment by jackocnr** [comment]
Hehe thanks for the feedback champ. If you do decide to build your own version, you should publish it on Github - I'd love to see what you come up with.
