### ISSUE TITLE
Ecuador Phone number validations

### ISSUE THREAD

**Issue by aymeperdomo** [jackocnr/intl-tel-input#883]
### Steps to reproduce
1.  Input this phone number : 0963103196  

### Expected behaviour
Show valid number

### Actual behaviour
Show invalid number

When the phone number starts with 096 and has the following digits as successor: [3, 4, 5 or 6], it shows that it is an invalid number, however, with the following digits as successors: [1, 2, 7, 8 or 9] the number is valid.

[Example Validation](https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html)

![Example  Validation (2)](https://user-images.githubusercontent.com/26690297/54560962-88758700-4991-11e9-8cef-e8d3ffc532e5.png)

See [link](https://www.howtocallabroad.com/ecuador/)

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

**Comment by aymeperdomo** [comment]
Hi, thanks for your answer. After checking the issue against [Phone Number Parser Demo](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html), the problem persists. I will report the problem with them.
