### ISSUE TITLE
Dial code not presented initially in v15

### ISSUE THREAD

**Issue by rukavina** [jackocnr/intl-tel-input#886]
### Steps to reproduce
1.  Open https://codepen.io/rukavinamilan/pen/MRebOY

### Expected behaviour
Focus should show dial code as it does in v14 https://codepen.io/rukavinamilan/pen/JVKbpN

### Actual behaviour
It shows no data

### Initialisation options
nationalMode: false

**Comment by jackocnr** [comment]
https://github.com/jackocnr/intl-tel-input/releases/tag/v15.0.0

**Comment by rukavina** [comment]
This is bad UX decision then because how would an user know if he/she is expected to enter full international or national number?

**Comment by jackocnr** [comment]
They should be able to enter either and then if you use `getNumber` it will always return the full international number (see Recommended Usage section of readme).
