### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by sambonim** [jackocnr/intl-tel-input#891]
I've noticed that the validation is accepting letters, if we mix letters with the right number of characters the validation will pass (ex: 201 203 302 w 3) 

### Steps to reproduce
1.  Validation form https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html
2.  Insert number with letters

### Expected behaviour
Don't accept letters

### Actual behaviour
Accepts letters

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.
