### ISSUE TITLE
Screen Reader devices are not able to detect navigated country code drop down list item

### ISSUE THREAD

**Issue by padu** [jackocnr/intl-tel-input#893]
### Steps to reproduce
1.  Open https://intl-tel-input.com/
2.  Start NVDA screen reader, press tab and navigate to demo country code drop down 
3.  Press UP/Down Key to navigate to country code items
4. On browser UI respective list item is highlighted but screen reader is not announcing it. 

### Expected behaviour
After UP/Down keyboard key at country code dropdown, screen reader should able to announce respective highlighted country code, that user want to select. 

### Actual behaviour
After UP/Down keyboard key at country code dropdown, screen reader is not able to detect highlighted country code item.

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by padu** [comment]
@jackocnr PR with #892, raised for issue fix. Please have a look.

**Comment by jackocnr** [comment]
Released in v15.1.0.
