### ISSUE TITLE
How can I change the placeholder number of only one country?

### ISSUE THREAD

**Issue by rafatmyo** [jackocnr/intl-tel-input#897]
I want to change the placeholder number for Mexico. Right now it's 044 222 123 4567 and I would like to remove the 044 since nobody dials it anymore leaving it like 222 123 4567, is this possible?

**Comment by jackocnr** [comment]
The best thing to do is open an issue with libphonenumber which is the project we use to generate the placeholder numbers.

In the meantime, a workaround would be to use `customPlaceholder` and check the country data, if it's Mexico, then use your custom number.
