### ISSUE TITLE
Flag is not updated when using 0046 instead of +46

### ISSUE THREAD

**Issue by josefinscreentek** [jackocnr/intl-tel-input#899]
Hi,
This is something between a bug and a feature request.

The flag is automatically updated correctly if you e.g. put +46 (Sweden country code) in the text field. But if you instead uses the format 0046 (that is also valid in the same way as +46), the flag is not updated.

Is this something that can easily be fixed?

Thank you in advance

**Comment by josefinscreentek** [comment]
And here are the steps to recreate the issue
### Steps to reproduce
1.  Use the plugin anywhere, e.g. the demo page
2.  Have the flag as default (anything else than Norway in this case)
3.  Add the number 004746000000

### Expected behaviour
The flag should be changed to Norway

### Actual behaviour
The flag remains as initialized.

If you instead uses +4746000000, the flag is updated to Norway

**Comment by jackocnr** [comment]
This question has been answered many times. See #5.
