### ISSUE TITLE
hiddenInput - square brackets not working as expected

### ISSUE THREAD

**Issue by carylewis** [jackocnr/intl-tel-input#902]
I am trying to use the hiddenInput feature, and I can't quite make out what the documentation is trying to say:

> Add a hidden input with the given name (or if your input name contains square brackets then it will give the hidden input the same name, replacing the contents of the brackets with the given name)

By input name, does that refer to the <input name=...> value?

I tried to use this in my code:

     <input id="phone" name="[phone]" type="tel">

but on submit, I don't see the getNumber value.

Can someone please provide an working example of using the square brackets hiddenInput feature?

Should I expect two things being submitted, the original value of the input field, and then an other value with just the getNumber() version?

**Comment by jackocnr** [comment]
I've updated the readme to be more clear. Does that make sense now?

**Comment by carylewis** [comment]
Yes, thank you, that's much better, and I got it working right away.

**Comment by carylewis** [comment]
Hi there, thanks again for the quick reply.

I had another quick comment - the github repo refers to the jQuery version,
but doesn't seem to supply any links to it.

I found one here:

https://www.jqueryscript.net/form/jQuery-International-Telephone-Input-With-Flags-Dial-Codes.html


Is that the latest one?

What are the differences between the jQuery and non-jquery versions - other
than non-jquery one doesn't use jquery.

I guess I'm asking if I can use the non-jquery version with jquery
functions?

**Comment by jackocnr** [comment]
If you're already using jQuery then it's easiest to just stick with the jQuery version of the plugin. You can find it in the build/ directory.
