### ISSUE TITLE
unexpected bugs in number validation

### ISSUE THREAD

**Issue by Michaelwan777** [jackocnr/intl-tel-input#903]
Hi! I've used this module for a while and it's pretty nice. 

But recently I found some bugs in phone number validation. For example, I want to enter a phone number which I have checked the validity of the phone number by making a call and answer successfully. Is it caused by some bugs in 'libphonenumber' from Google?

Any help is much appreciated!

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.
