### ISSUE TITLE
accessing getNumber method from jQuery

### ISSUE THREAD

**Issue by carylewis** [jackocnr/intl-tel-input#904]
I am using the jQuery version of intlTelInput, and I have multiple input fields in a form:

```
<form id="create">
    <input id="phone1" name="main1[phone]" type="tel">
    <input id="phone2" name="main2[phone]" type="tel">
    <button style="display:none" id="formbut">Submit</button>
  </form>

    <button id="but1"> test</button>

```
I have initialized the plug using jQuery:

```
$("input[type=tel]").intlTelInput({
        hiddenInput: "q",
        // options here
});

```
I need to do some preprocessing before I submit the form, so I added a click handler on my but1 button. 

My question is how do I access the getNumber() method on each instance, or on a particular instance of the input fields?

I was hoping that:

`$("#phone1").getNumber()`

would work, but it doesn't.

Can you explain how to get to use the getNumber() from jQuery?

**Comment by jackocnr** [comment]
We updated the readme to the non-jquery version in v14, so if you check [the readme for v13](https://github.com/jackocnr/intl-tel-input/tree/v13.0.4), you will see the documentation for the jquery version (as it was at that time).

**Comment by carylewis** [comment]
Thanks. Doh!

We'll make a donation, once we get every thing working.
