### ISSUE TITLE
If no phone number is entered, only country code is submitted

### ISSUE THREAD

**Issue by quinncomendant** [jackocnr/intl-tel-input#907]
I'm using intl-tel-input@15.1.0, configured as following:

    var input = document.querySelector('input[name="phone"]');
    window.intlTelInput(input, {
        hiddenInput: "intl_phone",
        preferredCountries: ['it', 'us', 'gr', 'nl', 'be', 'fr', 'es', 'ch', 'at', 'gb', 'dk', 'se', 'no', 'pl', 'de'],
        separateDialCode: true,
        utilsScript: "/js/intl-tel-input/js/utils.js",
    });

When I load the form page, the first of the preferredCountries is pre-selected ("it"). 

If I submit the form without entering a phone number, the `hiddenInput` field containing "+39" is submitted. The POST values include:

    [phone] => 
    [intl_phone] => +39

I would expect both `phone` and `intl_phone` to be completely empty.

Is there a way to exclude the country code from the `hiddenInput`field if the phone number is not entered?

**Comment by jackocnr** [comment]
I can repro this behaviour. Thanks for reporting this. More generally, the bug is that `getNumber` returns the international dial code when `separateDialCode` is enabled and the input is empty.

I'm afraid I don't have time to look into this myself right now, but I would welcome a pull request.

**Comment by jackocnr** [comment]
Fixed in v15.1.2.
