### ISSUE TITLE
Phone placeholder in Uzbekistan is wrong

### ISSUE THREAD

**Issue by Khujamurod97** [jackocnr/intl-tel-input#908]
When you choose Uzbekistan from the list, the placeholder  shows 8 91 234 56 78. I can't be valid. If we remove first digit : 91 234 56 78 that is right placeholder.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.
