### ISSUE TITLE
hiddenInput contains "+undefined" if no valid country code is selected

### ISSUE THREAD

**Issue by quinncomendant** [jackocnr/intl-tel-input#913]
### Steps to reproduce
1.  Setup intl-tel-input with a primary phone field `name="phone"` and a hiddenInput `name="intl_phone"`.
2.  Load a form page with `phone` prepopulated with an invalid phone number value: `value="1 3046457291"`.
3.  Notice there is no valid country code selection (the flag icon is "grey"). It will look like this: 
    <img width="389" alt="Screen Shot 2019-06-09 at 21 11 55" src="https://user-images.githubusercontent.com/6884276/59168638-352c5400-8afc-11e9-8e09-1a1f9daa4981.png">
4. Upon submitting the form, $_POST contains:

    [phone] => 1 3046457291
    [intl_phone] => +undefined1 3046457291

### Expected behaviour
If there is no valid country code selection, the country code number should remain blank. And the `intl_phone` hiddenInput should probably remain blank, or be set to the same as `phone`.

### Actual behaviour
If there is no valid country code selection, the country code number is "undefined".  The `intl_phone` hiddenInput contains `+undefined1 3046457291`.

### Initialisation options

    window.intlTelInput(input, {
        hiddenInput: "intl_phone",
        preferredCountries: ['it', 'us', 'gr', 'nl', 'be', 'fr', 'es', 'ch', 'at', 'gb', 'dk', 'se', 'no', 'pl', 'de'],
        separateDialCode: true,
        utilsScript: "/js/intl-tel-input/js/utils.js"
    });

**Comment by jackocnr** [comment]
Thanks for reporting. This is related to https://github.com/jackocnr/intl-tel-input/issues/907.

I don't have time to work on this myself right now, but would welcome a pull request.

**Comment by jackocnr** [comment]
Fixed in v15.1.2.
