### ISSUE TITLE
Extract area code from dial code for all NANP countries

### ISSUE THREAD

**Issue by jackocnr** [jackocnr/intl-tel-input#917]
e.g. American Samoa, where we have the dial code as +1684, but really the dial code is just +1 and the area code is 684.

Would you be up for tackling this @jyotsnagaddam?

Note: when this is implemented, I think we can safely remove [this complicated NANP condition](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js#L1152) in the getFullNumber method, which specifically looks for 4-digit dial codes starting with `1`, which I believe wont exist any more.

**Comment by jackocnr** [comment]
I ended up implementing this myself and it's now merged into master and will be included in the upcoming major release.

**Comment by jyotsnagaddam** [comment]
Thanks, I just started looking at it but have couple of questions, as I see some variables related to NANP, so and related conditions.  However thanks for resolving this too!

**Comment by jackocnr** [comment]
Thanks, I think those cases are fine. Though we may end up updating them to be more general as part of this: https://github.com/jackocnr/intl-tel-input/issues/920
