### ISSUE TITLE
Make flags circle

### ISSUE THREAD

**Issue by johndavemanuel** [jackocnr/intl-tel-input#919]
Is it possible to make the flag in circle?

**Comment by jackocnr** [comment]
I'm afraid not - if they were square then it would be easy to add border-radius styling to turn them into circles, but because they're rectangles it would never work - you'd be cropping too much. It would technically be possible to override the CSS to use your own circular flag images, but it would be a lot of work, as there are over 200 countries to support.

**Comment by johndavemanuel** [comment]
I see, I already have all countries flag in SVG, I will try to work on that and submit a pull request

**Comment by jackocnr** [comment]
Thanks for the thought, and it would be amazing to have the flags in SVG format, but just to warn you: I did try this once and the SVG files ended up being much bigger than the current PNGs, which makes it not worth it in my opinion. So I would only be interested in a PR if you can find a way to do it without a big increase in image filesize.

**Comment by johndavemanuel** [comment]
Thanks for the guide, I am also considering that issue, as the current flags are in one file only and being crop using CSS, maybe I can make a file image file of flag which is having circle flags, then adjust the css to each flag

**Comment by jackocnr** [comment]
Oh, sorry, I didn't think through my previous comment - I would be interested in a PR to change the existing rectangular flags to SVG, so it's easy to display them at any size, but actually I realise your goal is to get circular flags, which would mean either circular or maybe square flag images, and I'm not interested in supporting that in the plugin at this time - I want to keep the plugin as simple as possible. Apologies for that. But if you manage to get this working, it would be great if you could post about it in this issue, in case it can help anyone else.

**Comment by johndavemanuel** [comment]
I appreciate your kind response. Thank you! Great plugin by the way.
