### ISSUE TITLE
 Cannot read property 'toLowerCase' of undefined  at Iti.setCountry (intlTelInput.js:1224)

### ISSUE THREAD

**Issue by ragav-india** [jackocnr/intl-tel-input#923]
Hi Team, 

I am getting an error message as  Cannot read property 'toLowerCase' of undefined while setting a country using a setCountry(). I am setting a country from my form country dropdown menu as  

> iti.setCountry($('#country').val()); 

### Error Thrown 
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at Iti.setCountry (intlTelInput.js:1224)

```
// intTelInput.js

{
                key: "setCountry",
                value: function setCountry(originalCountryCode) { 
                    var countryCode = originalCountryCode.toLowerCase(); // error showing here
                    // check if already selected
                    if (!this.selectedFlagInner.classList.contains(countryCode)) {
                        this._setFlag(countryCode);
                        this._updateDialCode(this.selectedCountryData.dialCode, false);
                        this._triggerCountryChange();
                    }
                 }
```
Please guide me to fix this issue.

**Comment by jackocnr** [comment]
It sounds like `$('#country').val()` is returning `undefined`.
