### ISSUE TITLE
Update to latest libphonenumber v8.10.14

### ISSUE THREAD

**Issue by asiritsa** [jackocnr/intl-tel-input#926]
The current version of intl-tel-input uses v8.10.6 of libphonenumber. Please, update it to the newest v8.10.14 version.
https://github.com/google/libphonenumber/releases/tag/v8.10.14

**Comment by jackocnr** [comment]
Thanks for raising this issue. It actually only takes 5 minutes to do this yourself, if you'd be willing to submit a Pull Request? Instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber). Thanks :)

**Comment by jackocnr** [comment]
Released in v16.0.1
