### ISSUE TITLE
IE Error - Object doesn't support property or method 'remove'

### ISSUE THREAD

**Issue by ragav-india** [jackocnr/intl-tel-input#928]
Hi 
 
I am facing an issue in IE Browser ( v11.5) 

> ' Object doesn't support property or method 'remove' '

intlTelInput.js (927,21);

> "   containerClone.remove();"

Please kindly help to fix this problem.

**Comment by jackocnr** [comment]
Confirmed, [ChildNode.remove()](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove) is not supported in any version of IE *sigh*. Instead we should switch to `element.parentNode.removeChild(element)` according to [this SO answer](https://stackoverflow.com/a/40009566/217866). I don't have time to implement this myself right now but would welcome a Pull Request. Thanks.

**Comment by mac89** [comment]
@jackocnr Yeah, I'll fix it.

**Comment by jackocnr** [comment]
Released in v16.0.2.
