### ISSUE TITLE
valide phone number not validated

### ISSUE THREAD

**Issue by StillUpgrade** [jackocnr/intl-tel-input#930]
### Steps to reproduce
1.  enter +212 708219###
(ex: +212 708219111)
2.  phone number is triggered as not valid
3.  go to google's validation lib example :
https://libphonenumber.appspot.com/
enter the same phone, (country is 'MA') it's valid.

**Comment by jackocnr** [comment]
Please make sure you're using the latest version. I just tested on the validation demo page and your example number came up valid.

**Comment by StillUpgrade** [comment]
![image](https://user-images.githubusercontent.com/10169092/60716554-fc777300-9f1f-11e9-8e2f-c26b57bdbeb2.png)

you are talking about https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html right ? it's not valid for me.

**Comment by jackocnr** [comment]
Hmm that's weird. Try clearing your cache. I recently updated the plugin version on those demo pages.

**Comment by StillUpgrade** [comment]
🤦‍♂ It was the cache, thank you and sorry for the issue
