### ISSUE TITLE
Not Sending Country Code

### ISSUE THREAD

**Issue by clickspider** [jackocnr/intl-tel-input#934]
### Steps to reproduce
1.  Tried to access the dialCode (var countryData = iti.getSelectedCountryData();) but got an empty Object 

![image](https://user-images.githubusercontent.com/46437510/60968674-f87f9280-a31d-11e9-9af1-14060de68ab0.png)

2. I am using the latest version.

3.  I am using vue.js and the form is under a Modal.

### Expected behaviour
It should send the full number including the DialNumber to the server.

### Actual behaviour
Instead of that I am only getting the '+' (without the actual dialCode e.g. +31 / +1) and then the number that the user put in the input.

See Image:
![image](https://user-images.githubusercontent.com/46437510/60968309-097bd400-a31d-11e9-931e-a7ba681a28e1.png)

### Initialisation options
initialCountry: "auto",
separateDialCode: "true",
geoIpLookup: function(callback) {
    $.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
    var countryCode = (resp && resp.country) ? resp.country : "";
    callback(countryCode);
    });
},
hiddenInput: "full_phone",
utilsScript: "./build/js/utils.js"

**Comment by jackocnr** [comment]
What flag is selected, and what's in the input when you do this?

If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by clickspider** [comment]
Got it eventually. I declared the phone propriety in the wrong place in my code.
