### ISSUE TITLE
getValidationError returns 5

### ISSUE THREAD

**Issue by princefishthrower** [jackocnr/intl-tel-input#937]
### Steps to reproduce
1.  I call ini.isValid() first
2.  If false, I check the validation error to get more info
3.  validation error is 5

Example number is +4112312312123

### Expected behaviour
getValidationError() should return a number in the range 0-4 as described in the docs and source code:

```
// copied this from i18n.phonenumbers.PhoneNumberUtil.ValidationResult in https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/phonenumberutil.js and again put the keys in quotes.
// Also: added NOT_A_NUMBER to match i18n.phonenumbers.Error.NOT_A_NUMBER
var validationError = {
  "IS_POSSIBLE": 0,
  "INVALID_COUNTRY_CODE": 1,
  "TOO_SHORT": 2,
  "TOO_LONG": 3,
  "NOT_A_NUMBER": 4
};
```

Note: output from libphonenumber test site is:

```
****Parsing Result:****
{"country_code":41,"national_number":12312312123,"raw_input":"+4112312312123","country_code_source":1}

****Validation Results:****
Result from isPossibleNumber(): false
Result from isPossibleNumberWithReason(): 
Note: numbers that are not possible have type UNKNOWN, an unknown region, and are considered invalid.

****ShortNumberInfo Results:****
Result from isPossibleShortNumber: false
Result from isValidShortNumber: false
Result from isPossibleShortNumberForRegion: false
Result from isValidShortNumberForRegion: false

****Formatting Results:**** 
E164 format: invalid
Original format: +4112312312123
National format: 12312312123
International format: invalid
Out-of-country format from US: invalid
Out-of-country format from Switzerland: invalid

****AsYouTypeFormatter Results****
Char entered: + Output: +
Char entered: 4 Output: +4
Char entered: 1 Output: +41 
Char entered: 1 Output: +41 1
Char entered: 2 Output: +41 12
Char entered: 3 Output: +41123
Char entered: 1 Output: +411231
Char entered: 2 Output: +4112312
Char entered: 3 Output: +41123123
Char entered: 1 Output: +411231231
Char entered: 2 Output: +4112312312
Char entered: 1 Output: +41123123121
Char entered: 2 Output: +411231231212
Char entered: 3 Output: +4112312312123
```

### Actual behaviour
getValidationError returns 5

### Initialisation options
config options as follows:
```
window.intlTelInput(input, {
                hidden_input: 'telephone',
                separateDialCode: true,
                preferredCountries: ["ch", "at", "de"],
                initialCountry: "ch",
            });
```

**Comment by jackocnr** [comment]
Thanks for reporting this. We need to update our `validationError` codes in [utils.js](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/utils.js#L147) to match [libphonenumber's ones](https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/phonenumberutil.js#L966) which have been updated.

I would be open to a pull request to make this change. Thanks.

**Comment by princefishthrower** [comment]
Finally got around to doing this! I think PR 989 should solve it: https://github.com/jackocnr/intl-tel-input/pull/989

**Comment by jackocnr** [comment]
Thanks so much for this, but after thinking about it further, I think we need to take a different approach.

I think when I originally wrote [this code](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/utils.js#L71) I was trying to be clever, and make it as intuitive as possible for devs to use by mapping libphonenumber's Error enums to ValidationResult enums, but actually we've just ended up with something confusing and now broken as libphonenumber changes their enums. So now I think the best thing to do is to keep it simple and in `getValidationError` just return `e.message` directly, and add to the docs that this will be a `i18n.phonenumbers.Error` enum, and link to [the relevant libphonenumber source](https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/phonenumberutil.js#L69) and then this plugin will be a lot more stable and flexible and devs can handle errors however they want.

**Comment by jackocnr** [comment]
Fixed in v17. Thanks for your help on this one.
