### ISSUE TITLE
document.querySelector("#phone") is null

### ISSUE THREAD

**Issue by vickykrbu** [jackocnr/intl-tel-input#938]
### Steps to reproduce
1.  I have downloaded this project from jqueryScript.net and run the demo.html file from my local system and it is running correctly.
2.  Now when i integrated the same changes for my MVC application where i have one content folder which could be accessible for all the resources like img, css and script.

Inside this i keep the build folder of Intl-tel-input folder and took one Test.cshtml page where i am passing the required code as below:

<link href="@Url.Content("~/Content/build/css/intlTelInput.min.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/build/css/demo.css")" rel="stylesheet" />
<script src="@Url.Content("~/Content/build/js/intlTelInput.min.js")"></script>
<script>
    errorMsg = document.querySelector("#error-msg"),
 validMsg = document.querySelector("#valid-msg");
    var errorMap = ["Invalid number", "Invalid country code", "Too short", "Too long", "Invalid number"];
    var input = document.querySelector("#phone");
    var iti = window.intlTelInput(input1, {
        utilsScript: "/Content/build/js/utils.js"
    });
    var reset = function () {
        input.classList.remove("error");
        errorMsg.innerHTML = "";
        errorMsg.classList.add("hide");
        validMsg.classList.add("hide");
    };
    window.intlTelInput(input, {
      // allowDropdown: false,
      // autoHideDialCode: false,
      // autoPlaceholder: "off",
      // dropdownContainer: document.body,
      // excludeCountries: ["us"],
      // formatOnDisplay: false,
       geoIpLookup: function(callback) {
         $.get("http://ipinfo.io", function() {}, "jsonp").always(function(resp) {
           var countryCode = (resp && resp.country) ? resp.country : "";
           callback(countryCode);
         });
       },
      // hiddenInput: "full_number",
       initialCountry: "auto",
      // localizedCountries: { 'de': 'Deutschland' },
      // nationalMode: false,
      // onlyCountries: ['us', 'gb', 'ch', 'ca', 'do'],
      // placeholderNumberType: "MOBILE",
      // preferredCountries: ['cn', 'jp'],
      // separateDialCode: true,
      utilsScript: "/Content/build/js/utils.js",
    });
    $(document).ready(function () {
        $(validMsg).addClass("hide");
        input.addEventListener('blur', function () {
            reset();
            if (input.value.trim()) {
                if (iti.isValidNumber()) {
                    validMsg.classList.remove("hide");
                } else {
                    input.classList.add("error");
                    var errorCode = iti.getValidationError();
                    errorMsg.innerHTML = errorMap[errorCode];
                    errorMsg.classList.remove("hide");
                }
            }
        });
    });
    input.addEventListener('change', reset);
    input.addEventListener('keyup', reset);
</script>
<input id="phone" name="phone" type="tel">
<span id="valid-msg" class="hide">✓ Valid</span>
<span id="error-msg" class="hide"></span>

### Expected behaviour
When i run this test.cshtml in browser i was getting one console error like a.getAttribute() is not a function.

When i check through client side debugging in browser then found it that in below line input variable is null

var input = document.querySelector("#phone");

I have attached the screen shot for the same.

![intl-telinput_issue](https://user-images.githubusercontent.com/16345701/61297548-16effd00-a7fa-11e9-99c0-a6ee0f2c075e.png)

But input variable having value in demo.html page.

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
I'm afraid this is unrelated to the plugin, and so is outside the scope of the support I can provide. I recommend you try asking on [StackOverflow](https://stackoverflow.com/).
