### ISSUE TITLE
getSelectedCountryData().dialCode not changing

### ISSUE THREAD

**Issue by rafalilloblanco** [jackocnr/intl-tel-input#939]
I'm trying to receive the country code. The code is shown in the input, but it does not change when I select another.
![JS](https://user-images.githubusercontent.com/17000368/61435804-a223dc80-a939-11e9-9c1a-97da182226a8.JPG)
![HTML](https://user-images.githubusercontent.com/17000368/61435805-a2bc7300-a939-11e9-9f9d-4f88cad7844a.JPG)

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by jackocnr** [comment]
Great.
