### ISSUE TITLE
Have getNumber problem using Ajax , please help !

### ISSUE THREAD

**Issue by gsmdenis** [jackocnr/intl-tel-input#941]
Have getNumber problem using Ajax , please help !  this is popup window

https://codepen.io/gsmdenis/pen/GVqJNY

**Comment by jackocnr** [comment]
Seems to be working fine to me. If I load that codepen, and type a valid number then it appears in the output box. What is the problem you're having?

**Comment by gsmdenis** [comment]
hi, jack , thanks for your reply , the case i can not get the hiddenInput when submit, i know output working fine, thats just for test

**Comment by jackocnr** [comment]
You've set the `hiddenInput` to `"getNumber"` which doesn't make sense. Did you read the readme documentation for the `hiddenInput` option? You want to set it to the name that you want to give to the generated hidden input.

**Comment by gsmdenis** [comment]
yes, i read , but get a little bit confuse, that's why ask you for help , please guide me how make it works , thanks in advance

**Comment by jackocnr** [comment]
Your main input is called "mobile", so I recommend you set `hiddenInput` to `"mobile_full"`. Then look out for that POST parameter on your server.

I can see the hidden input is being created correctly, so I don't think this is a problem with the plugin - I'm guessing it's an issue on your server. I can't help with server issues, so I'd recommend asking on StackOverflow.

**Comment by gsmdenis** [comment]
i test at localhost , i try this at different pages, another please was not a popup window, Request method:POST working fine, but this code, no matter what i tried, can not get ""Country Code" (+xx), i also test with mobile_full seems same issue!
thanks for your reply !

**Comment by jackocnr** [comment]
Ah well if you're doing an Ajax request then you don't need the `hiddenInput` option, in your submit handler, you just get the full number using `iti.getNumber()`.

**Comment by gsmdenis** [comment]
Thanks for your reply, Seems i do like this still not work :

`<script>
var input = document.querySelector("#mobile");
var iti = window.intlTelInput(input, {
  nationalMode: true,  
  geoIpLookup: function(callback) {
    $.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
      var countryCode = (resp && resp.country) ? resp.country : "";
      callback(countryCode);
    });
  },
  utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@16.0.2/build/js/utils.js"
});
iti.getNumber();	
</script>`

**Comment by jackocnr** [comment]
I'm sorry but I think you're struggling with the basics of JavaScript and that's outside the scope of the support I can provide. I recommend you ask on StackOverflow.
