### ISSUE TITLE
Australian Phone number not working

### ISSUE THREAD

**Issue by Tamil** [jackocnr/intl-tel-input#942]
### Steps to reproduce
1.  Select country code as Australia
2.  Enter Phone number starting with 046+ (ex:0460400734)
3.  Click submit, it shows invalid phone number

### Expected behaviour
0460400734 is a valid Austalian number. But the plugin says its invalid

### Actual behaviour
plugin says its invalid

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
Please check you're using the latest version. The validation demo page shows that number as valid: https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html

**Comment by Codepadawan** [comment]
I need to use an older version (11.0.0), since I need compatibility with older browsers - is there anyway I can refer to the updated validation data while using an older verson?

**Comment by jackocnr** [comment]
I'm afraid not sorry.

**Comment by Codepadawan** [comment]
I just used the most recent `utils.js` file and that seemed to work.

**Comment by jackocnr** [comment]
Some things might work, but other things will likely be broken as sometimes the API changes. You can find out by looking at the commit history of the src/js/utils.js file.
