### ISSUE TITLE
InvalidStateError

### ISSUE THREAD

**Issue by cshwd** [jackocnr/intl-tel-input#943]
If i create 2 input with intlTelInput i have error:
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable.
Have anyone resolve this problem?

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by cshwd** [comment]
In my project i have 3 three inputs, and i need get data from this form and insert into db.
I have v15.1.0 version of plugin, i resolve this problem by comment out this line in file **intlTelInput.min.js** in line **428**, after comment out problem is gone.

` key: "_1", value: function (a) {
                        var b = this._z(a.getAttribute("data-country-code"));
                        this._2(), this._4(a.getAttribute("data-dial-code"), !0), this.a.focus();
                        var c = this.a.value.length;
                        this.a.setSelectionRange(c, c), b && this._8()
}`

**Comment by jackocnr** [comment]
I'm sorry but this is not enough information for me to debug the issue. I'm going to close this for now, but if you can provide a Codepen then I will happily re-open.
