### ISSUE TITLE
How to get country dial code after enter phone number

### ISSUE THREAD

**Issue by vickykrbu** [jackocnr/intl-tel-input#944]
### Steps to reproduce
1.  When i use this code: $("#phone").intlTelInput("getSelectedCountryData").dialCode; inside document.ready or document.load function getting intlTelInput is not a function error
2.  
3.  

### Expected behaviour
I should able to get the country dial code based on the current selected flag

### Actual behaviour
When i use this code:` $("#phone").intlTelInput("getSelectedCountryData").dialCode;` inside document.ready or document.load function getting intlTelInput is not a function error

### Initialisation options

First of all i just wanted to mentioned here whatever example i found in the github or stackoverflow no where it is mention like in which event we have to initialize the IntlTelInput function. But some how i managed to do that.
Below is my complete code
`<script>
   var input = document.querySelector("#IntlPhone");
    var errorMap = ["Invalid number", "Invalid country code", "Too short", "Too long", "Invalid number"];
    window.addEventListener("load", function () {
        
        errorMsg = document.querySelector("#error-msg"),
 validMsg = document.querySelector("#valid-msg");
        var iti = window.intlTelInput(input, {
            utilsScript: "/Content/build/js/utils.js"
        });
        window.intlTelInput(input, {
            // allowDropdown: false,
            // autoHideDialCode: false,
            // autoPlaceholder: "off",
            // dropdownContainer: document.body,
            // excludeCountries: ["us"],
            // formatOnDisplay: false,
             geoIpLookup: function(callback) {
               $.get("http://ipinfo.io", function() {}, "jsonp").always(function(resp) {
                 var countryCode = (resp && resp.country) ? resp.country : "";
                 callback(countryCode);
               });
             },
            // hiddenInput: "full_number",
            initialCountry: "auto",
            // localizedCountries: { 'de': 'Deutschland' },
            //nationalMode: false,
            // onlyCountries: ['us', 'gb', 'ch', 'ca', 'do'],
            placeholderNumberType: "MOBILE",
            // preferredCountries: ['cn', 'jp'],
            // separateDialCode: true,
            utilsScript: "/Content/build/js/utils.js",
        });
        $(validMsg).addClass("hide");
        input.addEventListener('blur', function () {
            reset();
            if (input.value.trim()) {
                if (iti.isValidNumber()) {
                    validMsg.classList.remove("hide");
                } else {
                    input.classList.add("error");
                    var errorCode = iti.getValidationError();
                    errorMsg.innerHTML = errorMap[errorCode];
                    errorMsg.classList.remove("hide");
                }
            }
        });
        input.addEventListener("countrychange", function () {
            $("#phone").intlTelInput("getSelectedCountryData").dialCode;
        });

        input.addEventListener('change', reset);
        input.addEventListener('keyup', reset);
    });

    
    var reset = function () {
        input.classList.remove("error");
        errorMsg.innerHTML = "";
        errorMsg.classList.add("hide");
        validMsg.classList.add("hide");
    };
</script>`

Till above code i used and i am able to get the current country flag selected based on the current user location on load.
Now when user enter some number after that i need here once user finished entering number then i should get the current country dial code to utilized that dial code for some purpose.
But when i used the code above "countrychange" event but this event is not firing.
If i am trying to use this event inside jquery.load function then getting IntlTelInput is not a function.

Please review my above code and suggest to access country dial code.

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by vickykrbu** [comment]
Hi Jackocnr,
Thank you for the quick response. I have gone through the pen link and found like here 
`var input = document.querySelector("#phone");`
above code is used direct in script without under any load functions but in my case when i used the same in outside input value is null. But if i put the same under window.load function then this code is working. Now one more thing i found here like i have checked the example demo page where this code is just put globally. but when i am trying to put the same in my application getting null value for the input variable. I really don't understand why. Currently i am trying to implement it for my MVC application.
Please suggest.

**Comment by jackocnr** [comment]
Hi there, I'm glad you solved your first problem. 

Re: your second problem, I'm afraid I have the same answer: please create a codepen to show the problem and then I can take a look :)

**Comment by vickykrbu** [comment]
Hi Jackocnr,
Finally i was able to create the code pen link is [here](https://codepen.io/vikash_kumar/pen/LwLaZY)
As i discussed above getting same error here. IntlTelInput is not a function.

**Comment by jackocnr** [comment]
You have switched from the pure JS syntax to the jQuery syntax. See the readme section on `getSelectedCountryData` for the pure JS syntax.
