### ISSUE TITLE
Ability to hide the flags

### ISSUE THREAD

**Issue by iccaprar** [jackocnr/intl-tel-input#951]
Hi,

We would like to make an addition to this nice plugin, that is to be able to use it without showing flags in the country dropdown. Is it ok to fork it for the change, and submit a feature PR, in case this is something that would be useful for everyone?

Thank you,
Cristi C.

### Steps to reproduce
1. Use the plugin in code  
2. Try to not show the flags in the dropdown (but keep the country name and prefix)
3.  -> not possible

### Expected behaviour
It should be possible to not show the flags if configured so, but keep having the country selector with the name and prefix numbers. allowDropdown is not usable for this.

### Actual behaviour
There is no configuration to not show the flags in the dropdown.

### Initialisation options
preferredCountries, nationalMode:false, initialCountry, utilsScript:"".

**Comment by jackocnr** [comment]
I think this is something that can be done with some simple CSS overrides. If you want to share them here to help others that would be great, but I don't think it's worth changing the core codebase for this. Thanks.

**Comment by iccaprar** [comment]
Indeed, I solved it by overriding the flag icon class width to 0 and some small change to avoid the width mapping for each country. Will share the modified source css for the library and the data.

Thanks!
