### ISSUE TITLE
Unable to see some countries' country codes with window.iti.getNumber()

### ISSUE THREAD

**Issue by firatcansucu** [jackocnr/intl-tel-input#954]
### Steps to reproduce
1.  open the demo page: https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/national-mode.html
2.  select Portugal, then enter a number (ex: 123456)
3.  enter `window.iti.getNumber()` in the console

### Expected behaviour
console to show +351123456; as it shows +31 before 123456 when you select Netherlands

### Actual behaviour
console shows only 123456

### Initialisation options
above

**Comment by jackocnr** [comment]
As per the documentation for that method:

> note that this method expects a valid number, and so should only be used after validation.
