### ISSUE TITLE
Why when i use geoIpLookup and set the initialCountry: "auto" but the result on webpage is undefined?

### ISSUE THREAD

**Issue by fransiscushuang** [jackocnr/intl-tel-input#955]
### Steps to reproduce
1.  Set `window.intlTelInput(input, {
           
            preferredCountries: ["id", "sg"],
            initialCountry: "auto",
            geoIpLookup: function(callback) {
                $.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
                    var countryCode = (resp && resp.country) ? resp.country : "";
                    callback(countryCode);
                });
            },

            utilsScript: "<?php echo BASE_URL . "asset/intl-tel-input-master/build/js/utils.js?1562189064761"; ?>"
        });`

### Expected behaviour
As my Ip address is from Indonesia it should pick Indonesia

### Actual behaviour
It is undefined, but the callback success pass the information and it show all the information about city, country, ip, etc.

here is the picture of the undefined

![Capture](https://user-images.githubusercontent.com/42550309/63366746-98f8b600-c3a4-11e9-8927-93dc094036a8.PNG)

### Initialisation options
I'm using the code from the example, here's the link [https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/default-country-ip.html](url)

**Comment by jackocnr** [comment]
Is the input empty when you init the plugin?

And can you confirm that your `geoIpLookup` function is passing `"id"` into the callback?

**Comment by fransiscushuang** [comment]
Yeah, it is passing "id" but on the elements it is still undefined. Emm, i show the country code using my code is that the problem, i put the value of dialCode to my input?

**Comment by jackocnr** [comment]
As per the docs for `initialCountry`: 

> Note that the "auto" option will not update the country selection if the input already contains a number.

**Comment by fransiscushuang** [comment]
So how can i show the dial code? Is there any function to show dial code?

**Comment by jackocnr** [comment]
If you want to show the dial code at all times, I'd recommend the `separateDialCode` option.

Can you confirm that if you leave the input empty then it is setting the flag correctly?

**Comment by fransiscushuang** [comment]
Yeah it works when input is empty, but my client want to show the dialcode. Is there any example of seperateDialCode function? so i can see how the function show the dialcode

**Comment by jackocnr** [comment]
> Yeah it works when input is empty

Great. I'll close this issue then.

> Is there any example of seperateDialCode function?

There is a screenshot in the readme. Just read about it in the readme and give it a try - it's fairly simple.

**Comment by fransiscushuang** [comment]
![Capture](https://user-images.githubusercontent.com/42550309/63444534-fc481e00-c460-11e9-9e48-e66d73c9bf1e.PNG)

Is it true? cause i try to do it like that but nothing change.. I have read Readme but there is no example for it on how using it.. can you please show me how to use it?

**Comment by e10a** [comment]
@fransiscushuang this is working for me (note: sep**a**rate not sep**e**rate)

`separateDialCode: true,`

Hope that solves that particular issue!
