### ISSUE TITLE
Support ecmascript 6/2015

### ISSUE THREAD

**Issue by Acra2** [jackocnr/intl-tel-input#958]
We have en Angular application and want to upgrade our typescript compilerOptions target from `es5` to `es2015`. But we got the following error message `Uncaught TypeError: Cannot use 'in' operator to search for 'intlTelInputUtils' in undefined` from the `utils.js` file

### Steps to reproduce
If you are running an angular 8 application:
1. set typescript compilerOptions target to `es2015`
2. run application

### Expected behaviour
Should work as normal

### Actual behaviour
excetion is thrown: `utils.js:1 Uncaught TypeError: Cannot use 'in' operator to search for 'intlTelInputUtils' in undefined
    at m (utils.js:1)
    at utils.js:466
    at Object../node_modules/intl-tel-input/build/js/utils.js (utils.js:470)
    at __webpack_require__ (bootstrap:79)`

**Comment by jackocnr** [comment]
utils.js is over 200KB - I would recommend excluding that from your JS bundle, and just loading it using the `utilsScript` option. It's already minified so you don't need to worry about that.

But if you insist on including it in your bundle, utils.js is generated by [libphonenumber](https://github.com/googlei18n/libphonenumber), so you'd have to raise the issue with them.

**Comment by nileshzala005** [comment]
@jackocnr how to use utilsScript?

**Comment by binDongKim** [comment]
I wonder how I'm supposed to use `utilsScript` option in Angular environment. I've been trying to refer the `utils.js` through `utilsScript` like:

```javascript
this.telIti = intlTelInput(this.telInputElem, {
    utilsScript: '../../node_modules/intl-tel-input/build/js/utils.js'
});
```

But it doesn't work :/

**Comment by nkarmi** [comment]
Any updates on this issue, because I'm facing the same error?

**Comment by Acra2** [comment]
@nileshzala005 @binDongKim @nkarmi
I'm sorry I haven't seen your questions earlier. I hope I can answer them by showing my configuration. I don't know if I used it the best way possible but this was the only way I got it working.

I have added the utils script to my assets configuration in `angular.json`
```
"assets": [
    ...
    {
    "glob": "utils.js",
    "input": "node_modules/intl-tel-input/build/js",
    "output": "/assets/scripts"
    }
],
```
This way the utils.js script will be available in your dist folder under `assets/scripts`.
You could also copy the utils.js file out of the node_modules and place it in you own `scr/app/assets` folder. But that way you may need to update utils script by hand on a package update.

In your intl-tel-input configuration you can use the script like this:
```
this.ngTelInput.intlTelInput({
    ...
    utilsScript: 'assets/scripts/utils.js'
});
```

I hope this answers your questions, please let me know otherwise.

**Comment by binDongKim** [comment]
@Acra2 
Thanks for sharing your solution. One question though: I've made it work by:
```
// in angular.json
 "scripts": [
  ...
  "./node_modules/intl-tel-input/build/js/utils.js"
]
```
just curious how it's different from your solution internally.

**Comment by Acra2** [comment]
@binDongKim 
It has to do with performance. If you place the script in de scripts section it wil be added to the scripts bundle. This means it will be loaded with each full page load. If you place the script in the assets section you can load the script when needed. I think in your solution you don't even need to use the `utilsScript` option because all functions are already loaded by the scripts bundle.

On our app the pages with the intl-tel input are not visited by every user. For that reason I don't want to load the script for every user, especially because this script is 200KB. This saves network traffic and therefore time. 

You can see the difference in bunlde size your self with this npm package https://www.npmjs.com/package/webpack-bundle-analyzer

**Comment by binDongKim** [comment]
@Acra2 You're right. I didn't have to use the `utilsScript` option which made me feel weird.
I took your ideas. Thank you!

Another kind of related question though: 
![스크린샷 2020-03-30 오후 3 06 35](https://user-images.githubusercontent.com/8830238/77880642-128c4700-7298-11ea-8a18-a3b826d93b84.png)

As you can see, I declared third party css files and scripts in `angular.json` so that the styles and functions they provide will work throughout my app. But considering your solution, some of them aren't needed in whole app, which sounds more correct to be loaded in certain pages as you approached with the above solution. Should I declare them like: 
```
{
  "glob": "some.js",
  "input": "node_modules/somePath",
  "output": "/assets/path"
}
``` 
But if I go with this, I may need to do some *import* thing to refer to it.
I'd appreciate if you share any ideas. Thank you.
