### ISSUE TITLE
Add new number

### ISSUE THREAD

**Issue by Gordondalos** [jackocnr/intl-tel-input#959]
### Steps to reproduce
add new number
+996 990 ХХ ХХ ХХ
+996 995 ХХ ХХ ХХ
+996 997 ХХ ХХ ХХ
+996 998 ХХ ХХ ХХ

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
I guess you mean for validation?

We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.
