### ISSUE TITLE
Country Automatically Changed to US from Canada

### ISSUE THREAD

**Issue by ranit2018** [jackocnr/intl-tel-input#963]
### Process: 
1.  Select **"Canada"** . Then, 
2.  Start typing Mobile number
3.  Country **automatically** changed to the **US**

### Not for only **Canada**. This bug is also for some other countries as well.

**Comment by jackocnr** [comment]
This question has already been answered, please search the existing issues before creating a new one.

**Comment by e-hop** [comment]
x2
