### ISSUE TITLE
Digit spacing issue

### ISSUE THREAD

**Issue by okkoos** [jackocnr/intl-tel-input#964]
Hello,
My application is using Jquery v3.3.1. I downloaded the latest version of International Telephone Input, it works fine, but I want to the input element to react like as https://numverify.com/ and automatically spacing the entered digits according to the country's number plan.
This site used International Telephone Input v6.0.8 and Jquery.1.9.1. How can I handle this with using the latest version of International Telephone Input ?
Best Regards.

**Comment by jackocnr** [comment]
The feature was called autoFormat. We removed it a while ago - see readme for explanation.
