### ISSUE TITLE
Utils.js error: goog is not defined

### ISSUE THREAD

**Issue by Edwardkrasava** [jackocnr/intl-tel-input#968]
I wrote the paths correctly, but script don't working
In console writes that such an error:  "Uncaught ReferenceError: goog is not defined"

It's my code:
id.intlTelInput({
        utilsScript:'frontend/libs/input_tel_mask/src/js/utils.js',
        defaultCountry: 'auto'
    });

**Comment by HafizQuraishi** [comment]
I'm getting same error how did you solve that

**Comment by Edwardkrasava** [comment]
It's very simple)
I'm inattentive.
In the folder there are two files Utils.js
Choose another.

**Comment by HafizQuraishi** [comment]
@Edwardkrasava  thanks for quick response.
I've tried that but I'm unable to get number getNumber return empty string and isValidNumber return null

**Comment by HafizQuraishi** [comment]
var input = document.querySelector("#phone");
			window.intlTelInput(input);
			var linkToUtils = url+'assets_users/js/utils.js';
        	var iti = intlTelInput(input,{
				utilsScript: linkToUtils
			});
            console.log(iti.getNumber());  // return me an empty string
            console.log(iti.isValidNumber()); // return me null

**Comment by Edwardkrasava** [comment]
@HafizQuraishi, sorry.
I don’t know how to solve this problem, maybe can read the documentation carefully.

**Comment by AhmedEl-Atab** [comment]
@Edwardkrasava 

**I had solved the problem!**
It seems that the source files that are placed in the "src" folder are not updated (containing bugs).

Use the files that are placed in the "build" folder, since in the "demo.html" every thing is working properly knowing that it is referring to the files in the "build folder".

This worked for me!

This is the folder to use:
[build.zip](https://github.com/jackocnr/intl-tel-input/files/4403633/build.zip)

**Comment by ico3iain** [comment]
I was having the same issue, but after reading the docs https://intl-tel-input.com/examples/lookup-country.html

This snippet helped me and all is working

```
const input = document.querySelector("#phone");
window.intlTelInput(input, {
  initialCountry: "auto",
  geoIpLookup: callback => {
    fetch("https://ipapi.co/json")
      .then(res => res.json())
      .then(data => callback(data.country_code))
      .catch(() => callback("us"));
  },
  utilsScript: "/intl-tel-input/js/utils.js?1710935347720" // just for formatting/placeholders etc
});
```
