### ISSUE TITLE
Wrong dialing code for +1 countries

### ISSUE THREAD

**Issue by Vedrine** [jackocnr/intl-tel-input#971]
Hi, I have noticed that your library shows the wrong country code for most of the +1 Pacific island countries.

For example the country code for Barbados is supposed to be +1246 but it shows +1.

<img width="311" alt="Capture" src="https://user-images.githubusercontent.com/33923690/65258171-b5eaeb00-db02-11e9-85ac-f26dcb221159.PNG">

**Comment by jackocnr** [comment]
Well countries like Barbados are part of the [North American Numbering Plan](https://www.wikiwand.com/en/North_American_Numbering_Plan) and technically the international dial code is +1, and the area code is 246.

Also as a data point, this is what Google do in their phone inputs, e.g. in Google Contacts:

<img width="341" alt="Screenshot 2019-09-20 at 10 12 25" src="https://user-images.githubusercontent.com/1186883/65314982-36572d80-db8f-11e9-9c2a-b4f4a147cfd3.png">
