### ISSUE TITLE
New metadata libphonenumber

### ISSUE THREAD

**Issue by relbraun** [jackocnr/intl-tel-input#972]
The google libphonenumber was updated and new patterns are released

**Comment by jackocnr** [comment]
Thanks for raising this issue. It actually only takes 5 minutes to do this yourself, if you'd be willing to submit a Pull Request? Instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber). Thanks :)

**Comment by michaelmouawaddo** [comment]
https://github.com/jackocnr/intl-tel-input/pull/973

**Comment by jackocnr** [comment]
Released in v16.0.4
