### ISSUE TITLE
French number beginning with a 7 are not valid

### ISSUE THREAD

**Issue by julien-leclercq** [jackocnr/intl-tel-input#974]
French international code is `+33` and mobile numbers begins with a `6` or a `7` followed with 8 numbers, for example `+337187265xx` should be valid (with x being numbers I just do not want to output a real number on the internet).

### Steps to reproduce
1.  Instanciate intl-tel-input with latest published version or master
2.  query validation on a number that starts with a `7`
3.  see that it is not validated 

### Expected behaviour
This kind of number should be valid.

### Actual behaviour
It is not.

### Additional infos 
Every other starting digit make a valid number to your lib except `0` which is fine.

### Initialisation options
I used the `demo.html` and the snippet you provide in the `isValidNumber` documentation

**Comment by julien-leclercq** [comment]
Sorry it was due to a mis knowledge from me on how +337xxxxxxxx numbers worked.
Thanks for the lib ! :)

**Comment by arnaud-zad** [comment]
@julien-leclercq Can you give more explanation ? I am facing the same issue
