### ISSUE TITLE
"Initial country" flag defaulting to the first country in the list

### ISSUE THREAD

**Issue by davidferlay** [jackocnr/intl-tel-input#975]
### Initialisation options

- Build a local Drupal website using this [starterkit](https://github.com/skilld-labs/skilld-docker-container) (requires docker-ce + docker-compose, then `make all`)
- This install includes Drupal [webform module](https://www.drupal.org/project/webform), which make uses of [intl-tel-input library](https://github.com/jackocnr/intl-tel-input) for it's telephone field type

### Steps to reproduce

- Go to http://your_local_site_ip/contact
- Click on telephone field flag icon 

### Observed result

- Telephone field is displayed with the US flag as default value because 
   - [initialCountry documentation](https://github.com/jackocnr/intl-tel-input#options)
      -  > If you leave initialCountry blank, it will default to the first country in the list.
   - [preferredCountries documentation](https://github.com/jackocnr/intl-tel-input#options) 
      -  > Type: Array Default: ["us", "gb"]

![image](https://user-images.githubusercontent.com/20738264/65759610-a3346f80-e11b-11e9-8d48-a87683b6c390.png)

### Expected result

- Without knowledge of documentation, user could naturaly actually expect to see some generic icon (flag [or not](https://fontawesome.com/icons/globe?style=light)) as initial value, instead of flag of the first country in the list

### Questions

- I propose as feature request to change behavior described in documentation, in order to provide a [generic icon](https://fontawesome.com/icons/globe?style=light) when initialCountry setting is left blank, instead of displaying the first country in the list

**Comment by jackocnr** [comment]
What do you propose for the generic icon? And do you really think that would be a better experience for the user?

If you want to default to the user's country, see initialCountry=auto setting.

Otherwise I think defaulting to the first country makes sense. It makes it clear what the input is for and how it works and shows the user they need to change it.

**Comment by davidferlay** [comment]
Hi @jackocnr , thanks for such a quick answer)

> What do you propose for the generic icon? 

I propose the globe icon from this opensource collection : https://feathericons.com/?query=globe

> Do you really think that would be a better experience for the user?

I do but it's only my opinion and I don't want to impose anything. I'd be happy to see other users to express their opinion

> If you want to default to the user's country, see initialCountry=auto setting.

Thanks for pointing this out, i had missed it and it can cover additional use cases ([like here](https://www.drupal.org/project/webform/issues/3084002))

> Otherwise I think defaulting to the first country makes sense. It makes it clear what the input is for and how it works and shows the user they need to change it.

It does make sense indeed. In my humble opinion, it should however exclude values defined by preferredCountries. Especially since it has default values.

**Comment by jackocnr** [comment]
> it should however exclude values defined by preferredCountries

Why? The preferredCountries setting is for you to specify the most likely option to your users - surely it makes sense to default to the most likely option rather than Afghanistan?

> Especially since it has default values

If the default values don't work for you, you should update them!

**Comment by davidferlay** [comment]
Is there any way to disable preferredCountries default values @jackocnr ?
Without passing any country code i mean

**Comment by jackocnr** [comment]
Yeah you should be able to pass an empty array. Does that solve your problem?

**Comment by davidferlay** [comment]
This might)
