### ISSUE TITLE
Unable to import utils.js

### ISSUE THREAD

**Issue by demo-igor** [jackocnr/intl-tel-input#980]
I'm trying to use intl-tel-input to create my own component on angular 1.6.
I can't use utilsScript or loadUtils, because I want to make npm package for my component.
So I'm trying to import everything all I needs.

Including inside of the component loooks like this
```
import intlTelInput from 'intl-tel-input';
import 'intl-tel-input/build/js/utils';

```
Using intl-tel-input looks like this 
```
this.intlTelInputCtrl = intlTelInput(this.inputEl[0], { initialCountry: 'us' });
```
After I create a bundle with my component and try to use in another project I get error:
**Uncaught TypeError: Cannot use 'in' operator to search for 'intlTelInputUtils' in undefined**

So my question is it possible to add utils.js and fix this error?

**Comment by jackocnr** [comment]
utils.js is quite a bit file - we recommend you lazy load it at runtime with the `utilsScript` option.

**Comment by demo-igor** [comment]
> utils.js is quite a bit file - we recommend you lazy load it at runtime with the `utilsScript` option.

I can't use utilsScript or loadUtils, because I want to make npm package for my component. So I would like to understand there is a way to add utils.js with another way?

**Comment by jackocnr** [comment]
Well utils.js doesn't export anything, so importing it wont work. It just defines a global on the window object. If you really want to include it in your bundle, you should just concatenate that file into your output JS with your build tool e.g. webpack.

**Comment by ff0041** [comment]
`import 'intl-tel-input/build/js/utils';` should work if you install `imports-loader`, and in `webpack.config.js` add:

```js
module.exports = {
  ...
  module: {
    rules: [
      {
        test: require.resolve('intl-tel-input/build/js/utils'),
        use: {
          loader: 'imports-loader',
          options: {
            wrapper: {
              thisArg: 'window',
              args: {
                module: false,
                exports: false,
                define: false,
              },
            },
          },
        },
      },
    ...
    ],
  },
}
```

Via https://stackoverflow.com/a/65373977
