### ISSUE TITLE
Not properly validating the Mexico Mobile Number

### ISSUE THREAD

**Issue by ragav-india** [jackocnr/intl-tel-input#982]
When i am trying to validate the mexico mobile phone number it was working correctly earlier. 
Eg. No. +52 (1) 811 987 8677 - Earlier
Eg. No. +52 811 987 8677 - Now. (1) is removed by mexico

Mexico has simplified its mobile number by removing 1 in front of the mobile number. [Here](https://www.mexperience.com/mexico-simplifies-telephone-dialing-rules/) is the article regarding this. 

Hence 1 is removed it is validating wrongly as Fixed line . i am unable to validate the correct mexico mobile numbers.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.
