### ISSUE TITLE
Issue in Validating Numbers

### ISSUE THREAD

**Issue by gopal91agrawal** [jackocnr/intl-tel-input#984]
### Steps to reproduce
1.  Put any indian number (+91) starting with 710
2.  Put check of isValidNumber
3.  

### Expected behaviour
Number should show validated

### Actual behaviour
Showing Invalid Numbers
check on official Demo page as well.

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

**Comment by gopal91agrawal** [comment]
> We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

I've check on their website but number is validating nicely on their site and when I'm testing that number on intlInput test site it shows invalid number.

**Comment by gopal91agrawal** [comment]
https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html
try any indian number i.e. 701XXXXXXX . It's not validating it.

**Comment by jackocnr** [comment]
Hmm that's strange, I just went to that page, and selected india and typed 7011234567 and it said it was valid. What number are you typing?

**Comment by gopal91agrawal** [comment]
> Hmm that's strange, I just went to that page, and selected india and typed 7011234567 and it said it was valid. What number are you typing?

Sorry , try 7101234567

**Comment by gopal91agrawal** [comment]
try 7109123456

**Comment by jackocnr** [comment]
The libphonenumber demo page says that number is not valid either. If you're sure it is valid you'll need to open an issue with them.
