### ISSUE TITLE
Philippine phone numbers now add a new '8' to all numbers

### ISSUE THREAD

**Issue by hornetnz** [jackocnr/intl-tel-input#986]
As of Oct 6th, the Philippines changed their phone number format. For example, the following number is changing from +63 2 765 4321 to +63 2 8765 4321
For more information on the required changes: https://pldtenterprise.com/8-digit-migration

I tested this one the libphonenumber test page and it came back valid, so may just need to bump your dependency.

http://libphonenumber.appspot.com/phonenumberparser?number=%2B63+2+8765+4321&country=PH
Validation Results
true
true
true
PH
FIXED_LINE

### Steps to reproduce
1.  Goto validation demo
2.  Use # "+63287654321"
3.  Note Not Valid
4. Use # "+6327654321"
5. Note Valid

### Expected behaviour
"+63287654321" should be valid

### Actual behaviour
"+63287654321" is not valid

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
Thanks for raising this issue. It actually only takes 5 minutes to update libphonenumber yourself, if you'd be willing to submit a Pull Request? Instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber). Thanks :)

**Comment by hornetnz** [comment]
I'm attempting to now, but the ant compile step is throwing some errors. Did I miss something?
`
     [exec] /Users/nikoleizinsli/IdeaProjects/closure-library/closure/goog/base.js:2415: ERROR - [JSC_DEPRECATED_PROP_REASON] Property defineClass of type goog has been deprecated: Use ES6 class syntax instead.
     [exec]   if (!goog.defineClass.SEAL_CLASS_INSTANCES) {
     [exec]        ^^^^^^^^^^^^^^^^
     [exec]
     [exec] /Users/nikoleizinsli/IdeaProjects/closure-library/closure/goog/base.js:2423: ERROR - [JSC_DEPRECATED_PROP_REASON] Property defineClass of type goog has been deprecated: Use ES6 class syntax instead.
     [exec]   var superclassSealable = !goog.defineClass.isUnsealable_(superClass);
     [exec]                             ^^^^^^^^^^^^^^^^
     [exec]
     [exec] /Users/nikoleizinsli/IdeaProjects/closure-library/closure/goog/base.js:2492: ERROR - [JSC_DEPRECATED_PROP_REASON] Property defineClass of type goog has been deprecated: Use ES6 class syntax instead.
     [exec]   for (var i = 0; i < goog.defineClass.OBJECT_PROTOTYPE_FIELDS_.length; i++) {
     [exec]                       ^^^^^^^^^^^^^^^^
     [exec]
     [exec] /Users/nikoleizinsli/IdeaProjects/closure-library/closure/goog/base.js:2493: ERROR - [JSC_DEPRECATED_PROP_REASON] Property defineClass of type goog has been deprecated: Use ES6 class syntax instead.
     [exec]     key = goog.defineClass.OBJECT_PROTOTYPE_FIELDS_[i];
     [exec]           ^^^^^^^^^^^^^^^^
     [exec]
     [exec] /Users/nikoleizinsli/IdeaProjects/closure-library/closure/goog/base.js:2510: ERROR - [JSC_DEPRECATED_PROP_REASON] Property defineClass of type goog has been deprecated: Use ES6 class syntax instead.
     [exec]   if (!COMPILED && goog.defineClass.SEAL_CLASS_INSTANCES) {
     [exec]                    ^^^^^^^^^^^^^^^^
     [exec]
     [exec] /Users/nikoleizinsli/IdeaProjects/closure-library/closure/goog/base.js:4168: ERROR - [JSC_DEPRECATED_PROP] Property TrustedTypes of type global this has been deprecated.
     [exec]   var policyFactory = goog.global.trustedTypes || goog.global.TrustedTypes;
     [exec]                                                   ^^^^^^^^^^^^^^^^^^^^^^^^
     [exec]
     [exec] /Users/nikoleizinsli/IdeaProjects/closure-library/closure/goog/string/string.js:1112: ERROR - [JSC_DEPRECATED_PROP_REASON] Property now of type goog has been deprecated: Use Date.now
     [exec]       Math.abs(Math.floor(Math.random() * x) ^ goog.now()).toString(36);
     [exec]                                                ^^^^^^^^
     [exec]
     [exec] 7 error(s), 0 warning(s), 98.6% typed
     [exec] calcdeps.py: JavaScript compilation failed.
`

**Comment by hornetnz** [comment]
I wiped all of the associated repos and started from scratch. I tried the ant compile-demo command again before replacing the demo.js file with the one from intl-tel-input, and got the same errors. I can't seem to find any issues with reference to these errors on the git of libphonenumber or closure-library. I'm not sure what else to try...

**Comment by Royts22** [comment]
![image](https://user-images.githubusercontent.com/17432273/67264135-c49b3800-f4dc-11e9-8e2b-89d71457e007.png)

**Comment by jackocnr** [comment]
Thanks for trying. I've never come across that issue and I'm not sure what to suggest. I've just updated it myself, and published in v16.0.7.

**Comment by originallyori** [comment]
@jackocnr @hornetnz was this ever fixed? I still don't see this fixed in v17.0.3 or v16.0.7

**Comment by jackocnr** [comment]
From the original issue:

> "+63287654321" should be valid

This is coming up as valid for me in v17.0.3.
