### ISSUE TITLE
intlTelInput is not a function

### ISSUE THREAD

**Issue by eltoredo** [jackocnr/intl-tel-input#991]
Hello,
I know this issue has been reported many times but none of the answers have been able to fix my problem.

### Steps to reproduce
Same as the Github ones, both css and js imports (that is the right path):
`<link rel="stylesheet" href="./node_modules/intl-tel-input/src/css/intlTelInput.css">`
`<script src="./node_modules/intl-tel-input/src/js/utils.js"></script>`
My input is generated dynamically with a 'tel' type
I then check the type and execute the following code:
`if (columnData.forminfo.fields[u].inputtype === "tel") {
    var input = $("#"+columnData.forminfo.fields[u].inputid);
    window.intlTelInput(input);
}`
But I also tried this (with the utils import too):
`var input = document.querySelector("#"+columnData.forminfo.fields[u].inputid);
var iti = intlTelInput(input, {
        utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@16.0.3/build/js/utils.js",
    });
}`

### Expected behaviour
I should have had my input created with the flag version.

### Actual behaviour
I get an error: 'intlTelInput is not a function'.

### Initialisation options
I put my code above.

If I don't use the `window.` in the first code, I get a 'intlTelInput is not defined' if it can help.

Thanks!

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by eltoredo** [comment]
I've already seen that answer before and I've got the same error.
I put all of my code above, even if it's not in a CodePen, because the way I create my input is slightly different (it's dynamic, whenever the user wants to create an input, it creates it with the type that he chose).

**Comment by jackocnr** [comment]
I'm afraid I can't debug it unless I see the code running.

**Comment by eltoredo** [comment]
I'll try on my side and will get back here if I can provide anything that helps

**Comment by eltoredo** [comment]
Here am I again.

This is a screen of the same problem, on a totally blank project: https://imgur.com/ur4VqRI

This is my code, the exact same as your Codepen:

HTML

`<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
</head>

<body>
	<h1>International Telephone Input</h1>
	<input type="tel" id="phone">
</body>

</html>

<script src="./test.js"></script>

<style>
	body {
		margin: 20px;
	}
	input {
		width: 250px;
		padding: 10px;
		border-radius: 2px;
		border: 1px solid #ccc;
	}
	input::placeholder {
		color: #BBB;
	}
</style>`

JS

`var input = document.querySelector("#phone");
var iti = window.intlTelInput(input, {
	utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@16.0.3/build/js/utils.js",
});

// store the instance variable so we can access it in the console e.g. window.iti.getNumber()
window.iti = iti;`

What's the problem there?

**Comment by jackocnr** [comment]
The problem is that you are not loading the plugin script...

Please see the Getting Started section of the Readme.

**Comment by eltoredo** [comment]
You are right, I have put it first but it did not work and in your Codepen, it was not present so I deleted it. I have put it again and I have the same exact problem.

In your Getting Started section, it is not the same code as your Codepen.

**Comment by jackocnr** [comment]
If you look at the Codepen settings, in the CSS section you will see we load the plugin's CSS file, and in the JavaScript section you will see we load the plugin's JS file.

If you can't get it working in Codepen, then please post the full code here for me to take a look.

**Comment by eltoredo** [comment]
Oh indeed, I didn't know about this on Codepen. Thanks for your help.

**Comment by eltoredo** [comment]
Is `input.getAttribute is not a function` a known issue? After having fixed the first issue, that was apparently the path (...), this new issue just appeared.

I have this code: 
```
var input = $("#"+columnData.forminfo.fields[u].inputid);
console.log("test"+input);

var iti = window.intlTelInput(input, {
    utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@16.0.3/build/js/utils.js",
});
window.iti.getNumber()
window.iti = iti;
```
with `columnData.forminfo.fields[u].inputid` being `K2M1ZLR18U0W3`, an ID generated dynamically in a JSON

And the result is:
```
TypeError: input.getAttribute is not a function - intlTelInput.js:146:60
test[object Object]
```

Any idea?

**Comment by jackocnr** [comment]
You're using a jQuery selector to select the input element, so it will return it wrapped in a jQuery object. Just use pure JS to select the element (as in the codepen) and it should work.

**Comment by eltoredo** [comment]
Rather than being `[object Object]`, it's null (I already tried but didn't get why it was this way because the actual ID isn't null if I console.log it).
And if I put the ID hard coded, like `#phone`, it just says that the input variable is null when it shouldn't.
Thnaks for all of your help though...

**Comment by jackocnr** [comment]
I'm sorry but if you're having problems with basic JavaScript operations like selecting an element, then I don't have time to provide support for that - I would recommend you ask on StackOverflow. best of luck.

**Comment by eltoredo** [comment]
Yeah, the problem surely comes from me but I'm not giving 100% of my time to fix it, thanks again and sorry for your time!

**Comment by jiDoe** [comment]
Hello. I'm having the same problem. when I use `window.intlTelInput(`, the chrome  console outputs `Uncaught TypeError: window.intlTelInput is not a function` and when I use `intlTelInput(`, the console outputs `intlTelInput is not defined`.

I installed "intl-tel-input": "^17.0.8" using yarn to my phoenix project. The css has no problems.
the js call is something like this:

**Comment by leik-software** [comment]
Same problem like @jiDoe here. Can't create it in code pen.

**Comment by jiDoe** [comment]
@leik-software these imports worked for me

`import intlTelInput from 'intl-tel-input'`
`import 'intl-tel-input/build/js/utils.js'`

**Comment by paddotk** [comment]
I had the same problem; the issue is that the given error is (or can be) misleading. In my case, the input field reference couldn't be found, so `intlTelInput(input, {...options});` would keep giving me either a `intlTelInput is not a function' or `Cannot read properties of undefined (reading 'getAttribute')` error.

**Comment by nmg196** [comment]
The error in my case was that I'd copied the wrong .js files into my project - I'd copied from the **src** folder instead of the **build** folder.

Check that your intl-tel-input.js file starts with a header like this, rather than pure JS code:

```
/*
 * International Telephone Input v17.0.18
 * https://github.com/jackocnr/intl-tel-input.git
 * Licensed under the MIT license
 */
```
