### ISSUE TITLE
Customplaceholder for specific country

### ISSUE THREAD

**Issue by shanjoyshajan** [jackocnr/intl-tel-input#992]
Need to know how to customPlaceholder for a specific country.

**Comment by jackocnr** [comment]
See the readme for that option. The second argument passed to that function is `selectedCountryData` so you should be able to check that.

**Comment by shanjoyshajan** [comment]
Can i get the code  if i want to change the placeholder only for saudia arabian country to 5XXXXXXX

**Comment by jackocnr** [comment]
I recommend you implement the customPlaceholder option, then open chrome devtools and put a breakpoint in that function, and inspect the selectedCountryData argument to see how you could use it. If you're not sure how to do that, I recommend you ask for help on StackOverflow.

**Comment by shanjoyshajan** [comment]
ok thank you
