### ISSUE TITLE
Need update libphonenumber

### ISSUE THREAD

**Issue by arthutox** [jackocnr/intl-tel-input#993]
Hi! New version is available now - https://github.com/google/libphonenumber/releases
v8.10.22
Can you pls update plugin?

**Comment by jackocnr** [comment]
Thanks for raising this issue. It actually only takes 5 minutes to do this yourself, if you'd be willing to submit a Pull Request? Instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber). Thanks :)

**Comment by arthutox** [comment]
Cool thx, but I try and have this error
[exec] Error: Unable to access jarfile /Users/user/projects/libphonenumber-tools/libphonenumber/javascript/../../closure-compiler/target/closure-compiler-1.0-SNAPSHOT.jar
     [exec] calcdeps.py: JavaScript compilation failed.
when run - ant -f libphonenumber/javascript/build.xml compile-demo

**Comment by jackocnr** [comment]
Does that file exist? And does your user have read/write/execute permissions on it?

**Comment by arthutox** [comment]
I can't find file at this path.

**Comment by arthutox** [comment]
I have another error, when I run - mvn -DskipTests
[INFO] Closure Compiler Parent ............................ SUCCESS [  0.248 s]
[INFO] Closure Compiler Externs ........................... SUCCESS [  0.869 s]
[INFO] Closure Compiler GWT App ........................... FAILURE [ 33.186 s]
[INFO] Closure Compiler Main .............................. SKIPPED
[INFO] Closure Compiler Linter ............................ SKIPPED
[INFO] Closure Compiler Unshaded .......................... SKIPPED
[INFO] Closure Compiler ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.130 s
[INFO] Finished at: 2019-11-06T14:37:50+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-6:compile (default-compile) on project closure-compiler-gwt: GWT Compiler exited with status 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :closure-compiler-gwt

tried - 
`mvn install`
but it not working. Have any idea? Thx!

**Comment by cstone-aruba** [comment]
Hello.

I submitted updates to libphonenumber and they have been included in the new release.

Please see http://github.com/google/libphonenumber/releases/tag/v8.11.0

Can intl-tel-input be updated to include the new release of libphonenumber please?

Regards
Craig.

**Comment by jackocnr** [comment]
Released in v16.0.8

**Comment by arthutox** [comment]
Many thanks guys!
