### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by bristl** [jackocnr/intl-tel-input#997]
###   Man where is Russia?
Lags, I don't always see it

**Comment by jackocnr** [comment]
This is not enough information for me to look into the issue effectively. Please read the [New Issue Checklist](https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist) and if necessary, open a new issue and follow the [New Issue Template](https://raw.githubusercontent.com/jackocnr/intl-tel-input/master/.github/ISSUE_TEMPLATE.md). If you are including any code, please [format it correctly](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).
